### ISSUE TITLE
Unable to join community after membership is accepted

### ISSUE THREAD

**Issue by chair28980** [status-im/status-desktop#13499] opened 2024-02-09 19:08 UTC
# Bug Report

## Description
When requesting to join a community, and accepted by the community admin, not able to join the community, `Membership request pending...` message remains displayed.

## Steps to reproduce

1. Request to join a community that requires approval
2. Admin approves
3. Pending request does not update

#### Expected behavior
- Pending request is approved and community is joined

#### Actual behavior
- Pending request remains pending

### Additional Information

![image](https://github.com/status-im/status-desktop/assets/29414216/e30c706f-6ed4-4b4b-bbd0-cd85d8fbb23d)

- Status desktop version: https://ci.status.im/job/status-desktop/job/nightly/
- Operating System: linux ubuntu 22

**Comment by jrainville** [comment] 2024-02-09 19:59
Hi @chair28980 . Sorry that you experience such problem.

I just tested with two dummy accounts and the flow worked for me.

I wonder, what version of Status Desktop is the admin on? We switched fleet lately, so if the admin is on an old version, it's possible that messages don't get sent or received properly to a newer version. 

Otherwise, do you or the admin see any error in the logs?

You can find them in `~/.config/Status/logs`. You can paste them here. You can also run the AppImage in a terminal to see logs while running the app.

**Comment by corpetty** [comment] 2024-02-09 20:29
tested with my desktop account on current master (built today). No problems with flow.

**Comment by chair28980** [comment] 2024-02-09 23:23
@jrainville version 0.9.9.0, status-go version 0.172.8, from the nightly build here https://ci.status.im/job/status-desktop/job/nightly/

**Comment by anastasiyaig** [comment] 2024-02-12 07:20
i could not reproduce as well, same with autotests, they are green for that flow

**Comment by jrainville** [comment] 2024-02-14 17:55
@chair28980 can you try again? If possible, make sure that the owner and yourself are on the same version.

**Comment by jrainville** [comment] 2024-02-22 16:19
Closing this as no one is able to reproduce. I feel like this might have been an unfortunate connection issue. Feel free to reopen if you reproduce again

**Closed by jrainville** 2024-02-22 16:19 UTC
Labels: bug, messenger-team
