### ISSUE TITLE
on macos, right clicking the icon on the dock and pressing quit is not quitting (but works in the top menu)

### ISSUE THREAD

**Issue by iurimatias** [status-im/status-desktop#3112] opened 2021-07-29 17:18 UTC
1. go to the dock and right click the status icon
2. click quit

result: doesn't quit

**Comment by saledjenic** [comment] 2021-07-30 06:47
@anastasiyaig please check this, I cannot reproduce it. That quit in the dock, does minimize only if your setting is "Minimize on close" set to true, in every other case it quits for me. It quits regularly either you quit on "window's close" or "selecting quite on right click menu from the dock" or "selecting quit from Status app' menu in system tray".

**Comment by anastasiyaig** [comment] 2021-07-30 06:48
@iurimatias 

i was not able to reproduce:

1. having toggle Minimize on close = OFF and right click -> Quit quits the app
2. having toggle Minimize on close = ON and right click -> does not quit the app



https://images.zenhubusercontent.com/261270348/22a6c285-ff97-4227-8352-29f8007ada00/screen_recording_2021_07_30_at_09_44_32.mov

Any additional ways how to reproduce the issue u describe? Also, there is another issue that u can't quit the app when it is back from sleep.

**Comment by saledjenic** [comment] 2021-08-02 12:22
@anastasiyaig I found that we're not able to close the app if you just start it and don't log in into it (most likely @iurimatias meant on that case :) ) cause in any other case, as you recorded we're able to close it. 

How it works now on macOs:

- A user is not logged in:
| Action  | "Minimize on close" set to true | "Minimize on close" set to false |
| ------------- | ------------- |
| close on "X" button | minimize | close |
| close on "Quit" from the dock | close | close |
| close on "Quit" | close | close |
| close on "Quit Status" from the app menu bar | close | close |

- A user is logged in:
| Action  | "Minimize on close" set to true | "Minimize on close" set to false |
| ------------- | ------------- |
| close on "X" button | minimize | close |
| close on "Quit" from the dock | close | close |
| close on "Quit" | close | close |
| close on "Quit Status" from the app menu bar | close | close |
| close on Profile > "Sign out & Quit" | close | close |

**Comment by anastasiyaig** [comment] 2021-08-02 12:23
agree, this case does not working to me as well :) lets fix it!

**Closed** 2021-08-16 17:35 UTC
Labels: bug, macos, general, priority 1: high
