### ISSUE TITLE
The page 'Your emojihash...' differs from the Design

### ISSUE THREAD

**Issue by elina2015** [status-im/status-desktop#6517] opened 2022-07-18 23:39 UTC
# Bug Report

## Steps to reproduce
1. Go to sign up a new account
2. Check the page according to the [Design](https://www.figma.com/file/17fc13UBFvInrLgNUKJJg5/Kuba%E2%8E%9CDesktop?node-id=1023%3A298171)

#### Expected behavior
<img width="808" alt="image" src="https://user-images.githubusercontent.com/14942081/179634602-a73fd5ec-4401-4502-8f35-a251354988cc.png">

#### Actual behavior
1. The space between the text and chains differs from the Design
2. The space between the chains and emojihash and identicon  ring differs from the Design
3. The chains are blurred
4. The emojihash is bigger than on the Design
5. The space between the emogihash and button 'Next' differs from the Design
<img width="1405" alt="image" src="https://user-images.githubusercontent.com/14942081/179634220-c5850a22-8223-4f84-82c8-e83992a243d4.png">

### Additional Information

- Status desktop version: https://ci.status.im/job/status-desktop/job/branches/job/macos/job/master/2347/
- Operating System: macOS Monterey

**Comment by iurimatias** [comment] 2022-07-24 21:54
duplicate of #6022

**Closed by iurimatias** 2022-07-24 21:54 UTC
Labels: onboarding, pixel-perfect-issues
