### ISSUE TITLE
Messages in a community channel overlap each other

### ISSUE THREAD

**Issue by elina2015** [status-im/status-desktop#7651] opened 2022-09-29 05:57 UTC
# Bug Report

## Steps to reproduce
Go to any channel of Status community

#### Expected behavior
Messages in a community channel don't overlap each other
#### Actual behavior
<img width="1428" alt="image" src="https://user-images.githubusercontent.com/14942081/192950606-f31f3c7f-4b31-4a26-9400-f49120c831b2.png">

<img width="1345" alt="image" src="https://user-images.githubusercontent.com/14942081/192950457-9f06f39d-9133-42a3-b470-ae5c13656807.png">

### Additional Information

- Status desktop version: https://ci.status.im/job/status-desktop/job/platforms/job/macos/221
- Operating System: macOS Monterey

**Comment by caybro** [comment] 2022-09-29 08:12
@elina2015 @iurimatias I simply cannot reproduce this on latest master: 
![Snímek obrazovky z 2022-09-29 10-11-12](https://user-images.githubusercontent.com/5377645/192977258-33587e9b-961b-429c-801c-b6f6efea4d40.png)

**Comment by caybro** [comment] 2022-09-29 08:16
Possible dupe of https://github.com/status-im/status-desktop/issues/7618

**Comment by PascalPrecht** [comment] 2022-09-29 18:44
![Screenshot from 2022-09-29 20-00-51](https://user-images.githubusercontent.com/445106/193116314-e1076c83-5645-4173-a2ba-bb2066ec9849.png)
I can reproduce it

**Comment by caybro** [comment] 2022-09-29 22:14
@micieslak since you were investigating this before and I can't simply reproduce... can you please open a PR that just reverts the culprit so that others affected by this can test? TIA

**Comment by PascalPrecht** [comment] 2022-09-30 05:48
@caybro can you also not reproduce this in the pinned messages modal? Cause then one suffers from the same issue.

**Comment by caybro** [comment] 2022-09-30 09:28
> @caybro can you also not reproduce this in the pinned messages modal? Cause then one suffers from the same issue.

Nope, I can't

**Comment by micieslak** [comment] 2022-09-30 15:14
It's a duplicate of https://github.com/status-im/status-desktop/issues/7618, closing.

**Closed by micieslak** 2022-09-30 15:14 UTC
Labels: bug, Communities, priority 1: high
