### ISSUE TITLE
Contact request acception creates notification with wrong text

### ISSUE THREAD

**Issue by PascalPrecht** [status-im/status-desktop#7479] opened 2022-09-21 15:15 UTC
Steps to reproduce:

1. Send a contact request to someone
2. Wait for the contact to accept you rrequest
3. When request is accepted, you receive a notification..... with your own message

It should probably rather say "[CONTACT] accepted your request"

**Comment by anastasiyaig** [comment] 2022-09-22 06:28
https://github.com/status-im/status-desktop/issues/7475 duplicate of this one

**Closed by anastasiyaig** 2022-09-22 06:28 UTC
Labels: bug, E:MutualContacts
