### ISSUE TITLE
[StatusChatInput] Can't send message by hitting return when mention suggestions box is open

### ISSUE THREAD

**Issue by 0x-r4bbit** [status-im/status-desktop#7612] opened 2022-09-27 13:37 UTC
So I was about to send a message and mentioned another account:

![Screenshot from 2022-09-27 15-35-17](https://user-images.githubusercontent.com/445106/192541337-76f03a3e-1c04-489e-a39f-60b09005ed3e.png)

After typing the "?", the suggestionbox stays open.
Hitting "enter" doesn't do anything, although it should send the message.
Even clicking the input field again doesn't help. As long as there's the `?` I can't send the message.

**Comment by iurimatias** [comment] 2022-10-03 14:39
can't replicate, will put on the backburner to analyze

**Comment by PascalPrecht** [comment] 2022-10-05 08:04
I can still replicate this in latest `master`
Actually caused me to run into #7686

**Comment by alexandraB99** [comment] 2022-12-20 15:09
I cannot reproduce, to me the mentions box is opening as soon as I type ? and when I press enter it closes and removes the ?, I'd say the mentions box should not open on ? key

**Comment by 0x-r4bbit** [comment] 2022-12-20 15:59
@alexandraB99 I'm experiencing the exact same now

**Comment by iurimatias** [comment] 2023-04-21 14:07
can still replicate this

**Comment by iurimatias** [comment] 2024-08-13 12:33
closing as this will be part of a wider rethink of this feature

**Closed by iurimatias** 2024-08-13 12:33 UTC
Labels: bug, Desktop ChatInput Markdown/Refactor, E:D Msg Bugfixes MX
