### ISSUE TITLE
Seems like Status can't be quit properly on Ubuntu

### ISSUE THREAD

**Issue by PascalPrecht** [status-im/status-desktop#8470] opened 2022-11-28 09:41 UTC
This hasn't been the case before so probably related to the latest release.
Here's how I typically close Status on my machine:

1. I "X" the app (which just closes the window)
2. I click the Status icon in my menu bar, open the menu and hit "Quit"

2) Usually closes the app, however, this time it did not. In addition: Because it seems to be still running, I can't restart the app. So now I'm stuck in limbo
![Screenshot from 2022-11-28 10-37-01](https://user-images.githubusercontent.com/445106/204244594-801c0fca-af45-4429-a57a-0b7baf06868f.png)

Version: `d0725d451`
OS: Ubuntu 20.04.5 LTS

**Comment by anastasiyaig** [comment] 2022-11-28 11:41
it is most likely a duplicate of https://github.com/status-im/status-desktop/issues/8401

**Closed by anastasiyaig** 2022-11-28 11:41 UTC
Labels: bug
