### ISSUE TITLE
Status app v0.13-RC5 fails to start on Ubuntu 20.04

### ISSUE THREAD

**Issue by IvanBelyakoff** [status-im/status-desktop#11295] opened 2023-06-28 10:34 UTC
# Bug Report

## Description

```
./StatusIm-Desktop-v0.13.0-rc.5-ab85c6-x86_64.AppImage
/home/jenkins/workspace/status-desktop/systems/linux/x86_64/package/src/nim_status_client.nim(193) nim_status_client
/home/jenkins/workspace/status-desktop/systems/linux/x86_64/package/src/nim_status_client.nim(100) mainProc
/home/jenkins/workspace/status-desktop/systems/linux/x86_64/package/src/constants.nim(78) ensureDirectories
/home/jenkins/workspace/status-desktop/systems/linux/x86_64/package/vendor/nimbus-build-system/vendor/Nim/lib/pure/os.nim(2552) createDir
/home/jenkins/workspace/status-desktop/systems/linux/x86_64/package/vendor/nimbus-build-system/vendor/Nim/lib/pure/os.nim(2522) existsOrCreateDir
/home/jenkins/workspace/status-desktop/systems/linux/x86_64/package/vendor/nimbus-build-system/vendor/Nim/lib/pure/os.nim(2495) rawCreateDir
/home/jenkins/workspace/status-desktop/systems/linux/x86_64/package/vendor/nimbus-build-system/vendor/Nim/lib/pure/includes/oserr.nim(95) raiseOSError
Error: unhandled exception: Read-only file system
Additional info: /tmp/.mount_StatusNGXgHc/usr/Status [OSError]
```

## Steps to reproduce

Just start the app

### Additional Information

- Status desktop version: 0.13-RC5
- Operating System: Ubuntu 20.04

**Comment by anastasiyaig** [comment] 2023-06-28 11:17
@jakubgs is there anything u can assist with?

**Comment by jakubgs** [comment] 2023-06-28 11:38
That looks like a bug in the app to me. Fails for me too, but in a different way:
```
INFO [06-28|13:37:07.179] Status backend initialized               backend=geth version=0.158.1 commit=a46bf97bf IpfsGatewayURL=https://ipfs.status.im/
Warning: Cannot open file '/home/jakubgs/.cache/appimage-run/b83951061806c3b816a10004a307fab37208f40fd3385f1b305d1dc838da492d/usr/status-dev.svg', because: No such file or directory (:0, )
Warning: Cannot open file '/home/jakubgs/.cache/appimage-run/b83951061806c3b816a10004a307fab37208f40fd3385f1b305d1dc838da492d/usr/status-dev.svg', because: No such file or directory (:0, )
INF 2023-06-28 13:37:07.382+02:00 Version: git master ab85c6f27              topics="status-app" tid=2 file=nim_status_client.nim:182
INF 2023-06-28 13:37:07.382+02:00 Commit: ab85c6f27                          topics="status-app" tid=2 file=nim_status_client.nim:183
INF 2023-06-28 13:37:07.382+02:00 Current date:                              topics="status-app" tid=2 file=nim_status_client.nim:184 currentDateTime=2023-06-28T13:37:07+02:00
INF 2023-06-28 13:37:07.382+02:00 starting application controller...         topics="status-app" tid=2 file=nim_status_client.nim:186
DBG 2023-06-28 13:37:07.382+02:00 init keycard using                         topics="keycard-service" tid=2 file=service.nim:83 pairingsJson=/home/jakubgs/.cache/appimage-run/b83951061806c3b816a10004a307fab37208f40fd3385f1b305d1dc838da492d/usr/Status/data/keycard/pairings.json
DBG 2023-06-28 13:37:07.383+02:00 initialization response:                   topics="keycard-service" tid=2 file=service.nim:86 initResp=ok
Warning: QQmlApplicationEngine failed to load component (:0, )
Warning: qrc:/main.qml:18:1: plugin cannot be loaded for module "StatusQ": '/home/jakubgs/.cache/appimage-run/b83951061806c3b816a10004a307fab37208f40fd3385f1b305d1dc838da492d/usr/bin/StatusQ/libStatusQ.so' is not an ELF object (qrc:/main.qml:18, )
Failed to load translation file /home/jakubgs/.cache/appimage-run/b83951061806c3b816a10004a307fab37208f40fd3385f1b305d1dc838da492d/usr/bin/i18n/qml_en.qm
INF 2023-06-28 13:37:07.496+02:00 starting application...                    topics="status-app" tid=2 file=nim_status_client.nim:189
WRN 2023-06-28 13:37:07.499+02:00 Error decoding signal                      topics="signals-manager" tid=2 file=signals_manager.nim:48 err="Unknown signal received: mediaserver.started"
Warning: Error while loading QML: QUrl("qrc:/main.qml") (:0, )
INF 2023-06-28 13:37:07.499+02:00 shutting down...                           topics="status-app" tid=2 file=nim_status_client.nim:157
INF 2023-06-28 13:37:07.499+02:00 logging out...                             topics="app-controller" tid=2 file=app_controller.nim:284
Traceback (most recent call last)
/home/jenkins/workspace/status-desktop/systems/linux/x86_64/package/src/nim_status_client.nim(193) nim_status_client
/home/jenkins/workspace/status-desktop/systems/linux/x86_64/package/src/nim_status_client.nim(166) mainProc
/home/jenkins/workspace/status-desktop/systems/linux/x86_64/package/src/app/boot/app_controller.nim(285) delete
/home/jenkins/workspace/status-desktop/systems/linux/x86_64/package/src/app_service/service/general/service.nim(43) logout
/home/jenkins/workspace/status-desktop/systems/linux/x86_64/package/src/backend/general.nim(27) logout
/home/jenkins/workspace/status-desktop/systems/linux/x86_64/package/vendor/nim-status-go/status_go.nim(143) logout
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
```

**Comment by anastasiyaig** [comment] 2023-06-28 11:38
oh okay! @jrainville @alexjba could u guys give it a try?

**Comment by alexjba** [comment] 2023-06-28 11:51
@anastasiyaig I can only try on macOS.

Looks like an import issue.
```
Warning: qrc:/main.qml:18:1: plugin cannot be loaded for module "StatusQ": '/home/jakubgs/.cache/appimage-run/b83951061806c3b816a10004a307fab37208f40fd3385f1b305d1dc838da492d/usr/bin/StatusQ/libStatusQ.so' is not an ELF object (qrc:/main.qml:18, )
```

**Comment by anastasiyaig** [comment] 2023-06-28 11:53
'/home/jakubgs/.cache/appimage ' looks suspicious @jakubgs

**Comment by jakubgs** [comment] 2023-06-28 12:02
Well yeah, I use [`appimage-run`](https://nixos.wiki/wiki/Appimage) on NixOS because otherwise it wouldn't work:

But that's irrelevant, you're focusing on the wrong thing. That's just a warning, as you can see at the beginning of the line.

The actual error is the crash:
```
Traceback (most recent call last)
/home/jenkins/workspace/status-desktop/systems/linux/x86_64/package/src/nim_status_client.nim(193) nim_status_client
/home/jenkins/workspace/status-desktop/systems/linux/x86_64/package/src/nim_status_client.nim(166) mainProc
/home/jenkins/workspace/status-desktop/systems/linux/x86_64/package/src/app/boot/app_controller.nim(285) delete
/home/jenkins/workspace/status-desktop/systems/linux/x86_64/package/src/app_service/service/general/service.nim(43) logout
/home/jenkins/workspace/status-desktop/systems/linux/x86_64/package/src/backend/general.nim(27) logout
/home/jenkins/workspace/status-desktop/systems/linux/x86_64/package/vendor/nim-status-go/status_go.nim(143) logout
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
```

**Comment by jakubgs** [comment] 2023-06-28 12:02
Although to be fair this is also an error:
```
Warning: Error while loading QML: QUrl("qrc:/main.qml") (:0, )
```

**Comment by alexjba** [comment] 2023-06-28 12:08
> Although to be fair this is also an error:
> 
> ```
> Warning: Error while loading QML: QUrl("qrc:/main.qml") (:0, )
> ```

True, QML qml is basically saying Warning, the app is crashing. 😄
It seems it can't link to StatusQ

**Comment by alexjba** [comment] 2023-06-28 12:10
@IvanBelyakoff Do you have the same QML error?
The stack trace is quite different..

**Comment by caybro** [comment] 2023-06-28 12:12
> > Although to be fair this is also an error:
> > ```
> > Warning: Error while loading QML: QUrl("qrc:/main.qml") (:0, )
> > ```
> 
> True, QML qml is basically saying Warning, the app is crashing. smile It seems it can't link to StatusQ

Strictly speaking, it doesn't link to it - it fails loading it from QML; and this is the culprit:
```
Warning: qrc:/main.qml:18:1: plugin cannot be loaded for module "StatusQ": '/home/jakubgs/.cache/appimage-run/b83951061806c3b816a10004a307fab37208f40fd3385f1b305d1dc838da492d/usr/bin/StatusQ/libStatusQ.so' is not an ELF object (qrc:/main.qml:18, )
```

**Comment by jakubgs** [comment] 2023-06-28 12:14
Right, but if I start an older RC2 it works fine:
```
 > appimage-run StatusIm-Desktop-v0.13.0-rc.2-9d8f8c-x86_64.AppImage    
StatusIm-Desktop-v0.13.0-rc.2-9d8f8c-x86_64.AppImage installed in /home/jakubgs/.cache/appimage-run/a9e9ec7a88d5f5e203e1a7570a2ccc49bee70cfcd8d9b59246919aef4d81bd50
INFO [06-28|14:13:24.721] Status backend initialized               backend=geth version=0.158.1 commit=a46bf97bf IpfsGatewayURL=https://ipfs.status.im/
INF 2023-06-28 14:13:24.915+02:00 Version: 0.13.0-rc.2                       topics="status-app" tid=2 file=nim_status_client.nim:182
INF 2023-06-28 14:13:24.915+02:00 Commit: 9d8f8c5c9                          topics="status-app" tid=2 file=nim_status_client.nim:183
INF 2023-06-28 14:13:24.915+02:00 Current date:                              topics="status-app" tid=2 file=nim_status_client.nim:184 currentDateTime=2023-06-28T14:13:24+02:00
INF 2023-06-28 14:13:24.915+02:00 starting application controller...         topics="status-app" tid=2 file=nim_status_client.nim:186
Critical: 
ERROR: No native SystemTrayIcon implementation available.
Qt Labs Platform requires Qt Widgets on this setup.
Add 'QT += widgets' to .pro and create QApplication in main().
 (:0, )
Critical: 
ERROR: No native Menu implementation available.
Qt Labs Platform requires Qt Widgets on this setup.
Add 'QT += widgets' to .pro and create QApplication in main().
 (:0, )
INF 2023-06-28 14:13:46.315+02:00 starting application...                    topics="status-app" tid=2 file=nim_status_client.nim:189
```

**Comment by jakubgs** [comment] 2023-06-28 13:02
But we already rolled back GCC 11 usage in that issue.

**Comment by jrainville** [comment] 2023-06-28 13:17
I have the same trace stack as Ivan, with nothing useful

**Comment by jrainville** [comment] 2023-06-28 13:19
> But we already rolled back GCC 11 usage in that issue.

It seems like https://github.com/status-im/status-desktop/pull/11159 was only merged in master. I'll cherry-pick on release too

**Comment by jrainville** [comment] 2023-06-28 13:25
Cherry-pick: https://github.com/status-im/status-desktop/pull/11304

**Comment by alexjba** [comment] 2023-06-28 17:04
> Cherry-pick: #11304

It's fixing this issue?

The initial stack reported here is quite different.

**Comment by jrainville** [comment] 2023-06-28 17:05
I'm not sure. Maybe? It's better to have the same in the release at least.

**Comment by alexjba** [comment] 2023-06-28 17:08
> It's better to have the same in the release at least.

No doubt 😄 I was just wondering if this task can be closed.

**Comment by jrainville** [comment] 2023-06-28 17:13
We're trying to have a Linux build from the Release pipeline. We'll see then

**Comment by jrainville** [comment] 2023-06-29 16:59
I just tested a master PR build and it has the same issue.

I'll try to do a local build to see if it works

**Comment by jrainville** [comment] 2023-06-29 17:23
Local build from the `release/0.13.x` branch and it works fine. I'll check master but it should be the same

**Comment by jrainville** [comment] 2023-06-29 18:22
Local master build also works fine. So the issue is in the hosts or the Jenkinsfile.

**Comment by anastasiyaig** [comment] 2023-06-29 20:29
local build is fine , autotests were running against rc5 and even passed. something is off with ci artifact

**Comment by jrainville** [comment] 2023-06-30 13:07
> local build is fine , autotests were running against rc5 and even passed. something is off with ci artifact

just to clarify, I meant that locally built release packages work (using `linux-build.sh`)

**Comment by jrainville** [comment] 2023-07-05 18:04
We have found the issue and are working on a fix.

We found that the issue is indeed located in this commit: https://github.com/status-im/status-desktop/commit/dad8e453919519cf8a7e35391d6731fbcb7b110a

We first thought it was a red herring because the commit message is `ci: bump client build retries to 20` and in theory, that would mean that it was just a bump in the amount of retries, but no, that is **the** commit that adds the retries.

In doing so, we are changing a little bit how we create the build. We call `make nim_status_client` which uses the `development` param by accident, which makes it so that the build thinks it is in development, making it fail to write or read something.

The error message was very bad, but it did give a clue. Kudos to @osmaczko for spotting it.

@jakubgs is working on fixing it by forcing the release mode instead of development.

**Comment by jakubgs** [comment] 2023-07-05 18:06
Here's the fix:

* https://github.com/status-im/status-desktop/pull/11427

Thanks for the debugging @jrainville. Though I do think we should get rid of this `RESOURCES_LAYOUT` parameter and just detect if the app is running in an AppImage at runtime.

**Closed** 2023-07-05 19:37 UTC
Labels: bug, priority 0: blocker
