### ISSUE TITLE
Many @mentions in the chat body area are not highlighted

### ISSUE THREAD

**Issue by John-44** [status-im/status-desktop#3540] opened 2021-09-15 06:13 UTC
![2021-09-15 07_03_26-Status Desktop](https://user-images.githubusercontent.com/22846356/133379878-53d8095b-21cd-4d92-99ff-90c26ddae49d.png)

In the attached image above, notice how the "@Nastya" and "@simon" @ mentions are not highlighted in the way all @mentions are highlighted.

In this example, I've applied a name "Nastya" to @Nastya 's chat key (her account isn't using an ENS username).  @Simon 's account *does* use an ENS username.

----------------

Desired resolution:  All @mentions in the chat body should be highlighted and clickable.

**Comment by iurimatias** [comment] 2021-09-15 17:20
duplicate of #3492 (not just ENS)

**Closed by iurimatias** 2021-09-15 17:20 UTC
Labels: bug, Chat, Communities, phase 2c
