### ISSUE TITLE
authentication: Could not retrieve private key from keystore

### ISSUE THREAD

**Issue by yakimant** [status-im/status-desktop#12132] opened 2023-09-12 09:30 UTC
# Bug Report

## Description

macOS authentication issue and not able to diable "Biometric login and transaction authentication.

## Steps to reproduce

Not sure, how did I get here.

##### Trying to login
1. macOS authentication
![Screenshot 2023-09-12 at 10 58 18](https://github.com/status-im/status-desktop/assets/1529006/33b72286-6cc8-4b0f-80a2-910b0e8c3c63)

##### When trying to disable "biometric login"
1. Enabled
![Screenshot 2023-09-12 at 11 24 24](https://github.com/status-im/status-desktop/assets/1529006/b537e81c-bccc-46f9-9977-9f535cdc3de9)
2. Trying to disable
![Screenshot 2023-09-12 at 11 24 28](https://github.com/status-im/status-desktop/assets/1529006/ac4c368a-45ef-420f-9cb3-6534869c4b89)

#### Expected behavior

1. macOS authentication succeeds
2. "biometric login" can be disabled

##### Trying to login
1. Status failure
![Screenshot 2023-09-12 at 10 58 41](https://github.com/status-im/status-desktop/assets/1529006/0dde7705-2f4f-47c1-b986-4427e3f77e66)
2. Status authentication
![Screenshot 2023-09-12 at 10 58 48](https://github.com/status-im/status-desktop/assets/1529006/df90945b-8183-474f-ad03-a5482101abf4)

##### When trying to disable "biometric login", nothing happens:
1. Entering password
![Screenshot 2023-09-12 at 11 24 40](https://github.com/status-im/status-desktop/assets/1529006/57e2cd32-3f40-41e3-91f0-f14965af569f)
2. After entering the macOS password
![Screenshot 2023-09-12 at 11 24 50](https://github.com/status-im/status-desktop/assets/1529006/4b95f1b6-e3f2-4406-a353-e270edcfe0f4)

### Additional Information

- Status desktop version: 0.13.3
- Operating System: macOS 13.4.1

**Comment by endulab** [comment] 2024-01-17 13:17
I can't reproduce the problem. I enabled/disabled the feature a few times using old and newly created account.
Can you recheck if the issue still exists?

**Comment by yakimant** [comment] 2024-01-24 15:06
I confirm it still exists. Let me try with update to 0.15.0

**Comment by yakimant** [comment] 2024-01-24 15:12
Yes, I confirm both issues:
1. Can't disable biometric auth
2. Can't login with macos auth

**Comment by yakimant** [comment] 2024-01-24 15:14
Let me know if any help with debugging is needed.
This issue is quite annoying.

**Comment by saledjenic** [comment] 2024-03-04 08:21
Since entire password management need to be re-done, closing this in favor of https://github.com/status-im/status-desktop/issues/13785

**Closed by saledjenic** 2024-03-04 08:21 UTC
Labels: bug, wallet-team, E:Desktop Onboarding & Login, E:Desktop Misc Bugfixes, sprint-01-15
