### ISSUE TITLE
The image selection is not applied for the profile picture

### ISSUE THREAD

**Issue by elina2015** [status-im/status-desktop#5239] opened 2022-03-29 02:46 UTC
# Bug Report

## Steps to reproduce

1. Launch the app
2. Hit "I'm new to Status" - "Generate new keys"
3. Hit "+" and upload a photo for the profile image
4. Select a part of the image
5. Hit "Done"
6. Check the appeared profile picture

#### Expected behavior
The selected part of the image is applied as a profile picture
#### Actual behavior
The selected part of the image is NOT applied as a profile picture
### Additional Information

https://user-images.githubusercontent.com/14942081/160520742-4abadf6d-b281-4a29-8c18-5dde030ecad0.mov

- Status desktop version: commit dcab50fe0944f65a1fafef3fdb9e7abe66277b6c
- Operating System: MacOS Big Sur 11.6.5 (20G526)

**Comment by iurimatias** [comment] 2022-04-05 21:13
duplicate of https://github.com/status-im/status-desktop/issues/5241

**Closed by iurimatias** 2022-04-05 21:13 UTC
Labels: bug, Profile, onboarding, priority 2: medium, E:Bugfixes
