### ISSUE TITLE
Community -> Community recovered has multiple owners (users with crown indicator)

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#9745] opened 2023-03-06 10:21 UTC
### Description

<img width="1838" alt="Screenshot 2023-03-06 at 13 11 17" src="https://user-images.githubusercontent.com/82375995/223082422-1febfa1b-ee80-4f8a-b8cd-e970441b6df4.png">

there is community PK recovering which a lot of users are shown with crowns. The problem here, that all these users were not granted the owner node permissions (they did not recover the community with PK or being transferred the ownership)

I cant reproduce this with dogfooding community for some reason.

community PK: `0xaafff1b42a3c8f93f1f9b6e35459a085b555dc5adeca2c6bb8b8c01b42871722`

**Comment by anastasiyaig** [comment] 2023-03-06 10:25
@jrainville this is kinda an investigation task, it is very interesting why it is happening. Originally, the issue came from mobile QA team , @churik adding u for visibility too

**Comment by jrainville** [comment] 2023-09-25 16:53
Closing since I don't think we've reproduced ever since.
Feel free to reopen if it happens again

**Closed by jrainville** 2023-09-25 16:53 UTC
Labels: bug, hard-to-replicate, messenger-team, E:Desktop Bugfixes 0.15
