### ISSUE TITLE
There's a search location that shouldn't exist

### ISSUE THREAD

**Issue by PascalPrecht** [status-im/status-desktop#7659] opened 2022-09-29 11:09 UTC
![Screenshot from 2022-09-29 13-07-39](https://user-images.githubusercontent.com/445106/193016106-589b1e03-4d64-4796-8806-e0d2df7fd912.png)

Notice in the dropdown menu how there's "Status CC" and "Status" in the search locations.
I'm only part of the "Status CC" community, so I shouldn't see another community in my search locations.

This could be related to the fact that there's always one "Status" community in status-go, but this needs to be verified.

**Comment by iurimatias** [comment] 2022-10-03 14:26
duplicate of https://github.com/status-im/status-desktop/issues/7701

**Closed by iurimatias** 2022-10-03 14:26 UTC
Labels: bug, ui, Chat
