### ISSUE TITLE
[StatusChatInput] Mention is deleted by mouse selection

### ISSUE THREAD

**Issue by alexjba** [status-im/status-desktop#8745] opened 2022-12-12 16:09 UTC
### Description
Add mention, add text, hit backspace, click just before the mention's last character -> Mention is deleted.
Root cause: StatusChatInput onCursorPositionChanged processes text based on last known key used. In this case backspace, even if the cursor was moved by mouse.

https://user-images.githubusercontent.com/47811206/207095155-5e551df4-5cf6-4edb-9175-7bb18461413b.mov

Reproduced on MacOs

**Comment by alexjba** [comment] 2022-12-12 16:21
Found in: #7686

**Comment by glitchminer** [comment] 2022-12-13 11:52
@alexjba , what OS and app version is this for? I could not reproduce it on mac / 8.1

**Comment by alexjba** [comment] 2022-12-13 13:42
@glitchminer I've updated the description to be more specific on the steps. Tested again on master and 0.8.0 and I could reproduce it.

**Comment by alexandraB99** [comment] 2022-12-20 14:34
@benjthayer could you give some input here, what should a mouse click do when in a mention and what type of cursor should be shown?

**Comment by benjthayer** [comment] 2023-01-04 09:51
Hi @alexandraB99 the expected behaviour would be that if the user clicks the mention, it should be highlighted in its entirety - this makes it easy to use backspace to delete the entire mention without having to delete it one character at a time. I believe we could follow Discord on this for MVP. One enhancement might be to use the pointing hand cursor instead of the arrow cursor - this would provide a clearer indicator to the user that the entire mention will be selected on click. Hope that helps!

cc @John-44 

https://user-images.githubusercontent.com/110033914/210527652-6e844530-c0f7-45cb-adfb-d52e5a05b1d9.mov

**Comment by alexandraB99** [comment] 2023-01-13 15:22
@benjthayer thanks for the answer! currently a backspace will delete the entire mention, there is no way someone can delete it one character at a time, so this is already working. Concluding for this task, the only thing that needs to be done is to change the cursor to pointing hand when hovering a mention, and select the entire mention when clicking on it. Please correct me f I'm wrong

**Comment by benjthayer** [comment] 2023-01-16 09:37
@alexandraB99 Correct! Thanks! :)

**Comment by iurimatias** [comment] 2024-08-13 12:31
closing as this will be part of a wider rethink of this feature

**Closed by iurimatias** 2024-08-13 12:31 UTC
Labels: bug, ui-team, Desktop ChatInput Markdown/Refactor, E:D Msg Bugfixes MX
