### ISSUE TITLE
The Pending Requests counter is shown not in the full size

### ISSUE THREAD

**Issue by elina2015** [status-im/status-desktop#5924] opened 2022-05-31 01:34 UTC
# Bug Report

## Description
The Pending Requests counter is shown not in the full size - the top part of it appears partially
## Steps to reproduce
1. User A blocked and unblocked User B
2. User B sent a Contact Request to User A
3. User A went to Settings -> Messaging -> Contacts -> Pending
#### Expected behavior
The counter is shown correctly
#### Actual behavior
The counters looks incorrect - the top part is cropped
### Additional Information
<img width="1287" alt="image" src="https://user-images.githubusercontent.com/14942081/171075349-ba9a2552-8b89-482b-b5b1-a5b5cc3a8fc9.png">

- Status desktop version: [Build #2137 (May 30, 2022, 9:02:25 AM)](https://ci.status.im/job/status-desktop/job/branches/job/macos/job/master/2137/)
- Operating System: macOS Monterey 12.3 Beta (21E5227a) M1

**Comment by alexandraB99** [comment] 2022-06-28 12:50
@elina2015 can't reproduce this on current master, please check again.
<img width="387" alt="rq" src="https://user-images.githubusercontent.com/31625338/176182743-a64fd52a-c795-479b-a413-18cb52170301.png">

**Comment by Hbouaz** [comment] 2022-06-28 13:13
same here I cannot reproduce it on master, once Elina re-verifies we can close it

**Closed** 2022-08-03 15:19 UTC
Labels: bug, ui, priority 4: minor, E:Bugfixes, Settings
