### ISSUE TITLE
Community - member count number is not updated after a member leaves and member still shows in the member list

### ISSUE THREAD

**Issue by virginiabalducci** [status-im/status-desktop#15044] opened 2024-06-04 21:41 UTC
# Bug Report

## Description

When a community member leaves by themselves, the member list should be updated.
- Member should no longer display on the member list
- Member count should show correct member count (substract the member who left)

## Steps to reproduce

1. Log in with a user who is a member of a community
2. Take notice of the member count
3. Leave the community
4. Log in with a user member of the community (member or owner)
5. Notice the member count stays the same
6. Notice that the member who left is still showing on the member list.

#### Expected behavior
- Member count to update the member count to reflect current number after a user leaves the community.
- Member who left the community should not be showing in the member list
#### Actual behavior
- Member count does not update when a member leaves the community.
- Member who left the community should no longer show as a member of the community.

### Additional Information

Console log
```
Warning: Qt Quick Layouts: Detected recursive rearrange. Aborting after two iterations. (:0, )
Warning: Qt Quick Layouts: Detected recursive rearrange. Aborting after two iterations. (:0, )
Warning: Qt Quick Layouts: Detected recursive rearrange. Aborting after two iterations. (:0, )
Warning: qrc:/app/AppLayouts/Communities/panels/OverviewSettingsPanel.qml:176:17: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... } (qrc:/app/AppLayouts/Communities/panels/OverviewSettingsPanel.qml:176, )
ERR 2024-06-04 18:24:55.641-03:00 Unknown request                            topics="community-service" tid=189266 file=service.nim:791 msg="Community request not found: 0x729214cdf8e6cc513612ee931a6b5b8e90e754369803a118923ba1a56b7bb542"
INF 2024-06-04 18:25:14.369-03:00 history request completed                  topics="mailservers-service" tid=189266 file=service.nim:171
```
tested this with:
- logged in with a user who is the owner, but it is not logged on the control node device.
- logged in with a user who is not the owner, admin but a simple member.

May be related to issue https://github.com/status-im/status-desktop/issues/14994

- Status desktop version: 2.29.0-rc7
- Operating System: OS Sonoma 14.5

**Comment by caybro** [comment] 2024-06-05 08:20
That looks like a backend bug... we're taking the number straight from the model so it looks like role is not updated properly? CC @jrainville

**Comment by jrainville** [comment] 2024-06-05 17:42
> tested this with:
> 
> - logged in with a user who is the owner, but it is not logged on the control node device.
> - logged in with a user who is not the owner, admin but a simple member.

I don't think we can do much about this. Until the control node processes the member leaving, the member list won't update.

We could try to do some client side patching of the community description, but it's extra work and is error prone, so I'm reluctant to do it.

Maybe there would be something else I'm missing? cc @mprakhov @osmaczko

**Comment by jrainville** [comment] 2024-06-05 18:03
Either we keep this opened for a long time as a bug/feature to address once we have time, or we close as it's relatively an edge case (Alice knows that Bob left but still sees him) and an expected behaviour with the current control node flow.

**Comment by jrainville** [comment] 2024-07-19 18:55
Closing as won't fix. This is the expected behaviour on a technical side. The UX is not amazing, but it's a rare case where Alice will know that Bob left and still look at the member list

**Closed by jrainville** 2024-07-19 18:55 UTC
Labels: bug, backend-team, E:D Comm Bugfixes 2.30
