### ISSUE TITLE
 Users unable to use the return key instead of clicking the ‘Continue’ primary action button in the 'Back up your seed phase' dialog.  

### ISSUE THREAD

**Issue by imagiMary** [status-im/status-desktop#10186] opened 2023-04-05 10:48 UTC
Version: V0.11.0-rc.2
OS: Ubuntu 22.10

Precondition: User has not backed up seed phrase yet.

<ins>Steps to reproduce:</ins>

1. Navigate to Setting / Back up seed phrase.

2. Navigate through the ‘Back up your seed phrase’ flow until Step 2 of 4.

3. Enter the requested seed phrase word into the text field and press the `return` key.

<ins>What currently incorrectly happens:</ins>

4. When the user presses `return` on their keyboard, nothing happens.

<ins>What is supposed to happen:</ins>

4. Pressing the `return` key should carry out the default command of the dialog. E.g. pressing the `return` key should be the same as the user clicking the ‘Continue’ primary action button. 

<ins>Other information</ins>
![03 27 Back up you seed phrase Step 2 of 4](https://user-images.githubusercontent.com/124154641/230057909-167139e9-a252-4204-a8a5-38d9a9f8ccb6.png)

**Comment by caybro** [comment] 2023-04-05 11:15
Ye... kbd handling is missing in general, in most components :/

**Comment by anastasiyaig** [comment] 2023-04-05 12:27
@imagiMary we just dont have it implemented in general. It works in some cases but thats all. I think there is a plan to implement shortcuts after MVP

**Comment by caybro** [comment] 2023-07-26 13:37
Dupe of https://github.com/status-im/status-desktop/issues/8309

**Closed by caybro** 2023-07-26 13:37 UTC
Labels: bug, ui-team
