### ISSUE TITLE
Community thumbnail is cut when cropped

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#2411] opened 2021-04-23 08:46 UTC
<img width="485" alt="Снимок экрана 2021-04-23 в 11 44 28" src="https://user-images.githubusercontent.com/82375995/115845237-5153e880-a429-11eb-9595-ad93ec45a911.png">

1. Install app
2. Enable Community in preferences
3. Create new community
4. add a picture

**Version:** `0.1.0-beta.9`, master build 23-04-2021

**Comment by jrainville** [comment] 2021-04-30 14:51
Closing because it is a duplicate of #2224 and the solution is to use a new API that is only available in QT 5.15, but we are waiting to do that because 5.15 has other issues

**Closed by jrainville** 2021-04-30 14:51 UTC
Labels: Communities, bug
