### ISSUE TITLE
[dogfooding] [BLOCKER] Application fails to open - Windows

### ISSUE THREAD

**Issue by Samyoul** [status-im/status-desktop#8162] opened 2022-11-08 11:53 UTC
# Bug Report

## Description

I install the application, run the application, nothing appears to happen, the application never loads.

I've monitors the system processes and it seems that the application does start a background process and starts loading data into system memory, memory usage gets to about 400 MB, then the process just terminates and that is the end.

## Steps to reproduce

Double click the Status application icon, nothing happens.

#### Expected behavior

The application opens

#### Actual behavior

The application does not open

### Additional Information

- Status desktop version: 0.7.0
- Operating System: Windows 10 Pro,

AMD FX-8370 Eight-Core-Processor 4.00 GHz
64-bit Operating System,
x64 based processor
32 GB RAM

**Comment by PascalPrecht** [comment] 2022-11-09 10:04
Possibly a dup of https://github.com/status-im/status-desktop/issues/8119

**Comment by iurimatias** [comment] 2022-11-15 19:32
duplicate of https://github.com/status-im/status-desktop/issues/8119

**Closed by iurimatias** 2022-11-15 19:32 UTC
Labels: bug, windows
