### ISSUE TITLE
An empty string is shown instead of emoji or message with emoji on a community channel

### ISSUE THREAD

**Issue by elina2015** [status-im/status-desktop#7653] opened 2022-09-29 06:15 UTC
# Bug Report

## Steps to reproduce
1. Open any channel and send an emoji or message with an emoji

#### Expected behavior
emoji or messages with emojis are shown correctly on a community channel 
#### Actual behavior
An empty string is shown instead of an emoji or a message with emoji in a community channel
### Additional Information

https://user-images.githubusercontent.com/14942081/192953363-8e781d40-c085-4038-bab1-8e749034904a.mov

- Status desktop version: https://ci.status.im/job/status-desktop/job/platforms/job/macos/221
- Operating System: macOS Monterey

**Comment by caybro** [comment] 2022-09-29 08:14
@endulab possible dupe of https://github.com/status-im/status-desktop/issues/7622

**Comment by endulab** [comment] 2022-09-29 10:09
Fixed in #7622

**Closed by endulab** 2022-09-29 10:09 UTC
Labels: bug, Communities, priority 1: high
