### ISSUE TITLE
Underscores in @mentions are treated as italic markup

### ISSUE THREAD

**Issue by igor-sirotin** [status-im/status-desktop#8475] opened 2022-11-28 11:27 UTC
# Bug Report

## Description

Text: `@lukas_tinkl @Patryk @Michal_Prime`

<img width="682" alt="image" src="https://user-images.githubusercontent.com/25482501/204266512-b1f57ce3-3703-4869-9933-f459209f065d.png">

**Comment by jrainville** [comment] 2022-11-28 15:40
https://media.giphy.com/media/kc0kqKNFu7v35gPkwB/giphy.gif

**Comment by caybro** [comment] 2022-11-29 10:04
You know what... I can't reproduce on Qt 5.15 :)

![image](https://user-images.githubusercontent.com/5377645/204499679-0c13d7a4-3832-4d2b-8600-911a6920b87a.png)

**Comment by anastasiyaig** [comment] 2022-11-29 14:05
i just was able to reproduce in master but i am using old QT 5.14.2, did not know we switched to 5.15

<img width="633" alt="Screenshot 2022-11-29 at 17 03 55" src="https://user-images.githubusercontent.com/82375995/204549934-52d545c8-178e-4c3d-b438-50d558a799b9.png">

**Comment by caybro** [comment] 2022-11-29 14:12
> i just was able to reproduce in master but i am using old QT 5.14.2, did not know we switched to 5.15
> 
> <img alt="Screenshot 2022-11-29 at 17 03 55" width="633" src="https://user-images.githubusercontent.com/82375995/204549934-52d545c8-178e-4c3d-b438-50d558a799b9.png">

We didn't (officially), I'm just pointing out to the fact it might very well be a Qt issue... in which case good luck to us fixing it :)

**Comment by alexandraB99** [comment] 2023-01-13 15:25
Design spec provided and will be implemented here https://github.com/status-im/status-desktop/issues/8464

**Comment by caybro** [comment] 2023-01-13 15:34
@alexandraB99 I believe this could be (easily) fixed in StatusSyntaxHighlighter.cpp

**Comment by alexandraB99** [comment] 2023-01-25 10:54
> @alexandraB99 I believe this could be (easily) fixed in StatusSyntaxHighlighter.cpp

that's true, nevertheless we do have now [design specs for mentions](https://www.figma.com/file/Mr3rqxxgKJ2zMQ06UAKiWL/%F0%9F%92%AC-Chat%E2%8E%9CDesktop?node-id=21104%3A500080) which we need to implement so all cases will be handled there.

**Comment by jrainville** [comment] 2023-03-01 15:22
Superseded by https://github.com/status-im/status-desktop/issues/9698

**Closed by jrainville** 2023-03-01 15:22 UTC
Labels: bug, Chat, priority 3: low, E:Bugfixes, S:3
