### ISSUE TITLE
Contacts details are fetched for not joined communites

### ISSUE THREAD

**Issue by osmaczko** [status-im/status-desktop#16641] opened 2024-10-29 09:00 UTC
### Description

As noted by @anastasiyaig, there are numerous consecutive logs for `getContactById` for newly created accounts. This occurs because we fetch curated community details to display them correctly in the communities portal. As a result, we also fetch all member details, which is incorrect. Stack trace:

```
/status/status-desktop/src/nim_status_client.nim(252) mainProc                                                                                           09:41:40 [1826/1845]
/status/status-desktop/vendor/nimqml/src/nimqml/private/qguiapplication.nim(29) exec                                                                                         
/status/status-desktop/vendor/nimqml/src/nimqml/private/qobject.nim(52) qobjectCallback                                                                                      
/status/status-desktop/vendor/nimqml/src/nimqml/private/qobject.nim(37) onSlotCalled
/status/status-desktop/vendor/nimbus-build-system/vendor/Nim/lib/core/macros.nim(559) onSlotCalled
/status/status-desktop/src/app/core/signals/signals_manager.nim(63) receiveSignal
/status/status-desktop/src/app/core/signals/signals_manager.nim(60) processSignal
/status/status-desktop/src/app/core/eventemitter.nim(58) emit
/status/status-desktop/src/app_service/service/community/service.nim(343) :anonymous
/status/status-desktop/src/app_service/service/community/service.nim(533) handleCommunityUpdates
/status/status-desktop/src/app/core/eventemitter.nim(58) emit
/status/status-desktop/src/app/modules/main/communities/controller.nim(90) :anonymous
/status/status-desktop/src/app/modules/main/communities/io_interface.nim(107) communityAdded
/status/status-desktop/src/app/modules/main/communities/module.nim(318) communityAdded
/status/status-desktop/src/app/modules/main/communities/io_interface.nim(37) getCommunityItem
/status/status-desktop/src/app/modules/main/communities/module.nim(209) getCommunityItem
/status/status-desktop/src/app/modules/main/communities/module.nim(183) createMemberItem
/status/status-desktop/src/app/modules/main/communities/controller.nim(342) getContactDetails
/status/status-desktop/src/app_service/service/contacts/service.nim(408) getContactDetails
/status/status-desktop/src/app_service/service/contacts/service.nim(323) fetchContact
/status/status-desktop/src/backend/contacts.nim(13) getContactById
```

**Comment by caybro** [comment] 2024-10-29 09:10
Related to (or dupe of?) https://github.com/status-im/status-desktop/issues/16509

**Comment by osmaczko** [comment] 2024-10-29 09:48
> Related to (or dupe of?) [#16509](https://github.com/status-im/status-desktop/issues/16509)

Similar but not a duplicate. Once the community is joined, the https://github.com/status-im/status-desktop/issues/16509 persists.

**Closed** 2024-11-01 14:32 UTC
Labels: goal:core:P1:memory_usage_community, goal:core:P1:cpu_usage_community, goal:core:P1:idle_cpu_usage
