### ISSUE TITLE
Data is not restored from Waku when recovering account 

### ISSUE THREAD

**Issue by qoqobolo** [status-im/status-desktop#12797] opened 2023-11-20 12:15 UTC
# Bug Report

## Description

Facing an issue with restoring my main user on Desktop: data from waku (communities, contacts) is not restored.

Preconditions:
1. I deleted the Status folder and installed this release build: https://ci.infra.status.im/job/status-desktop/job/release/job/release%2F0.15.x/14/
2. Recovered my user from the seed phrase

Result: empty account.
There were many contacts and communities there, including the Status CC community, but now there's nothing there.

I tried to recover the same user on mobile (on release as well), and all communities and contacts were restored from waku.
After that, I tried to perform a backup on mobile, and then restore the user again on desktop, but it didn’t work.

Some other users faced the same issue before. Ping @pavloburykh and @VolodLytvynenko for more details if needed. 

## Steps to reproduce

1. Delete the Status folder from your machine
2. Install Status Desktop 
3. Recover your user with seed phrase

#### Expected behavior
Communities and contacts are restored

#### Actual behavior
No communities and contacts

### Additional Information

- Status desktop version: https://ci.infra.status.im/job/status-desktop/job/release/job/release%2F0.15.x/14/
- Operating System: MacBook pro, Ventura 13.6.1, Intel

**Comment by anastasiyaig** [comment] 2023-11-20 12:43
I am not receiving anything from waku today as well (yes , there is some data i am expecting to be recovered)

<img width="1512" alt="Screenshot 2023-11-20 at 15 42 52" src="https://github.com/status-im/status-desktop/assets/82375995/cdac5c99-7c08-4dc7-a706-ba46e263adbc">

**Comment by anastasiyaig** [comment] 2023-11-20 12:44
@saledjenic is it something u can investigate?

**Comment by qoqobolo** [comment] 2023-11-20 12:52
> I am not receiving anything from waku today as well (yes , there is some data i am expecting to be recovered)

This screen **is not** even shown to me btw 
<img width="791" alt="Screenshot 2023-11-20 at 13 45 49" src="https://github.com/status-im/status-desktop/assets/67952253/fd26d73f-96a7-4044-b4ce-b3d9f75603c3">

That's how it looks like to me after importing the seed


https://github.com/status-im/status-desktop/assets/67952253/aaba7681-35bc-4b91-b989-f8d1f1693f6f

**Comment by jrainville** [comment] 2023-11-20 14:51
> This screen is not even shown to me btw

@qoqobolo do you remember if you chose the option `I am new to Status` or `I already use Status`? I'm asking this, because we do not try to fetch the data if the user selects `new to Status` since wouldn't have anything on the store nodes.

**Comment by qoqobolo** [comment] 2023-11-20 15:05
> do you remember if you chose the option I am new to Status or I already use Status? I'm asking this, because we do not try to fetch the data if the user selects new to Status since wouldn't have anything on the store nodes.

Oh I didn't know about this difference 🤔
On mobile, if you chose `I already use Status` you can only go through the syncing flow, there is no option to recover your acc with a seed phrase. 

So, the answer is: I used the `I am new to Status` option.

I will try the same user and the `I already use Status` option and get back with the result

**Comment by qoqobolo** [comment] 2023-11-20 15:41
I was hanging on this screen for about 30 min, the numbers were not changing.
Then I pressed `Continue` and got an error.
Should I have waited longer? I can try it one more time.

<img width="495" alt="Screenshot 2023-11-20 at 16 31 02" src="https://github.com/status-im/status-desktop/assets/67952253/c6e0adcf-56c8-4091-b1ac-084a9db28c66">

<img width="549" alt="Screenshot 2023-11-20 at 16 34 10" src="https://github.com/status-im/status-desktop/assets/67952253/7296c3d6-2a58-4926-898a-289f350bcade">

---

@jrainville and question about the difference in flow between mobile and desktop (that on mobile you can only use the seed phrase when you choose `I am new to Status`, and on desktop in both cases, but data fetching will be triggered only in one of them), do you know if this was done on purpose?
Perhaps this should be discussed.

**Comment by qoqobolo** [comment] 2023-11-20 15:47
Oh wait! After reopening the app I see all my data despite the error. 
So for me it works fine now (well, almost :)).

But for @anastasiyaig and @VolodLytvynenko the data was never restored, so I believe the issue is still relevant.
Otherwise, feel free to close it.

**Comment by jrainville** [comment] 2023-11-20 15:54
> I was hanging on this screen for about 30 min, the numbers were not changing.

I think it no longer fetches when it says continue. You'd need to press "Try to fetch profile again" for it to try some more.

> Then I pressed Continue and got an error.

What was the error?

> Should I have waited longer? I can try it one more time.

Maybe pressing "Try to fetch profile again" could have helped. It seems like it did find some data, since it shows the denominator.

> Oh wait! After reopening the app I see all my data despite the error.

Ok, so maybe we just failed at reporting that it worked? :thinking: 

> But for @anastasiyaig and @VolodLytvynenko the data was never restored, so I believe the issue is still relevant.
Otherwise, feel free to close it.

I'll try to reproduce later and see if I can find an answer. That feature is always hard to debug, because sometimes it's just the store nodes being annoying.
Pairing is a way better way to share an account between devices haha.

> @jrainville and question about the difference in flow between mobile and desktop (that on mobile you can only use the seed phrase when you choose I am new to Status, and on desktop in both cases, but data fetching will be triggered only in one of them), do you know if this was done on purpose?
Perhaps this should be discussed.

I'm not sure who the designer was for the Desktop onboarding, but yeah, it was done on purpose. If you select "New to Status", it makes no sense to try to fetch data for that account, since it's completely new.

As for the difference between mobile and desktop, I agree that we should resolve it.

I don't have hard opinions on whether it should be mobile adopting the Desktop design of having new vs old user, or Desktop adopting the mobile way of old user only using Pairing.

On one hand, I agree that if you already have Status, using Pairing is 100% better than seed phrase, however, if you did lose your other device, or your account got deleted or corrupted, you might not have the option to pair, so using the seed phrase to recover the data is nice.

I guess it's important in that case to make the options clear to the user, so they know what to expect.

**Comment by qoqobolo** [comment] 2023-11-20 15:57
> What was the error?

This one
<img width="508" alt="Screenshot 2023-11-20 at 16 55 57" src="https://github.com/status-im/status-desktop/assets/67952253/741d475e-bf0e-4d48-81ee-9fcc230c20bb">

**Comment by qoqobolo** [comment] 2023-11-20 15:58
> As for the difference between mobile and desktop, I agree that we should resolve it.

Okay, I'll pass this on for further discussion from the mobile side

**Comment by jrainville** [comment] 2023-11-20 16:46
> But for @anastasiyaig and @VolodLytvynenko the data was never restored, so I believe the issue is still relevant.
Otherwise, feel free to close it.

I can reproduce. I had manually backed up the data from my other desktop account on the same version and it never fetched anything.

Considering it worked for Diana, it seems like maybe the back up works for mobile and not desktop?

I hope it helps you investigate  @saledjenic

**Comment by saledjenic** [comment] 2023-11-22 10:10
@qoqobolo the difference between:
1. `I am new to Status` and 
2. `I already use Status` 

is that for the first option if you provide a seed phrase we assume that the seed phrase was generated somewhere else and the user has never before associated that seed phrase with the Status app. 

The second option (`I already use Status`) should be used to sync from the other device (if the user has it) and only in case the user really doesn't have another device (lost it) should go to the step to recover the data using seed phrase or keycard.

Of course user may use an already used seed phrase in the first case as well as a new seed phrase (generated out of the Status app) in the second case, but those are not the cases we are taking care of and we cannot guarantee for the data consistency in those cases cause we don't have a central server to check if that seed phrase was associated with the Status app before or not.

Additionally, if the user provided a seed phrase that was already used in the Status app for the first flow, we don't fetch backed-up data in that case. So it looks like the user has created a brand new Status account using the wanted seed phrase. In the second case if:
- data are fully fetched the user proceeds to the app and all good, has everything he had before, 
- data are partially fetched (the profile-related data are mandatory) other data can be fetched and applied later when they arrive (if not changed locally, cause in that case those will be the newest valid data)
- data are not fetched then you have an option to create a new Status account using a previously used seed phrase, but it would look like you followed the first option, providing a known seed phrase. 

Some reasons why data are not fetched could be:
- there is no backed-up data for the seed phrase
- there is no data for the seed phrase on the nodes the user is connected to

One more thing we should be aware of is if we use the "old" seed phrase, following the first option (`I am new to Status` onboarding flow) after you log in to the app, the backup can be created with an empty app state (no contacts, no communities, no wallet accounts...) that will make that backup the most recent one and any previously backed up data won't be considered as valid after that if you try to recover using that seed phrase.

Ofc at the end it might be some bug in the desktop app code, but the way to check if the recovering feature works or not is:
- create a brand new Status account (seed phrase that was not used before)
- add some wallet accounts, contacts... basically any details we're backing up
- for the dev builds we should have "Backup data" available on the Settings/Syncing screen and click it
- then remove the local Status folder and try to recover using the seed phrase you are sure you have backed up the data for
- if all is recovered then the feature works (and we can assume that in some cases waku doesn't send data for other seed phrases, where the reasons might be one of the two above-mentioned) if not, then we have an issue on the desktop app side.

**Comment by qoqobolo** [comment] 2023-11-22 11:28
Hey @saledjenic, thanks for the detailed explanation! It was good to get deeper insights into how this feature works.
But the difference between `I am new to Status` and `I already use Status` flows (in terms of restoring data) is already clear to me. 

What I'm still concerned about is that we have the difference between _mobile_ and _desktop_ in these flows.

**Desktop:**
you can choose either `I am new to Status` or `I already use Status` and there will be the option to use your seed phrase (with the difference you described above)

**Mobile:**
- if you choose `I am new to Status` you can create a brand new account OR you can use your "old" seed phrase _and your backed up data will be restored_;
- if you choose `I already use Status` **you can only sync your device with another one** (no option to use your seed)

And in fact, both approaches make sense, but I think it also makes sense to discuss whether we need this difference in the functionality. 

Perhaps @John-44 might also have some thoughts on this matter. Please take a look at this whenever you have spare time (starting from [this comment](https://github.com/status-im/status-desktop/issues/12797#issuecomment-1819212822)).

**Comment by John-44** [comment] 2023-11-22 12:17
> * if you choose `I already use Status` **you can only sync your device with another one** (no option to use your seed)

@qoqobolo this is only because this hasn't been built yet, it's all in the designs.  When more of the mobile onboarding designs are built, mobile will become functionally aligned with desktop here.

The issue is that desktop has all the required onboarding functionality, and currently mobile has only built a subset of the required onboarding functionality.

**Comment by qoqobolo** [comment] 2023-11-22 12:34
Thanks for the clarification @John-44!
No more questions or issues from my side.

**Comment by anastasiyaig** [comment] 2023-11-22 12:38
@qoqobolo are we happy to close this task?

**Comment by qoqobolo** [comment] 2023-11-22 12:49
> are we happy to close this task?

If there is no longer any need to investigate the cases you and @jrainville mentioned (https://github.com/status-im/status-desktop/issues/12797#issuecomment-1819439254), then yes sure let's close it

**Comment by jrainville** [comment] 2023-11-22 17:11
I know I couldn't fetch the data from my account after manually backing up, but I know that there were issues on the status-go side that affected the retrieval of messages. Hopefully once [this](https://github.com/status-im/status-go/pull/4360) is merged, it works. I'll test again once it is merged.

**Comment by jrainville** [comment] 2023-11-22 18:46
I'm using latest develop including the fix posted above and it seems to work fine:
![image](https://github.com/status-im/status-desktop/assets/11926403/382931d1-4fbc-41e5-b220-dd2dce33f448)

I'll close the issue

**Closed by jrainville** 2023-11-22 18:46 UTC
Labels: bug, wallet-team, E:Desktop Bugfixes 0.15
