### ISSUE TITLE
Outgoing pending CR notification does not show valid contact details

### ISSUE THREAD

**Issue by MishkaRogachev** [status-im/status-desktop#10400] opened 2023-04-24 08:04 UTC
<img width="571" alt="Screenshot 2023-04-24 at 12 07 29" src="https://user-images.githubusercontent.com/2522130/233936673-342c9e9b-b56a-428d-a2bc-e1dd1fa2577d.png">
Initial outgoing pending contact request notification does not show valid contact details, only public key is available

**Comment by MishkaRogachev** [comment] 2023-05-15 09:55
Tried top fix it using `requestContactInfo` [here](https://github.com/status-im/status-desktop/pull/10613), but it does not return valid details for a fresh contact. Need further investigation

**Comment by jrainville** [comment] 2023-06-13 17:13
I moved this out of 0.13. 

As I explain in the comment on the PR I had created (https://github.com/status-im/status-desktop/pull/10961#issuecomment-1589708743), this issue cannot be solved by using `requestContactInfo`, because the root cause is that the contacts haven't been online for more than 9 days.

Without my changes, I was able to get the right display name by logging in and forcing a contact update, then the account seeing the 3 word name updated from the mailserver.

So we can't actually fix this problem 100%. We cannot ensure that the contact info of someone will be propagated in the last 9 days.It's the same for https://github.com/status-im/status-desktop/issues/8022.

We could use new designs to just show something else than the 3 word name, but it still wouldn't be the display name.
Otherwise, we could increase the mailsever fetch range, but the issue still happens for accounts older than the new cut off date.

**Comment by iurimatias** [comment] 2024-01-26 17:23
Patryk says: not a bug

**Comment by iurimatias** [comment] 2024-02-14 19:12
moved to 2.39

**Comment by jrainville** [comment] 2024-08-26 15:21
Closing as there isn't much we can do about it. If it doesn't fetch the display name when sending the request, it probably won't won,t in the AC.
It fixes itself when the other person accepts (the acceptance contains the display name)

**Closed by jrainville** 2024-08-26 15:21 UTC
Labels: E:Desktop Contact Requests, Desktop Contact Requests, core-team
