### ISSUE TITLE
When writing a message, sometimes the @mention menu opens up when there is no at mention

### ISSUE THREAD

**Issue by John-44** [status-im/status-desktop#3544] opened 2021-09-15 06:39 UTC
When writing a message, sometimes the @mention menu opens up when there is no at mention e.g. click with a mouse on a random word and the at mention menu opens.  This seems more likely to happen if an @mention is deleted from a message that is being written in the message entry box.

**Comment by iurimatias** [comment] 2021-09-20 17:41
duplicate of #3535

**Closed by iurimatias** 2021-09-20 17:41 UTC
Labels: bug, Chat, Communities, phase 2c
