### ISSUE TITLE
1:1 Chat --> Reply to contact request shows after initial contact request message

### ISSUE THREAD

**Issue by benjthayer** [status-im/status-desktop#8405] opened 2022-11-23 13:34 UTC
**Issue:**
I sent a contact request to Pascal. His message in reply came through later but is shown in the 1:1 chat as coming before my contact request message. The `Today` and `Yesterday` markers are also shown in the wrong order.

**Expected behaviour:**
I would expect the contact request message I sent to be above the contact request reply in the chat given it was sent first. I would also expect the `Yesterday` marker to be above the `Today` marker.

<img width="911" alt="Screenshot 2022-11-23 at 13 30 32" src="https://user-images.githubusercontent.com/110033914/203559045-67e8871a-a66b-4f76-8333-0213ac8bae2e.png">

cc @PascalPrecht

**Comment by jrainville** [comment] 2022-12-08 21:53
Closing as a duplicate of https://github.com/status-im/status-desktop/issues/8466 (even though this one is older, the newer one has more info and already assigned)

**Closed by jrainville** 2022-12-08 21:53 UTC
Labels: Design-QA
