### ISSUE TITLE
Open last channel viewed after navigating to other tab

### ISSUE THREAD

**Issue by hesterbruikman** [status-im/status-desktop#3607] opened 2021-09-20 09:22 UTC
## Current
When navigating away from a community chat to any other tab (e.g. browser to open a channel, settings/profile or wallet) and coming back, the community chat opens on the first channel in the list of community channels

## Expected
When navigating away from a community chat to any other tab and coming back, the community chat opens on the last channel viewed in the community chat.

**Comment by alaibe** [comment] 2021-09-20 11:44
I think this has been fixed via: https://github.com/status-im/status-desktop/pull/3597 @Khushboo-dev-cpp

**Comment by iurimatias** [comment] 2021-09-20 17:21
duplicate of 3486

**Closed by iurimatias** 2021-09-20 17:21 UTC
