### ISSUE TITLE
it takes more than 1 minute to run 0.10.0 release on mac m1

### ISSUE THREAD

**Issue by flexsurfer** [status-im/status-desktop#10079] opened 2023-03-30 07:10 UTC
https://user-images.githubusercontent.com/11790366/228757001-3f094949-885b-401c-a3c3-d7a5d23dab52.mov

the app just hangs after 10 sec for ~40 seconds

**Comment by iurimatias** [comment] 2023-05-03 14:12
closing as duplicate of other tasks looking to improve startup time. the situation is also a bit better on apple silicon builds

**Closed by iurimatias** 2023-05-03 14:12 UTC
Labels: bug
