### ISSUE TITLE
Ctrl-V in chat should load/paste image content in clipboard

### ISSUE THREAD

**Issue by n-boc** [status-im/status-desktop#4063] opened 2021-11-08 15:44 UTC
e.g. take a screenshot, expect ctrl-v in chat to upload image. Current behavior requires user manually saving the screenshot to a file. 

Signal, for example, supports pasting clipboard content and doesn't automatically send it either. This is ideal.

**Comment by iurimatias** [comment] 2022-01-02 18:43
duplicate of #3591

**Closed by iurimatias** 2022-01-02 18:43 UTC
