### ISSUE TITLE
move reverse list fix in the chat messages list view

### ISSUE THREAD

**Issue by iurimatias** [status-im/status-desktop#2640] opened 2021-06-02 20:50 UTC

**Comment by richard-ramos** [comment] 2021-06-16 17:06
This was possibly fixed with #2712, since I was not able to reproduce the issue anymore with QT 5.15.2. Also this fix is necessary for proper positioning of the messages:

> ListView.BottomToTop - Items are laid out from the bottom of the view up to the top of the view.

**Comment by richard-ramos** [comment] 2021-06-16 17:07
cc: @PascalPrecht for helping me test in macos since he was the one having this error before

**Comment by richard-ramos** [comment] 2021-06-17 13:25
Looks like this is not an issue anymore! :)
https://github.com/status-im/status-desktop/pull/2712#issuecomment-863084710

**Closed** 2021-08-03 00:15 UTC
Labels: refactor
