### ISSUE TITLE
Browser Fingerprint protection

### ISSUE THREAD

**Issue by 3esmit** [status-im/status-desktop#1274] opened 2020-11-02 21:31 UTC
Status browser should by default randomize browser agent and other details (like volume, etc) to avoid fingerprinting users.

This is done by other privacy focused browsers, like Firefox and Brave. However more extensive measures can break the functionality of the website. 

For web3 this wouldn't be necessary, if the web3 dapps would be sandboxed to only have access to decentalized systems.

**Comment by iurimatias** [comment] 2021-01-19 22:42
adding to ideas list for the browser improvements, this is a duplicate of the ad & tracking blocker feature for the browser

**Closed by iurimatias** 2021-01-19 22:42 UTC
Labels: Browser, enhancement
