### ISSUE TITLE
can't add custom token

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#4040] opened 2021-11-04 09:44 UTC
<img width="1440" alt="Screenshot 2021-11-04 at 12 44 13" src="https://user-images.githubusercontent.com/82375995/140292173-4e66ab4d-bcbb-4685-a190-277399b4a8a3.png">

1. open status
2. enable wallet
3. click assets -> add custom token
4. in the address put this details: https://etherscan.io/address/0xeEf5E2d8255E973d587217f9509B416b41CA5870#code
5. check console

```
INF 2021-11-09 10:48:15.593+03:00 getPinnedMailserver                        topics="mailserver-interaction" tid=2124555 file=settings.nim:100 fleet=eth.prod result=
qrc:/app/AppLayouts/Wallet/popups/AddCustomTokenModal.qml:60: TypeError: Property 'getTokenDetails' of object Model(0x7f9a9447c600) is not a function
```

```
qrc:/app/AppLayouts/Wallet/popups/AddCustomTokenModal.qml:60: TypeError: Property 'getTokenDetails' of object Model(0x7f9d65ce87a0) is not a function
```

**Comment by anastasiyaig** [comment] 2021-11-09 07:52
not sure why it was closed, cuz the custom token can't be added still

**Comment by jrainville** [comment] 2021-11-09 14:28
I think it was closed automatically because my PR was merged. I have to say though that I never was able to reproduce the issue.
I found issues with getting the balance of custom tokens, so I fixed those, but maybe there is something else.
@anastasiyaig were you testing in a particular network? Ropsten, Mainnet?

**Comment by anastasiyaig** [comment] 2021-11-09 14:30
@jrainville it is mainnet, i am using this as source for testing https://ethereum.stackexchange.com/questions/38743/where-can-i-find-erc20-token-faucets-for-testing and it was working before

**Comment by jrainville** [comment] 2021-11-09 14:42
Ok, I'll try with your link

**Comment by jrainville** [comment] 2021-11-09 15:09
I can reproduce the error in the console. I think I hadn't noticed, because the token is really added, but indeed ,the value is not fetched. Fixing it right now

**Closed** 2021-11-11 14:58 UTC
Labels: bug, refactor
