### ISSUE TITLE
Adding an emoji reaction to the last (bottom) message doesn't scroll/show it

### ISSUE THREAD

**Issue by jrainville** [status-im/status-desktop#9061] opened 2023-01-11 14:24 UTC
# Bug Report

## Description

If you add an emoji reaction to the last message of a channel at the bottom, you can't see the reaction until you scroll, so it looks like it didn't work.

## Steps to reproduce

1. Go to a channel with messages or add one yourself
2. Scroll all the way down
3. Add a reaction to the last message
Result: can't see it

#### Expected behavior

The chat scrolls down so we stay at the bottom

The simple way of doing it is to force a scroll down when sending the reaction.
The (maybe) harder way, but the best way, would be to enforce that if we are at the bottom of the chat, it should stick there, so if there are new messages from anyone, we stay at the botom (like a magnet)

**Comment by caybro** [comment] 2023-01-12 11:47
I can reproduce but now always...

**Comment by borismelnik** [comment] 2023-01-12 11:56
okay, will try it :) but when you reload the app it helps?

**Comment by jrainville** [comment] 2023-01-12 16:05
I can consistently reproduce:

[Screencast 2023-01-12 11:04:01-emoji.webm](https://user-images.githubusercontent.com/11926403/212118582-c8340f45-865c-405f-917a-53db5bdc1082.webm)

I had to manually scroll each time.

**Comment by jrainville** [comment] 2023-01-12 20:45
It happens also when a link (eg Github) unfurls.

**Comment by alexandraB99** [comment] 2023-12-05 11:48
Can't reproduce on current master - closing 


https://github.com/status-im/status-desktop/assets/31625338/aa4ba3e8-bb5c-4b4f-9db8-a04cb327413c

**Closed by alexandraB99** 2023-12-05 11:48 UTC
Labels: bug, ui-team, E:Desktop Features 0.16, E:Desktop Bugfixes 0.16
