### ISSUE TITLE
Fetching messages not behaving as expected after restoring from seed phrase

### ISSUE THREAD

**Issue by glitchminer** [status-im/status-desktop#8291] opened 2022-11-16 15:54 UTC
# Bug Report

## Description

Log into a fresh instance of 0.8.0 beta RC1

## Steps to reproduce

Restore an account from seed phrase. Navigate to Status CC community.

#### Expected behavior

1. Default number/days of messages are known and loaded
2. Clicking on fetch earlier messages retrieves the expected number of messages
3. The messages received are in sequential order with no gaps

#### Actual behavior

1. The expected default number of days/messages to be loaded loaded is not known and appears to be inconsistent. 2 days loaded this time (14th, 15th), but previously seen around a week
2. The expected number of messages to be retrieved when clicking on fetch is not known - sometimes many days are brought back, other times only a few messages.
3. Clicking on Fetch did nothing on the first attempt. On the second attempt messages were retrieved, but only those prior to the 4th Nov. Messages between 4th and 14th were missing.

### Additional Information

- Status desktop version: 0.8.0 Beta RC1
- Operating System: Mac

**Comment by anastasiyaig** [comment] 2022-11-17 13:48
@iurimatias the issue is severe but i dont think we can fix it in 0.8.0, please move it to next release as it is important

**Comment by richard-ramos** [comment] 2022-11-28 14:30
@anastasiyaig please retry. There was an issue with mailservers returning messages consistently. A fix was deployed into the fleet so the experience retrieving messages should have improved. 

Similar issue: https://github.com/status-im/status-mobile/issues/14390

**Comment by jrainville** [comment] 2023-01-27 16:20
Closing as it should be fixed. Do reopen if you experience it again

**Closed by jrainville** 2023-01-27 16:20 UTC
Labels: bug, Communities, priority 1: high, syncing_and_message_history, E:Communities
