### ISSUE TITLE
User should be able to copy chat message text

### ISSUE THREAD

**Issue by emizzle** [status-im/status-desktop#1907] opened 2021-02-24 22:21 UTC
Reproduction:
1. Go to any chat
2. In any chat message, highlight the text with your mouse
3. Cmd+c / Ctrl+c to copy the text
4. Expected: Cmd+v / Ctrl+v does should paste the text
5. Actual: Cmd+v / Ctrl+v does not paste the text (it was not copied)

**Comment by rinzlxr** [comment] 2021-04-07 15:18
Note: i was not able to reproduce this using Arch Linux and Status version `beta.8.rc2`

**Comment by PascalPrecht** [comment] 2021-04-12 12:56
Closing this as non-reproducible

**Comment by michaelsbradleyjr** [comment] 2021-04-12 13:14
@PascalPrecht this was closed prematurely, but I forgot to leave a comment earlier, my bad.

In my experience, what @emizzle reported happens intermittently on macOS. I currently have no theories as to the cause.

After the app has been running for some time (but not always), attempting to copy text within the app to the clipboard stops working. The only way I've find to get it working again is to restart the app.

**Comment by PascalPrecht** [comment] 2021-04-14 07:58
That's odd. I did experience a different thing where, for some reason, hover events wouldn't be propagated at all anymore, rendering the cursor as arrow at all times. I have to hide and show the app again to "fix" it. Maybe these two issues are in the same ballpark?

**Comment by emizzle** [comment] 2021-04-14 08:25
I believe you're probably right, @PascalPrecht. The app has some weird behaviour where the window *appears* to be in focus, but in fact, it is not. When this happens, it seems like a subset of features in the app work. The workaround, as you've mentioned, is to change focus to another app, then change focus back to Status Desktop. This seems to fix most issues in this ballpark, however I cannot confirm if it fixes the originally posted issue as it is difficult to reproduce.

**Comment by iurimatias** [comment] 2021-07-15 14:41
duplicate of #2650

**Closed by iurimatias** 2021-07-15 14:41 UTC
Labels: Chat, bug
