### ISSUE TITLE
Contact request cannot be declined from the activity centre

### ISSUE THREAD

**Issue by Michal-Status** [status-im/status-desktop#13534] opened 2024-02-12 22:49 UTC
# Bug Report

## Description

It is impossible to reject a contact request using the activity centre. Accepting it works. When the user rejects a contact request from a contact that has been removed before, the app generates multiple "You removed XYZ as a contact" but clicking on the button does nothing, as the user is no longer a contact

## Steps to reproduce

1. Log into two accounts
2. Send a contact request from User1 to User2
3. Click on decline on Activity Center of User2

**Additional steps for generating multiple notifications**
4. Accept the contact request
5. Remove User1 from contacts
6. Send a Contact Request from User1 to User2 again
7. Decline the Contact Request multiple times using the activity center as User2

#### Expected behavior
It is possible to reject a contact request using the Activity Centre

#### Actual behavior
It is impossible to reject a contact request using the Activity Centre

### Additional Information

- Status desktop version: https://ci.infra.status.im/job/status-desktop/job/release/job/release%2F2.27.x/6/
- Operating System: macOS

https://github.com/status-im/status-desktop/assets/155960867/82808afa-4d69-4564-bef8-154d995b4be5
<img width="392" alt="Screenshot 2024-02-12 at 23 39 45" src="https://github.com/status-im/status-desktop/assets/155960867/6d9b067e-fab8-4302-af1c-189f290dec1f">

**Comment by anastasiyaig** [comment] 2024-02-13 06:36
there must be something else, because basic flow of rejecting contact request works and is even automated
@jrainville please take a look

**Comment by jrainville** [comment] 2024-02-22 16:17
I just tested and it works as expected. Maybe it was fixed in the meantime? Closing as no reproducible. @Michal-Status feel free to reopen if you still experience it

**Closed by jrainville** 2024-02-22 16:17 UTC
Labels: bug, messenger-team, E:Desktop Contact Requests, E:Desktop Activity Center MVP
