### ISSUE TITLE
Chat with long title is creating overlapping with notification icon and members list

### ISSUE THREAD

**Issue by faust4exe** [status-im/status-desktop#7677] opened 2022-09-29 20:23 UTC
### Description

1. Change group title to a very long one
2. Change window width to minimum
3. Observe the title and header buttons overlapping notification icon and members list

https://user-images.githubusercontent.com/6445843/193134340-9c6f5c83-523d-4918-90c7-2aa92f931762.mp4

**Comment by micieslak** [comment] 2022-10-07 14:51
Duplicate of https://github.com/status-im/status-desktop/issues/7647

**Closed by micieslak** 2022-10-07 14:51 UTC
Labels: ui, Chat, pixel-perfect-issues
