### ISSUE TITLE
App crashes on removing contact

### ISSUE THREAD

**Issue by Parveshdhull** [status-im/status-desktop#9830] opened 2023-03-10 08:07 UTC
# Bug Report

## Description

App crashes on removing contact
<details>
  <summary>Crash Logs</summary>

```
DBG 2023-03-09 00:41:57.643+05:30 [threadpool task thread] sending 'done' notice to pool topics="task-threadpool" tid=38717 file=threadpool.nim:105 threadid=3 task="{\"$type\":\"FetchAllCurrencyFormatsTaskArg:ObjectType\",\"vptr\":94252937294208,\"slot\":\"onAllCurrencyFormatsFetched\",\"tptr\":94252786107408}"
DBG 2023-03-09 00:41:57.646+05:30 NewBE_callPrivateRPC                       topics="rpc" tid=38684 file=core.nim:27 rpc_method=accounts_getAllMigratedKeyPairs
INF 2023-03-09 00:41:58.995+05:30 history request completed                  topics="mailservers-service" tid=38684 file=service.nim:183
INF 2023-03-09 00:42:00.014+05:30 history request started                    topics="mailservers-service" tid=38684 file=service.nim:178 numBatches=5
DBG 2023-03-09 00:42:19.189+05:30 NewBE_callPrivateRPC                       topics="rpc" tid=38684 file=core.nim:27 rpc_method=wakuext_getLatestVerificationRequestFrom
DBG 2023-03-09 00:42:24.681+05:30 NewBE_callPrivateRPC                       topics="rpc" tid=38684 file=core.nim:27 rpc_method=settings_notificationsGetExMuteAllMessages
DBG 2023-03-09 00:42:24.682+05:30 NewBE_callPrivateRPC                       topics="rpc" tid=38684 file=core.nim:27 rpc_method=settings_notificationsGetExPersonalMentions
DBG 2023-03-09 00:42:24.682+05:30 NewBE_callPrivateRPC                       topics="rpc" tid=38684 file=core.nim:27 rpc_method=settings_notificationsGetExGlobalMentions
DBG 2023-03-09 00:42:24.682+05:30 NewBE_callPrivateRPC                       topics="rpc" tid=38684 file=core.nim:27 rpc_method=settings_notificationsGetExOtherMessages
ERR 2023-03-09 00:42:24.693+05:30 error: requested community doesn't exists  topics="community-service" tid=38684 file=service.nim:559 communityId=0x02ba409c50c82a8d900223f4a188df03f888053c12b8651705650105687b37870a
DBG 2023-03-09 00:42:40.443+05:30 NewBE_callPrivateRPC                       topics="rpc" tid=38684 file=core.nim:27 rpc_method=wakuext_retractContactRequest
ERR 2023-03-09 00:42:40.443+05:30 rpc response error                         topics="rpc" tid=38684 file=core.nim:36 err="\nstatus-go error [methodName:wakuext_retractContactRequest, code:-32000, message:retract-contact-request: invalid id ]\n"
ERR 2023-03-09 00:42:40.443+05:30 error doing rpc request                    topics="rpc" tid=38684 file=core.nim:40 methodName=wakuext_retractContactRequest exception="\nstatus-go error [methodName:wakuext_retractContactRequest, code:-32000, message:retract-contact-request: invalid id ]\n"
INF 2023-03-09 00:42:40.443+05:30 shutting down...                           topics="status-app" tid=38684 file=nim_status_client.nim:144
DBG 2023-03-09 00:42:40.444+05:30 [threadpool] join thread                   topics="task-threadpool" tid=38714 file=threadpool.nim:256 threadid=10
DBG 2023-03-09 00:42:40.445+05:30 [threadpool] join thread                   topics="task-threadpool" tid=38714 file=threadpool.nim:256 threadid=11
DBG 2023-03-09 00:42:40.445+05:30 [threadpool] join thread                   topics="task-threadpool" tid=38714 file=threadpool.nim:256 threadid=12
DBG 2023-03-09 00:42:40.445+05:30 [threadpool] join thread                   topics="task-threadpool" tid=38714 file=threadpool.nim:256 threadid=13
DBG 2023-03-09 00:42:40.445+05:30 [threadpool] join thread                   topics="task-threadpool" tid=38714 file=threadpool.nim:256 threadid=14
DBG 2023-03-09 00:42:40.445+05:30 [threadpool] join thread                   topics="task-threadpool" tid=38714 file=threadpool.nim:256 threadid=15
DBG 2023-03-09 00:42:40.445+05:30 [threadpool] join thread                   topics="task-threadpool" tid=38714 file=threadpool.nim:256 threadid=16
DBG 2023-03-09 00:42:40.445+05:30 [threadpool] join thread                   topics="task-threadpool" tid=38714 file=threadpool.nim:256 threadid=2
DBG 2023-03-09 00:42:40.445+05:30 [threadpool] join thread                   topics="task-threadpool" tid=38714 file=threadpool.nim:256 threadid=4
DBG 2023-03-09 00:42:40.446+05:30 [threadpool] join thread                   topics="task-threadpool" tid=38714 file=threadpool.nim:256 threadid=5
DBG 2023-03-09 00:42:40.446+05:30 [threadpool] join thread                   topics="task-threadpool" tid=38714 file=threadpool.nim:256 threadid=6
DBG 2023-03-09 00:42:40.446+05:30 [threadpool] join thread                   topics="task-threadpool" tid=38714 file=threadpool.nim:256 threadid=7
DBG 2023-03-09 00:42:40.446+05:30 [threadpool] join thread                   topics="task-threadpool" tid=38714 file=threadpool.nim:256 threadid=8
DBG 2023-03-09 00:42:40.446+05:30 [threadpool] join thread                   topics="task-threadpool" tid=38714 file=threadpool.nim:256 threadid=9
DBG 2023-03-09 00:42:40.446+05:30 [threadpool] join thread                   topics="task-threadpool" tid=38714 file=threadpool.nim:256 threadid=1
DBG 2023-03-09 00:42:40.446+05:30 [threadpool] join thread                   topics="task-threadpool" tid=38714 file=threadpool.nim:256 threadid=3
INF 2023-03-09 00:42:40.446+05:30 logging out...                             topics="app-controller" tid=38684 file=app_controller.nim:267
Traceback (most recent call last)
/home/jenkins/workspace/status-desktop/platforms/linux/src/nim_status_client.nim(180) nim_status_client
/home/jenkins/workspace/status-desktop/platforms/linux/src/nim_status_client.nim(154) mainProc
/home/jenkins/workspace/status-desktop/platforms/linux/src/app/boot/app_controller.nim(270) delete
/home/jenkins/workspace/status-desktop/platforms/linux/src/app/global/global_singleton.nim(67) delete
/home/jenkins/workspace/status-desktop/platforms/linux/vendor/nimqml/src/nimqml/private/qqmlapplicationengine.nim(40) delete
SIGSEGV: Illegal storage access. (Attempt to read from nil?)

```
</details>

## Steps to reproduce
From left section, select contact, view profile and remove contact
(Contact is added from mobile and don't have display name)

### Additional Information

- Status desktop version: 0.10.0
- Operating System: Arch linux (6.2.2-arch1-1)

**Comment by Parveshdhull** [comment] 2023-03-10 09:02
`methodName=wakuext_retractContactRequest exception="\nstatus-go error [methodName:wakuext_retractContactRequest, code:-32000, message:retract-contact-request: invalid id ]\n"`

**Comment by caybro** [comment] 2023-03-10 09:58
Duplicate of https://github.com/status-im/status-desktop/issues/9625, fixed in https://github.com/status-im/status-desktop/pull/9647

**Closed by caybro** 2023-03-10 09:58 UTC
Labels: bug
