### ISSUE TITLE
panic: enode: can't sign record: record bigger than 300 bytes

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#9589] opened 2023-02-20 11:32 UTC
### Description

panic: enode: can't sign record: record bigger than 300 bytes

```goroutine 2880424 [running]:
github.com/ethereum/go-ethereum/p2p/enode.(*LocalNode).sign(0xc000a82200)
	/Users/jenkins/workspace/status-desktop/platforms/macos/vendor/status-go/vendor/github.com/ethereum/go-ethereum/p2p/enode/localnode.go:310 +0x568
github.com/ethereum/go-ethereum/p2p/enode.(*LocalNode).Node(0xc000a82200)
	/Users/jenkins/workspace/status-desktop/platforms/macos/vendor/status-go/vendor/github.com/ethereum/go-ethereum/p2p/enode/localnode.go:122 +0x172
github.com/waku-org/go-discover/discover.(*UDPv5).Self(0xc015508da8?)
	/Users/jenkins/workspace/status-desktop/platforms/macos/vendor/status-go/vendor/github.com/waku-org/go-discover/discover/v5_udp.go:178 +0x1d
github.com/waku-org/go-discover/discover.(*Table).self(...)
	/Users/jenkins/workspace/status-desktop/platforms/macos/vendor/status-go/vendor/github.com/waku-org/go-discover/discover/table.go:132
github.com/waku-org/go-discover/discover.(*Table).bucket(0xc0000e6140, {0xd9, 0xc2, 0x85, 0x74, 0xab, 0xcf, 0x10, 0x22, 0xdb, ...})
	/Users/jenkins/workspace/status-desktop/platforms/macos/vendor/status-go/vendor/github.com/waku-org/go-discover/discover/table.go:450 +0x37
github.com/waku-org/go-discover/discover.(*Table).bucketLen(0xc0f4f34bf3d1f208?, {0xd9, 0xc2, 0x85, 0x74, 0xab, 0xcf, 0x10, 0x22, 0xdb, ...})
	/Users/jenkins/workspace/status-desktop/platforms/macos/vendor/status-go/vendor/github.com/waku-org/go-discover/discover/table.go:445 +0x9a
github.com/waku-org/go-discover/discover.(*lookup).query(0xc023008fc0, 0xc0276ed830, 0xc001c4f190?)
	/Users/jenkins/workspace/status-desktop/platforms/macos/vendor/status-go/vendor/github.com/waku-org/go-discover/discover/lookup.go:155 +0x28f
created by github.com/waku-org/go-discover/discover.(*lookup).startQueries
	/Users/jenkins/workspace/status-desktop/platforms/macos/vendor/status-go/vendor/github.com/waku-org/go-discover/discover/lookup.go:126 +0x27b
anastasiya@MacBook-Pro-Anastasiya MacOS % PORT_SHIFT=100 ./nim_status_client
```

**Comment by caybro** [comment] 2023-02-20 11:44
@anastasiyaig version?

**Comment by stefandunca** [comment] 2023-02-20 11:51
@richard-ramos, this looks like the one we discussed last week. Do you have the extra logging changes you planned to do?

**Comment by anastasiyaig** [comment] 2023-02-20 12:02
@caybro my bad, i am on latest rc 0.10.0 (9 version)

**Comment by richard-ramos** [comment] 2023-02-21 12:38
> this issue looks like the one we discussed last week. Do you have the extra logging changes you planned to do?

Not yet. Will create a PR today for it updating go-waku in status-go/status-desktop.

**Comment by richard-ramos** [comment] 2023-02-23 15:23
@anastasiyaig @stefandunca @caybro 
PR #9619 got merged. If you reproduce the issue again, please let me know. In the terminal or logs you should see logs like these:

```
SetupENR ================================================================
Multiaddresses [/ip4/192.168.0.109/tcp/60000/p2p/16Uiu2HAkyHiY8ykb28SZtdML4nbxQecUKJzCKFF7FUPCx48pxGDG /ip4/127.0.0.1/tcp/60000/p2p/16Uiu2HAkyHiY8ykb28SZtdML4nbxQecUKJzCKFF7FUPCx48pxGDG /ip4/192.168.1.20/tcp/13210/p2p/16Uiu2HAkyHiY8ykb28SZtdML4nbxQecUKJzCKFF7FUPCx48pxGDG /ip4/0.0.0.0/tcp/13210/p2p/16Uiu2HAkyHiY8ykb28SZtdML4nbxQecUKJzCKFF7FUPCx48pxGDG]
------------------------------------------------------------
WriteMultiaddresses ================================================================
Multiaddresses: []
Failed to write ENR? false
SuccessIDX: -1

```

and in geth.log:
```
 100053 t=2023-02-23T11:20:04-0400 lvl=info msg="Setup ENR" multiaddresses="[/ip4/192.168.0.109/tcp/60000/p2p/16Uiu2HAkyHiY8ykb28SZtdML4nbxQecUKJzCKFF7FUPCx48pxGDG /ip4/127.0.0.1/tcp/60000/p2p/16Uiu2HAkyHiY8ykb28
       1 t=2023-02-23T11:20:04-0400 lvl=info msg="Updating ENR ---" multiaddr=[] successIDX=-1 Failed to write enr=false
```


If you run into this issue again, please do share this information so I might identify why is the crash happening

**Closed** 2023-02-24 13:56 UTC
Labels: bug, E:Wakuv2, E:Bugfixes
