### ISSUE TITLE
Transaction fee preview does not show real value of the transaction

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#13686] opened 2024-02-22 13:42 UTC
### Description

In community, try to mint token owner on Optimism. The app usually says it is around of 2 cents, when in fact it turns out to be 10 USD

https://optimistic.etherscan.io/tx/0xd67b5b25ea76b07579c0aacf66a55e4077f9e138ad8268045966936f06ed8d97

<img width="1967" alt="Screenshot 2024-02-22 at 15 11 41" src="https://github.com/status-im/status-desktop/assets/82375995/74725ea5-7e46-49d7-aa65-f0712b92f3f8">

**Comment by anastasiyaig** [comment] 2024-02-22 13:42
encountered with @pavloburykh today

**Comment by anastasiyaig** [comment] 2024-02-22 13:53
@jrainville @alaibe anything we could do here?

**Comment by jrainville** [comment] 2024-02-22 15:16
I have no idea why it would do that. Seems like something wrong happened. It says it should have cost `<0.0001`, but it was `0.0035`, which is way higher.

I feel like this should be handled by the wallet team, since it's gas estimation, unless maybe  @endulab knows what's up

**Comment by alaibe** [comment] 2024-02-23 07:28
@jrainville @endulab wei conversion incorrect?

**Comment by jrainville** [comment] 2024-03-11 14:56
FYI @alaibe this is a duplicate of the issue I opened last week (well mine is a dupe). Feel free to close or assign correctly

**Comment by alaibe** [comment] 2024-03-11 15:31
Cool. I will close it

**Closed** 2024-03-11 15:32 UTC
Labels: bug, wallet-team, E:Desktop Comm Perms and Minting MVP
