### ISSUE TITLE
No option to change password?

### ISSUE THREAD

**Issue by closewall** [status-im/status-desktop#2794] opened 2021-06-30 20:47 UTC
Why is there no option to change my login password? What if it becomes compromised? Or I want to change it to something more difficult with a password manager?

**Comment by iurimatias** [comment] 2021-07-05 20:46
This is a reasonable request and should be done soon now that https://github.com/status-im/status-go/pull/2223 is implemented

**Comment by iurimatias** [comment] 2021-07-15 14:46
realized there is already an issue open for this, will close this one as a duplicate of #1620

**Closed by iurimatias** 2021-07-15 14:46 UTC
Labels: Profile, feature
