### ISSUE TITLE
Contacts: Display name and profile picture are not available in request

### ISSUE THREAD

**Issue by glitchminer** [status-im/status-desktop#10214] opened 2023-04-06 12:40 UTC
# Bug Report

## Description

When sending a contact request via the popup shown after pasting key in the To: field, the display name and profile picture are not available

![image](https://user-images.githubusercontent.com/50769329/230380845-9ed0a02f-ca1f-4f3d-a82c-0ea325b9d8d4.png)

## Steps to reproduce

1. Set up 2 users with profile pics and display names: `1_24 Char Display Name__` and`2_24 Char Display Name__`
2. Paste chat key in To: field.
3. Send contact request modal does not show image or name

### Additional Information

- Status desktop version: 11RC2 build 8
- Operating System: Mac

**Comment by jrainville** [comment] 2023-04-06 13:49
Duplicate of https://github.com/status-im/status-desktop/issues/8924

**Closed by jrainville** 2023-04-06 13:49 UTC
Labels: bug, E:Bugfixes, E:MutualContacts
