### ISSUE TITLE
Enable bandwidth stats 

### ISSUE THREAD

**Issue by richard-ramos** [status-im/status-desktop#3745] opened 2021-09-29 15:11 UTC
On mobile it was requested to disable the bandwidth stats signal since it consumes resources on the js thread.
https://github.com/status-im/status-go/pull/2391, so once desktop uses that status-go version, bandwidth stats are going to be disabled by default.

To reenable them we need to add the following setting in the node config, and logout/login. This is something that can be done on a toggle.
```js
...
"ShhextConfig": {
    "BandwidthStatsEnabled": true
  }
...
```
Another possibility suggested by @cammellos is to modify status-go to have two API endpoints to enable/disable the bandwidth stats, and once the user enters the node management section, enable the stats, and disable them on leave. If this option is implemented, please remove the `BandwidthStatsEnabled` setting from status-go

**Comment by iurimatias** [comment] 2022-03-13 22:50
duplicate of https://github.com/status-im/status-desktop/issues/4990

**Closed by iurimatias** 2022-03-13 22:50 UTC
Labels: Node, needs-status-go, general, priority F3: nice to have
