### ISSUE TITLE
Emojis used in app should be the same as the ones provided by OS

### ISSUE THREAD

**Issue by PascalPrecht** [status-im/status-desktop#1609] opened 2021-01-11 16:24 UTC
Our emoji set is neither macOS, nor Windows emojis

**Comment by richard-ramos** [comment] 2021-01-19 20:44
related: https://github.com/status-im/status-desktop/issues/1414

Main takeaway from that issue is that Linux does not have the full emoji set, so ideally we should use macOs and windows emojis only on those OSs and keep using Twemoji on Linux. Although IMO using a single set of emojis across OS is fine because it's consistent.

**Comment by iurimatias** [comment] 2021-01-19 23:10
duplicate of #1414

**Closed by iurimatias** 2021-01-19 23:10 UTC
Labels: ui
