### ISSUE TITLE
Desktop login failure

### ISSUE THREAD

**Issue by jm-clius** [status-im/status-desktop#12831] opened 2023-11-22 15:15 UTC
# Bug Report

## Description

Login failure using builds from https://github.com/status-im/status-desktop/pull/12765 as part of Waku team dogfooding of static sharding, although the issue was also observed in earlier builds such as https://github.com/status-im/status-desktop/pull/12344.
I'm on a Windows 11 machine and used the `windows/x86_64` installer, specifying the `--datadir` parameter to specify the path to dogfooding credentials.

## Steps to reproduce

This is how I produce the bug consistently:
1. Install Status.exe using  `windows/x86_64` installer from https://github.com/status-im/status-desktop/pull/12765, https://github.com/status-im/status-desktop/pull/12344 or anything in between.
2. Run `Status.exe` with `--datadir` config.
3. Create a user using the normal procedures and close the app.
4. Run `Status.exe` with `--datadir` config.
5. Attempt to login

In about 9/10 cases failure to log in with behaviour as set out below under "Actual behavior".

#### Expected behavior

Logs in.

#### Actual behavior

Login failure with following error message:
![image](https://github.com/status-im/status-desktop/assets/68783915/574ec411-8ffc-42a1-bb57-09fc46dccbfe)

If you then proceed to close the application, the following exception is raised:
![image](https://github.com/status-im/status-desktop/assets/68783915/fa6795dc-0283-4942-82d3-c953c91da1ca)

Logs:
```
INF 2023-11-22 15:02:35.835+00:00 Version: 0.9.90                            topics="status-app" tid=13920 file=nim_status_client.nim:197
INF 2023-11-22 15:02:35.837+00:00 Commit: 7f00bc901                          topics="status-app" tid=13920 file=nim_status_client.nim:198
INF 2023-11-22 15:02:35.837+00:00 Current date:                              topics="status-app" tid=13920 file=nim_status_client.nim:199 currentDateTime=2023-11-22T15:02:35+00:00
INF 2023-11-22 15:02:35.837+00:00 starting application controller...         topics="status-app" tid=13920 file=nim_status_client.nim:201
INF 2023-11-22 15:02:38.279+00:00 starting application...                    topics="status-app" tid=13920 file=nim_status_client.nim:204
WRN 2023-11-22 15:02:38.279+00:00 Error decoding signal                      topics="signals-manager" tid=13920 file=signals_manager.nim:43 err="Unknown signal received: mediaserver.started"
ERR 2023-11-22 15:02:42.616+00:00 error:                                     topics="accounts-service" tid=13920 file=service.nim:669 procName=verifyDatabasePassword errDesription="failed to set `journal_mode` pragma: file is not a database"
WRN 2023-11-22 15:02:47.145+00:00 Error decoding signal                      topics="signals-manager" tid=13920 file=signals_manager.nim:43 err="Unknown signal received: mediaserver.started"
ERR 2023-11-22 15:02:47.563+00:00 rpc response error                         topics="rpc" tid=13920 file=core.nim:36 err="\nstatus-go error [methodName:wakuext_startMessenger, code:-32603, message:method handler crashed ]\n"
ERR 2023-11-22 15:02:47.563+00:00 error doing rpc request                    topics="rpc" tid=13920 file=core.nim:40 methodName=wakuext_startMessenger exception="\nstatus-go error [methodName:wakuext_startMessenger, code:-32603, message:method handler crashed ]\n"
ERR 2023-11-22 15:02:47.563+00:00 error:                                     topics="app-controller" tid=13920 file=app_controller.nim:465 errDescription="\nstatus-go error [methodName:wakuext_startMessenger, code:-32603, message:method handler crashed ]\n"
WRN 2023-11-22 15:02:50.393+00:00 Error decoding signal                      topics="signals-manager" tid=13920 file=signals_manager.nim:43 err="Unknown signal received: mediaserver.started"
ERR 2023-11-22 15:02:58.237+00:00 error:                                     topics="accounts-service" tid=13920 file=service.nim:669 procName=verifyDatabasePassword errDesription="failed to set `journal_mode` pragma: file is not a database"
WRN 2023-11-22 15:02:59.437+00:00 Error decoding signal                      topics="signals-manager" tid=13920 file=signals_manager.nim:43 err="Unknown signal received: mediaserver.started"
ERR 2023-11-22 15:02:59.777+00:00 rpc response error                         topics="rpc" tid=13920 file=core.nim:36 err="\nstatus-go error [methodName:wakuext_startMessenger, code:-32603, message:method handler crashed ]\n"
ERR 2023-11-22 15:02:59.777+00:00 error doing rpc request                    topics="rpc" tid=13920 file=core.nim:40 methodName=wakuext_startMessenger exception="\nstatus-go error [methodName:wakuext_startMessenger, code:-32603, message:method handler crashed ]\n"
ERR 2023-11-22 15:02:59.778+00:00 error:                                     topics="app-controller" tid=13920 file=app_controller.nim:465 errDescription="\nstatus-go error [methodName:wakuext_startMessenger, code:-32603, message:method handler crashed ]\n"
WRN 2023-11-22 15:03:02.647+00:00 Error decoding signal                      topics="signals-manager" tid=13920 file=signals_manager.nim:43 err="Unknown signal received: mediaserver.started"
ERR 2023-11-22 15:13:03.337+00:00 error:                                     topics="accounts-service" tid=13920 file=service.nim:669 procName=verifyDatabasePassword errDesription="failed to set `journal_mode` pragma: file is not a database"
WRN 2023-11-22 15:13:04.555+00:00 Error decoding signal                      topics="signals-manager" tid=13920 file=signals_manager.nim:43 err="Unknown signal received: mediaserver.started"
ERR 2023-11-22 15:13:05.107+00:00 rpc response error                         topics="rpc" tid=13920 file=core.nim:36 err="\nstatus-go error [methodName:wakuext_startMessenger, code:-32603, message:method handler crashed ]\n"
ERR 2023-11-22 15:13:05.109+00:00 error doing rpc request                    topics="rpc" tid=13920 file=core.nim:40 methodName=wakuext_startMessenger exception="\nstatus-go error [methodName:wakuext_startMessenger, code:-32603, message:method handler crashed ]\n"
ERR 2023-11-22 15:13:05.110+00:00 error:                                     topics="app-controller" tid=13920 file=app_controller.nim:465 errDescription="\nstatus-go error [methodName:wakuext_startMessenger, code:-32603, message:method handler crashed ]\n"
WRN 2023-11-22 15:13:07.988+00:00 Error decoding signal                      topics="signals-manager" tid=13920 file=signals_manager.nim:43 err="Unknown signal received: mediaserver.started"
INF 2023-11-22 15:13:51.528+00:00 shutting down...                           topics="status-app" tid=13920 file=nim_status_client.nim:173
INF 2023-11-22 15:13:51.529+00:00 logging out...                             topics="app-controller" tid=13920 file=app_controller.nim:288
```

### Additional Information

- Status desktop version: https://github.com/status-im/status-desktop/pull/12765
- Operating System: Windows 11

[geth.log](https://github.com/status-im/status-desktop/files/13441597/geth.log)

**Comment by richard-ramos** [comment] 2023-11-22 15:54
This seems to be the error that's causing your login issue. Looking at the code, this failure happens while trying to retrieve a free TCP and UDP port for the torrent service :thinking: 

```
ERROR[11-22|15:13:05.106|rpc/service.go:200]                                                             RPC method wakuext_startMessenger crashed: runtime error: invalid memory address or nil pointer dereference
goroutine 1898 [running]:
github.com/ethereum/go-ethereum/rpc.(*callback).call.func1()
	C:/Users/jenkins/workspace/_windows_x86_64_package_PR-12765/vendor/status-go/vendor/github.com/ethereum/go-ethereum/rpc/service.go:199 +0x89
panic({0x7ffe69e522c0, 0x7ffe698f0d80})
	C:/ProgramData/scoop/apps/go/current/src/runtime/panic.go:884 +0x213
github.com/status-im/status-go/protocol/communities.(*Manager).getTCPandUDPport(0x1c002ad0d80, 0x1c002935248?)
	C:/Users/jenkins/workspace/_windows_x86_64_package_PR-12765/vendor/status-go/protocol/communities/manager.go:540 +0x53f
github.com/status-im/status-go/protocol/communities.(*Manager).StartTorrentClient(0x1c002ad0d80)
	C:/Users/jenkins/workspace/_windows_x86_64_package_PR-12765/vendor/status-go/protocol/communities/manager.go:562 +0x57
github.com/status-im/status-go/protocol/communities.(*Manager).Start(0x1c002ad0d80)
	C:/Users/jenkins/workspace/_windows_x86_64_package_PR-12765/vendor/status-go/protocol/communities/manager.go:378 +0x7f
github.com/status-im/status-go/protocol.(*Messenger).Start(0x1c000a42900)
	C:/Users/jenkins/workspace/_windows_x86_64_package_PR-12765/vendor/status-go/protocol/messenger.go:786 +0x53a
github.com/status-im/status-go/services/ext.(*Service).StartMessenger(0x1c0006c8300)
	C:/Users/jenkins/workspace/_windows_x86_64_package_PR-12765/vendor/status-go/services/ext/service.go:193 +0x5c
github.com/status-im/status-go/services/ext.(*PublicAPI).StartMessenger(...)
	C:/Users/jenkins/workspace/_windows_x86_64_package_PR-12765/vendor/status-go/services/ext/api.go:789
reflect.Value.call({0x1c000a906e0?, 0x1c0005ec538?, 0x137f0091ae8?}, {0x7ffe6a1b870a, 0x4}, {0x1c0005f9470, 0x1, 0x0?})
	C:/ProgramData/scoop/apps/go/current/src/reflect/value.go:586 +0xb0b
reflect.Value.Call({0x1c000a906e0?, 0x1c0005ec538?, 0x1?}, {0x1c0005f9470?, 0x0?, 0x1c002929cb8?})
	C:/ProgramData/scoop/apps/go/current/src/reflect/value.go:370 +0xbc
github.com/ethereum/go-ethereum/rpc.(*callback).call(0x1c001b59bc0, {0x7ffe6a9e99a0?, 0x1c0038a66e0}, {0x1c000fdf590, 0x16}, {0x7ffe6bca8e68, 0x0, 0x7ffe67b2a777?})
	C:/Users/jenkins/workspace/_windows_x86_64_package_PR-12765/vendor/status-go/vendor/github.com/ethereum/go-ethereum/rpc/service.go:205 +0x3c5
github.com/ethereum/go-ethereum/rpc.(*handler).runMethod(0x1c000434788?, {0x7ffe6a9e99a0?, 0x1c0038a66e0?}, 0x1c00030b5e0, 0x0?, {0x7ffe6bca8e68?, 0x1c003be4870?, 0x90?})
	C:/Users/jenkins/workspace/_windows_x86_64_package_PR-12765/vendor/status-go/vendor/github.com/ethereum/go-ethereum/rpc/handler.go:391 +0x45
github.com/ethereum/go-ethereum/rpc.(*handler).handleCall(0x1c0000d2fc0, 0x1c0005f9410, 0x1c00030b5e0)
	C:/Users/jenkins/workspace/_windows_x86_64_package_PR-12765/vendor/status-go/vendor/github.com/ethereum/go-ethereum/rpc/handler.go:336 +0x239
github.com/ethereum/go-ethereum/rpc.(*handler).handleCallMsg(0x1c0000d2fc0, 0x30?, 0x1c00030b5e0)
	C:/Users/jenkins/workspace/_windows_x86_64_package_PR-12765/vendor/status-go/vendor/github.com/ethereum/go-ethereum/rpc/handler.go:297 +0x237
github.com/ethereum/go-ethereum/rpc.(*handler).handleMsg.func1(0x1c0005f9410)
	C:/Users/jenkins/workspace/_windows_x86_64_package_PR-12765/vendor/status-go/vendor/github.com/ethereum/go-ethereum/rpc/handler.go:138 +0x35
github.com/ethereum/go-ethereum/rpc.(*handler).startCallProc.func1()
	C:/Users/jenkins/workspace/_windows_x86_64_package_PR-12765/vendor/status-go/vendor/github.com/ethereum/go-ethereum/rpc/handler.go:225 +0xc5
created by github.com/ethereum/go-ethereum/rpc.(*handler).startCallProc
	C:/Users/jenkins/workspace/_windows_x86_64_package_PR-12765/vendor/status-go/vendor/github.com/ethereum/go-ethereum/rpc/handler.go:221 +0x8d
```

**Comment by jm-clius** [comment] 2023-11-22 16:33
Thanks @richard-ramos!
Interestingly I now seem able to log in and all I've done is close Telegram Desktop... Will confirm that this is the issue.

**Comment by jrainville** [comment] 2023-11-22 16:47
Is the torrent port dynamic like the waku port @richard-ramos ? If not, it's probably worth improving it.

**Comment by richard-ramos** [comment] 2023-11-22 18:52
This should help: https://github.com/status-im/status-go/pull/4363

**Comment by vvirtues** [comment] 2024-01-12 03:41
get the same thing but running the normal start menu shortcut. trying to figure out which application is "occupying the port"

**Comment by vvirtues** [comment] 2024-01-12 03:43
apparently it was discord/bitwarden for me

**Comment by vvirtues** [comment] 2024-01-12 03:46
nevermind, i guess i needed to wait a little bit after making my account

**Comment by mprakhov** [comment] 2024-01-29 15:44
non reproducible
the issue was fixed in https://github.com/status-im/status-go/pull/4363

**Closed by mprakhov** 2024-01-29 15:44 UTC
Labels: bug, messenger-team
