### ISSUE TITLE
The communities we leave are displayed in`Communities Portal` view

### ISSUE THREAD

**Issue by noeliaSD** [status-im/status-desktop#6210] opened 2022-06-22 17:41 UTC
### Description
1. Run a desktop instance.
2. Navigate to `Communities Portal` view.
3. Leave communities by using right mouse click in each community.

**Expected:**
Nothing happen in `Communities Portal` view.

**Actual:** 
The communities  we leave are added in the `Communities Portal` view as a community card.

**NOTE:** After logout / login, communities disappear from the `Communities Portal` view.

See video for better understanding:

https://user-images.githubusercontent.com/97019400/175101891-f081917c-1c49-4c42-9fa6-b0ee3b58f225.mov

**Comment by iurimatias** [comment] 2022-07-07 18:58
closing as sort of a duplicate of #6209

**Closed by iurimatias** 2022-07-07 18:58 UTC
Labels: bug, Communities, E:Communities, S:2
