### ISSUE TITLE
Request to join a community fails, even though I am already a member

### ISSUE THREAD

**Issue by caybro** [status-im/status-desktop#10015] opened 2023-03-24 12:25 UTC
# Bug Report

Two things here:
1. I am required to request access eventhough I am a member already

![image](https://user-images.githubusercontent.com/5377645/227520053-cb8e3315-e7f4-45e2-ab7d-478c29d1b948.png)

2. The request (silently) fails:
```
DBG 2023-03-24 13:21:20.584+01:00 NewBE_callPrivateRPC                       topics="rpc" tid=175154 file=core.nim:27 rpc_method=wakuext_requestToJoinCommunity
ERR 2023-03-24 13:21:20.778+01:00 rpc response error                         topics="rpc" tid=175154 file=core.nim:36 err="\nstatus-go error [methodName:wakuext_requestToJoinCommunity, code:-32000, message:table activity_center_notifications has no column named community_id ]\n"
ERR 2023-03-24 13:21:20.778+01:00 error doing rpc request                    topics="rpc" tid=175154 file=core.nim:40 methodName=wakuext_requestToJoinCommunity exception="\nstatus-go error [methodName:wakuext_requestToJoinCommunity, code:-32000, message:table activity_center_notifications has no column named community_id ]\n"
ERR 2023-03-24 13:21:20.778+01:00 Error requesting to join the community     topics="community-service" tid=175154 file=service.nim:825 msg="\nstatus-go error [methodName:wakuext_requestToJoinCommunity, code:-32000, message:table activity_center_notifications has no column named community_id ]\n"
```

## Steps to reproduce

Click the community invitation bubble (which is broken atm too, fix with a PR incoming)

#### Expected behavior

I can regain access to previously joined community

#### Actual behavior

Can not join without approval

### Additional Information

- Status desktop version: master 
- Operating System: linux

**Comment by caybro** [comment] 2023-03-24 12:34
Note this was a fresh and fully restored account from seedphrase

**Comment by 0x-r4bbit** [comment] 2023-03-24 13:29
Looks like a migration went sideways:

```
ERR 2023-03-24 13:21:20.778+01:00 rpc response error                         topics="rpc" tid=175154 file=core.nim:36 err="\nstatus-go error [methodName:wakuext_requestToJoinCommunity, code:-32000, message:table activity_center_notifications has no column named community_id ]\n"
ERR 2023-03-24 13:21:20.778+01:00 error doing rpc request                    topics="rpc" tid=175154 file=core.nim:40 methodName=wakuext_requestToJoinCommunity exception="\nstatus-go error [methodName:wakuext_requestToJoinCommunity, code:-32000, message:table activity_center_notifications has no column named community_id ]\n"
ERR 2023-03-24 13:21:20.778+01:00 Error requesting to join the community     topics="community-service" tid=175154 file=service.nim:825 msg="\nstatus-go error [methodName:wakuext_requestToJoinCommunity, code:-32000, message:table activity_center_notifications has no column named community_id ]\n"
```

**Comment by 0x-r4bbit** [comment] 2023-03-24 13:39
If you're seeing those logs, then yes.

**Comment by caybro** [comment] 2023-03-24 14:13
Hmm, that one actually checks the type of the community (not wrong) but doesn't check whether the user already is (or not) a member

**Comment by jrainville** [comment] 2023-03-24 14:21
We can see that he can also not chat currently in the input. 
It also has this condition:
```
!root.activeSectionData.joined || root.activeSectionData.amIBanned
```
So it seems like `joined` is not set properly.

I'll try later to reproduce the same steps and see if I get the same.

**Comment by 0x-r4bbit** [comment] 2023-03-24 14:22
Ah right, sorry I think what we're looking for is the `joined` property which is used to render that button in the first place:

https://github.com/status-im/status-desktop/blob/master/ui/app/AppLayouts/Chat/views/CommunityColumnView.qml#L81

There was a change recently by @mprakhov17 that made the communityData a `SectionItem`. Chances are it doesn't expose the `joined` property hence it's falsy

**Comment by jrainville** [comment] 2023-03-24 17:45
I tried reproducing, and while I don't get the same issues as you, I do get a weird behaviour.
It shows as if I'm a member, but when I type in a community that is not mine, it crashes. I'm gonna investigate. It's possible that both are related.

**Comment by jrainville** [comment] 2023-03-24 18:45
I fixed the issue I had. You can find the fix here: https://github.com/status-im/status-go/pull/3346

I still can't reproduce the errors you had. Can you give it another try with latest master and develop?

**Comment by caybro** [comment] 2023-03-27 12:19
Also, I wasn't required to "join/apply" manually

**Comment by jrainville** [comment] 2023-03-27 14:18
I'm gonna close this one for now. It seems like it was an issue importing the community, maybe due to a bad migration?
We can reopen it if it happens again

**Closed by jrainville** 2023-03-27 14:18 UTC
Labels: bug, Communities, priority F2: important, E:Communities

**Comment by caybro** [comment] 2023-03-27 14:22
> I'm gonna close this one for now. It seems like it was an issue importing the community, maybe due to a bad migration? We can reopen it if it happens again

Sure, just need to pull the respective status-go PR into 0.11/master? :)

**Comment by jrainville** [comment] 2023-03-27 14:25
TBH, the PR just fixes a possible crash, not the issue you had itself, but I will for sure update status-go's version in Desktop. I was just waiting for my other PR to be merged first
