### ISSUE TITLE
All the channels within a community have the same color

### ISSUE THREAD

**Issue by richard-ramos** [status-im/status-desktop#4182] opened 2021-11-25 17:41 UTC
I'm not 100% sure if this is a bug, tho. Please close it if it is not the case

![image](https://user-images.githubusercontent.com/1106587/143484042-4ac944da-ab0d-4359-a127-dfb6c16d927a.png)

**Comment by PascalPrecht** [comment] 2021-11-26 07:34
This is by design as of https://github.com/status-im/status-desktop/pull/4027

**Comment by PascalPrecht** [comment] 2021-11-26 10:50
Closing this.

**Closed by PascalPrecht** 2021-11-26 10:50 UTC
Labels: bug, ui, Chat, 0.4.0

**Comment by jrainville** [comment] 2021-11-26 14:54
Oh damn, it IS by design. I never saw that before. TIL
