### ISSUE TITLE
The double Title bar is shown for the app window

### ISSUE THREAD

**Issue by elina2015** [status-im/status-desktop#9164] opened 2023-01-18 01:42 UTC
# Bug Report

## Steps to reproduce
1. Open the app and check the title bar (minimize, close, maximize buttons)

#### Expected behavior
Only one Title bar is shown
#### Actual behavior
The double Title bar is shown
<img width="193" alt="image" src="https://user-images.githubusercontent.com/14942081/213060109-50dc8f64-7b05-47ba-ad24-98999b05ccaa.png">

### Additional Information

- Status desktop version: https://ci.infra.status.im/job/status-desktop/job/release/job/release%252F0.9.x/3/
- Operating System: macOS Monterey

**Comment by caybro** [comment] 2023-01-18 09:01
Duplicate of https://github.com/status-im/status-desktop/issues/9126

**Closed by caybro** 2023-01-18 09:01 UTC
Labels: bug
