### ISSUE TITLE
Trying to buy ENS on Ropsten causes app to crash

### ISSUE THREAD

**Issue by abhi-status** [status-im/status-desktop#5570] opened 2022-04-15 23:48 UTC
# Bug Report

## Description

[data.zip](https://github.com/status-im/status-desktop/files/8498917/data.zip)

https://www.loom.com/share/41dc4ec4603043a1879b3f1aff99039d

### Additional Information

- Status desktop version: Master

**Comment by anastasiyaig** [comment] 2022-04-18 06:37
@abhi-status  i will downgrade it , since it is Ropsten issue. Also, please do not post links to screencast, we discussed it a while ago, if u dont have anything in description apart of the video, it is important the video stays there as long as possible and relying to 3d party is not a best choice here. Please post video to store it on GitHub

**Comment by alaibe** [comment] 2022-04-29 08:07
@abhi-status could u try with latest master pls? I cannot reproduce the issue

**Comment by anastasiyaig** [comment] 2022-05-05 09:36
i was not able to reproduce it in  master fb8a3f91004d76d0c7b5e8f46c07feeee4146a19 from May 5, closing this one

**Closed by anastasiyaig** 2022-05-05 09:36 UTC
Labels: bug, crash, priority 2: medium
