### ISSUE TITLE
Left communities reappear in Communities Portal

### ISSUE THREAD

**Issue by caybro** [status-im/status-desktop#7953] opened 2022-10-19 11:14 UTC
# Bug Report
When a Discord community is imported, it doesn't appear in the Community portal (only in the main navbar). However, attempt to leaving the community results in the community being removed from the navbar (correct) but reappearing in the portal (wrong). From this point, you can navigate to the deleted/left community again (!) and it is duplicated in the portal as well

Before leaving:
![Snímek obrazovky z 2022-10-19 13-09-16](https://user-images.githubusercontent.com/5377645/196675977-498a4caf-ab79-46c3-9677-cdbf6eb793f6.png)

After leaving:
![image](https://user-images.githubusercontent.com/5377645/196675896-d5383e6e-22d0-4803-940e-6609c6b52acd.png)

After leaving a second time:
![image](https://user-images.githubusercontent.com/5377645/196676437-79084732-e484-41d8-b03a-fb3e51ce2646.png)

- Status desktop version: master
- Operating System: Linux

**Comment by caybro** [comment] 2022-10-19 11:17
CC @PascalPrecht not sure how much this is related to the Discord Import

**Comment by PascalPrecht** [comment] 2022-10-19 13:14
It shouldn't be related at all, but I'm happy to look into this once I have some spare cycles

**Comment by PascalPrecht** [comment] 2022-10-20 14:41
So couple of things need to be clarified here:

1. What communities are supposed to be shown in the "featured" section of the communities portal? I assume not only communities that I have been part of, but maybe communities I've seen/have been spectated?
2. If 1) is true, then leaving a community should not remove it from the feature section (I'm not sure if it should add it)
3. A while-importing but then deleted community should not show up anywhere and unless the import was finished, it's not published anywhere either.

So at this point I'm wondering if this issue is partially wrong expectations and partially funny results because the import doesn't spectate any communities.

**Comment by PascalPrecht** [comment] 2022-11-07 15:39
@caybro How are you leaving a second time here? After you've left, you can't rejoin if you're the only owner of the community. So how did leaving a second time work for you?

I'm trying to reproduce this, but I can't.

**Comment by caybro** [comment] 2022-11-07 15:43
> 



> @caybro How are you leaving a second time here? After you've left, you can't rejoin if you're the only owner of the community. So how did leaving a second time work for you?
> 
> I'm trying to reproduce this, but I can't.

I was able to rejoin... dunno how :) For leaving, I used the context menu from the main navbar (toolbutton)

**Comment by PascalPrecht** [comment] 2022-11-07 15:46
Okay, thanks @caybro 

@jrainville I believe there's not action here.

1. I've talked to @richard-ramos who confirmed that atm, the "featured" section of the portal has "undefined" behaviour because it isn't connected to the contract that should aggregate the actual data.
2. Leaving a community does seem to indeed make that community show up in the featured section, but this will be solved once that section talks to the contract instead.
3. I don't think there's a way to have multiple instances of the same community show up in the featured section via leaving the same community multiple times, at least if you've been the owner of that community, because rejoining is impossible atm

Having all that said, I'm not sure what to do here. I guess it makes sense to revisit, once the "featured" section is considered functional?

**Comment by jrainville** [comment] 2022-11-11 15:14
Ok, I'll close this for now, since the portal is gonna get re-implemented.

**Closed by jrainville** 2022-11-11 15:14 UTC
Labels: bug, E:Wakuv2, E:Communities, E: Discord-Import
