### ISSUE TITLE
[refactoring/base_01] channel list is overlpaing when a category is collapsed

### ISSUE THREAD

**Issue by iurimatias** [status-im/status-desktop#4047] opened 2021-11-04 16:05 UTC
1. create a community
2. add 2 categories
3. add a channel
4. collapse a category

![Screen Shot 2021-11-04 at 12 02 52 PM](https://user-images.githubusercontent.com/176720/140375586-93970b80-2c80-4904-bb04-a6fb2cd3c877.png)

![Screen Shot 2021-11-04 at 12 03 58 PM](https://user-images.githubusercontent.com/176720/140375614-89893f51-ed00-42c5-b99b-02d17976a657.png)

**Comment by Khushboo-dev-cpp** [comment] 2021-11-05 15:18
unable to reproduce this on latest refactoring/base_01[Uploading... Screen Recording 2021-11-05 at 4.15.55 PM.mov]

**Comment by Khushboo-dev-cpp** [comment] 2021-11-09 16:59
Found a fix for this https://github.com/status-im/StatusQ/pull/484

**Closed** 2021-11-17 13:29 UTC
Labels: bug, refactor, qml
