### ISSUE TITLE
Community rules are shown  partially

### ISSUE THREAD

**Issue by elina2015** [status-im/status-desktop#6937] opened 2022-08-10 00:04 UTC
# Bug Report

## Steps to reproduce
1. Join the 'test' chat and click 'Join' or 'Request access'
2. Check the modal with community rules

#### Expected behavior
The rules are not cropped and shown correctly
#### Actual behavior
The rules are shown partially
<img width="1286" alt="image" src="https://user-images.githubusercontent.com/14942081/183782267-57a132e4-e614-4df2-8142-40a7b50e0c36.png">

### Additional Information

- Status desktop version: https://ci.status.im/job/status-desktop/job/branches/job/macos/job/master/59/
- Operating System: macOS Monterey

**Comment by iurimatias** [comment] 2022-08-15 16:56
duplicate of https://github.com/status-im/status-desktop/issues/6856

**Closed by iurimatias** 2022-08-15 16:56 UTC
Labels: bug, Chat, priority 2: medium, E:Communities
