### ISSUE TITLE
Reply-to-messages are not shown in activity center

### ISSUE THREAD

**Issue by 0x-r4bbit** [status-im/status-desktop#8595] opened 2022-12-02 15:53 UTC
See all of the notifications in my AC. They have this reply arrow but not reply message in there (except the last item which is not a reply):

![Screenshot from 2022-12-02 16-51-44](https://user-images.githubusercontent.com/445106/205332487-2db23be3-90a4-4290-8049-2bffef2fa3d4.png)

**Comment by caybro** [comment] 2022-12-02 16:16
master/0.8? works for me in master

**Comment by caybro** [comment] 2022-12-02 16:17
This got merged yesterday: https://github.com/status-im/status-desktop/pull/8542

**Comment by PascalPrecht** [comment] 2022-12-02 16:21
Will try to reproduce this in master, but in 0.8 it's broken for sure.

**Comment by jrainville** [comment] 2022-12-08 21:45
I'll close this. Feel free to reopen if you experience it in master

**Closed by jrainville** 2022-12-08 21:45 UTC
Labels: bug, E:ActivityCenter
