### ISSUE TITLE
Inconsitent loading chat messages

### ISSUE THREAD

**Issue by MishkaRogachev** [status-im/status-desktop#6548] opened 2022-07-20 10:24 UTC
# Bug Report

https://user-images.githubusercontent.com/2522130/179958985-fed5e641-fc04-4740-9d63-4d3ffd593eaa.mov

## Steps to reproduce

Open any chat with lots of messages, fetch them and start to scroll rapidly

#### Expected behavior

- [  ] Chat list view component height is constant, scrollbar size does not jumping
- [  ] Not empty areas durning scrolling

#### Actual behavior

- [  ] Chat list view component height is jumping while scrolling
- [  ] Empty area appears at the top and bottom position if scroll fast

**Comment by MishkaRogachev** [comment] 2022-07-22 08:53
Same issue: https://github.com/status-im/status-desktop/issues/3067

**Comment by iurimatias** [comment] 2022-07-24 15:52
duplicate of #3067

**Closed by iurimatias** 2022-07-24 15:52 UTC
Labels: bug
