### ISSUE TITLE
[Profile Showcase - General] Add Profile preview perspective options [Stranger, Contacts, Verified Contacts]. This includes the filtering of the data visibility based on the dropbox. Also review `Send Message` button logic

### ISSUE THREAD

**Issue by alexandraB99** [status-im/status-desktop#13332] opened 2024-01-29 13:43 UTC
[Figma](https://www.figma.com/file/d0G7m8X6ELjQlFOEKQpn1g/Profile-WIP?type=design&node-id=9-112784&mode=design&t=gxavA5yTTwXWFu9s-0)

**Comment by caybro** [comment] 2024-02-05 13:21
Dupe of https://github.com/status-im/status-desktop/issues/13424

**Closed by caybro** 2024-02-05 13:21 UTC
Labels: ui-team, E:Desktop Profile Showcase, E:Desktop Features 0.17
