### ISSUE TITLE
[Performance] ChatPinnedMessages and FirstUnseenMessageID RPC calls are blocking the DB for a long time

### ISSUE THREAD

**Issue by alexjba** [status-im/status-desktop#10282] opened 2023-04-13 09:39 UTC
### Description
Please have a look on this profiling data:

<img width="1409" alt="Screenshot 2023-04-07 at 15 39 29" src="https://user-images.githubusercontent.com/47811206/231719064-68329bc5-8f44-4f4f-b3aa-25f7cb0cff6d.png">

These calls are blocking the DB for a long time and we can't request additional data for a few seconds while any of them are running.

**Comment by alexjba** [comment] 2023-04-13 09:45
@jrainville I've labeled this with `messenger-team` since it's affecting the chat performance, but I'm not sure if it should be on the status-desktop board or on status-go board.

**Comment by jrainville** [comment] 2023-04-20 20:05
I can't reproduce those long call times on current master.
I'm using the shared dev account and still, those calls resolve in less than a millisecond for me.

Is this an OS thing, an account/DB thing or was it maybe fixed in the meantime?

Maybe I'm calculating it badly. I just put a benchmark  `cpuTime() - time` after the call to ChatPinnedMessages and FirstUnseenMessageID on the Nim side (backend/messages.nim), and the times are this small (in seconds): 
```
DONE firstUnseenMessageID : 0.0002839660000000001
DONE fetchPinnedMessages : 0.01356774199999999
```

**Comment by jrainville** [comment] 2023-04-20 20:06
This is also before Andrea's fix + index added here https://github.com/status-im/status-go/pull/3414/files#diff-79719d4e91ccd3a2f5d16881e905800c23cc3e3054827916f24030cf052b1965, which will likely help as well

**Comment by alexjba** [comment] 2023-04-24 06:23
> I can't reproduce those long call times on current master. I'm using the shared dev account and still, those calls resolve in less than a millisecond for me.
> 
> Is this an OS thing, an account/DB thing or was it maybe fixed in the meantime?
> 
> Maybe I'm calculating it badly. I just put a benchmark `cpuTime() - time` after the call to ChatPinnedMessages and FirstUnseenMessageID on the Nim side (backend/messages.nim), and the times are this small (in seconds):
> 
> ```
> DONE firstUnseenMessageID : 0.0002839660000000001
> DONE fetchPinnedMessages : 0.01356774199999999
> ```

It definitely depends on the DB size. I'm using a DB with Status Community that has about 14GB. But I guess it can be considered an account with a reasonable size. I doubt it's dependent on the OS. Linux users are also reporting slow `firstUnseenMessageID` and `fetchPinnedMessages`.

**Comment by caybro** [comment] 2023-04-24 08:12
> > I can't reproduce those long call times on current master. I'm using the shared dev account and still, those calls resolve in less than a millisecond for me.
> > Is this an OS thing, an account/DB thing or was it maybe fixed in the meantime?
> > Maybe I'm calculating it badly. I just put a benchmark `cpuTime() - time` after the call to ChatPinnedMessages and FirstUnseenMessageID on the Nim side (backend/messages.nim), and the times are this small (in seconds):
> > ```
> > DONE firstUnseenMessageID : 0.0002839660000000001
> > DONE fetchPinnedMessages : 0.01356774199999999
> > ```
> 
> It definitely depends on the DB size. I'm using a DB with Status Community that has about 14GB. But I guess it can be considered an account with a reasonable size. I doubt it's dependent on the OS. Linux users are also reporting slow `firstUnseenMessageID` and `fetchPinnedMessages`.

Yup, it's very slow on large databases

**Comment by jrainville** [comment] 2023-04-24 14:37
This was incorrectly closed when my other PR was closed. Reopening

**Comment by osmaczko** [comment] 2023-04-27 17:36
Good news! I've identified the cause of the slow channel switching.

Here's our story, the sequence of events:
```
1. async getMessages -> locks the database for x ms
2. async getPinnedMessages -> locks the database for y ms
3. async getFirstUnseenMessageId -> locks the database for z ms
```

Contrary to what the profiler suggests, `getFirstUnseenMessageId` isn't the main issue. It's actually blocked for x+y+200 ms due to the database locks. I tested it in separation, `getFirstUnseenMessageId` is at max 250ms for huge channels and after this change: https://github.com/status-im/status-go/commit/a7d7609a771dda6ceaa1100a5209535570c530bb, it will be max 10ms. There will be no need to keep it async anymore.

To improve channel switching speed, it's crucial that we optimize the performance of the `getPinnedMessages` query. Since the database is single-threaded, there's no other solution. Consider a scenario where a user switches between 10 channels quickly. The last channel would only open after 10*(x+y+z) ms, as all the queries would stack up.

**Comment by osmaczko** [comment] 2023-04-28 10:02
Improving the performance of the `getPinnedMessages` query alone may not fully resolve the issue. It appears that in some cases, we lack control over what locks the database and the duration of the lock, see: #10471 (comment). This could also explain why switching between the same channels is sometimes fast and other times slow.

**Comment by jrainville** [comment] 2023-05-04 16:16
Dependent on https://github.com/status-im/status-desktop/issues/10558

**Comment by osmaczko** [comment] 2023-06-01 20:18
Has been fixed on the way of https://github.com/status-im/status-desktop/issues/10558 - the root cause was db locks

**Closed by osmaczko** 2023-06-01 20:18 UTC
Labels: performance, messenger-team
