### ISSUE TITLE
Account is not chosen by default on mint owner token view

### ISSUE THREAD

**Issue by Valentina1133** [status-im/status-desktop#15416] opened 2024-07-02 09:00 UTC
# Bug Report

## Steps to reproduce

1. Create community
2. Go to Community settings/ Tokens
3. Click Mint owner token button
4. Click Next button

#### Expected behavior
Account 1 is chosen by default in select account combobox

#### Actual behavior
Select account combobox is empty by default

### Additional Information
![9b4a28600a1672d7](https://github.com/status-im/status-desktop/assets/141633821/cc58373d-a719-4f1b-8205-4efd942d9b50)

- Status desktop version: the latest master build
- Operating System: macOS Ventura 13.5

**Comment by endulab** [comment] 2024-07-04 10:04
After investigation I found out that the problem is caused by a bug in AccountsSelector.
The bug was introduced here: https://github.com/status-im/status-desktop/commit/531252fd734e87628c53188234695fc2e9b979cb#diff-6caae88276cbbeb747bde8b5003573f21fd98586a2538cffd335bb9fcb67e3fc
It will be fixed by pr: https://github.com/status-im/status-desktop/pull/15389/files#diff-6caae88276cbbeb747bde8b5003573f21fd98586a2538cffd335bb9fcb67e3fc

**Closed** 2024-07-04 22:03 UTC
Labels: bug, backend-team, E:D Comm Bugfixes 2.30
