### ISSUE TITLE
"Send contact request" context menu action opens profile modal unnecessarily

### ISSUE THREAD

**Issue by PascalPrecht** [status-im/status-desktop#7633] opened 2022-09-28 11:40 UTC
Inside of a community, when opening the context menu of a member in the member list and hitting "Send contact request", not only the modal to send a contact request is opened, but also the profile modal of that member, which should happen:

![Screenshot from 2022-09-28 13-37-54](https://user-images.githubusercontent.com/445106/192769726-55521b2d-7a01-4e9c-be20-09172d54fde8.png)

Just open the contact request modal.

**Comment by caybro** [comment] 2022-09-28 13:19
Already in the works as part of https://github.com/status-im/status-desktop/issues/7360, PR https://github.com/status-im/status-desktop/pull/7621

**Comment by alexandraB99** [comment] 2022-09-28 14:15
this is also a duplicate of https://github.com/status-im/status-desktop/issues/6941

**Comment by iurimatias** [comment] 2022-10-03 14:42
duplicate of https://github.com/status-im/status-desktop/issues/6941

**Closed by iurimatias** 2022-10-03 14:42 UTC
Labels: bug, ui, E:MutualContacts

**Comment by alexandraB99** [comment] 2022-10-19 13:30
@caybro please move to done if this is the case
