### ISSUE TITLE
Exceeding the number of characters allowed in the "NickName" field

### ISSUE THREAD

**Issue by serhanwbahar** [status-im/status-desktop#4960] opened 2022-03-03 18:48 UTC
# Bug Report

## Description

It is possible to exceed the number of characters allowed in the "NickName" field; even if the button is grayed out, the user can validate the record by using the "Enter" key on the keyboard.

This bug came from HackerOne. The original report is [here](https://hackerone.com/reports/1491346). There is no security impact.

## Steps to reproduce

1. Input a large string that shouldn't work for the field of "Nickname."
2. You should see the button is grayed out
3. Press "Enter" from the keyboard

![bypass_length](https://user-images.githubusercontent.com/47040097/156629124-cce7dfc4-7971-4bfb-b655-16fd358296d8.png)

![bypass_length2](https://user-images.githubusercontent.com/47040097/156629593-8e2d86dd-0427-4f4c-8166-ef40fde6dd7f.png)

**Comment by endulab** [comment] 2022-03-09 13:45
The issue was fixed by commit from other issue:
https://github.com/status-im/status-desktop/commit/1d6d20200a2a0c2ac988074bd677435fda8c81a7

The problem is not reproducible now.

FYI @serhanwbahar @iurimatias

**Comment by iurimatias** [comment] 2022-03-13 13:22
confirmed

**Closed by iurimatias** 2022-03-13 13:22 UTC
Labels: bug, ui, Chat, priority 4: minor, E:Bugfixes
