### ISSUE TITLE
Changing password takes very long without any UI reaction

### ISSUE THREAD

**Issue by igor-sirotin** [status-im/status-desktop#11426] opened 2023-07-05 16:21 UTC
# Bug Report

## Description

This is what I see for about 20 minutes when changing password. I suppose there's a database re-encryption runs in the background, but we definitely need some UI for this process.
![Screenshot 2023-07-05 at 19 02 41](https://github.com/status-im/status-desktop/assets/25482501/70010656-c60e-4821-8637-82a34d1feb41)

Also a minor thing: password changed popup looks a bit broken:
<img width="1312" alt="image" src="https://github.com/status-im/status-desktop/assets/25482501/f2bce260-5179-41df-9b09-9a02d1596c28">

#### Expected behavior

UI:
- doesn't freeze
- asks the user not to close the app (because it will break the database)
- prior changing the password gives a warning that it might take a while

#### Actual behavior

UI freezes for 20 minutes or so.

### Additional Information

- Status desktop version: 0.13-rc5
- Operating System: MacOS 13.4 (22F66)

**Comment by jrainville** [comment] 2023-07-05 16:44
Duplicate of https://github.com/status-im/status-desktop/issues/10037

**Closed by jrainville** 2023-07-05 16:44 UTC
Labels: bug, ui-team, needs-design
