### ISSUE TITLE
The uploaded profile image on the onboarding page is not saved to Profile

### ISSUE THREAD

**Issue by elina2015** [status-im/status-desktop#6935] opened 2022-08-09 23:47 UTC
# Bug Report

## Steps to reproduce
1. Register a new user and upload a Profile image, finish the onboarding
2. Check the photo image on your profile

#### Expected behavior
The profile image is saved and shown correctly 
#### Actual behavior
The profile image is not saved
### Additional Information

- Status desktop version: https://ci.status.im/job/status-desktop/job/branches/job/macos/job/master/59/
- Operating System: macOS Monterey

**Comment by iurimatias** [comment] 2022-08-15 17:55
duplicate of https://github.com/status-im/status-desktop/issues/6861

**Closed by iurimatias** 2022-08-15 17:55 UTC
Labels: bug, Profile, onboarding, priority 1: high, squish
