### ISSUE TITLE
App crashes when I click on the Status Updates Icon in the nav bar

### ISSUE THREAD

**Issue by simonricoo** [status-im/status-desktop#1987] opened 2021-03-05 09:09 UTC
<img width="106" alt="Screen Shot 2021-03-05 at 10 05 56" src="https://user-images.githubusercontent.com/52249767/110093275-d2342380-7d9a-11eb-836c-4771bb31266f.png">

On the latest master:
<img width="641" alt="Screen Shot 2021-03-05 at 10 09 20" src="https://user-images.githubusercontent.com/52249767/110093304-dc562200-7d9a-11eb-9864-bef1801a6b44.png">

**Comment by jrainville** [comment] 2021-03-18 18:05
I tried reproducing on latest master on Linux and with new accounts, removing data folder and even re-importing an existing account, I couldn't get the crash.

**Comment by jrainville** [comment] 2021-03-22 13:46
I tested again this time on Windows, still no crash. I'll close this for now since I can't reproduce

**Closed by jrainville** 2021-03-22 13:46 UTC
Labels: bug
