### ISSUE TITLE
Community badge/icon against Mentions in Activity centre show in black until the app is rebooted

### ISSUE THREAD

**Issue by abhi-status** [status-im/status-desktop#5524] opened 2022-04-12 22:08 UTC
# Bug Report

## Description

On Windows, the user is not able to know what Community they were mentioned at, as the Community badge is not visible

Only when the app is rebooted, the badge shows up correctly.

#### Expected behavior
The Community badge & channel name must be clearly shown

#### Actual behavior
![image](https://user-images.githubusercontent.com/95302135/163062762-631dfca7-4610-4f33-8fb6-371e20e6c28a.png)

### Additional Information

- Status desktop version: Maser : 9c9d6330650312378901becb13584b1a6d4926a1
- Operating System: Windows

**Comment by iurimatias** [comment] 2022-05-09 19:51
duplicate of https://github.com/status-im/status-desktop/issues/5523

**Closed by iurimatias** 2022-05-09 19:51 UTC
Labels: bug, windows, Activity_center, priority 2: medium
