### ISSUE TITLE
Recurring notifications for past token airdrop

### ISSUE THREAD

**Issue by chair28980** [status-im/status-desktop#15717] opened 2024-07-22 19:25 UTC
# Bug Report

## Description

I have received multiple duplicate airdrop notifications for the same event, happens roughly at least once per week since the original airdrop event.

## Steps to reproduce

1. Receive an airdropped community access token
2. Receive the initial notification
3. Receive duplicate notification on daily/weekly basis

#### Expected behavior

Only one new notification for the event.

#### Actual behavior

Notifications return for the same event.

### Additional Information

- Status desktop version: 2.29
- Operating System: macos

### Screenshot
![Screenshot 2024-07-22 at 12 22 16 PM](https://github.com/user-attachments/assets/3e814f19-3a32-47ab-b539-0fa82802ec92)

**Comment by chair28980** [comment] 2024-07-22 19:32
Related to https://github.com/status-im/status-desktop/issues/14629

**Comment by jrainville** [comment] 2024-07-22 19:33
Closing as duplicate of https://github.com/status-im/status-desktop/issues/14629

**Closed by jrainville** 2024-07-22 19:33 UTC
Labels: bug
