### ISSUE TITLE
[base_bc] clicking on 1 on 1 after restarting the app is crashing the app.

### ISSUE THREAD

**Issue by iurimatias** [status-im/status-desktop#4545] opened 2022-01-24 13:56 UTC
# Bug Report

## Description

clicking on 1 on 1 after restarting the app is crashing the app.

## Steps to reproduce

1. open a 1 on 1 chat with a mobile contact
2. send a message and react to it
3. go to mobile, and also react to that message
4. restart app
5. click on the 1 on 1 chat

result: crash with this stack trace

```
INF 2022-01-23 18:12:11.473-05:00 shutting down... topics="status-app" tid=207032 file=nim_status_client.nim:121
...
/Users/iurimatias/Projects/Status/status-desktop/src/app_service/service/message/service.nim(250) onAsyncLoadMoreMessagesForChat
/Users/iurimatias/Projects/Status/status-desktop/src/app/core/eventemitter.nim(46) emit
/Users/iurimatias/Projects/Status/status-desktop/src/app/modules/main/chat_section/chat_content/messages/controller.nim(53) :anonymous
/Users/iurimatias/Projects/Status/status-desktop/src/app/modules/main/chat_section/chat_content/messages/private_interfaces/module_controller_delegate_interface.nim(3) newMessagesLoaded
/Users/iurimatias/Projects/Status/status-desktop/src/app/modules/main/chat_section/chat_content/messages/module.nim(132) newMessagesLoaded
/Users/iurimatias/Projects/Status/status-desktop/src/app/modules/shared_models/message_item.nim(197) addReaction
/Users/iurimatias/Projects/Status/status-desktop/src/app/modules/shared_models/message_reaction_model.nim(117) addReaction
/Users/iurimatias/Projects/Status/status-desktop/vendor/nimqml/src/nimqml/private/qabstractitemmodel.nim(237) dataChanged
/Users/iurimatias/Projects/Status/status-desktop/vendor/nimbus-build-system/vendor/Nim/lib/system/fatal.nim(49) sysFatal
Error: unhandled exception: index out of bounds, the container is empty [IndexError]
```

**Comment by saledjenic** [comment] 2022-01-25 09:17
This crash was caused by inconsistency on the `stauts-go` side, cause the state we had in local db doesn't match the real fetched state in terms of reactions. That's fixed in PR #4558 (related to the [issue-4525](https://github.com/status-im/status-desktop/issues/4525)).

If you're local db is already corrupted then, there is no help :), you have either delete local `Status` folder and re-import your account using seed phrase or to keep using the current one but without opening a chat where reactions got messed up.

**Closed** 2022-01-25 20:09 UTC
Labels: bug, hard-to-replicate, branch: base_bc
