### ISSUE TITLE
Clicking on the activity centre icon a second time to close the activity centre doesn't work

### ISSUE THREAD

**Issue by John-44** [status-im/status-desktop#3480] opened 2021-09-13 13:19 UTC
Clicking on the activity centre icon a second time to close the activity centre doesn't work.

As a general rule, when clicking on something opens a menu, clicking on the same thing a second time should close the menu.

**Comment by iurimatias** [comment] 2021-09-15 16:39
duplicate of #3331

**Closed by iurimatias** 2021-09-15 16:39 UTC
Labels: bug, Chat, Communities, Component Library
