### ISSUE TITLE
Community: placeholders of the New community fields are placed very close to the left edge

### ISSUE THREAD

**Issue by elina2015** [status-im/status-desktop#8948] opened 2023-01-04 04:01 UTC
# Bug Report

## Steps to reproduce
1. Go to create a community
2. Check placeholders in the fields on the first and second modal pages

#### Expected behavior
Placeholders of the New community fields are placed NOT very close to the left edge
#### Actual behavior
<img width="320" alt="image" src="https://user-images.githubusercontent.com/14942081/210482169-a421612c-a6bd-4c8f-9824-390ae30e3392.png">
<img width="401" alt="image" src="https://user-images.githubusercontent.com/14942081/210482206-2415d3b4-8f30-4111-a5f9-5bbc183e9eaa.png">

### Additional Information

- Status desktop version: https://github.com/status-im/status-desktop/releases/0.9.0-rc.1
- Operating System: macOS Monterey

**Comment by caybro** [comment] 2023-01-04 10:30
A duplicate of https://github.com/status-im/status-desktop/issues/8910

**Closed by caybro** 2023-01-04 10:30 UTC
Labels: bug, Communities, 0.9.0
