### ISSUE TITLE
Messages are not received in the encrypted community

### ISSUE THREAD

**Issue by chaitanyaprem** [status-im/status-desktop#11211] opened 2023-06-21 16:23 UTC
# Bug Report

edit: it turns out the issue is about not receiving messages. See comments below

Messages sent by me are not getting delivered in status CC community channels. Direct messages sent to contacts seem to be working fine.

## Description
I have recently installed Status Desktop on my macbook and joined the Status CC Community as i am a new joinee. 
I am seeing messages sent by others in the same community channel. 

Attaching screenshots of a channel seen by me and my colleague.
Screenshot as seen in my app: <img width="1545" alt="Screenshot 2023-06-21 at 7 04 40 PM" src="https://github.com/status-im/status-desktop/assets/20137744/d310c780-9d2d-4e9d-8319-2d99e4a84431">
Secreenshot as seen in my colleague's app: ![image](https://github.com/status-im/status-desktop/assets/20137744/e4bbd595-fffa-41d9-8b42-6360b8035b54)

As you can see, my colleague doesn't see the message sent by me, whereas it is shown in my view. Similarly he is not able to see the message sent by another person SidActual whereas i am able to see it. 

Similarly the intro message i have posted in intros channel also is not delivered, as my colleague is not able to see it.

Looks like something has gone wrong wrt communities.

I have even restarted the status app, but still noticing the same behaviour.

## Steps to reproduce

Nothing specific, already highlighted in description.

#### Expected behavior
My messages should be sent to community channels once my request to join has been accepted.

#### Actual behavior
None of my messages are being sent out/delivered.

### Additional Information

- Status desktop version: 0.12.0
- Operating System: MacOS 13.4 (22F66) on M2 MBP

**Comment by jrainville** [comment] 2023-06-21 16:28
Hi, I can see your message in the channel `#weeb-room`. I feel like you are having low peers. Can you activate the "Node management" setting in Profile > Advanced? 

Then, you'll have a new tab on the left called "Node Management". Check how many peers you have.

Actually, looking at the screenshots, I think it's your colleague that is having issues. Here is was I see:
![image](https://github.com/status-im/status-desktop/assets/11926403/99fa2986-b23e-4146-a62c-d8a5847aff68)

**Comment by chaitanyaprem** [comment] 2023-06-21 16:31
Thansk @jrainville for quick response. 
 I have node management enabled, and i can see 9 peers. 
That is interesting, @richard-ramos is the colleague i was referring to.
Are you able to see my intro message in the intros channel?

**Comment by jrainville** [comment] 2023-06-21 16:51
> Are you able to see my intro message in the intros channel?

Yes

> That is interesting, @richard-ramos is the colleague i was referring to.

Did you open the same data dir mutliple times by any chance?

**Comment by chaitanyaprem** [comment] 2023-06-21 16:57
Ok.

Not sure what you mean by same data dir? Is it used by status desktop app for local storage?

**Comment by jrainville** [comment] 2023-06-21 17:00
> Not sure what you mean by same data dir? Is it used by status desktop app for local storage?

Sorry, that was a question for @richard-ramos . Basically, the app generate a data directory with a DB the first time you login. You can move that data directory somewhere else, but if you open it somewhere else and use it at the same time as the original copy, it can create issues with the encryption keys.

**Comment by chaitanyaprem** [comment] 2023-06-21 17:09
Ah..Ok. Got it.

**Comment by richard-ramos** [comment] 2023-06-21 17:35
Hmm. i think i haven't? I'll try restoring my account from scratch

**Comment by richard-ramos** [comment] 2023-06-21 18:09
After restoring my account, I can only see my `test` message in #weeb-room: 
![image](https://github.com/status-im/status-desktop/assets/1106587/df2a2818-7691-400c-9a2d-acc39373a35b)

I do see other messages from today in diff channels tho. Maybe the messages didn't arrive to the store node

**Comment by richard-ramos** [comment] 2023-06-21 18:42
Update:
Checking with @Jo, we see that the problem seems to happen only with the status community. Using a newer community works just fine

**Comment by richard-ramos** [comment] 2023-06-21 18:47
@cammellos, I can reproduce this error consistently with the status community. 
How does this hash ratchet group id is created? for some reason i don't have it?

**Comment by cammellos** [comment] 2023-06-21 19:11
@richard-ramos the keys most likely haven't been propagated, how did you get access to the community?
@Samyoul has been working on something that should allev'iate the issue for a while as well, any update @Samyoul ?

**Comment by richard-ramos** [comment] 2023-06-21 19:45
> how did you get access to the community?
I restored my account using the seedphrase

**Comment by cammellos** [comment] 2023-06-21 19:54
> > how did you get access to the community?
> 
> I restored my account using a seedphrase

which version of desktop did you have before? the keys should be in the backup, but depends on which version of desktop you were running

**Comment by richard-ramos** [comment] 2023-06-21 19:55
I was using a ~1w old .AppImage built from `master`

**Comment by cammellos** [comment] 2023-06-21 19:56
> I was using a ~1w old .AppImage built from `master`

it should have definitely had the keys, I will take a look at it, some bug for sure

**Comment by osmaczko** [comment] 2023-07-11 20:14
I took a closer look into the issue by comparing the `key_id`s from valid and invalid instances.
```
SELECT key_id, CAST(hex(group_id) AS TEXT) AS group_id
FROM hash_ratchet_encryption
```

For a valid instance (where the client can receive community messages):
```
3564023328 | 03073514D4C14A7D10AE9FC9B0F05ABC904D84166A6AC80ADD58BF6A3542A4E50A
3564023329 | 03073514D4C14A7D10AE9FC9B0F05ABC904D84166A6AC80ADD58BF6A3542A4E50A
3680164834 | 03073514D4C14A7D10AE9FC9B0F05ABC904D84166A6AC80ADD58BF6A3542A4E50A
3680164835 | 03073514D4C14A7D10AE9FC9B0F05ABC904D84166A6AC80ADD58BF6A3542A4E50A
3680164836 | 03073514D4C14A7D10AE9FC9B0F05ABC904D84166A6AC80ADD58BF6A3542A4E50A
3680164837 | 03073514D4C14A7D10AE9FC9B0F05ABC904D84166A6AC80ADD58BF6A3542A4E50A
3680164838 | 03073514D4C14A7D10AE9FC9B0F05ABC904D84166A6AC80ADD58BF6A3542A4E50A
```

On the other hand, an invalid instance:
```
3564023328 | 03073514D4C14A7D10AE9FC9B0F05ABC904D84166A6AC80ADD58BF6A3542A4E50A
3564023329 | 03073514D4C14A7D10AE9FC9B0F05ABC904D84166A6AC80ADD58BF6A3542A4E50A
3680164834 | 03073514D4C14A7D10AE9FC9B0F05ABC904D84166A6AC80ADD58BF6A3542A4E50A
3680164835 | 03073514D4C14A7D10AE9FC9B0F05ABC904D84166A6AC80ADD58BF6A3542A4E50A
3680164836 | 03073514D4C14A7D10AE9FC9B0F05ABC904D84166A6AC80ADD58BF6A3542A4E50A
3680164837 | 03073514D4C14A7D10AE9FC9B0F05ABC904D84166A6AC80ADD58BF6A3542A4E50A
```

The invalid instance is lacking the latest ratchet key with id 3680164838. **The question arises, why wasn't the newest ratchet key delivered to one of the clients?** This issue will be mitigated with: https://github.com/status-im/status-go/issues/3404

Side issues:
- key_id is wrong, it should be unix timestamp in ms, @Samyoul [spotted](https://github.com/status-im/status-go/issues/3675) it already
- 5 keys were created in a row (3680164834...3680164838), seems wrong, there might be a logic error in status-go when distributing new keys

**Comment by osmaczko** [comment] 2023-07-12 08:27
I've linked a PR that should mitigate the issue. It accomplishes this through periodic rekeying, which is set to occur every hour by default.

**Comment by osmaczko** [comment] 2023-07-12 08:27
Currently blocked by https://github.com/status-im/status-go/issues/3675

**Comment by alexjba** [comment] 2023-09-19 09:18
I have the same issue and @caybro as well. I've also tried to restore from seed, leave and delete the community. In this case the re-join request is either not sent by my client, or not received by the owner.

> The invalid instance is lacking the latest ratchet key with id 3680164838

@osmaczko @cammellos Can I manually update the DB in order to fix this? If there's a way to manually fix this from the DB I'd be more than happy do it until we have a proper fix. It's been weeks since I'm out of Status community.

**Comment by caybro** [comment] 2023-09-19 09:35
> I have the same issue and @caybro as well. I've also tried to restore from seed, leave and delete the community. In this case the re-join request is either not sent by my client, or not received by the owner.
> 
> > The invalid instance is lacking the latest ratchet key with id 3680164838
> 
> @osmaczko @cammellos Can I manually update the DB in order to fix this? If there's a way to manually fix this from the DB I'd be more than happy do it until we have a proper fix. It's been weeks since I'm out of Status community.

Yes please :/ Same happens for me

**Comment by osmaczko** [comment] 2023-09-19 10:48
> @osmaczko @cammellos Can I manually update the DB in order to fix this? If there's a way to manually fix this from the DB I'd be more than happy do it until we have a proper fix. It's been weeks since I'm out of Status community.

I believe the easiest way would be to leave and join the community. This should trigger the control node to send you the newest key. If that doesn't help we can have a call to identify the issue.

**Comment by jrainville** [comment] 2023-09-19 13:29
I think that since Iuri updated to 0.14, the Status CC community is kinda frozen. It can't send new descriptions for now.
That's because the description is too big since it sends members in all the channels.

There is a fix in PR. Once it's merged and Iuri updates, leaving and rejoining should work.

**Comment by osmaczko** [comment] 2023-09-19 14:04
> I think that since Iuri updated to 0.14, the Status CC community is kinda frozen. It can't send new descriptions for now. That's because the description is too big since it sends members in all the channels.
> 
> There is a fix in PR. Once it's merged and Iuri updates, leaving and rejoining should work.

Technically, request to join and keys propagation are done through different messages, so it should work. Although I am not sure how would clients react to `CommunityDescription` with themselves still on member list when they leave and than join. Worth to try.

**Comment by osmaczko** [comment] 2023-10-30 20:40
The issue has been mitigated. The community should heal itself due to the implemented rekeying loop. Additionally, the key_id has been enhanced and should no longer overflow.

**Closed by osmaczko** 2023-10-30 20:40 UTC
Labels: bug, blocked, messenger-team, C3, E:Desktop Community Bugfixes MVP
