### ISSUE TITLE
When you try to mention nickname that starts or ends with a space, an error is sent in the chat

### ISSUE THREAD

**Issue by churik** [status-im/status-desktop#10249] opened 2023-04-10 15:33 UTC
# Bug Report

## Description
Currently, if the custom name of the user starts/ends with a space, the error is shown when attempting to mention them.

## Steps to reproduce

- open a community
- rename any member to `    username`
- try to mention them in the community

#### Expected behavior
can mention any member regardless of the username

#### Actual behavior

https://user-images.githubusercontent.com/4557972/231187794-b825375e-7dda-40fe-9ea4-a51e49700f4a.mp4

### Additional Information

- Status desktop version: master 31/03/23
- Operating System: Mac OS Ventura 13.2.1

**Comment by anastasiyaig** [comment] 2023-04-11 09:51
@churik your video / screenshot seems to be failed to upload

**Comment by iurimatias** [comment] 2023-04-20 15:07
duplicate of https://github.com/status-im/status-desktop/issues/10120

**Closed by iurimatias** 2023-04-20 15:07 UTC
Labels: bug, messenger-team
