### ISSUE TITLE
App crashes from sending a payment

### ISSUE THREAD

**Issue by chainvisions** [status-im/status-desktop#1016] opened 2020-09-26 06:55 UTC
I have tried sending a payment on the Windows version of Status and when I clicked "Request Address" to get the recipient's address, the app crashed.  After logging back in, I found that clicking on the chat makes the app crash immediately. After clicking the chat, I have found that logging in makes the app crash and this happens for around three times and the fourth time allows you to login successfully without it crashing. I have also found that clicking on the recipient in a chat and clicking "Send message" makes the app crash and it returns the following error message:
```
Traceback (most recent call last)
C:\dev\nim-status-client\src\nim_status_client.nim(167) nim_status_client
C:\dev\nim-status-client\src\nim_status_client.nim(110) mainProc
C:\dev\nim-status-client\vendor\nimqml\src\nimqml\private\qqmlapplicationengine.nim(34) delete
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
```

**Comment by michaelsbradleyjr** [comment] 2020-09-26 12:46
There is a memory corruption bug we’re aware of and working to resolve. It can manifest in various ways in almost any part of the app, and the traceback you included above is typical of that bug. Don’t worry too much about trying to capture details of the crashes because this bug is a kind of “race condition” and therefore subject to randomness. You may be able to produce it consistently for a whole day, and then tomorrow it could become infrequent.

**Comment by jrainville** [comment] 2020-09-28 13:37
@chainvisions if you do manage to login, you can try to `Clear the history` of the recipient. If the error is in the chat list of the recipient, it might get rid of it

**Comment by iurimatias** [comment] 2021-01-19 22:53
duplicate of another issue. can confirm this issue doesn't seem to happen anymore / can't replicate

**Closed by iurimatias** 2021-01-19 22:53 UTC
Labels: Chat, bug
