### ISSUE TITLE
Some buttons using bold text while others aren't

### ISSUE THREAD

**Issue by iurimatias** [status-im/status-desktop#7359] opened 2022-09-14 20:17 UTC
# Bug Report

## Description

On onboarding (including welcome screen) there are buttons that use bold text, yet in other screens the buttons are not bold. This needs to be made consistent and according to design.

another example is the the community requests modal

![upload_3b078f8ac45ca129c915a5af268686aa](https://user-images.githubusercontent.com/176720/190258337-d8d1383a-84d5-4ae1-9a39-12c8383d62ec.png)

**Comment by caybro** [comment] 2022-09-14 21:59
This is not bold but medium and by design :) We need to fix the other buttons

StatusBaseButton has this:
```qml
font.weight: Font.Medium
```

**Comment by alexandraB99** [comment] 2022-09-16 15:36
@caybro please close if fixed already

**Comment by caybro** [comment] 2022-09-18 12:04
Should get fixed with https://github.com/status-im/status-desktop/pull/7396

**Closed** 2022-09-19 20:10 UTC
Labels: ui, E:Onboarding, pixel-perfect-issues, S:1
