### ISSUE TITLE
Can't sign in to Kyberswap

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#2559] opened 2021-05-13 13:38 UTC
<img width="1552" alt="Screenshot 2021-05-13 at 16 37 35" src="https://user-images.githubusercontent.com/82375995/118133471-8d1b1600-b409-11eb-9200-fa198114168f.png">

`js: 'window.webkitStorageInfo' is deprecated. Please use 'navigator.webkitTemporaryStorage' or 'navigator.webkitPersistentStorage' instead.`

**Comment by iurimatias** [comment] 2021-05-31 19:58
apparently we can get around this by enabling/disabling compatibility mode

**Comment by iurimatias** [comment] 2022-03-11 20:53
duplicate of #3323

**Closed** 2022-05-15 22:57 UTC
Labels: bug, Browser, priority 2: medium, E:Browser, E:Bugfixes
