### ISSUE TITLE
Right click -> Close makes the app not responding

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#8401] opened 2022-11-23 08:53 UTC
### Description

**Version:** master commit 9f076ed70c5680e056cffad794e3b46feeaa786e

1. launch the app
2. login
3. right click the app icon in trey - close

<img width="1440" alt="Screenshot 2022-11-23 at 11 34 57" src="https://user-images.githubusercontent.com/82375995/203504941-c6db13e7-39b2-4e2c-87ee-91cf96816b8f.png">

**Comment by caybro** [comment] 2022-11-23 09:20
I can reproduce on Linux too; the app just hangs :/

**Comment by jrainville** [comment] 2022-11-28 19:10
I did a bisect and found that the commit introducing the issue is `6c0806c2e1dc278794de8789eb99473e57c6e94e` (https://github.com/status-im/status-desktop/pull/8348).
I'm investigating why. I think it might be the new async task. 
cc @Khushboo-dev-cpp

**Comment by jrainville** [comment] 2022-11-28 20:04
It's because of the `startFetchingHistoryTimer`funciton. If I remove the threadpool start, it closes immediately. If I set the timer to 5 seconds instead of 20 minutes, it closes in <5 seconds.
I'm trying to see if there is a way to fix that

**Comment by jrainville** [comment] 2022-11-28 20:32
All our timers seem to do that. We just didn't realize the effects because all other timers are 5 seconds or less.
There is  a problem with our threads where they don't get a proper signal to close.

**Comment by jrainville** [comment] 2022-11-28 21:05
I opened a hotfix PR. Waiting for Anthony's reply to see if I can remove the draft

**Comment by jrainville** [comment] 2022-11-28 21:12
Draft removed. Can be reviewed and merged

**Comment by endulab** [comment] 2022-12-01 10:39
@jrainville @Khushboo-dev-cpp @alaibe if this is a timer issue, we can use Qt Timer which was added in #6179. You can now have 20 minutes timer.

**Comment by caybro** [comment] 2022-12-12 11:01
@jrainville @endulab the bug is back in master... same symptoms, likely same issue

![image](https://user-images.githubusercontent.com/5377645/207029085-e3e97466-a679-413e-93fe-beac5c8207f6.png)

**Comment by endulab** [comment] 2022-12-15 09:34
@caybro @jrainville works ok for me on current master.

**Comment by anastasiyaig** [comment] 2022-12-15 09:35
I tested it as well today, confirm it is working on latest master as of commit 50427390ddb1f769e3313adb7b7deef612037138

**Comment by jrainville** [comment] 2022-12-15 17:12
I only see the Nim timer still used in `keycard/service` and it's only 3 seconds, so I doubt it is it.

Maybe @caybro had a request timing out in a thread? Can you reproduce @caybro ?

**Comment by caybro** [comment] 2023-01-03 18:21
@jrainville @anastasiyaig I was not able to reproduce on today's master

**Closed** 2023-01-09 17:21 UTC
Labels: bug, general, E:Bugfixes
