### ISSUE TITLE
Preserve state that members list was opened in community

### ISSUE THREAD

**Issue by PascalPrecht** [status-im/status-desktop#3549] opened 2021-09-15 08:01 UTC
It would be cool if, when I restart Status and go back to the community, I don't have to reopen the user list every single time.
Maybe we can save the state of opened members lists for each community (and probably chat in general)?

**Comment by iurimatias** [comment] 2021-09-15 20:11
duplicate of #3502

**Closed by iurimatias** 2021-09-15 20:11 UTC
