### ISSUE TITLE
Add @everyone at mention functionality, to @ mention everybody in a community

### ISSUE THREAD

**Issue by John-44** [status-im/status-desktop#8479] opened 2022-11-28 13:03 UTC
Add @everyone at mention functionality, to @ mention everybody in a community or an ad-hoc group chat.

If a user types @everyone then that message should appear as an @ mention for everybody in the community (or ad-hoc group chat).

@everyone should also appear as an entry in the @ mention autocomplete.

"@everybody" should be classed as a "Global @ Mention", we already have the interface for managing global @ mentions in the Notifications Settings design, see below:

![2022-11-28 13_02_16-Window](https://user-images.githubusercontent.com/22846356/204284617-27b55c07-796f-4b0b-a039-c8e5d441fe39.png)

(from https://www.figma.com/file/idUoxN7OIW2Jpp3PMJ1Rl8/%E2%9A%99%EF%B8%8F-Settings-%7C-Desktop?node-id=702%3A75214&t=LML4DUnj0V6tmYaH-1 )

**Comment by jrainville** [comment] 2022-11-28 15:31
This is a duplicate of https://github.com/status-im/status-desktop/issues/8311, but contains way more info, so I'll close the other one.

**Comment by PascalPrecht** [comment] 2022-12-05 14:32
> @everyone should also appear as an entry in the @ mention autocomplete.

What would that look like? Right now the suggestion box looks like this:
![Screenshot from 2022-12-05 15-30-45](https://user-images.githubusercontent.com/445106/205662296-42a9379c-1d3f-4c1f-a68e-b55445465cc8.png)

We could probably use some icon instead of a profile picture if we want to add `@everyone` to that list.
I checked discord, and discord doesn't add  `@everyone` to the suggestions.

**Comment by PascalPrecht** [comment] 2022-12-05 15:08
Another thing @John-44 the screenshot you've posted there, also what's currently implemented, in the sound settings we say `@here` or `@channel`.

Is `@here` == `@everyone` ?
I know that on discord, I believe, `@here` is for everyone who's online while `@everyone` is everyone regardless of their online state.

I don't think we can really distinguish like that atm, so I'd say we replace `@here` with `@everyone` in the settings description?

**Comment by jrainville** [comment] 2022-12-05 15:36
As for the icon, use whatever placeholder you see that fits. We'll create  anew issue if the design comes in afterwards

**Comment by PascalPrecht** [comment] 2022-12-05 15:43
>  @PascalPrecht for this current issue, only do @everyone, where it pings everyone in a community. One we have token gated channels, we'll add support for @here. There is an issue open for @here I think.

Sure thing, but shouldn't we also replace `@here` with `@everyone` in the settings descriptoin for now? Because don't support `@here` and `@channel` atm. Then they shouldn't show up in the UI IMO

**Comment by jrainville** [comment] 2022-12-05 15:57
> Because don't support @here and @channel atm. Then they shouldn't show up in the UI IMO

Sorry, I hadn't seen it in the screenshot. Yes, ignore any mention of `@here` for now

**Closed** 2022-12-21 09:19 UTC
Labels: feature, E:Communities, S:4
