### ISSUE TITLE
3 words name instead of display name while logging in after profile restore

### ISSUE THREAD

**Issue by chaitanyaprem** [status-im/status-desktop#14053] opened 2024-03-20 01:15 UTC
# Bug Report

After installing 2.27 and doing a profile restoration, everytime i try to login my username is not displayed in login prompt rather 3 random words are shown. After logging in the username is shown in the profile section though.

## Description

Attaching a screenshot of same. 
<img width="1371" alt="Screenshot 2024-03-20 at 6 42 58 AM" src="https://github.com/status-im/status-desktop/assets/20137744/6e9b9ffc-b38d-4e57-8af6-b582c4613bc8">
<img width="246" alt="Screenshot 2024-03-20 at 6 44 54 AM" src="https://github.com/status-im/status-desktop/assets/20137744/4c029cff-69d3-4384-859f-f691f6159b00">

#### Expected behavior
Username should be shown in login screen.

### Additional Information

- Status desktop version: 2.27.0
- Operating System: macOS Sonoma 14.4

**Comment by anastasiyaig** [comment] 2024-03-20 08:39
its a dupe of https://github.com/status-im/status-desktop/issues/13050

**Comment by anastasiyaig** [comment] 2024-03-20 12:01
@jrainville can you please check on that?

**Comment by jrainville** [comment] 2024-03-20 14:17
Ah, yes, I've seen this before. It only happens when restoring the account. I think the account creation doesn't update the accounts DB (the unencrypted one). So we need to fix it.

It's not a huge priority though, so I'll put it in 2.29

**Comment by igor-sirotin** [comment] 2024-03-21 22:17
I'm able to reproduce this and aim to fix it together with https://github.com/status-im/status-desktop/issues/12977.

**Closed** 2024-03-25 15:43 UTC
Labels: bug, messenger-team, E:Desktop Onboarding & Login, status-waku-integ
