### ISSUE TITLE
Communities sidebar glitched, missing profiles

### ISSUE THREAD

**Issue by du64** [status-im/status-desktop#7256] opened 2022-09-07 03:16 UTC
# Bug Report

## Description
When loading the desktop app, there's a chance it will show multiples of the communities, which makes settings and other options inaccessible. When this happens, profile pictures and names also disappear.

![Screenshot from 2022-09-06 22-12-49](https://user-images.githubusercontent.com/65834069/188780507-017f5cd9-62b7-40d6-8b72-b8d1bb2e4365.png)

### Additional Information

- Status desktop version: https://github.com/status-im/status-desktop/pull/7231
- Operating System: ZorinOS 16, Windows 10, Windows 11

**Comment by iurimatias** [comment] 2022-09-22 20:10
duplicate of https://github.com/status-im/status-desktop/issues/7167

**Closed by iurimatias** 2022-09-22 20:10 UTC
Labels: bug
