### ISSUE TITLE
(waku peer exchange?) segmentation fault (core dumped)

### ISSUE THREAD

**Issue by fryorcraken** [status-im/status-desktop#9516] opened 2023-02-09 21:54 UTC
# Bug Report

## Description

Segmentation fault.

## Steps to reproduce

Not sure, likely related to lack of connection and sleep time.

#### Expected behavior

no segfault

#### Actual behavior

yes segfault

### Additional Information

- Status desktop version: 0.9.0
- Operating System: Linux Fedora

```
RR 2023-02-09 18:36:47.956+11:00 error doing rpc request                    topics="rpc" tid=339576 file=core.nim:33 methodName=wallet_getWalletToken exception="\nstatus-go error [methodName:wallet_getWalletToken, code:-32000, message:Get \"https://min-api.cryptocompare.com/data/pricemulti?fsyms=DGX,USDS,LINK,HT,AKRO,TCAD,MDS,NMR,LPT,CVC,NPXS,ETH2X-FLI,ST,RAE,ATM,EDO,IOST,SNM,ENG,SPN&tsyms=AUD,USD&extraParams=Status.im\": dial tcp: lookup min-api.cryptocompare.com: no such host ]\n"
ERR 2023-02-09 18:36:47.956+11:00 [threadpool task thread] exception         topics="task-threadpool" tid=339576 file=threadpool.nim:100 error="\nstatus-go error [methodName:wallet_getWalletToken, code:-32000, message:Get \"https://min-api.cryptocompare.com/data/pricemulti?fsyms=DGX,USDS,LINK,HT,AKRO,TCAD,MDS,NMR,LPT,CVC,NPXS,ETH2X-FLI,ST,RAE,ATM,EDO,IOST,SNM,ENG,SPN&tsyms=AUD,USD&extraParams=Status.im\": dial tcp: lookup min-api.cryptocompare.com: no such host ]\n"
ERR 2023-02-09 18:46:47.688+11:00 rpc response error                         topics="rpc" tid=339573 file=core.nim:29 err="\nstatus-go error [methodName:wallet_getWalletToken, code:-32000, message:Get \"https://min-api.cryptocompare.com/data/all/coinlist\": dial tcp: lookup min-api.cryptocompare.com: no such host ]\n"
ERR 2023-02-09 18:46:47.688+11:00 error doing rpc request                    topics="rpc" tid=339573 file=core.nim:33 methodName=wallet_getWalletToken exception="\nstatus-go error [methodName:wallet_getWalletToken, code:-32000, message:Get \"https://min-api.cryptocompare.com/data/all/coinlist\": dial tcp: lookup min-api.cryptocompare.com: no such host ]\n"
ERR 2023-02-09 18:46:47.688+11:00 [threadpool task thread] exception         topics="task-threadpool" tid=339573 file=threadpool.nim:100 error="\nstatus-go error [methodName:wallet_getWalletToken, code:-32000, message:Get \"https://min-api.cryptocompare.com/data/all/coinlist\": dial tcp: lookup min-api.cryptocompare.com: no such host ]\n"
ERR 2023-02-09 18:56:47.429+11:00 rpc response error                         topics="rpc" tid=339572 file=core.nim:29 err="\nstatus-go error [methodName:wallet_getWalletToken, code:-32000, message:Get \"https://min-api.cryptocompare.com/data/pricemulti?fsyms=QRL,EDG,PAY,WETH,XPA,PAXG,CFI,RARE,WTC,SPN,DAI,BUFF,GNT,DNT,AVT,WIBB,UNI,USDD,RAE,SNM&tsyms=AUD,USD&extraParams=Status.im\": dial tcp: lookup min-api.cryptocompare.com: no such host ]\n"
ERR 2023-02-09 18:56:47.429+11:00 error doing rpc request                    topics="rpc" tid=339572 file=core.nim:33 methodName=wallet_getWalletToken exception="\nstatus-go error [methodName:wallet_getWalletToken, code:-32000, message:Get \"https://min-api.cryptocompare.com/data/pricemulti?fsyms=QRL,EDG,PAY,WETH,XPA,PAXG,CFI,RARE,WTC,SPN,DAI,BUFF,GNT,DNT,AVT,WIBB,UNI,USDD,RAE,SNM&tsyms=AUD,USD&extraParams=Status.im\": dial tcp: lookup min-api.cryptocompare.com: no such host ]\n"
ERR 2023-02-09 18:56:47.429+11:00 [threadpool task thread] exception         topics="task-threadpool" tid=339572 file=threadpool.nim:100 error="\nstatus-go error [methodName:wallet_getWalletToken, code:-32000, message:Get \"https://min-api.cryptocompare.com/data/pricemulti?fsyms=QRL,EDG,PAY,WETH,XPA,PAXG,CFI,RARE,WTC,SPN,DAI,BUFF,GNT,DNT,AVT,WIBB,UNI,USDD,RAE,SNM&tsyms=AUD,USD&extraParams=Status.im\": dial tcp: lookup min-api.cryptocompare.com: no such host ]\n"
ERR 2023-02-09 19:06:48.172+11:00 rpc response error                         topics="rpc" tid=339578 file=core.nim:29 err="\nstatus-go error [methodName:wallet_getWalletToken, code:-32000, message:Get \"https://min-api.cryptocompare.com/data/pricemultifull?fsyms=PLR,LINK,SUSD,DNT,DCN,EKO,ADX,SPIKE,UBT,WETH,NEXO,OTN,EDO,WTC,GNT,AKRO,EOS,BTM,ETH,MLN,COB,NMR,STORJ,TCAD,VGX,EVX,XAUR,BLZ,BRLN,XDATA,ANT,DTA,KIN,EDG,USDS,TGT,FUN,OMG,STX,CRV,TAAS,RHOC,PAXG,CND,XEENUS,TIME,TGBP,HST,MDA,SNT,SUB,BNB,MTL,IOST,HT,LPT,TRX,FRAX,ABYSS,UKG,CDT,SPN,AVT,REP,ENJ,PPP,WINGS,ZSC,ENG,DPY,RAE,PRG,BNT,LEND,SALT,AE,ICN,ELF,ATM,MTH,USDP,MDS,GNO,TUSD,ADI,UBI,ENS,REQ,BTU,ETH2X-FLI,OGN,POWR,TRST,SAI,R,PAY,GEN,FUEL,MCO,GRID,WBTC,BAND,WGN,GRT,WIBB,OXT,VERI,HEZ,ABT,ICOS,CENTRA,MGO,XPA,ZEENUS,DGD,AMB,MANA,XRL,BUFF,TKN,NPXS,QSP,BLT,CDAI,VRS,MOKSHA,SNT,DAI,ZRX,AMPL,SNM,AUSDC,COMP,MKR,MFG,TNT,LXS,USDT,DLT,UPP,RLC,SAN,PT,SNGLS,APPC,CFI,POLY,LRC,MOC,RARE,QRL,ROL,REN,CSNO,USDC,FXC,1ST,LINK,BAT,VIB,POE,QKC,WABI,USDD,HND,DAT,MOD,SNX,SPANK,GLM,STORM,SOCKS,YEENUS,RCN,MET,UNI,CVC,LOOM,PPT,DRT,AST,KNC,TAUD,RDN,BAL,ST,DGX&tsyms=AUD,USD&extraParams=Status.im\": dial tcp: lookup min-api.cryptocompare.com: no such host ]\n"
ERR 2023-02-09 19:06:48.172+11:00 error doing rpc request                    topics="rpc" tid=339578 file=core.nim:33 methodName=wallet_getWalletToken exception="\nstatus-go error [methodName:wallet_getWalletToken, code:-32000, message:Get \"https://min-api.cryptocompare.com/data/pricemultifull?fsyms=PLR,LINK,SUSD,DNT,DCN,EKO,ADX,SPIKE,UBT,WETH,NEXO,OTN,EDO,WTC,GNT,AKRO,EOS,BTM,ETH,MLN,COB,NMR,STORJ,TCAD,VGX,EVX,XAUR,BLZ,BRLN,XDATA,ANT,DTA,KIN,EDG,USDS,TGT,FUN,OMG,STX,CRV,TAAS,RHOC,PAXG,CND,XEENUS,TIME,TGBP,HST,MDA,SNT,SUB,BNB,MTL,IOST,HT,LPT,TRX,FRAX,ABYSS,UKG,CDT,SPN,AVT,REP,ENJ,PPP,WINGS,ZSC,ENG,DPY,RAE,PRG,BNT,LEND,SALT,AE,ICN,ELF,ATM,MTH,USDP,MDS,GNO,TUSD,ADI,UBI,ENS,REQ,BTU,ETH2X-FLI,OGN,POWR,TRST,SAI,R,PAY,GEN,FUEL,MCO,GRID,WBTC,BAND,WGN,GRT,WIBB,OXT,VERI,HEZ,ABT,ICOS,CENTRA,MGO,XPA,ZEENUS,DGD,AMB,MANA,XRL,BUFF,TKN,NPXS,QSP,BLT,CDAI,VRS,MOKSHA,SNT,DAI,ZRX,AMPL,SNM,AUSDC,COMP,MKR,MFG,TNT,LXS,USDT,DLT,UPP,RLC,SAN,PT,SNGLS,APPC,CFI,POLY,LRC,MOC,RARE,QRL,ROL,REN,CSNO,USDC,FXC,1ST,LINK,BAT,VIB,POE,QKC,WABI,USDD,HND,DAT,MOD,SNX,SPANK,GLM,STORM,SOCKS,YEENUS,RCN,MET,UNI,CVC,LOOM,PPT,DRT,AST,KNC,TAUD,RDN,BAL,ST,DGX&tsyms=AUD,USD&extraParams=Status.im\": dial tcp: lookup min-api.cryptocompare.com: no such host ]\n"
ERR 2023-02-09 19:06:48.172+11:00 [threadpool task thread] exception         topics="task-threadpool" tid=339578 file=threadpool.nim:100 error="\nstatus-go error [methodName:wallet_getWalletToken, code:-32000, message:Get \"https://min-api.cryptocompare.com/data/pricemultifull?fsyms=PLR,LINK,SUSD,DNT,DCN,EKO,ADX,SPIKE,UBT,WETH,NEXO,OTN,EDO,WTC,GNT,AKRO,EOS,BTM,ETH,MLN,COB,NMR,STORJ,TCAD,VGX,EVX,XAUR,BLZ,BRLN,XDATA,ANT,DTA,KIN,EDG,USDS,TGT,FUN,OMG,STX,CRV,TAAS,RHOC,PAXG,CND,XEENUS,TIME,TGBP,HST,MDA,SNT,SUB,BNB,MTL,IOST,HT,LPT,TRX,FRAX,ABYSS,UKG,CDT,SPN,AVT,REP,ENJ,PPP,WINGS,ZSC,ENG,DPY,RAE,PRG,BNT,LEND,SALT,AE,ICN,ELF,ATM,MTH,USDP,MDS,GNO,TUSD,ADI,UBI,ENS,REQ,BTU,ETH2X-FLI,OGN,POWR,TRST,SAI,R,PAY,GEN,FUEL,MCO,GRID,WBTC,BAND,WGN,GRT,WIBB,OXT,VERI,HEZ,ABT,ICOS,CENTRA,MGO,XPA,ZEENUS,DGD,AMB,MANA,XRL,BUFF,TKN,NPXS,QSP,BLT,CDAI,VRS,MOKSHA,SNT,DAI,ZRX,AMPL,SNM,AUSDC,COMP,MKR,MFG,TNT,LXS,USDT,DLT,UPP,RLC,SAN,PT,SNGLS,APPC,CFI,POLY,LRC,MOC,RARE,QRL,ROL,REN,CSNO,USDC,FXC,1ST,LINK,BAT,VIB,POE,QKC,WABI,USDD,HND,DAT,MOD,SNX,SPANK,GLM,STORM,SOCKS,YEENUS,RCN,MET,UNI,CVC,LOOM,PPT,DRT,AST,KNC,TAUD,RDN,BAL,ST,DGX&tsyms=AUD,USD&extraParams=Status.im\": dial tcp: lookup min-api.cryptocompare.com: no such host ]\n"
ERR 2023-02-09 19:16:47.897+11:00 rpc response error                         topics="rpc" tid=339571 file=core.nim:29 err="\nstatus-go error [methodName:wallet_getWalletToken, code:-32000, message:Get \"https://min-api.cryptocompare.com/data/all/coinlist\": dial tcp: lookup min-api.cryptocompare.com: no such host ]\n"
ERR 2023-02-09 19:16:47.897+11:00 error doing rpc request                    topics="rpc" tid=339571 file=core.nim:33 methodName=wallet_getWalletToken exception="\nstatus-go error [methodName:wallet_getWalletToken, code:-32000, message:Get \"https://min-api.cryptocompare.com/data/all/coinlist\": dial tcp: lookup min-api.cryptocompare.com: no such host ]\n"
ERR 2023-02-09 19:16:47.897+11:00 [threadpool task thread] exception         topics="task-threadpool" tid=339571 file=threadpool.nim:100 error="\nstatus-go error [methodName:wallet_getWalletToken, code:-32000, message:Get \"https://min-api.cryptocompare.com/data/all/coinlist\": dial tcp: lookup min-api.cryptocompare.com: no such host ]\n"
ERR 2023-02-09 19:26:47.647+11:00 rpc response error                         topics="rpc" tid=339574 file=core.nim:29 err="\nstatus-go error [methodName:wallet_getWalletToken, code:-32000, message:Get \"https://min-api.cryptocompare.com/data/all/coinlist\": dial tcp: lookup min-api.cryptocompare.com: no such host ]\n"
ERR 2023-02-09 19:26:47.648+11:00 error doing rpc request                    topics="rpc" tid=339574 file=core.nim:33 methodName=wallet_getWalletToken exception="\nstatus-go error [methodName:wallet_getWalletToken, code:-32000, message:Get \"https://min-api.cryptocompare.com/data/all/coinlist\": dial tcp: lookup min-api.cryptocompare.com: no such host ]\n"
ERR 2023-02-09 19:26:47.648+11:00 [threadpool task thread] exception         topics="task-threadpool" tid=339574 file=threadpool.nim:100 error="\nstatus-go error [methodName:wallet_getWalletToken, code:-32000, message:Get \"https://min-api.cryptocompare.com/data/all/coinlist\": dial tcp: lookup min-api.cryptocompare.com: no such host ]\n"
Warning: "Object does not exist at path “/org/freedesktop/NetworkManager/ActiveConnection/508”" (:0, )
Warning: "Object does not exist at path “/org/freedesktop/NetworkManager/ActiveConnection/502”" (:0, )
Warning: "Object does not exist at path “/org/freedesktop/NetworkManager/ActiveConnection/500”" (:0, )
Warning: "Object does not exist at path “/org/freedesktop/NetworkManager/ActiveConnection/499”" (:0, )
INF 2023-02-09 19:27:54.707+11:00 active mailserver changed                  topics="mailservers-service" tid=339537 file=service.nim:163 node=/dns4/node-02.gc-us-central1-a.status.prod.statusim.net/tcp/30303/p2p/16Uiu2HAmDQugwDHM3YeUp86iGjrUvbdw3JPRgikC7YoGBsT2ymMg
Warning: "Object does not exist at path “/org/freedesktop/NetworkManager/ActiveConnection/508”" (:0, )
Warning: "Object does not exist at path “/org/freedesktop/NetworkManager/ActiveConnection/502”" (:0, )
Warning: "Object does not exist at path “/org/freedesktop/NetworkManager/ActiveConnection/500”" (:0, )
Warning: "Object does not exist at path “/org/freedesktop/NetworkManager/ActiveConnection/499”" (:0, )
Warning: "Object does not exist at path “/org/freedesktop/NetworkManager/ActiveConnection/508”" (:0, )
Warning: "Object does not exist at path “/org/freedesktop/NetworkManager/ActiveConnection/502”" (:0, )
Warning: "Object does not exist at path “/org/freedesktop/NetworkManager/ActiveConnection/500”" (:0, )
Warning: "Object does not exist at path “/org/freedesktop/NetworkManager/ActiveConnection/499”" (:0, )
INF 2023-02-09 19:28:09.634+11:00 mailserver not working                     topics="mailservers-service" tid=339537 file=service.nim:173
INF 2023-02-09 19:28:09.645+11:00 removing active mailserver                 topics="mailservers-service" tid=339537 file=service.nim:161
Warning: "Object does not exist at path “/org/freedesktop/NetworkManager/ActiveConnection/508”" (:0, )
Warning: "Object does not exist at path “/org/freedesktop/NetworkManager/ActiveConnection/502”" (:0, )
Warning: "Object does not exist at path “/org/freedesktop/NetworkManager/ActiveConnection/500”" (:0, )
Warning: "Object does not exist at path “/org/freedesktop/NetworkManager/ActiveConnection/499”" (:0, )
Warning: "Object does not exist at path “/org/freedesktop/NetworkManager/ActiveConnection/508”" (:0, )
Warning: "Object does not exist at path “/org/freedesktop/NetworkManager/ActiveConnection/502”" (:0, )
Warning: "Object does not exist at path “/org/freedesktop/NetworkManager/ActiveConnection/500”" (:0, )
Warning: "Object does not exist at path “/org/freedesktop/NetworkManager/ActiveConnection/499”" (:0, )
Warning: "Object does not exist at path “/org/freedesktop/NetworkManager/ActiveConnection/508”" (:0, )
Warning: "Object does not exist at path “/org/freedesktop/NetworkManager/ActiveConnection/502”" (:0, )
Warning: "Object does not exist at path “/org/freedesktop/NetworkManager/ActiveConnection/500”" (:0, )
Warning: "Object does not exist at path “/org/freedesktop/NetworkManager/ActiveConnection/499”" (:0, )
INF 2023-02-09 19:29:14.050+11:00 active mailserver changed                  topics="mailservers-service" tid=339537 file=service.nim:163 node=/dns4/node-02.ac-cn-hongkong-c.status.prod.statusim.net/tcp/30303/p2p/16Uiu2HAmFy8BrJhCEmCYrUfBdSNkrPw6VHExtv4rRp1DSBnCPgx8
INF 2023-02-09 19:29:17.059+11:00 mailserver available                       topics="mailservers-service" tid=339537 file=service.nim:168
MAILSERVER AVAILABLE: ref 0x7f7299b83150 --> []

2023-02-09T19:29:17.087+1100	INFO	swarm2	swarm/swarm_dial.go:386	error resolving /dns4/node-01.ac-cn-hongkong-c.status.prod.statusim.net/tcp/443/tls/sni/node-01.ac-cn-hongkong-c.status.prod.statusim.net/ws/p2p/16Uiu2HAkvEZgh3KLwhLwXg95e5ojM8XykJ4Kxi2T7hk22rnA7pJC: lookup node-01.ac-cn-hongkong-c.status.prod.statusim.net: no such host
panic: runtime error: slice bounds out of range [:2] with capacity 0

goroutine 403 [running]:
github.com/waku-org/go-waku/waku/v2/utils.Multiaddress(0x1c0025e30e0)
	/home/jenkins/workspace/status-desktop/platforms/linux/vendor/status-go/vendor/github.com/waku-org/go-waku/waku/v2/utils/enr.go:184 +0x5db
github.com/waku-org/go-waku/waku/v2/utils.EnodeToPeerInfo(0x3?)
	/home/jenkins/workspace/status-desktop/platforms/linux/vendor/status-go/vendor/github.com/waku-org/go-waku/waku/v2/utils/enr.go:207 +0x19
github.com/waku-org/go-waku/waku/v2/discv5.evaluateNode(0x1c0025e30e0)
	/home/jenkins/workspace/status-desktop/platforms/linux/vendor/status-go/vendor/github.com/waku-org/go-waku/waku/v2/discv5/discover.go:232 +0x3f
github.com/ethereum/go-ethereum/p2p/enode.(*filterIter).Next(0x1c007568000)
	/home/jenkins/workspace/status-desktop/platforms/linux/vendor/status-go/vendor/github.com/ethereum/go-ethereum/p2p/enode/iter.go:119 +0x54
github.com/waku-org/go-waku/waku/v2/protocol/peer_exchange.(*WakuPeerExchange).iterate(0x1c000ed8380, {0x7f72a39569a8, 0x1c004664580})
	/home/jenkins/workspace/status-desktop/platforms/linux/vendor/status-go/vendor/github.com/waku-org/go-waku/waku/v2/protocol/peer_exchange/waku_peer_exchange.go:327 +0x245
github.com/waku-org/go-waku/waku/v2/protocol/peer_exchange.(*WakuPeerExchange).runPeerExchangeDiscv5Loop(0x1c000ed8380, {0x7f72a39569a8, 0x1c004664580})
	/home/jenkins/workspace/status-desktop/platforms/linux/vendor/status-go/vendor/github.com/waku-org/go-waku/waku/v2/protocol/peer_exchange/waku_peer_exchange.go:370 +0x28f
created by github.com/waku-org/go-waku/waku/v2/protocol/peer_exchange.(*WakuPeerExchange).Start
	/home/jenkins/workspace/status-desktop/platforms/linux/vendor/status-go/vendor/github.com/waku-org/go-waku/waku/v2/protocol/peer_exchange/waku_peer_exchange.go:94 +0x1c5
[1]    339537 segmentation fault (core dumped)  ~/.local/bin/StatusIm-Desktop-v0.9.0-ef27bb.AppImage

```

**Comment by richard-ramos** [comment] 2023-02-09 21:56
Fixed in https://github.com/status-im/status-desktop/pull/9509

**Comment by caybro** [comment] 2023-02-13 13:56
Dupe of https://github.com/status-im/status-desktop/pull/9509

**Closed by caybro** 2023-02-13 13:56 UTC
Labels: bug
