### ISSUE TITLE
Chat: Messages are not being delivered in a timely manner

### ISSUE THREAD

**Issue by glitchminer** [status-im/status-desktop#9463] opened 2023-02-06 15:14 UTC
# Bug Report

## Description

Several instances have been reported now of messages not arriving soon after they were sent.

For example:

1. DMs that do not arrive until a day later or after a restart
2. Messages in chats that arrive later and appear in the history, sometimes changing the context of a message sent in multiple parts.
3. In a group chat, having members of the group chat not being able to see messages from 1 or more parties while the rest of the users can see everyone's.

## Steps to reproduce

1. Send DM and ask recipient if they can see it straight away
2. Observe messages after a restart or simply arriving later and being inserted into the history of the previous day
3. Chat with a group and confirm if all members can see each message

#### Expected behavior

Messages arrive in a timely manner

#### Actual behavior

The arrival time of the messages is unpredictable from the UI

### Additional Information

- Status desktop version: 0.10.0 RC3
- Operating System: Mac

**Comment by anastasiyaig** [comment] 2023-03-06 14:41
@jrainville can we assign to someone to investigate?

**Comment by jrainville** [comment] 2023-03-06 14:59
> i was able to see this issue as well recently, i failed to receive messages in my DMs until i restarted the app several times.

Did you note a low number of peers on any of the accounts?

**Comment by anastasiyaig** [comment] 2023-03-06 15:12
i am around 29 now but indeed i did not think of noting the peers count before i did the restart :(

**Comment by jrainville** [comment] 2023-03-06 15:15
If possible, if anyone experiences this again, note the peer count. It's very important to know if this is a network issue or an app issue.

I don't think I can assign anyone to this until then, because they will be investigating blindly.

**Comment by osmaczko** [comment] 2023-03-10 14:15
I experienced it today as well. My peer count was at around 45. Post restart, the direct message from @glitchminer appeared immediately.

**Comment by glitchminer** [comment] 2023-03-10 14:35
Hi @jrainville , I saw this again today where the DM was only received after a restart. There were 21 peers before and after.

**Comment by jrainville** [comment] 2023-03-10 14:54
Ok, I wonder if it's related to some sort of contact desync? Can you guys check your contact list to see if you are really mutual contact with each other? @osmaczko @glitchminer 
It's worth checking also next time it happens, before restarting, in case it fixed itself for some reason.

**Comment by glitchminer** [comment] 2023-03-10 15:01
A contact issue sounds sounds plausible. Before restart the contact state was showing as mutual contact on my side and after restarting @osmaczko is now showing as pending contact request - which doesn't really make sense either because it was only delivered after restarting.

**Comment by osmaczko** [comment] 2023-03-10 15:08
I think the contacts miss-synchronization happened to me in similar case:
1. Send a contact request to userA
2. Get the request accepted from userA
3. Restore the account
4. Send/receive message to/from userA

**Comment by jrainville** [comment] 2023-03-10 15:09
Cool, I'm glad we found the root cause. We then need to make it way clearer when people are not mutual.
Which version were you guys on?

**Comment by osmaczko** [comment] 2023-03-10 15:13
> Cool, I'm glad we found the root cause. We then need to make it way clearer when people are not mutual. Which version were you guys on?

0.10.0

**Comment by glitchminer** [comment] 2023-03-10 15:31
Same, 0.10.0. 

Making it clearer that there will be an issue because of not currently being mutual contacts will help. Why the mutual contact state somehow reverted to pending may also need looked at, as to start the chat in the first place and have message history we were previously mutual contacts at some time.

**Comment by MishkaRogachev** [comment] 2023-03-13 07:26
@jrainville i suppose this happen durning latest contact request changes and affect old created accounts. Also mutual contact not recovered properly after account has been restored. So what should be fixed in the PR:
* Ensure that current contact requests mechanism works properly
* Mutual contacts recovery

or just
* Fix ability to receive messages from not mutual contacts (maybe with additional rules)

**Comment by jrainville** [comment] 2023-03-13 14:09
> Fix ability to receive messages from not mutual contacts (maybe with additional rules)

We used to have a mechanism to get the first 1-1 message from a user as a message in the activity center. Maybe it was removed from designs or maybe we just lost it? @John-44 do you know? IMO, it can still be useful in those cases where someone lost their mutual contacts without knowing. That way, they can receive an AC notification from contact X and realize that they are no longer a contact.

> Ensure that current contact requests mechanism works properly

Otherwise, I think "Ensure that current contact requests mechanism works properly" is still important to fix. Right now, it seems a little broken. If you lose your contacts, you can still chat with the person, but it should be blocked. I know we've had a couple of issues where the "blurb" with the hand image was showing inappropriately, but people could still write. It should be that we show that "blurb" and image + button to add contact when you are not mutual and also disable the input.
Let me see if I find the design for that.

> Mutual contacts recovery

As for "Mutual contacts recovery", that would obviously be a good solution, but it's not that simple. We already have some other efforts on this anyway, so don't bother with it.

**Comment by MishkaRogachev** [comment] 2023-03-14 13:32
Found an easier to reproduce:
1. Send a contact request to userA
2. Get the request accepted from userA
3. Remove userA from contacts
4. Send/receive message to/from userA
So first thing - we just need to disable or delete chat for non contacts 1-to-1

**Comment by anastasiyaig** [comment] 2023-03-14 13:34
@MishkaRogachev thanks for investigation! Indeed, there are 2 problems:

- chatting with non-contact
- losing mutual contact connection randomly (become Pending instead)

**Comment by John-44** [comment] 2023-03-14 13:37
> We used to have a mechanism to get the first 1-1 message from a user as a message in the activity center. Maybe it was removed from designs or maybe we just lost it? @John-44 do you know?

@jrainville no it hasn't been removed from the designs, it's still there.  See the designs below (from the Kuba figma) for how incoming contact requests (including the message that arrives with the contact request) should be displayed in the notification centre: 

![2023-03-14 13_35_30-Kuba⎜Desktop – Figma](https://user-images.githubusercontent.com/22846356/225018181-4b65f908-9fab-4652-b4b3-c63061993c3a.png)

**Comment by John-44** [comment] 2023-03-14 13:39
Yes, other than the initial message that arrives with a contact request, it should not be possible to 1on1 message with somebody who is not a contacts request.

**Comment by MishkaRogachev** [comment] 2023-03-15 06:05
> @MishkaRogachev thanks for investigation! Indeed, there are 2 problems:
> 
> * chatting with non-contact
> * losing mutual contact connection randomly (become Pending instead)

Created separated issue for the first problem: https://github.com/status-im/status-desktop/issues/9899

**Comment by jrainville** [comment] 2023-04-13 13:58
Closing this issue as the second problem was fixed here https://github.com/status-im/status-desktop/issues/9899
and the first problem is gonna be resolved in https://github.com/status-im/status-desktop/issues/9899

**Closed by jrainville** 2023-04-13 13:58 UTC
Labels: bug, Chat, priority 1: high, E:Bugfixes

**Comment by glitchminer** [comment] 2023-04-13 14:23
@jrainville , just checking, both problems are resolved by the same issue?

**Comment by jrainville** [comment] 2023-04-13 19:29
Sorry, I messed up. I checked with @MishkaRogachev and the second issue is actually by design. I can't seem to find the issue tracking that, but it is planned to make it clearer that contacts come back as pending when recovering.
