### ISSUE TITLE
messenger: sometimes history is not fetched

### ISSUE THREAD

**Issue by caybro** [status-im/status-desktop#9361] opened 2023-01-30 15:37 UTC
# Bug Report

Sometimes, right after startup, only very recent message(s) is displayed but history is empty. On another start, history is back to normal

Empty history:
![Snímek obrazovky z 2023-01-30 16-31-30](https://user-images.githubusercontent.com/5377645/215521800-fcd2102c-7ae5-45d6-86bc-7b615455a8db.png)

Correct history:
![Snímek obrazovky z 2023-01-30 16-34-37](https://user-images.githubusercontent.com/5377645/215521809-bb0d92e0-8573-4469-80df-4fc9c4e864e0.png)

### Additional Information

- Status desktop version: master
- Operating System: linux

**Comment by 0x-r4bbit** [comment] 2023-01-31 10:23
@caybro I'm having trouble reproducing this. Anything in particular that needs to be done other than restarting the app and hoping that the history doesn't show up?

For me it always shows up. Tested this with community channels and group chats

**Comment by caybro** [comment] 2023-01-31 12:39
> @caybro I'm having trouble reproducing this. Anything in particular that needs to be done other than restarting the app and hoping that the history doesn't show up?
> 
> For me it always shows up. Tested this with community channels and group chats

Hmm no, nothing in particular to reproduce this :/

**Comment by richard-ramos** [comment] 2023-01-31 12:49
In the logs for desktop do you see logs like these?
```
INF 2023-01-31 08:30:15.187-04:00 active mailserver changed                  topics="mailservers-service" tid=1784795 file=service.nim:163 node=/dns4/node-01.gc-us-central1-a.status.prod.statusim.net/tcp/30303/p2p/16Uiu2HAkwBp8T6G77kQXSNMnxgaMky1JeyML5yqoTHRM8dbeCBNb
INF 2023-01-31 08:30:15.193-04:00 mailserver available                       topics="mailservers-service" tid=1784795 file=service.nim:168
MAILSERVER AVAILABLE: ref 0x7fef397650d8 --> []

INF 2023-01-31 08:30:15.194-04:00 history request started                    topics="mailservers-service" tid=1784795 file=service.nim:178 numBatches=4
```
and/or `history request completed`, `history request failed`, `history request success` ?

**Comment by caybro** [comment] 2023-01-31 13:19
> In the logs for desktop do you see logs like these?
> 
> ```
> INF 2023-01-31 08:30:15.187-04:00 active mailserver changed                  topics="mailservers-service" tid=1784795 file=service.nim:163 node=/dns4/node-01.gc-us-central1-a.status.prod.statusim.net/tcp/30303/p2p/16Uiu2HAkwBp8T6G77kQXSNMnxgaMky1JeyML5yqoTHRM8dbeCBNb
> INF 2023-01-31 08:30:15.193-04:00 mailserver available                       topics="mailservers-service" tid=1784795 file=service.nim:168
> MAILSERVER AVAILABLE: ref 0x7fef397650d8 --> []
> 
> INF 2023-01-31 08:30:15.194-04:00 history request started                    topics="mailservers-service" tid=1784795 file=service.nim:178 numBatches=4
> ```
> 
> and/or `history request completed`, `history request failed`, `history request success` ?

@richard-ramos yup (some of the logs might be unrelated but pasting it entirely):
```
INF 2023-01-31 14:16:47.034+01:00 history request started                    topics="mailservers-service" tid=57741 file=service.nim:178 numBatches=4
2023-01-31T14:16:47.834+0100	WARN	net/identify	identify/peer_loop.go:93	failed to send Identify Push	{"peer": "16Uiu2HAmDXqkk5jopVd1Gbx2ZkRn5BN52C6xKzQfKvA3J5SiBeLr", "error": "failed to open push stream: transient connection to peer"}
2023-01-31T14:16:47.834+0100	WARN	net/identify	identify/peer_loop.go:93	failed to send Identify Push	{"peer": "16Uiu2HAmS7c6cenFkN47aZMadL8Y1XcwGn5ohELR7AjDtcUj1Avn", "error": "failed to open push stream: transient connection to peer"}
2023-01-31T14:16:50.208+0100	INFO	net/identify	identify/id.go:369	failed negotiate identify protocol with peer	{"peer": "16Uiu2HAm6NozKZJwkC2kC9G23fe5fbfkMBHUoCQJxLJU6hD8YLcz", "error": "stream reset"}
2023-01-31T14:16:50.208+0100	INFO	net/identify	identify/id.go:369	failed negotiate identify protocol with peer	{"peer": "16Uiu2HAm6NozKZJwkC2kC9G23fe5fbfkMBHUoCQJxLJU6hD8YLcz", "error": "stream reset"}
2023-01-31T14:16:50.208+0100	WARN	net/identify	identify/id.go:334	failed to identify 16Uiu2HAm6NozKZJwkC2kC9G23fe5fbfkMBHUoCQJxLJU6hD8YLcz: stream reset
2023-01-31T14:16:50.208+0100	WARN	net/identify	identify/id.go:334	failed to identify 16Uiu2HAm6NozKZJwkC2kC9G23fe5fbfkMBHUoCQJxLJU6hD8YLcz: stream reset
2023-01-31T14:16:50.208+0100	WARN	net/identify	identify/peer_loop.go:93	failed to send Identify Push	{"peer": "16Uiu2HAm6NozKZJwkC2kC9G23fe5fbfkMBHUoCQJxLJU6hD8YLcz", "error": "failed to open push stream: no usable connection to peer"}
INF 2023-01-31 14:16:50.211+01:00 history request failed                     topics="mailservers-service" tid=57741 file=service.nim:188 requestId=4fe9557b34e0b798864808da6f80fbec734f86846865d8a4b017abdd04ca842f peerId=16Uiu2HAmSve7tR5YZugpskMv2dmJAsMUKmfWYEKRXNUxRaTCnsXV errorMessage="stream reset"
INF 2023-01-31 14:16:50.225+01:00 mailserver not working                     topics="mailservers-service" tid=57741 file=service.nim:173
INF 2023-01-31 14:16:50.225+01:00 removing active mailserver                 topics="mailservers-service" tid=57741 file=service.nim:161
2023-01-31T14:16:50.327+0100	INFO	net/identify	identify/id.go:369	failed negotiate identify protocol with peer	{"peer": "16Uiu2HAm3VfcKjvavLTHCVaH3swJM4EW9y8sA11eaNN3TLHLVrKS", "error": "stream reset"}
2023-01-31T14:16:50.327+0100	INFO	net/identify	identify/id.go:369	failed negotiate identify protocol with peer	{"peer": "16Uiu2HAm3VfcKjvavLTHCVaH3swJM4EW9y8sA11eaNN3TLHLVrKS", "error": "stream reset"}
2023-01-31T14:16:50.327+0100	WARN	net/identify	identify/id.go:334	failed to identify 16Uiu2HAm3VfcKjvavLTHCVaH3swJM4EW9y8sA11eaNN3TLHLVrKS: stream reset
2023-01-31T14:16:50.327+0100	WARN	net/identify	identify/id.go:334	failed to identify 16Uiu2HAm3VfcKjvavLTHCVaH3swJM4EW9y8sA11eaNN3TLHLVrKS: stream reset
INF 2023-01-31 14:16:50.725+01:00 active mailserver changed                  topics="mailservers-service" tid=57741 file=service.nim:163 node=/dns4/node-01.do-ams3.status.prod.statusim.net/tcp/30303/p2p/16Uiu2HAm6HZZr7aToTvEBPpiys4UxajCTU97zj5v7RNR2gbniy1D
ACTIVE MAILSERVER CHANGED: ref 0x7fbdfd6f5968 --> [nodeAddress = 0x7fbd33afbba0"/dns4/node-01.do-ams3.status.prod.statusim.net/tcp/30303/p2p/16Uiu2HAm6HZZr7aToTvEBPpiys4UxajCTU97zj5v7RNR2gbniy1D"]
```

**Comment by richard-ramos** [comment] 2023-01-31 13:24
Would be interesting to see why this `stream reset` happened:
```
INF 2023-01-31 14:16:50.211+01:00 history request failed                     topics="mailservers-service" tid=57741 file=service.nim:188 requestId=4fe9557b34e0b798864808da6f80fbec734f86846865d8a4b017abdd04ca842f peerId=16Uiu2HAmSve7tR5YZugpskMv2dmJAsMUKmfWYEKRXNUxRaTCnsXV errorMessage="stream reset"
```

**Comment by richard-ramos** [comment] 2023-01-31 13:39
I could not find logs in kibana related to the history request `4fe9557b34e0b798864808da6f80fbec734f86846865d8a4b017abdd04ca842f` for the peer 
```
/dns4/node-02.do-ams3.status.prod.statusim.net/tcp/30303/p2p/16Uiu2HAmSve7tR5YZugpskMv2dmJAsMUKmfWYEKRXNUxRaTCnsXV" 
```

Interestingly enough there are a few `stream reset` in the logs you shared. Is your internet connection estable / are you using desktop behind a VPN or firewall?

**Comment by richard-ramos** [comment] 2023-01-31 13:41
cc: @LNSD for additional ideas to debug this in case the other stream resets are part of normal operation (i do get few of those too for peers i could not connect to)

**Comment by LNSD** [comment] 2023-01-31 13:50
If the query ID does not appear in the Kibana logs, then the nodes did not receive the query.

@richard-ramos check the moment the queries happened and cross-check with the Grafana dashboard to see any anomalous behaviour (CPU peak, connection errors peak, Waku Store queries peak, etc.). 

There are several reasons for a stream to reset (e.g., reaching the maximum concurrent connections limit).

**Comment by caybro** [comment] 2023-02-01 12:06
@0x-r4bbit I found a pattern here: this issue happens upon startup with the "new messages marker"; so if the channel in question has some new, only those will be displayed, and nothing else. Upon next startup, the history appears correctly as there are no new/missed messages

**Comment by caybro** [comment] 2023-02-01 12:33
To illustrate that, here's the only new message (a reply in fact) with its corresponding original message, and a few days gap in between:

![image](https://user-images.githubusercontent.com/5377645/216043490-33928c79-60be-478a-a20c-f934070e6659.png)

**Comment by anastasiyaig** [comment] 2023-02-09 13:26
I have just reproduced that. I had some messages in several groups. Then i restarted the app and all history is gone apart of 3-4 messages from today (the recent ones)

<img width="1541" alt="Screenshot 2023-02-09 at 16 05 55" src="https://user-images.githubusercontent.com/82375995/217820908-95029fd6-0fb0-4732-b2ac-1cc7096e3f84.png">

**Comment by jrainville** [comment] 2023-02-09 14:26
A couple of us are having it today 0.10 RC5 for me.

The scroll up not getting the old DB messages is the most annoying part

**Comment by jrainville** [comment] 2023-02-10 14:44
Assigning to @osmaczko since he could reproduce and he probably has a clue what could be causing it. Also, Pascal is gonna help with community permission

**Closed** 2023-02-14 15:01 UTC
Labels: bug, priority 1: high, messenger
