### ISSUE TITLE
adding a custom chain crashes desktop

### ISSUE THREAD

**Issue by richard-ramos** [status-im/status-desktop#4042] opened 2021-11-04 12:47 UTC
Steps to reproduce:
1. In Advanced settings, select Network.
2. Add custom network with the following values:  
- Endpoint: 'https://bsc-dataseed.binance.org/'  
- ChainId: 56
- Name: Binance Smart Chain
3. Select the new network
4. Login again. 

Desktop will crash with the following error:
```
/home/richard/status/status-desktop/src/app/utilsView/view.nim(78) getEnsRegisterAddress
/home/richard/status/status-desktop/vendor/status-lib/status/ens.nim(323) statusRegistrarAddress
/home/richard/status/status-desktop/vendor/status-lib/vendor/nim-web3/web3/conversions.nim(91) $
/home/richard/status/status-desktop/vendor/status-lib/vendor/nim-task-runner/vendor/nim-stew/stew/byteutils.nim(135) toHex
/home/richard/status/status-desktop/vendor/status-lib/vendor/nim-task-runner/vendor/nim-stew/stew/byteutils.nim(122) toHexAux
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
make: *** [Makefile:551: run-linux] Error 1
```

It seems it's trying to obtain information for Status ENS and since there's no contract for binance, it fails crashing the app

**Comment by anastasiyaig** [comment] 2021-11-12 06:58
this is a duplicate of https://github.com/status-im/status-desktop/issues/3963, closing

**Closed by anastasiyaig** 2021-11-12 06:58 UTC
Labels: bug
