### ISSUE TITLE
Members in the members list have an icon, that we are waiting for the member revealed adresses

### ISSUE THREAD

**Issue by mprakhov** [status-im/status-desktop#14999] opened 2024-05-31 13:12 UTC
# Bug Report

## Description

In the member's list (all members) the sandbox icon must be set only if ownership has been changed, users were kicked and the new owner is waiting for revealed addresses from the old members.
However, the sandbox icon is set to all members on newly created community

https://github.com/status-im/status-desktop/assets/117639195/b086ed80-8b49-4049-bb53-07e3016b9d62

## Steps to reproduce

1. Create the comunity
2. Add new member
3. Check members list

#### Expected behavior

Members do not have a sandbox icon

#### Actual behavior

Members have a sandbox icon

### Additional Information

- Status desktop version: latest master
- Operating System: macOS

**Comment by caybro** [comment] 2024-05-31 13:24
Duplicate of: https://github.com/status-im/status-desktop/issues/14994

**Closed by caybro** 2024-05-31 13:24 UTC
Labels: bug, backend-team
