### ISSUE TITLE
Can't edit my own message

### ISSUE THREAD

**Issue by osmaczko** [status-im/status-desktop#8164] opened 2022-11-08 12:24 UTC
# Bug Report

## Description

After the app restarted, I can't edit my own message. This happens probably only for messages edited before. May be related to #8163 

![image](https://user-images.githubusercontent.com/33099791/200562682-cdae15c7-0b07-474b-8e90-8cde0dad61d9.png)

**Comment by PascalPrecht** [comment] 2022-11-09 09:35
This seems to be a dupe of #7879 and will likely be fixed with https://github.com/status-im/status-desktop/pull/8168

**Comment by PascalPrecht** [comment] 2022-11-09 09:35
Unassigning myself

**Comment by borismelnik** [comment] 2022-11-11 12:49
Yes it fixed. It happens cos edit request was sent without contentType and contentType was changed to `UKNOWN`. By current logic, you can edit just text and emoji messages. I will close it.

**Closed by borismelnik** 2022-11-11 12:49 UTC
Labels: bug, Chat
