### ISSUE TITLE
[Join Permissions] Edit shared addresses popup doesn't pre-select already shared accounts

### ISSUE THREAD

**Issue by alexjba** [status-im/status-desktop#14289] opened 2024-04-04 11:47 UTC
# Bug Report

## Description

When opening the edit shared addresses popup there the addreses already shared with the community are not pre-selected.

<img width="694" alt="Screenshot 2024-04-04 at 14 32 58" src="https://github.com/status-im/status-desktop/assets/47811206/253fc2d1-a3cf-4747-a970-399a171c2eeb">

## Steps to reproduce

1. Join a community and share an account address
2. Right click on the community icon and select Edit Shared Addresses

#### Expected behavior
 The popup shows all wallet addresses and the already shared ones are pre-selected
#### Actual behavior
 The popup shows all wallet addresses and the already shared ones are NOT pre-selected
### Additional Information

- Status desktop version: https://github.com/status-im/status-desktop/commit/8d6454367
- Operating System: MacOs

**Comment by caybro** [comment] 2024-04-04 11:50
It's "alright" here, minus the channels:
![image](https://github.com/status-im/status-desktop/assets/5377645/addd5a29-64a4-46f0-a2cd-5a1587844361)

**Comment by caybro** [comment] 2024-04-16 12:57
@jrainville not sure this is actually for us or the `messenger-team`; feel free to close as I couldn't reproduce myself

**Comment by jrainville** [comment] 2024-04-16 13:41
I finally understood this bug yesterday.

Turns out the problem is with re-imported account where the community was re-imported automatically.

The previous saved addresses are saved in your own DB and they are not backed up, so when you re-import, you don't get them back.

To fix this, we should either backup our addresses (maybe in the community or something) or we ask a privileged member for our addresses back.

Either way, it would be for the messenger team indeed @caybro 

I'll switch it

**Comment by jrainville** [comment] 2024-06-11 18:52
I closed by mistake

**Comment by jrainville** [comment] 2024-06-18 14:31
Fixed here https://github.com/status-im/status-go/pull/5314

**Closed by jrainville** 2024-06-18 14:31 UTC
Labels: bug, backend-team, E:Desktop Community Shared Addresses Selection, Desktop Community Shared Addresses Selection
