### ISSUE TITLE
Touch ID popup showing up earlier than expected

### ISSUE THREAD

**Issue by borismelnik** [status-im/status-desktop#6240] opened 2022-06-27 09:01 UTC
# Bug Report

## Description

When app is launched Touch ID popup showing earlier than app window. And if you use it nothing happens.

## Steps to reproduce

1. Run app 

#### Expected behavior

Touch ID should be pop up when password field is shown on window 

#### Actual behavior

Touch ID pop up before window is showing up

### Additional Information

- Status desktop version: `master`
- Operating System:  macOS 12.2

**Comment by iurimatias** [comment] 2023-04-24 20:10
closing as a sort of duplicate of https://github.com/status-im/status-desktop/issues/7726

**Closed by iurimatias** 2023-04-24 20:10 UTC
