### ISSUE TITLE
[StatusChatInput] If a username that contains an ”_” is entered into the message input field, all text after it becomes italic

### ISSUE THREAD

**Issue by imagiMary** [status-im/status-desktop#9698] opened 2023-03-01 15:20 UTC
Version: 0.9
OS: Windows 10

If a username that contains an underscore character (”_”) is entered into the message input field, all text after it becomes italic.  This is because underscore is a markdown character.  

 e.g. @Pepper_Talent renders the text succeeding the”_” in the message input field as italic, including the rest of the username, and this is incorrect.

***

<ins>Steps to reproduce:</ins>

1. Navigate to any messaging or community channel screen that contains a message input field.

2. Type a message in the message input field @ mentioning a user with a username that contains an underscore’ e.g. ‘@Mary_’ or ‘@Pepper_Talent’. 

<ins>What currently incorrectly happens:</ins>

3. In the message input field, the text following the username that contains an underscore will be rendered in italics.
_Note:_ The markdown character is not rendered in the message body area once the message is posted, **this is correct**. 

Example screenshots:

![32 Special charactors should not be rendered](https://user-images.githubusercontent.com/124154641/222181197-06235313-9d08-408a-96bd-58b004d57e9f.png)

&nbsp;
![32 Special charactors should not be rendered 2](https://user-images.githubusercontent.com/124154641/222181229-5e173e68-218b-421e-aa50-0c6c0fa332c0.png)

&nbsp;
<ins>What is supposed to happen:</ins>

3. Markdown characters in usernames should be ignored. The text in the message input field should not be altered if a username that contains a markdown character is entered.

<ins>Other information</ins>
This is specific to underscores as the only other markdown character that is allowed in usernames (a hyphen) is correctly ignored when a username that contains a hyphen is entered.

**Comment by jrainville** [comment] 2023-03-01 15:22
Duplicate of https://github.com/status-im/status-desktop/issues/8475, but this new ticket contains more info, so I'll close the old one instead.

**Comment by alexandraB99** [comment] 2023-04-03 14:43
@John-44 @imagiMary, these are already known issues, and more or less already reported (eg https://github.com/status-im/status-desktop/issues/7091). We have got [design specs](https://www.figma.com/file/Mr3rqxxgKJ2zMQ06UAKiWL/%F0%9F%92%AC-Chat%E2%8E%9CDesktop?node-id=21104-500080) for how formatting should behave 
and will be implemented [here](https://github.com/status-im/status-desktop/issues/8464).  However this requires a bigger effort and testing and as it's going to most probably break things we decided to leave it for after MVP. That said, do you think it's such a high prio so that it's refactored/fixed in 0.12? (same applies for https://github.com/status-im/status-desktop/issues/9700

**Comment by John-44** [comment] 2023-04-03 14:49
> @John-44 @imagiMary, these are already known issues, and more or less already reported (eg #7091). We have got [design specs](https://www.figma.com/file/Mr3rqxxgKJ2zMQ06UAKiWL/%F0%9F%92%AC-Chat%E2%8E%9CDesktop?node-id=21104-500080) for how formatting should behave and will be implemented [here](https://github.com/status-im/status-desktop/issues/8464). However this requires a bigger effort and testing and as it's going to most probably break things we decided to leave it for after MVP. That said, do you think it's such a high prio so that it's refactored/fixed in 0.12? (same applies for #9700)

We could bump it to 0.13 perhaps?  I'll bump to 0.13 for now and then we can discuss on a call later this week

**Comment by alexandraB99** [comment] 2023-04-05 16:05
@John-44 shall we move https://github.com/status-im/status-desktop/issues/9700 also to 0.13 then?

**Comment by John-44** [comment] 2023-04-05 18:38
> @John-44 shall we move #9700 also to 0.13 then?

@alexandraB99 yes good point.  I've just moved #9700 to 0.13

**Comment by caybro** [comment] 2023-09-08 12:21
This is more of a refactor task with a minor impact; but quite a big one effort-wise. Pls reconsider moving this to "later"

**Comment by iurimatias** [comment] 2024-08-13 12:27
closing as this will be part of a wider rethink of this feature

**Closed by iurimatias** 2024-08-13 12:27 UTC
Labels: bug, ui-team, refactor, Design-QA, Desktop ChatInput Markdown/Refactor, E:D Msg Bugfixes MX
