### ISSUE TITLE
Pinned messages shows uncorrect number of messages 

### ISSUE THREAD

**Issue by guylouis** [status-im/status-desktop#3566] opened 2021-09-15 12:57 UTC
In communities, with 0.3.0-beta, after restart (signout/signin) the wrong number of pinned messages is shown. Moreover this number evolves if scrolling the community, number can still be bad after scrolling though. Moreover this number can be more than the limit 3 pinned messages. 

This is reproductible 100% of the times.

Exemple:
- yesterday I created 4 messages m1-m2-m3-m4 then I pinned m1-m2-m3, and then pinned m4
- this morning after restart of status desktop, the indicator shows 1 pinned message only (which seems empty when clicking on the pin). If I scroll, then 4 pinned messages are shown and one is empty

https://user-images.githubusercontent.com/11461437/133437258-27c8f756-3214-46c9-b053-515fa63e51c7.mov

**Comment by iurimatias** [comment] 2021-09-20 19:56
duplicate of #3024

**Closed by iurimatias** 2021-09-20 19:56 UTC
Labels: bug, Communities
