### ISSUE TITLE
Failed to migrate after updating to 0.13

### ISSUE THREAD

**Issue by igor-sirotin** [status-im/status-desktop#11132] opened 2023-06-19 10:09 UTC
# Bug Report

## Description

So my attempt to update to 0.13-rc2 didn't go quite well 🙁 

1. I couldn't login with TouchID: `Couldn't retrieve private key from keystore. The specified item could not be found in the keychain.`
2. After logging manually with password re-encryption started and failed with Login failed: `FAILED TO MIGRATE TO VERSION 1686048341: CHECK CONSTRAINT FAILED: LENGTH(TRIM(KEY_UID)) > 0 IN LINE O`

Not sure if these is on issue.

<img width="1518" alt="Screenshot 2023-06-19 at 12 43 58" src="https://github.com/status-im/status-desktop/assets/25482501/fa334058-94f3-4ad8-ab46-ac88a28ec6bf">

<img width="1562" alt="Screenshot 2023-06-19 at 12 52 10" src="https://github.com/status-im/status-desktop/assets/25482501/fd58b1f6-6da5-4b7a-906f-3582a70cca1e">

________

- Status desktop version: 0.13.0-rc (downloaded from [GitHub releases](https://github.com/status-im/status-desktop/releases/tag/untagged-2e2e1217d2853d4221e7))
- Operating System: MacOS 13.4
- Full log: [app_20230619_124337.log](https://github.com/status-im/status-desktop/files/11786920/app_20230619_124337.log)

**Comment by igor-sirotin** [comment] 2023-06-19 10:10
The migration seems to be added here: https://github.com/status-im/status-go/pull/3540/files

cc @stefandunca

**Comment by igor-sirotin** [comment] 2023-06-19 11:16
We should add a scrollview to that error, that looks not beautiful 😄

**Comment by stefandunca** [comment] 2023-06-19 12:42
> The migration seems to be added here: https://github.com/status-im/status-go/pull/3540/files
> 
> cc @stefandunca
That migration is a custom GO migration, the accompanied SQL migration you mentioned is no-op and used as a marker. The error shows that one of the SQL migrations leading to that custom migration failed.

Judjing by the error it might be this one that failed: https://github.com/status-im/status-go/blob/0fcf3abd83fc4da4a072766ad953602624651e72/appdatabase/migrations/sql/1683627613_accounts_and_keycards_improvements.up.sql#LL8C6-L8C6

**Comment by dlipicar** [comment] 2023-06-19 14:01
Here's the contents of my `accounts` table
```
address	wallet	chat	type	storage	pubkey	path	name	color	created_at	updated_at	hidden	emoji	derived_from	clock	key_uid	keypair_name	last_used_derivation_index
	1	0				m/44'/60'/0'/0/0	Status account	#4360df	2022-12-01 11:43:41	2022-12-01 11:43:41	0	<img class="emoji" draggable="false" alt="🔑" src="qrc:/StatusQ/src/assets/twemoji/svg/1f511.svg?72x72" width="16" height="16" style="vertical-align: top"/> 	0xc354Ba7924b3d4ee98fab5A28e34AcB7aDe83aA1	0	0xa3c624c4241da85b2c4ea9ad68eac36e70f9f62074948ae917fe408b1fdd3e11	Dario	0
	0	0	generated		0x0434e08ac97980ea69127dfc4e50e78db23c7d7b8865d19bb149b3c325577e142b62b6b2c2311fab72d09105c901da2f0f272cdac4c15c3ac6e918a7194398f0fc	m/44'/60'/0'/0/1	Test	#2946C4	2022-12-01 11:54:17	2022-12-01 11:54:17	0			1669895654396		Dario	1
	0	1				m/43'/60'/1581'/0'/0	Dario		2022-12-01 11:43:41	2022-12-01 11:43:41	0			0	0xa3c624c4241da85b2c4ea9ad68eac36e70f9f62074948ae917fe408b1fdd3e11		0
```

**Comment by igor-sirotin** [comment] 2023-06-19 14:06
@stefandunca Yes, I did. Tried several times 😄 
But double-checking everything now.

**Comment by igor-sirotin** [comment] 2023-06-19 14:20
## DBBrowser
<img width="433" alt="image" src="https://github.com/status-im/status-desktop/assets/25482501/b0334ac0-4796-4e91-b465-f61d01ff439e">

## CLI `sqlcipher`

```bash

➜  data sqlcipher accounts.sql
SQLite version 3.41.2 2023-03-22 11:56:21 (SQLCipher 4.5.4 community)
Enter ".help" for usage hints.
sqlite> SELECT name, keyUid FROM accounts;
sirotin-1|0x1783df06f1030e3681f6fd109545ab17d247d5431022869bb8092a5a817f2912
sirotin-test-1|0x34994f72ba02d1a2054164d795949eb4ee2fce3bce8335eb3e1cf22c37259960
qwertyuiop|0x9955c719449eefe2ec1284928d01d84704a5d3cb41ffc0cfdb43db9207ecfa4e
sirotin|0xd73baeb6587b8d979f908ecf0caa4bfb314f4c2086fd078d7c9b4e73d1250f71
qwertyasdfgh|0xfe4fbeefcb8e85a2016e52034af15945e51282ab5c8605e41dc2055d760bc8a2
```

```bash
➜  data ls -l | grep 0xd73baeb6587b8d979f908ecf0caa4bfb314f4c2086fd078d7c9b4e73d1250f71
-rw-r--r--@  1 igorsirotin  staff  6344515584 Jun 19 12:47 0xd73baeb6587b8d979f908ecf0caa4bfb314f4c2086fd078d7c9b4e73d1250f71-v4.db
-rw-r--r--@  1 igorsirotin  staff       32768 Jun 19 17:15 0xd73baeb6587b8d979f908ecf0caa4bfb314f4c2086fd078d7c9b4e73d1250f71-v4.db-shm
-rw-r--r--@  1 igorsirotin  staff       73976 Jun 19 12:47 0xd73baeb6587b8d979f908ecf0caa4bfb314f4c2086fd078d7c9b4e73d1250f71-v4.db-wal
```

```bash
➜  data sqlcipher 0xd73baeb6587b8d979f908ecf0caa4bfb314f4c2086fd078d7c9b4e73d1250f71-v4.db
SQLite version 3.41.2 2023-03-22 11:56:21 (SQLCipher 4.5.4 community)
Enter ".help" for usage hints.
sqlite> PRAGMA key = "<my-password-hash-here>";
ok
sqlite> PRAGMA cipher_page_size = 8192;
sqlite> PRAGMA kdf_iter = 256000;
sqlite> PRAGMA cipher_hmac_algorithm = HMAC_SHA1;
sqlite> PRAGMA cipher_kdf_algorithm = PBKDF2_HMAC_SHA1;
sqlite> 
sqlite> .tables
Error: file is not a database
sqlite> 

```

**Comment by alexjba** [comment] 2023-06-19 14:58
>  ```shell
> ➜  data ls -l | grep 0xd73baeb6587b8d979f908ecf0caa4bfb314f4c2086fd078d7c9b4e73d1250f71
> -rw-r--r--@  1 igorsirotin  staff  6344515584 Jun 19 12:47 0xd73baeb6587b8d979f908ecf0caa4bfb314f4c2086fd078d7c9b4e73d1250f71-v4.db
> -rw-r--r--@  1 igorsirotin  staff       32768 Jun 19 17:15 0xd73baeb6587b8d979f908ecf0caa4bfb314f4c2086fd078d7c9b4e73d1250f71-v4.db-shm
> -rw-r--r--@  1 igorsirotin  staff       73976 Jun 19 12:47 0xd73baeb6587b8d979f908ecf0caa4bfb314f4c2086fd078d7c9b4e73d1250f71-v4.db-wal
> ```

The DB file looks good. I see the `wal` file there and it gives me hope 😄 . It means the DB was opened after migration and had some write operations.

**Comment by igor-sirotin** [comment] 2023-06-19 15:11
Checked that the password is correct by opening `0.12.0` version.
But I'm not able to open the backed up database with DBBrowser as well 🤔 

Though I was able to open it with CLI, it shows me an empty database.
```bash
sqlite> .tables
sqlite>
```

I see from instructions that I should build latest `sqlcipher` locally. This didn't work for me, I get a build error, so I am using the one from `brew`. That might be an issue with CLI, but I'm able to open other local database.

**Comment by igor-sirotin** [comment] 2023-06-19 15:37
I seem to have the latest version. Also succeeded to build it locally after all, version is the same.
```
SQLite version 3.41.2 2023-03-22 11:56:21 (SQLCipher 4.5.4 community)
```

Still not able to open the backed up database, but now I get `Error: file is not a database`.
```
➜  Application Support sqlcipher Status/data/0xd73baeb6587b8d979f908ecf0caa4bfb314f4c2086fd078d7c9b4e73d1250f71.db
SQLite version 3.41.2 2023-03-22 11:56:21 (SQLCipher 4.5.4 community)
Enter ".help" for usage hints.
sqlite> PRAGMA key = "0x041ae69448532a5d89533669b0125c0acec83f5db1722ee68d49f18a397427d2";
ok
sqlite> PRAGMA cipher_page_size = 1024;
sqlite> PRAGMA kdf_iter = 256000;
sqlite> PRAGMA cipher_hmac_algorithm = HMAC_SHA1;
sqlite> PRAGMA cipher_kdf_algorithm = PBKDF2_HMAC_SHA1;
sqlite> .tables
Error: file is not a database
sqlite> 
```

**Comment by stefandunca** [comment] 2023-06-19 15:55
I think it was corrupted for some reason. I can't think of any reason other than stopping the encryption process. However, @alexjba saw it was finished successfully.

**Comment by igor-sirotin** [comment] 2023-06-19 16:01
@stefandunca I am not able to open manually even the backup database that wasn't opened with `0.13-rc2`

**Comment by igor-sirotin** [comment] 2023-06-19 16:11
this might be related: https://github.com/status-im/status-go/pull/3559

**Comment by igor-sirotin** [comment] 2023-06-19 16:56
Opening database with `PRAGMA cipher_compatibility = 3;` doesn't help.

**Comment by stefandunca** [comment] 2023-06-20 11:10
> @stefandunca I am not able to open manually even the backup database that wasn't processed by `0.13-rc2`. So I suppose that I can't open the "processed by `0.13`" for the same reason and it might be still be not corrupted.

Sounds strange. If not corrupted, may it be that the password changed in the encryption process than the one you expect? I know there was a password change some time ago (changed case) but can't imagine how that would affect the current migration.

**Comment by igor-sirotin** [comment] 2023-06-20 14:24
sooo, we have some updates 🙂 

## News

1. I succeeded to open my database.
The problem was that I expected `kdfIterations` to be `256000`, but the accounts database shows that it's `3200`.

2. The processed by `0.13` database is not corrupted.
It opens fine, but shows that the migration failed.
```SQL
SELECT * FROM status_go_schema_migrations
[(1683627613, 'true')]
```

## Action items

1. From this it seems that the migrations failed because it was using `kdfIterations = 256000` instead of the right value, just like I did.
    * @dlipicar Could you please check your database (that failed to migrate) `kdfIterations` value?
    * We also agreed with @alexjba that he will test this.

2. Why is my database still on `kdfIterations = 3200`? 🤔 
Should we have migrated after https://github.com/status-im/status-desktop/pull/6997?
@jrainville probably you know overall picture?

**Comment by jrainville** [comment] 2023-06-20 16:07
> Why is my database still on kdfIterations = 3200? thinking
Should we have migrated after https://github.com/status-im/status-desktop/pull/6997?
@jrainville probably you know overall picture?

Hmm, I guess it should have migrated, though I'm not sure what could have prevented it. @richard-ramos do you have an idea?

**Comment by alexjba** [comment] 2023-06-21 07:39
>From this it seems that the migrations failed because it was using kdfIterations = 256000 instead of the right value, just like I did.

DB re-encryption works fine with `kdfIterations = 3200`. Had no issues migrating a large DB configured with 3200 KDF iter.

Fixing the migration script mentioned here https://github.com/status-im/status-desktop/issues/11132#issuecomment-1597120900 should be enough to close this issue.

**Comment by stefandunca** [comment] 2023-06-21 10:16
> 1. From this it seems that the migrations failed because it was using `kdfIterations = 256000` instead of the right value, just like I did.

Not sure what you mean here. From your description sounds to me like you had a failure migrating the accounts table because of the missing `key_uuid` like @dlipicar also had.

@igor-sirotin this migration failure is just a side effect for the broken accounts table. looking now into what could lead to this initial outcome.

Could you please look at the `accounts` table and confirm the missing key_uuid. Could you share more about your account entries (are they all as you expected)?

>    * @dlipicar Could you please check your database (that failed to migrate) `kdfIterations` value?

I had some debugging sessions with @dlipicar but AFAIK he didn't get into the KDF iteration issue. He had the same authenticate failure and then the expected migration failure due to a missing key_uuid entry for one of the accounts (as he posted above)

> 2. Why is my database still on `kdfIterations = 3200`? 🤔

@alexjba when do we change the KDF iterations? after migrating to a higher value? Might it be that we update the KDF only if we migrate successfully or after we encrypt the DB?

**Comment by alexjba** [comment] 2023-06-21 11:10
> @alexjba when do we change the KDF iterations? after migrating to a higher value? Might it be that we update the KDF only if we migrate successfully or after we encrypt the DB?

All I could find so far is that it's configurable when creating the DB, but no migration process for existing DB.

> I had some debugging sessions with @dlipicar but AFAIK he didn't get into the KDF iteration issue. He had the same authenticate failure and then the expected migration failure due to a missing key_uuid entry for one of the accounts (as he posted above)

Not sure yet the KDF iter number has anything to do with the migration failure. @dlipicar would be interesting to find if your account is also configured to `kdfIterations = 3200`.

One thing's for sure, would be great to reproduce it. @igor-sirotin @dlipicar Can you also reproduce it on test accounts you're comfortable sharing?

**Comment by stefandunca** [comment] 2023-06-21 12:39
For some reason, the accounts that failed the migration have invalid data for the new structure and violate this requirement https://github.com/status-im/status-go/blob/eeaaf0ce3f1faf83471b8bc5756ad169a42b2a0b/appdatabase/migrations/sql/1683627613_accounts_and_keycards_improvements.up.sql#L40

At first glance, there are old accounts with empty or `generated` types and empty `key_uid`. Looking now at how to fix this without dropping these accounts.

**Comment by igor-sirotin** [comment] 2023-06-21 12:52
@stefandunca 

I have just basic accounts there. `key_uid` is empty for both of them.

`accounts` before migration:
<img width="1633" alt="image" src="https://github.com/status-im/status-desktop/assets/25482501/6ab95cb5-4bef-4caa-958e-3f8c695a385b">

`accounts` after migration attempt:

<img width="1581" alt="image" src="https://github.com/status-im/status-desktop/assets/25482501/79fdd660-020f-4ecf-8b2c-34e841ea6481">

**Comment by stefandunca** [comment] 2023-06-21 13:05
> I have just basic accounts there. `key_uid` is empty for both of them.

Exactly this is the root cause.

> `accounts` before migration:
> ...
> `accounts` after migration attempt:

The migration doesn't affect the old `accounts` data; it will drop the table if run successfully.

The problem is that the new migration structure enforces some requirements that not all old accounts follow. Not good that some of them are main accounts.

**Comment by igor-sirotin** [comment] 2023-06-21 13:25
I talked to @richard-ramos, he said migration to `kdfIterations = 256000` was never done.

Probably it doesn't make sense to do as it's not that many users with `3200` left. I myself can migrate manually 😄 Or even keep things as is for future testing just in case. 

Though currently it might be not too hard to implement using https://github.com/status-im/status-go/pull/3607 work.
I'm not the one to decide, just wanted to summarise 🙂 

cc @alexjba @jrainville

**Comment by jrainville** [comment] 2023-06-21 13:29
@igor-sirotin is the fact that you are on `3200` causing issues or just makes it confusing when trying to debug the DB?

**Comment by jrainville** [comment] 2023-06-21 13:36
Ok, then let's ignore it for now. Maybe add a note in the Notion notes about inspecting the DB to say that the KDF might be `3200` if it's old.

**Comment by saledjenic** [comment] 2023-06-26 07:34
> Why is my database still on kdfIterations = 3200?

@igor-sirotin the account I'm using is also on  kdfIterations = 3200, looks like migration script to update it to 256000 was not executed.

> I talked to @richard-ramos, he said migration to kdfIterations = 256000 was never done.

Not sure why, cause creating new accounts whichever way will set kdfIterations to 256000, so I'm not sure why we didn't migrate that for old users.

Now let's discuss the empty `key_uid` issue, which is the main reason why some users couldn't migrate to 0.13.0.
When I was switching old `accounts` table to new `keypairs` and `keypairs_accounts` I deliberately set very strong constraints on `key_uid` (`key_uid VARCHAR PRIMARY KEY NOT NULL CHECK (length(trim(key_uid)) > 0)`) cause any keypair we cannot know/resolve key uid for is unusable according to new requirements. There was no way to generate key uid for such accounts during migration.

The affected accounts should be only those which are created before status-go version `0.108.4`, in other words very old accounts. For them there is no other way except to recovering. 

Thinking now, for the imported keypairs via seed phrase or private key we cannot do anything. For the profile keypair basically we cannot do anything as well, but we can check if the `key_uid` column is set in the `settings` table for those old accounts and simply try to set it to the profile keypair row to `keypairs` and `keypairs_accounts` table, that could be a way to save profile keypair only (but now sure if we have that `key_uid` column set in `settings` table for that old accounts, @igor-sirotin could you check?).

**Comment by iurimatias** [comment] 2023-06-26 13:44
We decided to close this as wont'fix, requires recovering account instead.

**Closed by iurimatias** 2023-06-26 13:44 UTC
Labels: bug, priority F0: urgent

**Comment by igor-sirotin** [comment] 2023-06-27 08:15
@saledjenic 
Just checked the `settings` table. I do have `key_uid` column there. It actually equals to the database file name.

**Comment by saledjenic** [comment] 2023-06-27 09:05
@igor-sirotin thanks, then the minor improvement we can do is to add a migration script which will copy it to the `key_uid` column of the profile keypair row in `keypairs` and `keypairs_accoutns` tables. That will save from recovering only those users who don't have any other keypair imported (via seed phrase or private key), in other case recovering is the only way to go (unless affected user is not the dev and can open the db and add key_uid manually 😉 ).

All in all, this topic is closed, cause very small number of users will be affected and not worth investing an effort, especially when we know that we're still in the development phase.

**Comment by igor-sirotin** [comment] 2023-06-27 09:06
I succeeded to migrate to 0.13. Before migrating:
* get you `key_uid` from `settings` table
* Execute SQL: `UPDATE accounts SET key_uid="<your-key-uid-here>";`

That's it, just run the `0.13` version after this.

**Comment by saledjenic** [comment] 2023-06-27 09:09
Ahhh no, that works only if you don't have imported keypairs, only a profile keypair related accounts.

If it works for you, means you didn't have imported accounts.
