### ISSUE TITLE
Incorrect onboarding flow

### ISSUE THREAD

**Issue by saledjenic** [status-im/status-desktop#6789] opened 2022-08-03 08:05 UTC
If we follow the flow `first run - old user - Enter a seed phrase` that flows says that after entering seed phrase we should fetch from the waku all available data for that user, like display name, user photo, wallet addresses, settings... not sure what else is/will be available there, but in general that's what we should do (the similar should be done, fetching the data from waku for `first run - old user - Login with Keycard` flow, after correct pin is entered).

But instead of above described seems that from the start flow `first run - old user - Enter a seed phrase` was wrongly implemented cause it is exactly the same as `first run - new user - lmport a seed phrase - lmport a seed phrase`.

Corresponding figma:
https://www.figma.com/file/17fc13UBFvInrLgNUKJJg5/Kuba%E2%8E%9CDesktop?node-id=1042%3A303014

**Comment by iurimatias** [comment] 2022-08-03 17:19
duplicate of https://github.com/status-im/status-desktop/issues/5622

**Closed by iurimatias** 2022-08-03 17:19 UTC
Labels: bug, onboarding, E:Onboarding
