### ISSUE TITLE
user cannot join community after getting airdrop dropped

### ISSUE THREAD

**Issue by iurimatias** [status-im/status-desktop#13055] opened 2023-12-19 18:24 UTC
# Bug Report

**Version:** 0.15 RC 9, shards.test fleet

## Steps to reproduce

1. create a community
2. create a nft or token
3. set permissions to that only users with that token that was airdroped can become member
4. airdrop to someone
5. invite that user to the community

result: user cannot join the community

could be sharding related

**Comment by anastasiyaig** [comment] 2023-12-19 18:25
<img width="1717" alt="Screenshot 2023-12-19 at 18 48 04" src="https://github.com/status-im/status-desktop/assets/82375995/930ab3ec-5965-4d20-98d8-5cfc491628ad">

**Comment by MishkaRogachev** [comment] 2023-12-20 14:09
Tried to reproduce on the current master:
1. created a community
2. created a collectible

4. settled permissions to that only user with airdrop can become member
<img width="643" alt="Screenshot 2023-12-20 at 20 50 29" src="https://github.com/status-im/status-desktop/assets/2522130/61919c39-3a18-4a92-9908-067afa1616d3">

5. airdrop to someone
<img width="643" alt="Screenshot 2023-12-20 at 20 51 41" src="https://github.com/status-im/status-desktop/assets/2522130/2dcff8e1-b14c-4e2c-b61d-2de06a5370a2">

7. invited that user to the community
8. request to join (that user)
<img width="621" alt="Screenshot 2023-12-20 at 20 57 01" src="https://github.com/status-im/status-desktop/assets/2522130/acdc1b8c-6b3d-4452-a687-ae876899f66d">

10. accepted the request to join
<img width="621" alt="Screenshot 2023-12-20 at 20 58 55" src="https://github.com/status-im/status-desktop/assets/2522130/62415f83-af7d-4705-b96e-3794cb235d6d">

11. a user successfully joins the community

**Comment by anastasiyaig** [comment] 2023-12-20 14:12
right , this is what we saw in release branch along with shards.test, this was not mentioned in initial description

**Comment by osmaczko** [comment] 2024-01-04 22:13
Can't reproduce on latest master on shards.test:


https://github.com/status-im/status-desktop/assets/33099791/2c9e5fab-068d-4e58-9f1b-ee98e94473cb

**Comment by osmaczko** [comment] 2024-01-05 08:57
Did more testing, there is an issue indeed. It appears that we sent the initial request to join the community with an invalid address. **By canceling the request to join and then re-entering the addresses, the process seems to work correctly.** Investigating request to join flow now..


https://github.com/status-im/status-desktop/assets/33099791/3581a4a9-4ea4-4665-8e36-178d8ac5a02e

**Comment by osmaczko** [comment] 2024-01-05 09:34
The issue is that first request to join is not delivered to control node at all.

**Comment by osmaczko** [comment] 2024-01-05 12:50
The first request to join was not delivered because, for some reason, the receiver had a legacy version of the community description in which no owner token had been minted. Consequently, the request was sent to the wrong receiver, it was  community pubkey instead of the new owner's pubkey.

**Comment by osmaczko** [comment] 2024-01-05 12:54
> some reason, the receiver had a legacy version of the community description in which no owner token had been minted

This is most likely side effect of: https://github.com/status-im/status-go/pull/4341, as we no longer attach community description when we share a community.

**Comment by osmaczko** [comment] 2024-01-05 15:52
Will be mitigated by: https://github.com/status-im/status-go/pull/4533

**Comment by osmaczko** [comment] 2024-01-08 20:29
Fixed by https://github.com/status-im/status-go/pull/4533.

NOTE: Community links might be not clickable at first, because they resolve quite slowly due to the workaround of fetching data over an entire month. We have [decided](https://github.com/status-im/status-go/pull/4535#issuecomment-1881357456) **not** to include the optimization that would mitigate this issue.

@iurimatias please remember to cherry-pick it to 0.15.0 release branch :pray:

**Closed by osmaczko** 2024-01-08 20:29 UTC
Labels: bug, E:Desktop Community Admin Improvements, E:Community Sharding, status-waku-integ, sprint-01-02
