### ISSUE TITLE
Quitting the app during a burn causes crash and incorrect total on next launch

### ISSUE THREAD

**Issue by glitchminer** [status-im/status-desktop#11596] opened 2023-07-20 09:29 UTC
# Bug Report

## Description

Initiate a token burn (eg. 100 tokens)
Open etherscan
Quit immediately while burn is in progress (fire icon, spinner)
Next launch will crash
Launch after that starts but token total will not have updated (remaining is ok because it updates directly)

![image](https://github.com/status-im/status-desktop/assets/50769329/5a558d80-0878-460a-b432-f3d34af9470e)

#### Expected behavior

Total to be correct
App not to crash on launch

### Additional Information

- Status desktop version: https://github.com/status-im/status-desktop/pull/11393
- Operating System: Mac

**Comment by stefandunca** [comment] 2024-04-12 08:01
After investigating the issue my current understanding is that we cache the total supply in `community_tokens` table and it is interrupted by the legacy `watch` pending transaction. This should be fixed with @endulab's current work to migrate to the async and sql transaction process the pending.
However, I still see the possibility to externally burn that I'm not sure we take into account. We should regularly update the token total supply by calling the contract's `maxSupply`.
@endulab let's sync how can we efficiently do this.

I can't reproduce the crash though.

**Comment by stefandunca** [comment] 2024-04-12 09:00
I just had a discussion with @endulab and he confirmed that his work of making the reporting process robust will fix this side effect of updating the total supply. The fix will be tackled by this work: https://github.com/status-im/status-go/issues/4351

**Comment by stefandunca** [comment] 2024-04-12 09:42
Duplicate of [#4351(https://github.com/status-im/status-go/issues/4351)

**Closed by stefandunca** 2024-04-12 09:42 UTC
Labels: bug, wallet-team, E:Desktop Bugfixes 2.27.0
