### ISSUE TITLE
[CommunityPortal] Search by tags 

### ISSUE THREAD

**Issue by alexandraB99** [status-im/status-desktop#7300] opened 2022-09-09 16:47 UTC
### Description
- Implement  search by tags (implement designs for tags in community delegate)
- Implement designs for no tags selected, tags are currently unresponsive, implement hover, selected/unselected states

**Comment by micieslak** [comment] 2022-10-20 12:02
Duplicate of https://github.com/status-im/status-desktop/pull/7929, nothing to do :)

**Closed by micieslak** 2022-10-20 12:02 UTC
Labels: ui
