### ISSUE TITLE
transfering balance between accounts does not immediately update in the UI

### ISSUE THREAD

**Issue by iurimatias** [status-im/status-desktop#2260] opened 2021-04-15 21:53 UTC
steps

1. add a test account with balance in it (e.g use account in ganache)
2. transfer from one account to the other (press send, select accounts, etc..)

result: balance of to account remains at 0, after restarting the app the balance is updated
expected: it should update the balance in the accounts when possible

**Comment by saledjenic** [comment] 2021-07-07 12:57
I cannot reproduce this. Sending eth, using ropsten network, from one to another account updates balance on that another account appropriately. That's not an immediate action, need some time, in this moment around 30-40 seconds, but it gets updated. I am moving this to QA column so it may be tested again.

**Closed** 2021-08-19 15:22 UTC
Labels: Wallet
