### ISSUE TITLE
Corrupted and invalid UI for closed communityfor Token Master token holder in spectate mode 

### ISSUE THREAD

**Issue by mprakhov** [status-im/status-desktop#14113] opened 2024-03-22 09:40 UTC
# Bug Report

## Description

I have a closed community minted token master token and member permissions. When the client, who has a token master token opens the community in spectate mode to join it - the wrong UI

## Steps to reproduce

1. Owner - create the community, mint owner token, add member permission, and send token master token to the User
2. The user does not fit member permission, but he has a token master token
3. Owner sends an invite to the User
4. User goes to community spectate mode (opens invite)

#### Expected behavior

There should not be any messages that I don't have permission to view and post in channels as I have a TokenMaster token and there is no private channels

#### Actual behavior

https://github.com/status-im/status-desktop/assets/117639195/604f7470-f8bc-4f91-8887-b53cb971a5df

### Additional Information

- Status desktop version: branch 2.28.xx
- Operating System: macos

**Comment by jrainville** [comment] 2024-03-22 16:58
Closing as duplicate of https://github.com/status-im/status-desktop/issues/14085

**Closed by jrainville** 2024-03-22 16:58 UTC
Labels: bug, ui-team
