### ISSUE TITLE
Quitting application by right clicking on dock result in crash

### ISSUE THREAD

**Issue by glitchminer** [status-im/status-desktop#10642] opened 2023-05-11 12:22 UTC
# Bug Report

## Description

The application is crashing when quitting. This was found via the dock right click menu on Mac

![image](https://github.com/status-im/status-desktop/assets/50769329/b615935f-0fde-4c3c-9196-447d0c4fa56d)

![image](https://github.com/status-im/status-desktop/assets/50769329/4501b42f-ab7d-4d0a-91fb-914cd4c03b20)

- Status desktop version: 0.12.0 RC1
- Operating System: Mac

**Comment by jrainville** [comment] 2023-05-11 14:13
Duplicate of https://github.com/status-im/status-desktop/issues/10464

**Closed by jrainville** 2023-05-11 14:13 UTC
Labels: bug, messenger-team
