### ISSUE TITLE
Create community text input does not have left padding

### ISSUE THREAD

**Issue by mprakhov** [status-im/status-desktop#8898] opened 2022-12-27 12:04 UTC
# Bug Report

## Description

Create community text input does not have left padding

## Steps to reproduce

1. Go to the community
2. Click Create New Community

#### Expected behavior

Input have a left padding

#### Actual behavior

Input does not have a left padding
![Screenshot 2022-12-27 at 13 44 25](https://user-images.githubusercontent.com/117639195/209663832-baae9052-272c-4c20-ae0b-c8ed5c9a883c.jpg)

### Additional Information

This is regression. On v. 0.8.1 everything is ok

- Status desktop version: master branch commit d59cffd623e536d928ce8305100fc1ff956528d0
- Operating System: macos

**Comment by caybro** [comment] 2023-01-03 16:28
Same for the Edit community page:
![image](https://user-images.githubusercontent.com/5377645/210398894-027097e0-2138-428c-8bd8-eaa24b988385.png)

**Comment by alexandraB99** [comment] 2023-01-10 11:00
@mprakhov cannot reproduce on current master, could you please check?

**Comment by mprakhov** [comment] 2023-01-10 11:03
I think @caybro fixed it already

**Comment by caybro** [comment] 2023-01-10 11:11
Yeah, fixed with https://github.com/status-im/status-desktop/pull/8968

**Comment by caybro** [comment] 2023-01-10 11:11
@iurimatias @jrainville should be backported to 0.9 branch

**Closed by caybro** 2023-01-10 11:11 UTC
Labels: bug, ui, Communities, pixel-perfect-issues
