### ISSUE TITLE
Onboarding: Counts of fetched data does not match the account

### ISSUE THREAD

**Issue by glitchminer** [status-im/status-desktop#10358] opened 2023-04-18 22:50 UTC
# Bug Report

## Description

After restoring from seed phrase the user is presented with a count of how many items have been synced. The following counts were wrong:

- 10 contacts were shown but the account had 18
- 24 communities are shown but the account only has 13 active

![image](https://user-images.githubusercontent.com/50769329/232920869-b30cd463-f1cc-495d-86f3-bb50b359cbc2.png)

## Steps to reproduce

Take note of how many contacts and communities are expected to be fetched during a restore
With a fresh install, restore the account from seed phrase and check the counts of data shown to be fetched

#### Expected behavior

Counts of contacts and communities before a restore match those after a restore.

#### Actual behavior

Counts do not match

### Additional Information

- Status desktop version: https://ci.status.im/job/status-desktop/job/branches/job/macos/job/aarch64/job/package/job/PR-10292/3/ (found during #10292 )
- Operating System: Mac

------

# Update

After the discussion below, we should be using % instead of numbers, so this task is to update this dialogue.

**Comment by alexandraB99** [comment] 2023-11-20 13:48
@glitchminer cannot reproduce this one, could you please double check and close if not?

**Comment by glitchminer** [comment] 2023-11-22 20:47
Hi @alexandraB99 , I was able to reproduce this.

| item                                   | fetched count | shown after login|
| --- | --- | --- |
| contacts                            | 7                      | 5                           |
| community memberships| 14                     |9                           |

I think it may be related to this bug on retrieving data from waku in general https://github.com/status-im/status-desktop/issues/12797

**Comment by alexjba** [comment] 2023-12-06 15:41
I can reproduce this and there are 2 aspects to clarify:

1. The number of contacts we see in the profile fetching view is not the number of mutual contacts that's being fetched. It's the number of backup messages we expect to process, each one containing max. 20 contacts.

2. The number of communities in the profile fetching view represents the active communities + deleted communities.

@glitchminer In your case the app probably fetched ~7*20 contacts, 9 active communities, 5 deleted communities.

@benjthayer Is the current behaviour the expected one? Same as @glitchminer, I was expecting to see a parity between the numbers presented in the profile fetching view and the data presented in the app after the sync was finished.

**Comment by benjthayer** [comment] 2023-12-06 16:13
> I can reproduce this and there are 2 aspects to clarify:
> 
> 1. The number of contacts we see in the profile fetching view is not the number of mutual contacts that's being fetched. It's the number of backup messages we expect to process, each one containing max. 20 contacts.
> 2. The number of communities in the profile fetching view represents the active communities + deleted communities.
> 
> @glitchminer In your case the app probably fetched ~7*20 contacts, 9 active communities, 5 deleted communities.
> 
> @benjthayer Is the current behaviour the expected one? Same as @glitchminer, I was expecting to see a parity between the numbers presented in the profile fetching view and the data presented in the app after the sync was finished.

I would also expect for the profile fetching view to tally with the numbers inside the app. If the numbers the user sees in the fetch flow are less, the user will think there has been an issue with the fetching of data. Similarly if the numbers are more - they may think the fetch is inaccurate or reflective of a less recent point in time.

**Comment by alexjba** [comment] 2023-12-07 08:32
> > I can reproduce this and there are 2 aspects to clarify:
> > 
> > 1. The number of contacts we see in the profile fetching view is not the number of mutual contacts that's being fetched. It's the number of backup messages we expect to process, each one containing max. 20 contacts.
> > 2. The number of communities in the profile fetching view represents the active communities + deleted communities.
> > 
> > @glitchminer In your case the app probably fetched ~7*20 contacts, 9 active communities, 5 deleted communities.
> > @benjthayer Is the current behaviour the expected one? Same as @glitchminer, I was expecting to see a parity between the numbers presented in the profile fetching view and the data presented in the app after the sync was finished.
> 
> I would also expect for the profile fetching view to tally with the numbers inside the app. If the numbers the user sees in the fetch flow are less, the user will think there has been an issue with the fetching of data. Similarly if the numbers are more - they may think the fetch is inaccurate or reflective of a less recent point in time.

@jrainville @saledjenic Could you please confirm if we need to backup the deleted communities and all the imported contacts as well? (as opposed to importing only the active communities and contacts that would end up being visible in the client)

If we actually need all the data, showing only the progress for the active communities and contacts only would be misleading as well. We could easily end up showing in the UI that the sync process is completed, but there's still lots of data to be imported.
@benjthayer In this case, WDYT of showing the progress in percentage instead of count numbers?

**Comment by benjthayer** [comment] 2024-01-25 16:23
Perhaps there is a distinction to be made on what we are actually fetching vs what the user is expecting to see in order to make a decision on whether to proceed with that profile or create a new one. The info I'm most concerned with as a user is how many mutual contacts and how many current community memberships etc. have been fetched so I know how complete the profile will be. 

Once we have all of the data, are we able to parse it in order to present figures that are more in line with what the user might expect to see? If so, we could show just the progress bars without the numbers - then at the end of the 2mins, if possible, we could filter the fetched data down to what the user would expect - ie how many mutual contacts, how many current community memberships etc.

How this is handled on mobile for reference incase this is easier to achieve (general progress screen (this could just as easily be the progress bars without the numbers) and a tally of what could and couldn't be fetched):
https://www.figma.com/file/o4qG1bnFyuyFOvHQVGgeFY/Onboarding-for-Mobile?type=design&node-id=3172-340624&mode=design&t=qiwwrSVC6PYRJnnj-4

**Comment by alexjba** [comment] 2024-02-08 13:55
> Perhaps there is a distinction to be made on what we are actually fetching vs what the user is expecting to see in order to make a decision on whether to proceed with that profile or create a new one. The info I'm most concerned with as a user is how many mutual contacts and how many current community memberships etc. have been fetched so I know how complete the profile will be.
> 
> Once we have all of the data, are we able to parse it in order to present figures that are more in line with what the user might expect to see? If so, we could show just the progress bars without the numbers - then at the end of the 2mins, if possible, we could filter the fetched data down to what the user would expect - ie how many mutual contacts, how many current community memberships etc.
> 
> How this is handled on mobile for reference incase this is easier to achieve (general progress screen (this could just as easily be the progress bars without the numbers) and a tally of what could and couldn't be fetched): https://www.figma.com/file/o4qG1bnFyuyFOvHQVGgeFY/Onboarding-for-Mobile?type=design&node-id=3172-340624&mode=design&t=qiwwrSVC6PYRJnnj-4
> 
> @saledjenic @John-44 @alexjba

@jrainville do we have the APIs that can provide the total number of contacts and communities the user has? I'm wondering if this can be a UI only task, or we need some nim/backend implementation as well.

**Comment by jrainville** [comment] 2024-02-08 14:14
> @jrainville do we have the APIs that can provide the total number of contacts and communities the user has? I'm wondering if this can be a UI only task, or we need some nim/backend implementation as well.

We don't have that currently.

It would be quite simple to add, but if doing something similar to what the mobile design does is enough, I'd go with that. It's way simpler for everyone :smile: 

We can use percents like others have proposed above to make it less confusing.

**Comment by saledjenic** [comment] 2024-02-12 07:51
Displaying percentages is for sure better than displaying real numbers. Especially when we know that for each group a single message may refer to a single item of that group (like a single backup message represents a single community, a single backup message represents a single keypair) or to a group of items of that group (a single backup message refers to up to 20 contacts). 

Also knowing that we're backing up the info about removed items as well, the things with real numbers may be even more misleading. That's one reason more to display percentages instead of real numbers.

But what in the following case, where the user created a new Status account, then added 100 contacts, then removed them all and then went to recover his account (that means that the info about all of my removed 100 contacts is backed up via 5 backed-up messages, 20 contacts per message).

Now when he sees the fetching backed-up data screen, he sees the progress bar for contacts displaying contacts or percentages (whatever) but he knows that he doesn't have any contacts. If we go with percentages in this case the info about contacts will be considered successfully fetched after all 5 messages are received, and the progress bar will gradually add 20 per 20 percent to the progress bar.

**Comment by iurimatias** [comment] 2024-10-29 20:49
this needs to be reviewed in the context of the upcoming revamped onboardingthis needs to be reviewed in the context of the upcoming revamped onboarding

**Comment by jrainville** [comment] 2024-12-09 18:36
Closing this as the new onboarding got rid of those screens to instead do them in the background using an AC notification and maybe a banner

**Closed by jrainville** 2024-12-09 18:36 UTC
Labels: bug, E:Desktop Onboarding & Login, core-team
