### ISSUE TITLE
Clicking on a sticker in a sent message crashes the app

### ISSUE THREAD

**Issue by benjthayer** [status-im/status-desktop#13973] opened 2024-03-14 13:24 UTC
Setup:
MacOS M2

Version: 2.27.0-rc.6

Steps to reproduce:
Click any sticker in a sent message - app automatically crashes 

<img width="557" alt="Screenshot 2024-03-14 at 1 24 16 PM" src="https://github.com/status-im/status-desktop/assets/110033914/fb510fd3-a5e4-4964-9d89-8ce9e541e676">

**Comment by jrainville** [comment] 2024-03-14 13:57
I tested clicking your own sticker and it works fine. I'll test clicking on someone else's

**Comment by jrainville** [comment] 2024-03-14 14:09
I tested clicking on someone else's sticker and it works as well. Both on 2.27 and 2.28.

Do you have logs when that happens @benjthayer ?

**Comment by benjthayer** [comment] 2024-03-14 14:50
> I tested clicking on someone else's sticker and it works as well. Both on 2.27 and 2.28.
> 
> Do you have logs when that happens @benjthayer ?

Hmmm seems to be working ok now. Clicked on the same sticker and it didn't crash - it loaded the sticker menu 👍

**Comment by jrainville** [comment] 2024-03-14 15:05
> > I tested clicking on someone else's sticker and it works as well. Both on 2.27 and 2.28.
> > Do you have logs when that happens @benjthayer ?
> 
> Hmmm seems to be working ok now. Clicked on the same sticker and it didn't crash - it loaded the sticker menu 👍

Hmm, I wonder if that only happens when you have never loaded any sticker before? I'll try to investigate a little more later

**Comment by mprakhov** [comment] 2024-03-18 17:09
we need logs with the crash, I was unable to repro this issue
Tested cases:
1. User_1 sent sticker A, User_2 opened sticker A (both have the same sticker pack installed)
2. User_1 sent sticker B, User_2 opened sticker B, which is absent in his sticker pack
3. User_1 sent sticker B to the newly created User_3, User_3 opened sticker B

All works fine

**Comment by jrainville** [comment] 2024-03-18 17:23
It's possible that it was fixed in master in the meantime, or it was an unfortunate coincidence (a crash happened at the same time as clicking).
It seems like Ben himself can't reproduce.

I'll close for now. @benjthayer 2.27 will be released today, you can use it and if you ever experience that crash again, reopen the issue and grab the logs from `Status/logs`. Thanks.

**Closed by jrainville** 2024-03-18 17:23 UTC
Labels: bug, crash, messenger-team
