### ISSUE TITLE
Syncing issue - Chats removed on mobile on syncing

### ISSUE THREAD

**Issue by iurimatias** [status-im/status-desktop#7074] opened 2022-08-17 19:15 UTC
# Bug Report

## Description

A issue has been reported by a user that upon attempting to sync mobile and desktop, the chats were removed on mobile.
We need to investigate this and understand why it happens and on what app or  part of the stack. (i.e is it a desktop issue, is it  mobile, is it status-go, all of them etc..)

## Steps to reproduce

1. import account to desktop
2. go to settings and attempt to sync

**Comment by PascalPrecht** [comment] 2022-08-21 16:47
Were able to reproduce this. 
Seems like this is related to when an account was imported via Keycard. 

Syncing devices then will remove group and one on one chats on synced devices.
Will post updates here as this is being investigated.

**Comment by PascalPrecht** [comment] 2022-08-24 08:22
Turns out this is not related to keycard, but to backups being performed by status.

**Comment by PascalPrecht** [comment] 2022-08-30 11:31
Fix has landed in status-go as of: https://github.com/status-im/status-go/pull/2815

**Closed by PascalPrecht** 2022-08-30 11:31 UTC
Labels: bug, priority 0: blocker, priority F0: urgent
