### ISSUE TITLE
Application slows down when user as data folder with lots of chats & messages

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#3083] opened 2021-07-28 08:56 UTC
The application is visibly slow when having data folder stored in place, even the size of the data is relatively small (36,9 Mb in my case). The login to the application is taking approximately 6 seconds, also the app itself is really slow, which is not the case for brand new account, however when data folder is getting bigger - the performance decreases as well.

I am not sure we have this issue tracked somewhere, so logged this one for investigation

https://user-images.githubusercontent.com/82375995/127294297-99af2c21-73d7-466a-a4d5-1dee1921c3c3.mov

**Comment by anastasiyaig** [comment] 2021-07-28 08:56
@iurimatias @michaelsbradleyjr @saledjenic @jrainville

**Comment by iurimatias** [comment] 2021-07-29 17:05
closing as duplicate of #1642

**Closed by iurimatias** 2021-07-29 17:05 UTC
Labels: Chat, bug, performance, priority 1: high
