### ISSUE TITLE
Primary nav badge sometimes missing

### ISSUE THREAD

**Issue by caybro** [status-im/status-desktop#10264] opened 2023-04-11 17:36 UTC
# Bug Report

- the `#desktop` channel has unread messages but the primary nav doesn't show any badge
- its parent `Desktop` category doesn't show in bold(er) either as it should

![image_11-04-2023_19-35-01](https://user-images.githubusercontent.com/5377645/231243629-a13fec66-bfaf-453f-a72e-d32f4abd7a3d.png)

### Additional Information

- Status desktop version: master
- Operating System: linux

**Comment by osmaczko** [comment] 2023-04-12 10:57
I was about to report the same issue.

https://user-images.githubusercontent.com/33099791/231437312-3cb50964-58d6-4543-98e3-4b2964f949d0.mp4

**Comment by osmaczko** [comment] 2023-04-12 10:59
Note, it happens on 0.11.0 RC2 and is a good candidate for release blocker. cc: @jrainville

**Comment by caybro** [comment] 2023-04-14 09:08
Better but... still not quite right:
![image](https://user-images.githubusercontent.com/5377645/231999691-6033ee7d-3b81-4ca8-aea1-b5e300005575.png)

Primary nav badge is fine (:heavy_check_mark:), `people-ops` has new messages (:heavy_check_mark:) but its parent category `General` is _not_ highlighted (:red_circle:)

**Comment by caybro** [comment] 2023-04-14 09:49
Or here, where I don't have any unread private/group messages, yet the primary badge is still showing up:
![image](https://user-images.githubusercontent.com/5377645/232010820-814d3642-37c7-41aa-9b32-1a7180a89be6.png)

**Comment by jrainville** [comment] 2023-04-14 14:26
I opened those two issues to track the problems you found. 
It's gonna be easier to track, since this ticket is more about the badge not showing
https://github.com/status-im/status-desktop/issues/10313
https://github.com/status-im/status-desktop/issues/10314

**Comment by jrainville** [comment] 2023-05-15 19:09
Reopening because I can still reproduce in 0.12 RC1 :unamused:

**Comment by jrainville** [comment] 2023-05-19 16:59
Investigation update: I was able to reproduce with my release app and take a snapshot of the DB before anything could be modified.

The community didn't have a badge, nor the channels in it, but if I looked in some of the channels, there were new messages.

I used `sqlcipher` to check inside the DB and I could confirm that the `unviewed_message_count` of all channels was indeed 0, when it shouldn't.

So the problem is that the `unviewed_message_count` gets reset somehow.

I then reopened the app and did another snapshot. This time, I did have the badge on the community and two of the channels.

Again, I dug into the DB and saw that the `unviewed_message_count` was 1 (hence why we had the badges), but if I counted the `seen=0` messages, it was more than that (5 for one of them). So it seems like it's not because we `mark_as_read` accidentally, because the messages would be marked as `seen` otherwise.

I'll check everywhere that `unviewed_message_count` can be modified and see what could be the problem. It's something that affects all the channels in the community somehow.

Sadly, it's hard to reproduce, or rather it's unclear what causes it to reproduce. My one way so far has been to close at the end of day and when I reopen in the next morning, even though there are new messages, the `unviewed_message_count` value didn't update correctly or got reset.

**Comment by jrainville** [comment] 2023-05-19 19:30
I created this draft PR https://github.com/status-im/status-desktop/pull/10750 to test if the fix is really what fixes it.
I'll need to test it multiple days in a row to be sure, because I'm fairly sure this is  a race condition situation.

**Comment by jrainville** [comment] 2023-05-23 13:15
Update after testing my new PR: It did **not** fix it at all.

I could see the badge saying "2" on the community, then it reset to just unseen badge (normal grey circle), and only one channel was marked as unread. So something actively resets the counters.

**Comment by jrainville** [comment] 2023-05-24 13:48
Update after adding logs:

I can 100% confirm that we have something that fully resets the community chats:

```
t=2023-05-24T09:09:48-0400 lvl=info msg="Save this chat" chat name=intros unreadCount=0 unreadMentiosn=0
t=2023-05-24T09:09:48-0400 lvl=info msg="Save this chat" chat name=rger unreadCount=0 unreadMentiosn=0
t=2023-05-24T09:09:48-0400 lvl=info msg="Save this chat" chat name=rfgghh unreadCount=0 unreadMentiosn=0
t=2023-05-24T09:09:48-0400 lvl=info msg="Save this chat" chat name=social-media unreadCount=0 unreadMentiosn=0
t=2023-05-24T09:09:48-0400 lvl=info msg="Save this chat" chat name=pets unreadCount=0 unreadMentiosn=0
t=2023-05-24T09:09:48-0400 lvl=info msg="Save this chat" chat name=status-specifications unreadCount=0 unreadMentiosn=0
t=2023-05-24T09:09:48-0400 lvl=info msg="Save this chat" chat name=ask-legal unreadCount=0 unreadMentiosn=0
t=2023-05-24T09:09:48-0400 lvl=info msg="Save this chat" chat name=user-docs unreadCount=0 unreadMentiosn=0
t=2023-05-24T09:09:48-0400 lvl=info msg="Save this chat" chat name=waku-deployments unreadCount=0 unreadMentiosn=0
t=2023-05-24T09:09:48-0400 lvl=info msg="Save this chat" chat name=emergencies unreadCount=0 unreadMentiosn=0
t=2023-05-24T09:09:48-0400 lvl=info msg="Save this chat" chat name=community-tokens unreadCount=0 unreadMentiosn=0
t=2023-05-24T09:09:48-0400 lvl=info msg="Save this chat" chat name=townhall-logistics unreadCount=0 unreadMentiosn=0
t=2023-05-24T09:09:48-0400 lvl=info msg="Save this chat" chat name=memes unreadCount=0 unreadMentiosn=0
t=2023-05-24T09:09:48-0400 lvl=info msg="Save this chat" chat name=status-network unreadCount=0 unreadMentiosn=0
t=2023-05-24T09:09:48-0400 lvl=info msg="Save this chat" chat name=ecosystem-development unreadCount=0 unreadMentiosn=0
t=2023-05-24T09:09:48-0400 lvl=info msg="Save this chat" chat name=fdfdgd unreadCount=0 unreadMentiosn=0
t=2023-05-24T09:09:48-0400 lvl=info msg="Save this chat" chat name=general unreadCount=0 unreadMentiosn=0
t=2023-05-24T09:09:48-0400 lvl=info msg="Save this chat" chat name=keycard unreadCount=0 unreadMentiosn=0
t=2023-05-24T09:09:48-0400 lvl=info msg="Save this chat" chat name=marketing-china unreadCount=0 unreadMentiosn=0
t=2023-05-24T09:09:48-0400 lvl=info msg="Save this chat" chat name=mobile-internal unreadCount=0 unreadMentiosn=0
t=2023-05-24T09:09:48-0400 lvl=info msg="Save this chat" chat name=wwewe unreadCount=0 unreadMentiosn=0
t=2023-05-24T09:09:48-0400 lvl=info msg="Save this chat" chat name=dasfd unreadCount=0 unreadMentiosn=0
t=2023-05-24T09:09:48-0400 lvl=info msg="Save this chat" chat name=status-go unreadCount=0 unreadMentiosn=0
t=2023-05-24T09:09:48-0400 lvl=info msg="Save this chat" chat name=learn-to-code unreadCount=0 unreadMentiosn=0
t=2023-05-24T09:09:48-0400 lvl=info msg="Save this chat" chat name=music unreadCount=0 unreadMentiosn=0
t=2023-05-24T09:09:48-0400 lvl=info msg="Save this chat" chat name=community-dapp unreadCount=0 unreadMentiosn=0
t=2023-05-24T09:09:48-0400 lvl=info msg="Save this chat" chat name=random unreadCount=0 unreadMentiosn=0
t=2023-05-24T09:09:48-0400 lvl=info msg="Save this chat" chat name=test1 unreadCount=0 unreadMentiosn=0
t=2023-05-24T09:09:48-0400 lvl=info msg="Save this chat" chat name=general unreadCount=0 unreadMentiosn=0
t=2023-05-24T09:09:48-0400 lvl=info msg="Save this chat" chat name=infra-commits unreadCount=0 unreadMentiosn=0
t=2023-05-24T09:09:48-0400 lvl=info msg="Save this chat" chat name=wallet-team unreadCount=0 unreadMentiosn=0
t=2023-05-24T09:09:48-0400 lvl=info msg="Save this chat" chat name=alerts-ens-distribution unreadCount=0 unreadMentiosn=0
t=2023-05-24T09:09:48-0400 lvl=info msg="Save this chat" chat name=dasdasd unreadCount=0 unreadMentiosn=0
t=2023-05-24T09:09:48-0400 lvl=info msg="Save this chat" chat name=migration-to-status-help unreadCount=0 unreadMentiosn=0
t=2023-05-24T09:09:48-0400 lvl=info msg="Save this chat" chat name=activity-centre unreadCount=0 unreadMentiosn=0
t=2023-05-24T09:09:48-0400 lvl=info msg="Save this chat" chat name=general-banter unreadCount=0 unreadMentiosn=0
t=2023-05-24T09:09:48-0400 lvl=info msg="Save this chat" chat name=rffefe unreadCount=0 unreadMentiosn=0
t=2023-05-24T09:09:48-0400 lvl=info msg="Save this chat" chat name=infra unreadCount=0 unreadMentiosn=0
t=2023-05-24T09:09:48-0400 lvl=info msg="Save this chat" chat name=desktop-e2e-tests unreadCount=0 unreadMentiosn=0
t=2023-05-24T09:09:48-0400 lvl=info msg="Save this chat" chat name=distributor unreadCount=0 unreadMentiosn=0
t=2023-05-24T09:09:48-0400 lvl=info msg="Save this chat" chat name=games unreadCount=0 unreadMentiosn=0
t=2023-05-24T09:09:48-0400 lvl=info msg="Save this chat" chat name=standups unreadCount=0 unreadMentiosn=0
t=2023-05-24T09:09:48-0400 lvl=info msg="Save this chat" chat name=dogfooding unreadCount=0 unreadMentiosn=0
t=2023-05-24T09:09:48-0400 lvl=info msg="Save this chat" chat name=blockchain-data unreadCount=0 unreadMentiosn=0
t=2023-05-24T09:09:48-0400 lvl=info msg="Save this chat" chat name=corona-chan unreadCount=0 unreadMentiosn=0
t=2023-05-24T09:09:48-0400 lvl=info msg="Save this chat" chat name=travel-requests unreadCount=0 unreadMentiosn=0
t=2023-05-24T09:09:48-0400 lvl=info msg="Save this chat" chat name=desktop-ui unreadCount=0 unreadMentiosn=0
t=2023-05-24T09:09:48-0400 lvl=info msg="Save this chat" chat name=architecture unreadCount=0 unreadMentiosn=0
t=2023-05-24T09:09:48-0400 lvl=info msg="Save this chat" chat name=xwwq unreadCount=0 unreadMentiosn=0
t=2023-05-24T09:09:48-0400 lvl=info msg="Save this chat" chat name=governance unreadCount=0 unreadMentiosn=0
t=2023-05-24T09:09:48-0400 lvl=info msg="Save this chat" chat name=events unreadCount=0 unreadMentiosn=0
t=2023-05-24T09:09:48-0400 lvl=info msg="Save this chat" chat name=general unreadCount=0 unreadMentiosn=0
t=2023-05-24T09:09:48-0400 lvl=info msg="Save this chat" chat name=reading-room unreadCount=0 unreadMentiosn=0
t=2023-05-24T09:09:48-0400 lvl=info msg="Save this chat" chat name=weeb-room unreadCount=0 unreadMentiosn=0
t=2023-05-24T09:09:48-0400 lvl=info msg="Save this chat" chat name=marketing-internal unreadCount=0 unreadMentiosn=0
t=2023-05-24T09:09:48-0400 lvl=info msg="Save this chat" chat name=mobile unreadCount=0 unreadMentiosn=0
t=2023-05-24T09:09:48-0400 lvl=info msg="Save this chat" chat name=nimbus-integration unreadCount=0 unreadMentiosn=0
t=2023-05-24T09:09:48-0400 lvl=info msg="Save this chat" chat name=pm unreadCount=0 unreadMentiosn=0
t=2023-05-24T09:09:48-0400 lvl=info msg="Save this chat" chat name=test2re unreadCount=0 unreadMentiosn=0
t=2023-05-24T09:09:48-0400 lvl=info msg="Save this chat" chat name=war-chan unreadCount=0 unreadMentiosn=0
t=2023-05-24T09:09:48-0400 lvl=info msg="Save this chat" chat name=mobile-ui-reviews unreadCount=0 unreadMentiosn=0
t=2023-05-24T09:09:48-0400 lvl=info msg="Save this chat" chat name=mobile-ui unreadCount=0 unreadMentiosn=0
t=2023-05-24T09:09:48-0400 lvl=info msg="Save this chat" chat name=status-client-offsite unreadCount=0 unreadMentiosn=0
t=2023-05-24T09:09:48-0400 lvl=info msg="Save this chat" chat name=web unreadCount=0 unreadMentiosn=0
t=2023-05-24T09:09:48-0400 lvl=info msg="Save this chat" chat name=dwqdqw unreadCount=0 unreadMentiosn=0
t=2023-05-24T09:09:48-0400 lvl=info msg="Save this chat" chat name=desktop unreadCount=0 unreadMentiosn=0
t=2023-05-24T09:09:48-0400 lvl=info msg="Save this chat" chat name=waku-e2e unreadCount=0 unreadMentiosn=0
t=2023-05-24T09:09:48-0400 lvl=info msg="Save this chat" chat name=sports unreadCount=0 unreadMentiosn=0
t=2023-05-24T09:09:48-0400 lvl=info msg="Save this chat" chat name=status-takeovers unreadCount=0 unreadMentiosn=0
t=2023-05-24T09:09:48-0400 lvl=info msg="Save this chat" chat name=people-ops unreadCount=0 unreadMentiosn=0
t=2023-05-24T09:09:48-0400 lvl=info msg="Save this chat" chat name=ask-finance unreadCount=0 unreadMentiosn=0
t=2023-05-24T09:09:48-0400 lvl=info msg="Save this chat" chat name=process-governance unreadCount=0 unreadMentiosn=0
t=2023-05-24T09:09:48-0400 lvl=info msg="Save this chat" chat name=mobile-animation unreadCount=0 unreadMentiosn=0
t=2023-05-24T09:09:48-0400 lvl=info msg="Save this chat" chat name=security unreadCount=0 unreadMentiosn=0
t=2023-05-24T09:09:48-0400 lvl=info msg="Save this chat" chat name=mobile-prs unreadCount=0 unreadMentiosn=0
t=2023-05-24T09:09:48-0400 lvl=info msg="Save this chat" chat name=community-permissions unreadCount=0 unreadMentiosn=0
```

The only thing is I somehow do not have the source of where those were called. I can at least confirm that this is done is a loop, so probably calling `saveChats`.

**Comment by jrainville** [comment] 2023-05-26 17:42
I finally found the answer. I found it yesterday, but I needed to test it first to be sure, and all this morning, my badges were kept alive.

I'll test again in the following days, but I'm pretty confident this is it.

Status-go PR here: https://github.com/status-im/status-go/pull/3539

**Closed** 2023-05-29 17:57 UTC
Labels: bug, messenger-team
