### ISSUE TITLE
Crash when clicking community channel

### ISSUE THREAD

**Issue by dlipicar** [status-im/status-desktop#12012] opened 2023-08-25 12:09 UTC
# Bug Report

## Description

Using [StatusIm-Desktop-v0.14.0-rc.1-8d2cac-aarch64.dmg](https://github.com/status-im/status-desktop/releases/download/untagged-c98d33348b4c633a81b4/StatusIm-Desktop-v0.14.0-rc.1-8d2cac-aarch64.dmg)

I was in the checking out some messages in a community. Then I clicked one of the channels which had new messages (highlighted), and Status crashed.

Crash report:

[CrashReport.txt](https://github.com/status-im/status-desktop/files/12438901/CrashReport.txt)

Last lines of geth log:
```
t=2023-08-25T08:47:43-0300 lvl=warn msg="Was passed p2p address with a different peerId. found: 16Uiu2HAkyScd7DiwgMwzfw8CFFhznH3wRzciqEUfjDzn7vyimR8c, expected: 16Uiu2HAmRd9NBvPET1uH6RKUf8GdZrHXpDhw9vHXdmQCTWSbEww4"
t=2023-08-25T08:47:43-0300 lvl=warn msg="Was passed p2p address with a different peerId. found: 16Uiu2HAmL5okWopX7NqZWBUKVqW8iUxCEmd5GMHLVPwCgzYzQv3e, expected: 16Uiu2HAmJvKEkdAnitEoPRJbovyyGgYJB9p6uzUPPvw7YgQ2Dfhy"
t=2023-08-25T08:47:43-0300 lvl=warn msg="Was passed p2p address with a different peerId. found: 16Uiu2HAmDQugwDHM3YeUp86iGjrUvbdw3JPRgikC7YoGBsT2ymMg, expected: 16Uiu2HAkxgrP4BniL3vZ9ejS6FoVGVKU86dnVkoxwdEyAMPRPZeK"
t=2023-08-25T08:47:43-0300 lvl=warn msg="Was passed p2p address with a different peerId. found: 16Uiu2HAmL5okWopX7NqZWBUKVqW8iUxCEmd5GMHLVPwCgzYzQv3e, expected: 16Uiu2HAmDNbB5jhoM9bAmrWathzGjo7KmYeFnpx2MXUSS7qYYLpq"
t=2023-08-25T08:47:43-0300 lvl=warn msg="Was passed p2p address with a different peerId. found: 16Uiu2HAmVkKntsECaYfefR1V2yCR79CegLATuTPE6B9TxgxBiiiA, expected: 16Uiu2HAmDW2cEeJ2d8QU1tqeGQzzNpS3eMPGq5ixGRPLYwKZrMYC"
t=2023-08-25T08:47:43-0300 lvl=warn msg="Was passed p2p address with a different peerId. found: 16Uiu2HAkyScd7DiwgMwzfw8CFFhznH3wRzciqEUfjDzn7vyimR8c, expected: 16Uiu2HAm9PQXjRi52H1zo2HTiFmy1Wykj2EDpmUoai1ciVNJ8hhW"
t=2023-08-25T08:47:43-0300 lvl=warn msg="Was passed p2p address with a different peerId. found: 16Uiu2HAmKTYnoPKebjWy63e1zPKiYRCQvm25W5mNSnCFE8EmzLga, expected: 16Uiu2HAmRdp9xGbWnh1TPgqcBjfHFBPw1TbhTn58Pxu36MUg31PT"
t=2023-08-25T08:47:43-0300 lvl=warn msg="Was passed p2p address with a different peerId. found: 16Uiu2HAmL5okWopX7NqZWBUKVqW8iUxCEmd5GMHLVPwCgzYzQv3e, expected: 16Uiu2HAm4x6XWudXXK1ZGpzb8Nf9BXfXyQTHZEeU72HfpwmFKWX8"
t=2023-08-25T08:47:43-0300 lvl=info msg="load erc20 transfers in range" from=124,812,999 to=124,813,050 batchSize=500,000
t=2023-08-25T08:47:43-0300 lvl=info msg="wallet historical downloader for erc20 transfers finished" chainID=42161 address=0xa1E277eA6b97eFfc5b61B3BF5dE03F438981247E from=124,812,999 to=124,813,050 time=642.437667ms headers=0
t=2023-08-25T08:47:43-0300 lvl=info msg="load erc20 transfers in range" from=124,812,999 to=124,813,050 batchSize=500,000
t=2023-08-25T08:47:43-0300 lvl=info msg="wallet historical downloader for erc20 transfers finished" chainID=42161 address=0xF0A1098CCF735D109e9D29837BCEd9B520D593Be from=124,812,999 to=124,813,050 time=760.556833ms headers=0
t=2023-08-25T08:47:44-0300 lvl=info msg="load erc20 transfers in range" from=17,991,504 to=17,991,506 batchSize=500,000
t=2023-08-25T08:47:44-0300 lvl=info msg="wallet historical downloader for erc20 transfers finished" chainID=1 address=0x0ADB6CaA256A5375C638C00e2fF80A9Ac1b2d3A7 from=17,991,504 to=17,991,506 time=761.75475ms headers=0
t=2023-08-25T08:47:44-0300 lvl=info msg="eth historical downloader finished successfully" chain=42161 address=0x0ADB6CaA256A5375C638C00e2fF80A9Ac1b2d3A7 from=124,813,004 to=124,813,055 total blocks=0 time=697.687875ms
t=2023-08-25T08:47:44-0300 lvl=info msg="wallet historical downloader for erc20 transfers start" chainID=42161 address=0x0ADB6CaA256A5375C638C00e2fF80A9Ac1b2d3A7 from=124,813,004 to=124,813,055
t=2023-08-25T08:47:44-0300 lvl=info msg="iterative downloader" address=0x0ADB6CaA256A5375C638C00e2fF80A9Ac1b2d3A7 from=124,813,004 to=124,813,055 size=500,000
t=2023-08-25T08:47:44-0300 lvl=info msg="load erc20 transfers in range" from=124,813,004 to=124,813,055 batchSize=500,000
t=2023-08-25T08:47:44-0300 lvl=info msg="wallet historical downloader for erc20 transfers finished" chainID=42161 address=0x0ADB6CaA256A5375C638C00e2fF80A9Ac1b2d3A7 from=124,813,004 to=124,813,055 time=585.392416ms headers=0
t=2023-08-25T08:47:45-0300 lvl=warn msg="Was passed p2p address with a different peerId. found: 16Uiu2HAmUCVBLbmwKWaonuFzbLY1Nvhi1Hgk1zVn6H8u7D9B86jL, expected: 16Uiu2HAmRsxgFftnZFGvVJ26A8hKZdes5nTCMYBxoG9doHdxiGGV"
t=2023-08-25T08:47:46-0300 lvl=warn msg="Was passed p2p address with a different peerId. found: 16Uiu2HAkvEZgh3KLwhLwXg95e5ojM8XykJ4Kxi2T7hk22rnA7pJC, expected: 16Uiu2HAmAzWTsA3pLdE2qBNTvsJMrK7UA4tau8nKeJMttsNoHGux"
t=2023-08-25T08:47:46-0300 lvl=warn msg="Was passed p2p address with a different peerId. found: 16Uiu2HAmFy8BrJhCEmCYrUfBdSNkrPw6VHExtv4rRp1DSBnCPgx8, expected: 16Uiu2HAmH2RUfhEZQvaQ5Le3gc9d5sAt1cPzmYvrt1D7xXGuQjPg"
t=2023-08-25T08:47:46-0300 lvl=warn msg="Was passed p2p address with a different peerId. found: 16Uiu2HAmL5okWopX7NqZWBUKVqW8iUxCEmd5GMHLVPwCgzYzQv3e, expected: 16Uiu2HAkzH8jmJyYSx52fZCnpSwnnuS7NLbcvZ6G1ZJv1qtDmnN3"
t=2023-08-25T08:47:46-0300 lvl=warn msg="Was passed p2p address with a different peerId. found: 16Uiu2HAkwBp8T6G77kQXSNMnxgaMky1JeyML5yqoTHRM8dbeCBNb, expected: 16Uiu2HAmHAqkXp5P5mXXRY8vcinKxz8aFNtyvbVuiQoUgERpceAh"
t=2023-08-25T08:47:46-0300 lvl=warn msg="Was passed p2p address with a different peerId. found: 16Uiu2HAm4v86W3bmT1BiH6oSPzcsSr24iDQpSN5Qa992BCjjwgrD, expected: 16Uiu2HAm7UVm429jYCWQBdb3vxoxWbkGie7dvjcSdgWfDuoFPjWt"
t=2023-08-25T08:47:46-0300 lvl=warn msg="Was passed p2p address with a different peerId. found: 16Uiu2HAmDQugwDHM3YeUp86iGjrUvbdw3JPRgikC7YoGBsT2ymMg, expected: 16Uiu2HAmMcHFgARoFJpi4CgpT7DumDLXffWwGnPD1V1GDw8HgkJM"
t=2023-08-25T08:47:46-0300 lvl=warn msg="Was passed p2p address with a different peerId. found: 16Uiu2HAm1fVVprL9EaDpDw4frNX3CPfZu5cBqhtk9Ncm6WCvprpv, expected: 16Uiu2HAkwpsLn79mvbiX1NNMT5sJnPTShvsUWkgD3vuu4SWusdeL"
t=2023-08-25T08:47:46-0300 lvl=warn msg="Was passed p2p address with a different peerId. found: 16Uiu2HAmSve7tR5YZugpskMv2dmJAsMUKmfWYEKRXNUxRaTCnsXV, expected: 16Uiu2HAmK6w5yVgmP6MAp4FSg5AsNrRLBaB4VjYpwfzjrcRTNpw7"
t=2023-08-25T08:47:46-0300 lvl=warn msg="Was passed p2p address with a different peerId. found: 16Uiu2HAm6HZZr7aToTvEBPpiys4UxajCTU97zj5v7RNR2gbniy1D, expected: 16Uiu2HAm3MePvkfTwXJx9SQof1CGG2BS4ER5dGETWs8ccMdALGZU"
t=2023-08-25T08:47:46-0300 lvl=warn msg="Was passed p2p address with a different peerId. found: 16Uiu2HAkzhuFzJ6Diy2xgeqzrK8yw7GEp1MqFYxhzTXTzYbvpKKB, expected: 16Uiu2HAmSCRMwSVQUojvmTJX2PHmC1BwmEniHswH6DkG8WEA5bGu"
t=2023-08-25T08:47:46-0300 lvl=warn msg="Was passed p2p address with a different peerId. found: 16Uiu2HAmSve7tR5YZugpskMv2dmJAsMUKmfWYEKRXNUxRaTCnsXV, expected: 16Uiu2HAmUCqPqJM6SJqt9XTD1v4za1ue3nZ2kdodnefGbH3FLxk6"
t=2023-08-25T08:47:46-0300 lvl=warn msg="Was passed p2p address with a different peerId. found: 16Uiu2HAmSve7tR5YZugpskMv2dmJAsMUKmfWYEKRXNUxRaTCnsXV, expected: 16Uiu2HAmUCqPqJM6SJqt9XTD1v4za1ue3nZ2kdodnefGbH3FLxk6"
t=2023-08-25T08:47:47-0300 lvl=warn msg="Was passed p2p address with a different peerId. found: 16Uiu2HAmL5okWopX7NqZWBUKVqW8iUxCEmd5GMHLVPwCgzYzQv3e, expected: 16Uiu2HAm2nMBWiNh9kMX6iZnEqurZBBg4w3wBbDGw1722mA5KBwE"
t=2023-08-25T08:47:47-0300 lvl=warn msg="Was passed p2p address with a different peerId. found: 16Uiu2HAm1fVVprL9EaDpDw4frNX3CPfZu5cBqhtk9Ncm6WCvprpv, expected: 16Uiu2HAm83nVyBwSUZWUQwnsM6Ncmg7PZBdXtj3ueM6R8pVbxn26"
t=2023-08-25T08:47:47-0300 lvl=info msg="processing message" site=RetrieveAll hash=0x64f851589bb949011225d825b5ea19f9656771b8d2c29be4dfb6152afa301f24 message-id=0x5c12f20b1a87df5b041c037892fd4225302fa2bebae0ccda12021ccb1ac72413
t=2023-08-25T08:47:47-0300 lvl=info msg="processing message" type=STATUS_UPDATE senderID=0x0486081a2b823f02047d770d53b98a2d822c9606d068213c999ed1e425320103635c68a159231b5b76954dc62569235e5c5d00fd43232598d7547b33d52e37838a
t=2023-08-25T08:47:47-0300 lvl=info msg="handling StatusUpdate"
t=2023-08-25T08:47:47-0300 lvl=info msg="processing message" site=RetrieveAll hash=0xec981ee7e295f08959c0de2c4f796c32535220cf0bd32715a05645f1856f62ed message-id=0x5c12f20b1a87df5b041c037892fd4225302fa2bebae0ccda12021ccb1ac72413
t=2023-08-25T08:47:47-0300 lvl=info msg="processing message" type=STATUS_UPDATE senderID=0x0486081a2b823f02047d770d53b98a2d822c9606d068213c999ed1e425320103635c68a159231b5b76954dc62569235e5c5d00fd43232598d7547b33d52e37838a
t=2023-08-25T08:47:47-0300 lvl=info msg="processing message" site=RetrieveAll hash=0x8ef0fb7b872a4ede2f911de6019147e1d9f98edd4fa5f0bb3067a2be5eb75980 message-id=0x5c12f20b1a87df5b041c037892fd4225302fa2bebae0ccda12021ccb1ac72413
t=2023-08-25T08:47:47-0300 lvl=info msg="processing message" type=STATUS_UPDATE senderID=0x0486081a2b823f02047d770d53b98a2d822c9606d068213c999ed1e425320103635c68a159231b5b76954dc62569235e5c5d00fd43232598d7547b33d52e37838a
t=2023-08-25T08:47:48-0300 lvl=warn msg="Was passed p2p address with a different peerId. found: 16Uiu2HAkzhuFzJ6Diy2xgeqzrK8yw7GEp1MqFYxhzTXTzYbvpKKB, expected: 16Uiu2HAmDr5zmzerofa4hVs6UUyKJygE6EsqrnfULJ7TjZ679dUc"
t=2023-08-25T08:47:48-0300 lvl=warn msg="Was passed p2p address with a different peerId. found: 16Uiu2HAmKTYnoPKebjWy63e1zPKiYRCQvm25W5mNSnCFE8EmzLga, expected: 16Uiu2HAmJ6QbSL3pv4uq91Wnbqna5PEncVLL4KtC3No9kd8AM5iF"
t=2023-08-25T08:47:48-0300 lvl=warn msg="Was passed p2p address with a different peerId. found: 16Uiu2HAmKTYnoPKebjWy63e1zPKiYRCQvm25W5mNSnCFE8EmzLga, expected: 16Uiu2HAmJ6QbSL3pv4uq91Wnbqna5PEncVLL4KtC3No9kd8AM5iF"
t=2023-08-25T08:47:48-0300 lvl=warn msg="Was passed p2p address with a different peerId. found: 16Uiu2HAkyScd7DiwgMwzfw8CFFhznH3wRzciqEUfjDzn7vyimR8c, expected: 16Uiu2HAmHfm96YryZiRxerecbj45h2x2UNoeJG59gMYAXArfHeh5"
t=2023-08-25T08:47:48-0300 lvl=warn msg="Was passed p2p address with a different peerId. found: 16Uiu2HAkvEZgh3KLwhLwXg95e5ojM8XykJ4Kxi2T7hk22rnA7pJC, expected: 16Uiu2HAmHkVuHvBJNKbVNnTZqwbVv8KGtU57robnk2mYPdP3j55p"
t=2023-08-25T08:47:48-0300 lvl=warn msg="Was passed p2p address with a different peerId. found: 16Uiu2HAmK6w5yVgmP6MAp4FSg5AsNrRLBaB4VjYpwfzjrcRTNpw7, expected: 16Uiu2HAkwowWVZRdZsxqcy8bNLaufCxn83mqSL7uWNH8gQB9yJw3"
t=2023-08-25T08:47:48-0300 lvl=warn msg="Was passed p2p address with a different peerId. found: 16Uiu2HAm1fVVprL9EaDpDw4frNX3CPfZu5cBqhtk9Ncm6WCvprpv, expected: 16Uiu2HAmAAAUcBqeobYqxgBpdBcBpwahZTv6iX1wxxes2R3wFuHx"
t=2023-08-25T08:47:48-0300 lvl=warn msg="Was passed p2p address with a different peerId. found: 16Uiu2HAkvEZgh3KLwhLwXg95e5ojM8XykJ4Kxi2T7hk22rnA7pJC, expected: 16Uiu2HAmHkVuHvBJNKbVNnTZqwbVv8KGtU57robnk2mYPdP3j55p"

```

Last lines of app log:

```
INF 2023-08-25 08:45:31.073-03:00 history request completed                  topics="mailservers-service" tid=10405 file=service.nim:183
INF 2023-08-25 08:46:54.345-03:00 history request started                    topics="mailservers-service" tid=10405 file=service.nim:178 numBatches=0
INF 2023-08-25 08:46:54.346-03:00 history request completed                  topics="mailservers-service" tid=10405 file=service.nim:183
ERR 2023-08-25 08:46:54.391-03:00 rpc response error                         topics="rpc" tid=10405 file=core.nim:36 err="\nstatus-go error [methodName:wallet_getPendingTransactions, code:-32000, message:no such table: pending_transactions ]\n"
ERR 2023-08-25 08:46:54.391-03:00 error doing rpc request                    topics="rpc" tid=10405 file=core.nim:40 methodName=wallet_getPendingTransactions exception="\nstatus-go error [methodName:wallet_getPendingTransactions, code:-32000, message:no such table: pending_transactions ]\n"
ERR 2023-08-25 08:46:54.391-03:00 error:                                     topics="transaction-service" tid=10405 file=service.nim:133 errDescription="\nstatus-go error [methodName:wallet_getPendingTransactions, code:-32000, message:no such table: pending_transactions ]\n"
ERR 2023-08-25 08:46:54.391-03:00 rpc response error                         topics="rpc" tid=10405 file=core.nim:36 err="\nstatus-go error [methodName:wallet_getPendingTransactions, code:-32000, message:no such table: pending_transactions ]\n"
ERR 2023-08-25 08:46:54.391-03:00 error doing rpc request                    topics="rpc" tid=10405 file=core.nim:40 methodName=wallet_getPendingTransactions exception="\nstatus-go error [methodName:wallet_getPendingTransactions, code:-32000, message:no such table: pending_transactions ]\n"
ERR 2023-08-25 08:46:54.391-03:00 error:                                     topics="transaction-service" tid=10405 file=service.nim:133 errDescription="\nstatus-go error [methodName:wallet_getPendingTransactions, code:-32000, message:no such table: pending_transactions ]\n"
ERR 2023-08-25 08:46:56.585-03:00 rpc response error                         topics="rpc" tid=10405 file=core.nim:36 err="\nstatus-go error [methodName:wallet_getPendingTransactions, code:-32000, message:no such table: pending_transactions ]\n"
ERR 2023-08-25 08:46:56.585-03:00 error doing rpc request                    topics="rpc" tid=10405 file=core.nim:40 methodName=wallet_getPendingTransactions exception="\nstatus-go error [methodName:wallet_getPendingTransactions, code:-32000, message:no such table: pending_transactions ]\n"
ERR 2023-08-25 08:46:56.585-03:00 error:                                     topics="transaction-service" tid=10405 file=service.nim:133 errDescription="\nstatus-go error [methodName:wallet_getPendingTransactions, code:-32000, message:no such table: pending_transactions ]\n"
ERR 2023-08-25 08:46:56.586-03:00 rpc response error                         topics="rpc" tid=10405 file=core.nim:36 err="\nstatus-go error [methodName:wallet_getPendingTransactions, code:-32000, message:no such table: pending_transactions ]\n"
ERR 2023-08-25 08:46:56.586-03:00 error doing rpc request                    topics="rpc" tid=10405 file=core.nim:40 methodName=wallet_getPendingTransactions exception="\nstatus-go error [methodName:wallet_getPendingTransactions, code:-32000, message:no such table: pending_transactions ]\n"
ERR 2023-08-25 08:46:56.586-03:00 error:                                     topics="transaction-service" tid=10405 file=service.nim:133 errDescription="\nstatus-go error [methodName:wallet_getPendingTransactions, code:-32000, message:no such table: pending_transactions ]\n"
```

**Comment by dlipicar** [comment] 2023-08-25 12:26
Ok it's now crashing right after login
[app_20230825_092250.log](https://github.com/status-im/status-desktop/files/12439052/app_20230825_092250.log)
[geth.log.zip](https://github.com/status-im/status-desktop/files/12439057/geth.log.zip)

**Comment by dlipicar** [comment] 2023-08-25 12:36
@jrainville no idea if this is messenger-related, but FYI

**Comment by jrainville** [comment] 2023-08-25 13:24
Duplicate of https://github.com/status-im/status-desktop/issues/11996

**Closed by jrainville** 2023-08-25 13:24 UTC
Labels: bug
