### ISSUE TITLE
support status-im:// and join.status.im urls in browser

### ISSUE THREAD

**Issue by richard-ramos** [status-im/status-desktop#1511] opened 2020-12-09 18:05 UTC
User should be able to use Desktop's browser and enter status-im:// addresses and join.status.im URLs to open chats / profiles / etc

**Comment by jrainville** [comment] 2020-12-09 18:18
This is a duplicate of https://github.com/status-im/nim-status-client/issues/837

**Comment by iurimatias** [comment] 2021-01-19 23:26
duplicate of #837

**Closed by iurimatias** 2021-01-19 23:26 UTC
Labels: Browser, enhancement
