### ISSUE TITLE
Set global appearance setting to System default (Windows)

### ISSUE THREAD

**Issue by hesterbruikman** [status-im/status-desktop#2177] opened 2021-04-02 11:59 UTC
Following #2144  

Once the appearance setting is global, next step is to set the default of this global setting to 'system default' when the app is launched for the first time

This is likely already the case on Mac, but showed to be more difficult on Windows. As part of this issue it would be good to verify the current behavior on Mac and Linux for any changes required.

**User story** 
As a user who is new to Status
I want for the application to respect my system Language and Display settings on launch (account creation/import)
Because these are settings I prefer for my applications

Related discussion: https://github.com/status-im/status-desktop/discussions/2145

**Comment by iurimatias** [comment] 2021-07-15 19:20
duplicate of #1725

**Closed by iurimatias** 2021-07-15 19:20 UTC
Labels: Profile, feature, windows
