### ISSUE TITLE
Dapps button is not clickable when using VPN

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#16797] opened 2024-11-22 08:55 UTC
### Description

I am connected to Anmezia VPN on Windows. When having this connection running, i cant click Dapps button, it is inactive.

I can access other resources like GH or Jenkins when being on this VPN, also accessing https://fedoraproject.org/static/hotspot.txt says `Ok`

```
WRN 2024-11-22 08:41:10.045Z qt warning                                 topics="qt" tid=17588 text="WebEngineContext used before QtWebEngine::initialize() or OpenGL context creation failed." file=:0 category=default
WRN 2024-11-22 08:41:10.594Z qt warning                                 topics="qt" tid=17588 text="QML Loader: Binding loop detected for property \"active\"" file=qrc:/StatusQ/Components/WebEngineLoader.qml:72 category=default
DBG 2024-11-22 08:41:10.991Z qt message                                 topics="qt" tid=17588 text="WC WalletConnectSDK.wcCall.init; root.projectId: 87815d72a81d739d2a7ce15c2cfdefb3" file=qrc:/app/AppLayouts/Wallet/services/dapps/WalletConnectSDK.qml:105 category=qml
ERR 2024-11-22 08:41:10.994Z qt error                                   topics="qt" tid=17588 text="Failed initializing WebChannel or initialization not run" file=qrc:/app/AppLayouts/Wallet/services/dapps/sdk/generated/bundle.js:2 category=js
ERR 2024-11-22 08:41:11.014Z qt error                                   topics="qt" tid=17588 text="Uncaught (in promise) TypeError: Cannot read property 'sdkInitialized' of undefined" file=qrc:/app/AppLayouts/Wallet/services/dapps/sdk/src/index.html:7 category=js
ERR 2024-11-22 08:41:36.314Z qt error                                   topics="qt" tid=17588 text="[object Object] No matching key. proposal: 1732250159377856" file=qrc:/app/AppLayouts/Wallet/services/dapps/sdk/generated/bundle.js:2 category=js
ERR 2024-11-22 08:41:36.315Z qt error                                   topics="qt" tid=17588 text="Uncaught (in promise) TypeError: Cannot read property 'onProposalExpire' of undefined" file=qrc:/app/AppLayouts/Wallet/services/dapps/sdk/generated/bundle.js:2 category=js
```

![Image](https://github.com/user-attachments/assets/e5ac9a71-43c3-4776-b445-8b0c9d9dacf0)

**Comment by alexjba** [comment] 2024-11-26 15:27
Closing it for now. Looks like it's specific to Amnezia VPN connections. Cannot reproduce on other VPNs

**Closed by alexjba** 2024-11-26 15:27 UTC
Labels: bug, dapp-interactions, wallet-team
