### ISSUE TITLE
[refactoring/base_02] Contact list is empty in Profile

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#4100] opened 2021-11-11 17:49 UTC
# Bug Report

## Description

Contact list is empty in Profile

## Steps to reproduce

1. open app
2. open 1x1 chat and add someone to contacts, like any random public key `0x0478632dbe2f720f1f7f1ade080010fbede8ed1f4eebc164e2621bb55bed45757f4a3eb0495552cc26480f209607aeb34223fc4d8363fb074fede6082baf26db08`
3. open profile -> contacts

#### Expected behavior

List of contacts contain recently added contact

#### Actual behavior

List of contacts say that no contacts added

<img width="1552" alt="Screenshot 2021-11-11 at 20 48 46" src="https://user-images.githubusercontent.com/82375995/141345163-b0de9c76-724e-4c4e-a264-a3db74dfd162.png">

<img width="1552" alt="Screenshot 2021-11-11 at 20 48 56" src="https://user-images.githubusercontent.com/82375995/141345191-0963efc8-d2b8-469c-96ba-459d0936c91b.png">

### Additional Information

- Status desktop version: r`efactoring_base02` branch, commit https://github.com/status-im/status-desktop/commit/224cb706623c84e3573010c41d435bdea19ffa19
- Operating System: masOS Big Sur

**Comment by alexandraB99** [comment] 2021-11-19 19:55
After a chat with @jrainville, this is fixed in base_bc, not sure how we want to proceed here.

**Comment by jrainville** [comment] 2021-11-22 14:23
@saledjenic is currently rebasing base_02 on master and then base_bc on base_02, so hopefully, soon, we will be able to merge base_bc in base_02.
I guess it also depends on when we want to merge base_02 in master

**Comment by saledjenic** [comment] 2021-11-22 15:55
> @saledjenic is currently rebasing base_02 on master and then base_bc on base_02, so hopefully, soon, we will be able to merge base_bc in base_02. I guess it also depends on when we want to merge base_02 in master

@jrainville @alexandraB99 `base_bc` won't come to `base_02`

`base_02` is on top of the `master` now, and `base_bc` is on top of the `base_02`.

As discussed with @PascalPrecht we're waiting for some issue (not sure which one, something related to go as @PascalPrecht said) to be fixed and that `base_02` will be merged into `master`. Since then all fixes will target `master` and `base_bc` will be the only branch related to refactor.

**Comment by jrainville** [comment] 2021-11-22 15:57
So in that case, it would be valid to just do a quick fix for this issue. Don't worry @alexandraB99 if you have to do an ugly patch, since it's gonna get  correctly fixed and removed when base_bc will be merged.

Let me know if you need help finding the problem and/or fix

**Comment by alexandraB99** [comment] 2021-11-22 23:48
@jrainville there is definitely some regression there, your commits regarding this are there twice, even thrice sometimes but all the changes are missing at the end. Doing `git log --all --author="Jonathan Rainville" --grep="contacts"` I get the following:
[git log.png](https://images.zenhubusercontent.com/60e32e06eddded5b0a4e2749/80fc900d-1b7b-4bfa-943c-2154d90ae7f6)

I tried cherry-picking these commits back but I get conflicts, which is the order to be followed?!

**Comment by jrainville** [comment] 2021-11-23 14:43
That's weird. Maybe they are there multiple times because of rebases.
Anyway, here is the order, but since it's base on base_bc, it might still not work/get a lot of conflicts

![image](https://user-images.githubusercontent.com/11926403/143045248-1c5d8c70-ee03-4667-b064-79f3baa9753e.png)

**Comment by alexandraB99** [comment] 2021-11-23 18:16
[This](https://github.com/status-im/status-desktop/pull/4161) should be bringing the changes back, however there is a crash happening when trying to add a new contact which happens in base_bc as well. I am looking into it.. @jrainville any idea?

**Comment by jrainville** [comment] 2021-11-23 18:25
I haven't tested it in a while. It could be that Sale's commit to improve the code broke it. I did the first three commits and the last one `general improvement` was made by Sale.

**Comment by alexandraB99** [comment] 2021-11-24 00:59
@jrainville fixed in base_bc [here](https://github.com/status-im/status-desktop/pull/4162) and in base_02 [here](https://github.com/status-im/status-desktop/pull/4161). However for base_02 there is a [commit](https://github.com/status-im/status-lib/commit/4ff2b6857c6af35da2337d729dc2ddf54c2e2c9c) from @PascalPrecht that might be fixing the crash caused by the `discard callPrivateRPC("saveContact".prefix, payload)`, I haven't tested yet. What is the plan for base_02 when it comes to status-lib? should it point to master? because currently this commit is not in there

**Comment by PascalPrecht** [comment] 2021-11-24 12:28
> What is the plan for base_02 when it comes to status-lib? should it point to master? because currently this commit is not in there

`base_02` has now been merged into master and includes fixes for `saveContact` API calls breaking.

**Closed** 2021-12-01 18:51 UTC
Labels: bug, refactor_base_02
