### ISSUE TITLE
Transfer ownership modal is broken

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#2997] opened 2021-07-21 08:29 UTC
The issue appears when clicking Back up button at the widget:

<img width="1012" alt="Screenshot 2021-07-23 at 16 20 48" src="https://user-images.githubusercontent.com/82375995/126787832-c5405445-aa6b-42a8-a010-f677bb141e32.png">

1. copy to clipboard is not working
2. back button lost the icon

<img width="480" alt="Screenshot 2021-07-21 at 11 23 23" src="https://user-images.githubusercontent.com/82375995/126457306-4a693498-99a4-4b51-9d1a-3a5503ff3a52.png">

**Comment by PascalPrecht** [comment] 2021-07-21 09:45
I cannot reproduce both of these issues.

**Comment by PascalPrecht** [comment] 2021-07-21 11:22
Alright, so this one is weird..
I did manage to reproduce it and it seems to be related to the code we call right before we open the popup.

E..g when commenting these lines, the issue is gone:

https://github.com/status-im/status-desktop/blob/4dab6f92398f3e7175b6a767474e67c5e1a2bc6b/ui/app/AppLayouts/Chat/CommunityComponents/BackUpCommuntyBanner.qml#L65-L67

The modal in itself just works fine though, the exact same modal is used in another place where this issue doesn't occur. Only difference is that we don't temper with `appSettings`.

It's unclear to me however, how this is even closely related to this modal behaving like this...

Maybe @borismelnik or @alexandraB99 have an idea?

**Comment by iurimatias** [comment] 2021-08-03 01:25
@anastasiyaig I cannot reproduce this

**Comment by iurimatias** [comment] 2021-08-06 21:37
assigning this to @PascalPrecht please close if this is no longer an issue

**Comment by PascalPrecht** [comment] 2021-08-12 09:44
This is still reproducible and I still don't know what to do about it...

**Closed** 2021-08-16 18:10 UTC
Labels: bug, Communities, priority 3: low
