### ISSUE TITLE
[community chat] community member list missing

### ISSUE THREAD

**Issue by caybro** [status-im/status-desktop#12046] opened 2023-08-30 18:01 UTC
# Bug Report

Recently the member list of a community seems to be working only like 1/10 runs:

Working:
![Snímek obrazovky z 2023-08-30 19-50-40](https://github.com/status-im/status-desktop/assets/5377645/54110fe9-22a3-45ce-9d32-c6920e97c020)

Next run (and a few other runs throughout the day), not working:
![image](https://github.com/status-im/status-desktop/assets/5377645/d0620a6f-e6d9-4a2a-a045-8158323e3eb4)

## Steps to reproduce

Just start the app, navigate to the community. Doesn't matter if the app is started with that community upfront. No errors or relevant warning in console; seems like some race condition. Group chats or my own test community seems not affected at all

### Additional Information

- Status desktop version: master
- Operating System: Linux

**Comment by glitchminer** [comment] 2023-08-30 19:45
Also intermittently happening in 0.14.0 RC3

**Comment by jrainville** [comment] 2023-08-31 16:58
Have you only seen this with the Status CC community @caybro @glitchminer ?

Is so, that is expected until Iuri updates his control node.
The member list was updated to support different members per chat (because of private channel with permissions), and it needs the control node to send the new list.

I haven't told Iuri to update yet because we haven't figured out the crashes yet

**Comment by caybro** [comment] 2023-08-31 17:01
And it doesn't happen every time

**Comment by glitchminer** [comment] 2023-08-31 17:39
Same, I've seen it on other communities. I've also seen it in a couple of instances where I'm running the control node.

**Comment by MishkaRogachev** [comment] 2023-09-05 09:43
I noticed the following pattern: communities with the following channelId do not work:
```
0x03769999b26cfd88788c882b56232fa5f58735795bdd463820d127b9a23d4415d426a31ed9-fd9a-4ccb-964b-0c2765b4b91e
0x03073514d4c14a7d10ae9fc9b0f05abc904d84166a6ac80add58bf6a3542a4e50a04eb974b-d9d4-41cc-851e-47c6a71b19e8
```
And newer communities works:
```
0x0371a41ddce69526fef3ccd2e0a870f2f6aa064fbfc16cae3b0dd48c2b8789b142b2796d0a-3dd5-4e80-847b-c684689177e1
```
ChannelId for such communities are 2 chars shorter

**Comment by MishkaRogachev** [comment] 2023-09-05 20:59
small update on the investigation:
- nim and qml parts work fine
- new communities work fine
- for old communities in status-go chat.Members in all channels from `config.CommunityDescription.Chats` are already empty
- The binary blob in the members column of the chats table is not empty and looks the same for old and new communities

**Comment by MishkaRogachev** [comment] 2023-09-06 11:16
Members column is not processed correctly for old communities. (New community's channel highlighted here)
<img width="1147" alt="Screenshot 2023-09-06 at 14 03 47" src="https://github.com/status-im/status-desktop/assets/2522130/573edaa5-8eae-44e9-bfaa-58e634db3a94">

But binary blob has the same length in the database 
<img width="1446" alt="Screenshot 2023-09-06 at 14 07 35" src="https://github.com/status-im/status-desktop/assets/2522130/c9df5d8d-2663-4265-b8cb-cd75a0f10df9">

I suppose there is a technically unfeasible issue with decoding, mentioned [here](https://github.com/status-im/status-go/pull/3942/files#diff-0c22647108517d38489ae5faa65a914ade3be02ea7a7e37355a82739da9aeb69L4521)

**Comment by caybro** [comment] 2023-09-08 11:30
This is what I'm seeing in today's master:

![image](https://github.com/status-im/status-desktop/assets/5377645/c16a9f82-3fb5-47d6-aca0-d2412260c4e9)

**Comment by MishkaRogachev** [comment] 2023-09-08 12:29
> This is what I'm seeing in today's master:

Me, too. But this is a slightly different problem: something is wrong with the community description update. Еhinking about how it could be reproduced...
<img width="1325" alt="Screenshot 2023-09-08 at 16 27 11" src="https://github.com/status-im/status-desktop/assets/2522130/0645def9-ef93-4c9e-884c-0b114b45cf45">

**Comment by MishkaRogachev** [comment] 2023-09-11 09:04
I propose to close this ticket in favor of [this](https://github.com/status-im/status-desktop/issues/12114) one, as it is a different problem.

**Comment by caybro** [comment] 2023-09-11 10:45
> I propose to close this ticket in favor of [this](https://github.com/status-im/status-desktop/issues/12114) one, as it is a different problem.

Fine with me personally as long as somebody's actually working on fixing it :)

**Comment by jrainville** [comment] 2023-09-18 16:47
Closed in favour https://github.com/status-im/status-desktop/issues/12114

**Closed by jrainville** 2023-09-18 16:47 UTC
Labels: bug, messenger-team, E:Desktop Community Bugfixes MVP
