### ISSUE TITLE
[refactoring/base_01]  using ‘clear history’ deletes all channels upon reopening the app

### ISSUE THREAD

**Issue by iurimatias** [status-im/status-desktop#3988] opened 2021-11-01 14:14 UTC
1. open a bunch fo channels
2. select a channel and click 'clear history'
3. restart app

result: chats are gone, some error in status-go

**Comment by richard-ramos** [comment] 2021-11-02 18:49
Could not be reproduced

**Comment by alaibe** [comment] 2021-11-12 12:40
Closing because PR has been merged and fixed

**Closed by alaibe** 2021-11-12 12:40 UTC
Labels: bug, refactor, priority 0: blocker
