### ISSUE TITLE
Recipient of airdrop could not see token name, badge and image

### ISSUE THREAD

**Issue by glitchminer** [status-im/status-desktop#14436] opened 2024-04-16 14:30 UTC
# Bug Report

## Description

Airdropped a community token. The recipient could not see the token name, name of community or image.

![image](https://github.com/status-im/status-desktop/assets/50769329/1f571a1e-6451-40f9-b0e8-efe4e45b022b)

## Steps to reproduce

Airdrop community token
View collectibles in wallet

#### Expected behavior

Community tokens displayed in wallet with image, community name and token name.

### Additional Information

- Status desktop version: 2.28.1 RC1
- Operating System: Mac

**Comment by dlipicar** [comment] 2024-05-01 12:43
Seems to be a duplicate of https://github.com/status-im/status-desktop/issues/14437
@Cuteivist is working on it.

**Closed** 2024-05-03 12:41 UTC
Labels: bug, wallet-team
