### ISSUE TITLE
[Password settings flow]Use the account keyuid for biometrics instead of the display name + keycard identification when needed

### ISSUE THREAD

**Issue by alaibe** [status-im/status-desktop#13897] opened 2024-03-08 08:28 UTC
Form @saledjenic: User is able to create 2, 3 different Status profile (each profile is new seed phrase), but set the same display name for each of them, while pins/passwords can be different. Then when using biometrics next time, cause we're reading the entry (pin/password) based on the key which is display name a wrong one can be retrieved and user won't be able to login using biometrics because of that.

So a proposition is to use either:
- 3-words name as an entry key for biometrics (alias)
- or **keyuid**

**Comment by stefandunca** [comment] 2024-03-19 16:24
This seems like a duplicate of https://github.com/status-im/status-desktop/issues/10424 which was fixed here https://github.com/status-im/status-desktop/pull/10645. Waiting for @saledjenic to confirm this before closing it.

**Comment by saledjenic** [comment] 2024-03-19 20:42
@stefandunca yes, looking at the code it looks like that.

**Comment by stefandunca** [comment] 2024-03-19 20:50
Closing as duplicate of https://github.com/status-im/status-desktop/issues/10424 which was fixed here https://github.com/status-im/status-desktop/pull/10645

**Closed by stefandunca** 2024-03-19 20:50 UTC
Labels: wallet-team, feature
