### ISSUE TITLE
[WINDOWS Desktop release] COMMUNITY : "Create Community" button does not appears

### ISSUE THREAD

**Issue by emilieandthebee** [status-im/status-desktop#16221] opened 2024-08-30 12:33 UTC
# Bug Report

## Description

[WINDOWS Desktop release] COMMUNITY : "Create Community" button does not appears

## Steps to reproduce

1) Use Windows STATUS desktop version from https://status.app/
2) Once you are logged in, from the navigation sidebar, click "Communities"
3) On top of the content area, try ti find the "Create Community" button

#### Expected behavior
a "Create Community" button shall appear

#### Actual behavior
there is no "Create Community" button

### Additional Information
Related documentation: https://status.app/help/communities/create-a-status-community

- Status desktop version: 2.30.0 (Status) 0.179.11 (Status Go)
- Operating System: WINDOWS 11

![image](https://github.com/user-attachments/assets/8f2e539e-bcdb-48c7-a4b0-674158dbb228)

**Comment by jrainville** [comment] 2024-08-30 15:47
Hi @emilieandthebee , we voluntarily hid the "Create Community" button as the whole suite of Community features are still in Beta.

If you wish to own a community, you need to enable the feature in the Settings > Advanced > Enable Community Creation

Do note that being a Community Control Node comes with a couple responsibilities. You can check our guide here: https://status.app/help/communities/about-the-control-node-in-status-communities.

I'm going to close this issue since it's not a bug per se.

Hope it answers your question :smile:

**Closed by jrainville** 2024-08-30 15:47 UTC
Labels: bug

**Comment by emilieandthebee** [comment] 2024-08-31 07:17
Thank you! 😉
