### ISSUE TITLE
[DogFooding] Kickof a community 

### ISSUE THREAD

**Issue by apentori** [status-im/status-desktop#13300] opened 2024-01-25 15:13 UTC
# Bug Report

Part of the Doha Dog fooding.

## Description

I was kicked out of the Dogfooding community upon restarting of the application a day after synchronizing with the mobile version.

#### Expected behavior

Having access to the community in desktop and mobile.

#### Actual behavior

No access of the community in Desktop after rebooting.
 ome message where loaded. Messages send from someone in the community after restart not visible.
Message saying i was kick out. ![image](https://github.com/status-im/status-desktop/assets/124469871/dfb2621e-040e-4c45-8cb4-a8f1b60ead61)
Community not accessible in mobile.

### Additional Information

- Status desktop version: StatusIm-Desktop-240102-035700-73025c-nightly-x86_64.AppImage
- Operating System: 
```
Distributor ID:	Pop
Description:	Pop!_OS 22.04 LTS
Release:	22.04
Codename:	jammy
```

Logs after booting 
[Desktop-community-issues.log.zip](https://github.com/status-im/status-desktop/files/14053878/Desktop-community-issues.log.zip)
All logs [desktop.log](https://github.com/status-im/status-desktop/files/14053863/desktop.log)

**Comment by mprakhov** [comment] 2024-01-30 10:54
@apentori could you please provide more details:
1. Was Doha community on you mobile device?
2. Some timestamps when it is happened?

**Comment by apentori** [comment] 2024-01-31 08:48
## Timelime 
1. I joined the Community on the desktop application 24/01 - 10h40 CET
2. I downloaded the nighly build of the Android version 24/01 (couldn't see the community in Mobile app but could send message on it in Desktop app)- Afternoon 
3. Bug happened at the launch of the Desktop app (Got kicked out of the community) - 25/01 - 15:48:30

## Solution
asked to join the community again

**Comment by apentori** [comment] 2024-01-31 12:38
[geth.1.log](https://github.com/status-im/status-desktop/files/14111728/geth.1.log)
[geth.2.log](https://github.com/status-im/status-desktop/files/14111729/geth.2.log)
Status-go log files

**Comment by mprakhov** [comment] 2024-02-02 16:26
Was not able to reproduce
The problem can be divided into 2 steps
1. After the sync - on the mobile device community is absent
2. After launching the desktop app - the user was kicked

I assumed that the issue was related to backup, but on step 1 I did not observe any issues, so my both devices are synced

**Comment by mprakhov** [comment] 2024-02-05 15:48
Closing as non reproducible
Logs is not helpful as we need a debug logs

**Closed by mprakhov** 2024-02-05 15:48 UTC
Labels: bug, messenger-team
