### ISSUE TITLE
'Create new community' window dialog should be a modal dialog

### ISSUE THREAD

**Issue by jorge-campo** [status-im/status-desktop#16490] opened 2024-10-09 08:24 UTC
# Bug Report

## Description

When the user is filling out the 'Create new community' dialog, the dialog disappears if the user clicks somewhere else on the Status Desktop screen. This causes the user to lose all the settings and information entered so far.

## Steps to reproduce

1. Open Status desktop
2. Click `Communities` and, on the `Discover communities` page, click `Create community`.
3. Click `Create new`.
4. Enter some information, such as community name, description, and color.
5. Click anywhere outside the 'Create new community' dialog.

#### Expected behavior

The 'Create new community' dialog should be a modal one. It should only be possible to close the dialog by clicking on the close (x) control. Additionally, if the user enters information in any field and closes the dialog, Status desktop should as the user for confirmation. Example: 
- **Message**: "You have unsaved changes. Are you sure you want to close this window? Any information you have entered will be lost."
- **Options**: [Discard changes] [Cancel]

#### Actual behavior

The 'Create new community' dialog closes when the user clicks on any other part of the Status Desktop app, discarding the information the user has entered so far.

### Additional Information

- Status desktop version: 2.30.00
- Operating System: macOS Sequoia 15.0.1

https://github.com/user-attachments/assets/9cb37bcc-2483-41f1-8f29-0ac05b0d2dfe

**Comment by caybro** [comment] 2024-10-09 09:44
@benjthayer I think we might already have a dupe of this?

**Comment by benjthayer** [comment] 2024-10-09 12:10
> [@benjthayer](https://github.com/benjthayer) I think we might already have a dupe of this?

Yeah I think this is logged here:
https://github.com/status-im/status-desktop/issues/14902

**Comment by caybro** [comment] 2024-10-09 12:24
Dupe of https://github.com/status-im/status-desktop/issues/14902

**Closed by caybro** 2024-10-09 12:24 UTC
Labels: bug, E:Desktop Communities UX fix - Medium, core-team
