### ISSUE TITLE
Contacts: mutual contacts are reset to contact requests when recovering account (clean data folder)

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#8200] opened 2022-11-11 08:58 UTC
### Description

1. open status
2. add someone to contacts to become mutual contacts (contact request accepted)
3. make sure the contact is present in contacts tab
4. wipe out the data folder or simply re-install the app
5. recover the same account
6. check contacts

As result, all mutual contacts are now awaiting contact request confirmation
<img width="1642" alt="Screenshot 2022-11-11 at 10 36 23" src="https://user-images.githubusercontent.com/82375995/201303748-3ec5de8b-0bf0-4f3a-909d-c1b36117a97c.png">

**Status version:** master commit 42234c7d49f0478e3c80ab0a8f1e8607075cc9f6

**Comment by PascalPrecht** [comment] 2022-11-11 09:16
@anastasiyaig can you do me a favour and check if the same list of contacts also shows up under "Contacts"?

**Comment by anastasiyaig** [comment] 2022-11-11 09:17
@PascalPrecht 

<img width="1642" alt="Screenshot 2022-11-11 at 12 17 07" src="https://user-images.githubusercontent.com/82375995/201307618-9aa852a2-d2da-4ff5-9ea0-ac00f61c02f0.png">

**Comment by PascalPrecht** [comment] 2022-11-11 09:19
Thanks, I'll look into this

**Comment by PascalPrecht** [comment] 2022-11-14 09:25
I'm having trouble reproducing this.
Not saying this isn't an issue, because I know others ran into this as well.

I tried with an account that had 3 contacts.

After reimporting the account, I had one contact and no pending requests. Maybe I need to give it more time for backups to fully kick in...

**Comment by caybro** [comment] 2022-11-14 09:27
> I'm having trouble reproducing this. Not saying this isn't an issue, because I know others ran into this as well.
> 
> I tried with an account that had 3 contacts.
> 
> After reimporting the account, I had one contact and no pending requests. Maybe I need to give it more time for backups to fully kick in...

Perhaps another factor could be that the other side is using an older version

**Comment by PascalPrecht** [comment] 2022-11-14 09:31
I don't think that matters here. The contacts + contact requests are all retrieved from your local database.
So depending on under which conditions something is shown as contact request, you'll see contact requests.

AFAIK we're relying on "system tags" (like `added`, `hasAddedUs` ) to determine whether there's requests or not.
Those tags have been around for a looong time, so even if the request was sent from a 0.7.0 version, it should show up.

Anyways, will have to do further digging.

**Comment by PascalPrecht** [comment] 2022-11-17 14:38
Alright, quick update here:

I can reproduce this reliably and the problem is that, after re-importing an account, the contacts are shown as requests because they have their system tag `added = false` **although** they should be `added = true` since they have been accepted in the past.

I do some further digging, but right now I think there are two options where stuff can go sideways:

1. The requests we see as requests are indeed the requests that were sent originally. When reimporting an account, we probably receive the original contact requests from the store nodes, at which point they were indeed `added = false`. And since there are no contacts in the local database after reimporting, from the app's perspective they indeed look like new requests.
2. Another place where this **could** go wrong is when the app receives a backup from store nodes and maybe for some reason, the `added = true` flag isn't set in the backup message. I looked at the code and I'd say this is rather unlikely but still throwing it out here as an option for brainstorming

I'm gonna do further investigation to get to the bottom of this.

**Comment by PascalPrecht** [comment] 2022-11-17 15:01
Ha, guess what. Turns out both options are true.

I can see that my account first receives all the contact requests via backup, at which point they are `added = false` (which they shouldn't be), and then I receive all the actual contact requests (most likely the original ones), where they are also `added = false`.

Next I'm going to look into why the backup doesn't have the `added = true` flags, even though contacts have been accepted in the past.

**Comment by PascalPrecht** [comment] 2022-11-21 09:58
> I can see that my account first receives all the contact requests via backup, at which point they are added = false (which they shouldn't be),

Okay so the backed up data I receive has contacts with `added = false` because this was in fact the only backup that happened. It seems we're only backing up data every 8 hours (as opposed to 2 min), so these are likely backup signals that are quite old. @cammellos I'm specifically referring to this:

```golang
				if uint64(now) <= backupIntervalSeconds+lastBackup {
					m.logger.Debug("not backing up")
					continue
				}
```
While the check happens every 2 mins, we have a 8 hours (`backupIntervalSeonds == 28800) tolerance. I assume this is by design?

How do you feel about performing a backup during specific actions as well (e.g. accepting contacts, joining communities)?
Otherwise users will run into scenarios where they re-import their account and receive backups with data that's outdated.

> and then I receive all the actual contact requests (most likely the original ones), where they are also added = false.

Few days have past since I've looked into this, now I can't reproduce this anymore. Need to check why, but I think the original contact requests are now no longer considered relevant.

**Comment by PascalPrecht** [comment] 2022-11-21 10:06
@anastasiyaig I can't seem to reproduce this anymore.
Would you like to give this another spin?

**Comment by cammellos** [comment] 2022-11-21 10:06
> While the check happens every 2 mins, we have a 8 hours (backupIntervalSeconds == 28800 seconds) tolerance. I assume this is by design?

Correct, backup are expensive in terms of storage, so we don't want to make them too often.

> How do you feel about performing a backup during specific actions as well (e.g. accepting contacts, joining communities)?
Otherwise users will run into scenarios where they re-import their account and receive backups with data that's outdated.

We could of course, though I think we need to think about the importance of backup, since I think we are overestimating how useful and often it's used.

Backup is only useful when you restore your account and you have no other devices. 
This should be rare (we do it ourselves because we are devs, but users should not do that very often).

If you have another device, the user should be pairing up their devices before entering the seed phrase, in which case backup is not used/useful. 
So not sure how much is worth polishing a re-install flow, which for most users should very rarely happen (I haven't re-installed my status app in roughly 2 years now)

**Comment by PascalPrecht** [comment] 2022-11-21 10:10
@cammellos thank you for confirming. I think your reasoning is fair.

> @anastasiyaig I can't seem to reproduce this anymore.

@anastasiyaig false alarm, I can still reproduce this. Just took some time for the request to come through.

**Comment by PascalPrecht** [comment] 2022-11-21 10:18
@cammellos coming back to the other issue here, how do we want to handle the following case:

1. User A receives contact request from User B and accepts it
2. User A wipes out their Status folder and re-imports their account (no device syncing has happened)
3. After re-importing, User A receives the contact request from 1) via store nodes. Because the database doesn't have any contacts yet, this looks like a new contact request, even though this was accepted before

The result is the issue @anastasiyaig has described here in the og issue. Plenty of contacts that she's already accepted now show up as contact requests.

My first guess was to rely on backups, they seem to be processed first anyways. But since we can't guarantee the backup we get is indeed up-to-date (due to the 8 hour tolerance), this isn't really an option.

You mentioned:

>  the user should be pairing up their devices before entering the seed phrase

Maybe I'm missing something here, but isn't pairing devices only available **after** the seed phrase was entered? You gotta know what account you're dealing with after all...

**Comment by anastasiyaig** [comment] 2022-11-21 10:23
We cant pair devices until we log in
Also syncing devices to have contacts to be recovered / stored correctly - this requirement is smth i never heard about

**Comment by PascalPrecht** [comment] 2022-11-21 10:34
> Also syncing devices to have contacts to be recovered / stored correctly - this requirement is smth i never heard about

I don't think this is intended to be honest. This all seems to be a result of your backup not being up-to-date.
So if you don't happen to re-import your account every < 8 hours, it looks like you won't run into this issue.

**Comment by cammellos** [comment] 2022-11-21 10:35
> Maybe I'm missing something here, but isn't pairing devices only available after the seed phrase was entered? You gotta know what account you're dealing with after all...

It is, but that's what @Samyoul & @siddarthkay are working on, and once that's ready (we are getting closer), that should be the way to restore an account on a different device.

> After re-importing, User A receives the contact request from 1) via store nodes. Because the database doesn't have any contacts yet, this looks like a new contact request, even though this was accepted before

To some extend this is inevitable, you can minimize the possibility of that happening by reducing the time between backups, as you pointed out.

My 2p, is that this is fine, what you are describing is somehow an edge case, and this kind of degradation of UX is acceptable to me. 
If a user has reinstalled the app, they will not have to re-accept the contact requests sent over that were not backed up, I'd say that's acceptable, and likely there's other flows that requires more polishing/bugfixing when it comes to backup/syncing.

**Comment by PascalPrecht** [comment] 2022-11-21 10:44
@anastasiyaig as per @cammellos statement, I'm going to close this. Let me know if you think this needs further discussion!

**Closed by PascalPrecht** 2022-11-21 10:44 UTC
Labels: bug, priority 1: high, E:Wakuv2, E:Bugfixes
