### ISSUE TITLE
Balance doesn't display owned assets correctly when using custom tokens

### ISSUE THREAD

**Issue by piskel** [status-im/status-desktop#2037] opened 2021-03-13 15:54 UTC
Following the issue #2036, now when using the wallet with a custom token the assets' quantity isn't displayed at all.
![image](https://user-images.githubusercontent.com/10447278/111035827-7a419080-841c-11eb-88a5-13716ebd623e.png)

But unchecking the custom token from "Manage  Assets" menu fixes the numbers.
![image](https://user-images.githubusercontent.com/10447278/111035863-a6f5a800-841c-11eb-94fd-7f029c14e4f4.png)

**Comment by jrainville** [comment] 2021-03-22 20:13
I can't reproduce this issue, but testing it out made me discover other issues, so there is that

**Comment by jrainville** [comment] 2021-03-26 14:27
I'm going to close since I still can't reproduce after a couple of commits have landed in master including some fixes to the wallet assets

**Closed by jrainville** 2021-03-26 14:27 UTC
