### ISSUE TITLE
Seed phrase suggestion combobox selects the wrong word

### ISSUE THREAD

**Issue by MishkaRogachev** [status-im/status-desktop#12371] opened 2023-10-06 14:25 UTC
# Bug Report

## Description

https://github.com/status-im/status-desktop/assets/2522130/0c026b88-1672-49ec-81fc-4c8f229d3947

## Steps to reproduce

- Restore account with seed phrase
- Try to pick a word with `enter` press 

#### Expected behavior

Highlighted word is selected

#### Actual behavior

A word after highlighted one is selected

### Additional Information

- Status desktop version: latest master
- Operating System: Mac OS

**Comment by anastasiyaig** [comment] 2023-10-09 10:10
these things with keyboard actions are annoying :/

**Comment by caybro** [comment] 2023-10-12 11:16
Actually is a dupe of https://github.com/status-im/status-desktop/issues/10708

**Closed by caybro** 2023-10-12 11:16 UTC
Labels: bug, ui-team, E:Onboarding & Login
