### ISSUE TITLE
When a user blocks another user, the blocked user should also be kicked from all ad-hoc group chats the blocking user owns, and banned from all Communities the blocking user owns

### ISSUE THREAD

**Issue by benjthayer** [status-im/status-desktop#8975] opened 2023-01-05 17:04 UTC
**Background**
Design have done a body of work to make the flows and implications around Blocking a user more comprehensive. Through this body of work it was confirmed with @John-44 that when a user blocks another user, the blocked user should also be kicked from all ad-hoc group chats owned by the blocking user and banned from all Communities owned by the blocking user.

This should be clarified to the blocking user at the point at which they select to block a user via the following confirm block dialog which contains a checkbox which is selected and disabled stating:

_Ban [Display name] from all current and future Group Chats and Communities that I own_

<img width="1440" alt="Confirm block dialog" src="https://user-images.githubusercontent.com/110033914/210838411-2229e57b-c6a4-400a-8191-62ceebbd005d.png">

**Figma:**
https://www.figma.com/file/ibJOTPlNtIxESwS96vJb06/%F0%9F%91%A4-Profile-%7C-Desktop?node-id=1503%3A14889&t=33ycAeE4YzwiKHlD-1

**Comment by iurimatias** [comment] 2023-01-05 18:33
@benjthayer are you sure about this? in particualr groups chats aren't supose to have a single admin like before. It also doesn't make sense to me that blocking a user wou ld kick them from communities the user owns, that might not be their goal they might simply not want to chat with that person anymore cc: @John-44

**Comment by John-44** [comment] 2023-01-05 19:34
@iurimatias let's discuss when I'm back next week.  The challenge we are facing is that when UserA blocks UserB, UserB becomes totally invisible in all contexts to UserA.  This is a problem if (for example) UserA is also the owner of a community the UserB is a member of, because once UserA has blocked UserB, UserA will no longer be able moderate UserB's messages in the community, or even see UserB in their community.  Similar issue with ad-hoc group chats.  Anyhow, let's talk through this next week.

**Comment by iurimatias** [comment] 2024-03-28 13:58
closed as duplicate of https://github.com/status-im/status-desktop/issues/8805

**Closed by iurimatias** 2024-03-28 13:58 UTC
Labels: to analyze, messenger-team, Design-QA, E:Desktop Chat Messages & Chat Features, E:Desktop Messaging UX fix - Low
