### ISSUE TITLE
Wallet: relation between multi-transactions and their sub-transactions might be broken

### ISSUE THREAD

**Issue by stefandunca** [status-im/status-desktop#11404] opened 2023-07-04 14:07 UTC
Found out after [allowing empty multi-transactions](https://github.com/status-im/status-go/pull/3712) (that have no sub-transaction) in a filter that I have many which are also duplicates of transactions fetched from `transfers`. 

This task is to investigate and fix this issue.

At a glance, the previous implementation was refactored: https://github.com/status-im/status-go/blob/8184ae62ed62b570a7723cc5766db825478b1ac0/services/wallet/transfer/commands.go#L485C38-L485C38
Check first if it is still doing its job.

@dlipicar mentioned that this might also be related to the hash of a transfer is our internal so that might be a problem for non native transactions

**Comment by stefandunca** [comment] 2023-07-14 14:24
After looking in the wrong direction found out that [`propagatePendingMultiTx`](https://github.com/status-im/status-go/blob/64f77065674584b57c934e6ea90b47e733d53ebd/services/wallet/transfer/commands.go#L452C39-L452C39) is called after the [`DeletePending`](https://github.com/status-im/status-go/blob/016e0552f9eb0714d1fb51e4c8533b7a599e442d/services/wallet/transfer/transaction.go#L291). Therefore the corresponding pending transaction is never found. Hence for every send `multi_transactions` entry, there is at least one dangling unmatched transaction in `transfers`.

The latest change https://github.com/status-im/status-go/pull/3704 doesn't fix this, and following comments in https://github.com/status-im/status-go/pull/3704#discussion_r1262835183 it seems this will take a while.

Therefore I assign this issue to you @IvanBelyakoff, to link the following work to it.

**Comment by anastasiyaig** [comment] 2023-08-02 10:25
https://github.com/status-im/status-desktop/issues/11754 this is related as well (@stefandunca please close it if that is a duplicate of your task)

**Closed** 2023-08-02 14:19 UTC
Labels: bug, wallet-team, E:Desktop New Activity
