### ISSUE TITLE
macOS Big Sur - App crashes on startup

### ISSUE THREAD

**Issue by siphiuel** [status-im/status-desktop#8194] opened 2022-11-10 11:00 UTC
# Bug Report

## Description

Application crashes immediately upon startup.

## Steps to reproduce

I tried both the 0.7.0 release and the build from https://ci.infra.status.im/job/status-desktop/job/master/567/.
Verified that `~/Library/Application Support/Status` is empty.
After launching the app, i get `Status cannot be opened`.
The report contains this:
```
Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    DYLD, [0x4] Symbol missing

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Symbol not found: __ZTTNSt3__114basic_ifstreamIcNS_11char_traitsIcEEEE
  Referenced from: /Applications/Status.app/Contents/MacOS/nim_status_client
  Expected in: /usr/lib/libc++.1.dylib
 in /Applications/Status.app/Contents/MacOS/nim_status_client
```

#### Expected behavior
Application launches and i see that initial onboarding screen.

#### Actual behavior
Crash.

### Additional Information

- Status desktop version: either 0.7.0 or nightly build from https://ci.infra.status.im/job/status-desktop/job/master/567/
- Operating System: macOS Big Sur 11.7

**Comment by caybro** [comment] 2022-11-10 12:40
Dupe of https://github.com/status-im/status-desktop/issues/8182; pls update your macOS

**Closed by caybro** 2022-11-10 12:40 UTC
Labels: bug

**Comment by siphiuel** [comment] 2022-11-10 12:47
@caybro thanks, and sorry for not noticing the issue previously reported. I cannot update my macOS as my laptop cannot run newer versions. Will it work if i build from source myself?

**Comment by caybro** [comment] 2022-11-10 12:49
> @caybro thanks, and sorry for not noticing the issue previously reported. I cannot update my macOS as my laptop cannot run newer versions. 

I didn't mean updating to a newer/major version; latest Big Sur should do fine

> Will it work if i build from source myself?

Yes, it should

**Comment by siphiuel** [comment] 2022-11-10 13:47
I've updated to Big Sur 11.7.1 (the latest), but it still crashes.
