### ISSUE TITLE
Search freezes the app

### ISSUE THREAD

**Issue by osmaczko** [status-im/status-desktop#8777] opened 2022-12-14 09:29 UTC
# Bug Report

## Description

If you change the string in app search dialog many times the app will freeze. It will eventually unfreeze itself but it takes a while.

https://user-images.githubusercontent.com/33099791/207557021-5727647f-6879-4abc-8425-11cc353120b9.mp4

### Additional Information

- Status desktop version: v0.8.1-2356ac
- Operating System: Ubuntu 22.04

**Comment by 0x-r4bbit** [comment] 2022-12-21 10:40
@osmaczko I've tired this in the latest 0.8.1 release as well as latest master and I can't reproduce this one.
Are you still able to reproduce this?

**Comment by anastasiyaig** [comment] 2022-12-21 12:34
i gave it a try in latest master, cant reproduce :(

**Comment by 0x-r4bbit** [comment] 2022-12-21 12:35
@osmaczko couldn't reproduce it either anymore. So I'll close this for now.
Feelf ree to reopen if this happens again.

**Closed by 0x-r4bbit** 2022-12-21 12:35 UTC
Labels: bug, Chat, priority 1: high, 0.8.1
