### ISSUE TITLE
The text 'Update to latest version to see a nice image here!' appears with a received picture in 1-1 chat

### ISSUE THREAD

**Issue by elina2015** [status-im/status-desktop#5934] opened 2022-05-31 04:54 UTC
# Bug Report

## Steps to reproduce
1. In 1-1 chat, receive a picture from the mobile version of the app

#### Expected behavior
The text 'Update to latest version to see a nice image here!' is NOT shown above the picture

#### Actual behavior
The text 'Update to latest version to see a nice image here!' is shown above the picture
### Additional Information
<img width="1105" alt="image" src="https://user-images.githubusercontent.com/14942081/171095268-c608a941-fbed-4e8d-9ed9-983be16077ac.png">
Status desktop version: [Build #2137 (May 30, 2022, 9:02:25 AM)](https://ci.status.im/job/status-desktop/job/branches/job/macos/job/master/2137/)
Operating System: macOS Monterey 12.3 Beta (21E5227a) M1

**Comment by iurimatias** [comment] 2022-06-03 18:11
this was previously fixed in https://github.com/status-im/status-desktop/pull/5780

**Comment by Hbouaz** [comment] 2022-06-20 11:30
can this be closed?

**Comment by alaibe** [comment] 2022-06-20 11:34
@Hbouaz not yet, the issue is still open for when the message is sent via mobile

**Closed** 2022-06-21 15:35 UTC
Labels: bug, ui, Chat, priority 2: medium, E:Bugfixes, S:2
