### ISSUE TITLE
While Sign out, the loader is shown infinitely

### ISSUE THREAD

**Issue by elina2015** [status-im/status-desktop#8533] opened 2022-12-01 07:25 UTC
# Bug Report

## Steps to reproduce
1. Log in and open any community or chat
2. click Settings - Sign Out and Quit

#### Expected behavior
The user is signed out and the app is closed
#### Actual behavior
While Sign out, the loader is shown infinitely
### Additional Information
Logs are here:
[report.txt](https://github.com/status-im/status-desktop/files/10130172/report.txt)

- Status desktop version: https://github.com/status-im/status-desktop/pull/8449
- Operating System: macOS Monterey

**Comment by caybro** [comment] 2022-12-01 08:56
Looks like a duplicate of https://github.com/status-im/status-desktop/issues/8401

**Comment by jrainville** [comment] 2022-12-01 14:39
Seems like the PR linked is on top of the fix, so maybe it's something else :thinking:

**Comment by caybro** [comment] 2022-12-01 14:41
> Seems like the PR linked is on top of the fix, so maybe it's something else thinking

Are you sure it's really on top? :) GitHub's PRs don't work that way

**Comment by jrainville** [comment] 2022-12-01 14:48
I checked the commit history and the PR's commit was on top of latest-ish master. I now see that Michal rebased 5 hours ago, so it's more than likely that Elina tested an "older" version.
@elina2015 if you have time, can you check if you experience the same again on his PR or on master? Thank.

**Comment by iurimatias** [comment] 2023-01-09 17:20
duplicate of

**Closed by iurimatias** 2023-01-09 17:20 UTC
Labels: bug, Settings
