### ISSUE TITLE
Can't see user statuses when viewing profile

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#2744] opened 2021-06-22 08:45 UTC
**On mobile:** can open someone's profile and see its statuses

![IMG_3866](https://user-images.githubusercontent.com/82375995/122893402-fbc78980-d34e-11eb-8404-305bd2dee40c.jpg)

![IMG_3867](https://user-images.githubusercontent.com/82375995/122893440-01bd6a80-d34f-11eb-8ff0-dbb2aea668e1.jpg)

**On desktop:**

<img width="1012" alt="Screenshot 2021-06-22 at 11 43 16" src="https://user-images.githubusercontent.com/82375995/122893505-10a41d00-d34f-11eb-88aa-41b5321a6969.png">

@simonricoo @errorists should it be any design input required there? I was looking into https://www.figma.com/file/Zz6KMBxwrB0l2NPgsjnPjq/%F0%9F%91%A4-Profile%E2%8E%9CDesktop?node-id=1968%3A13644

**Comment by iurimatias** [comment] 2021-07-18 21:07
duplicate of #2408

**Closed by iurimatias** 2021-07-18 21:07 UTC
Labels: Design, Timelines, feature, ui
