### ISSUE TITLE
Syncing: syncing with previously used seed phrase does not work

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#12550] opened 2023-10-25 14:06 UTC
### Description

<img width="1920" alt="Screenshot 2023-10-25 at 16 59 21" src="https://github.com/status-im/status-desktop/assets/82375995/46c0285f-f933-4f94-ba1a-83d7e05cd48d">

```
ERR 2023-10-25 16:59:12.533+03:00 login error                                topics="app-controller" tid=14927950 file=module.nim:444 methodName=onNodeLogin errDesription="cannot retrieve a valid key for a given account: no key for given address or file"
```

1. get a seed phrase
2. open 1 app of status
3. click I am new to status - import seed phrase
4. login
5. open syncing section and create a sync code
6. open 2 app instance
7. click I already use status - enter sync code
8. wait until login button appears
9. click login button

**Comment by anastasiyaig** [comment] 2023-10-25 14:09
@igor-sirotin can u please check on that? It was definitely working before.
@jrainville can we have it for 0.15? seems recent regression (or a feature change, dunno)

**Comment by jrainville** [comment] 2023-10-25 14:13
Yeah this is a bad regression. I know it worked a few weeks ago because I added 1-1 and group chats. I'll see if Igor has time, otherwise I'll look into it

**Comment by jrainville** [comment] 2023-10-25 20:06
I still haven't figured out the reason, but it seems like it's some kind of race condition or time based.

Basically, if you wait a couple of seconds before pressing Login, it will work, but if you press immediately, it fails because the accounts cache is empty.

I need to dig more. It's not code I'm familiar with, but clearly something is getting loaded that we need to wait for.

Also, closing the app on the failure and reopening works, so saving the DB does work either way.

**Comment by jrainville** [comment] 2023-10-26 15:05
Ok I found the reason. We need to wait for the `geth_backend` to be initialized, otherwise the `accountManager` is nil and we try to login with an empty account cache.

I'll try to make it so that we only send the signal back to desktop when the backend is initialized.

**Closed** 2023-10-27 18:49 UTC
Labels: bug, messenger-team, E:Desktop Messenger Syncing
