### ISSUE TITLE
Segmentation fault (Linux)

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#12880] opened 2023-11-27 13:45 UTC
### Description

```
Traceback (most recent call last)
/home/anastasiya/status-desktop/src/nim_status_client.nim(208) nim_status_client
/home/anastasiya/status-desktop/src/nim_status_client.nim(181) mainProc
/home/anastasiya/status-desktop/src/app/boot/app_controller.nim(297) delete
/home/anastasiya/status-desktop/src/app/modules/startup/io_interface.nim(19) delete
/home/anastasiya/status-desktop/src/app/modules/startup/module.nim(87) delete
/home/anastasiya/status-desktop/vendor/nimqml/src/nimqml/private/qqmlapplicationengine.nim(29) setRootContextProperty
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
make: *** [Makefile:815: run-linux] Segmentation fault (core dumped)
```

1. build the app on linux (latest master)
2. close the app by clicking cross button
3. check the console

**Comment by anastasiyaig** [comment] 2023-11-27 13:47
@jrainville can we have someone look into that?
@jakubgs found a lot of errors on ci leading to this problem

**Comment by jakubgs** [comment] 2023-11-27 14:12
I'm not 100% sure if that exact failure isn't specific to this PR:

* https://github.com/status-im/status-desktop/pull/12856

**Comment by mprakhov** [comment] 2023-11-27 14:34
in https://github.com/status-im/status-desktop/pull/12856 crash was on a startup and it was caused by file movement in the master (started to crash after the rebase). Not related to the close crash

**Comment by anastasiyaig** [comment] 2023-11-27 14:36
@mprakhov good, i was just saying how i was able to repro the problem.

**Comment by jrainville** [comment] 2023-11-27 17:21
I tried bissecting to find where the issue was introduced, but it seems like we've had that problem since forever :weary: 
I tried a commit from February 2023 and it still had a crash on close. The error message was a bit different, but it's still crashing with `SIGSEGV`

I'll try to find the root in the master code.

**Comment by jrainville** [comment] 2023-11-27 18:24
I closed by mistake

**Closed** 2023-11-28 11:41 UTC
Labels: bug, messenger-team, E:Desktop Bugfixes 0.15
