### ISSUE TITLE
[base_bc] switching channels show same messages

### ISSUE THREAD

**Issue by iurimatias** [status-im/status-desktop#4418] opened 2022-01-11 22:16 UTC
note: possibly fixed by https://github.com/status-im/status-desktop/pull/4380

https://user-images.githubusercontent.com/176720/149029887-ca5341a4-8673-4990-8a85-6d09207d8092.mov

**Comment by anastasiyaig** [comment] 2022-01-12 12:10
i cant reproduce it now at commit 71110d040d66cbec846d6da012b9ee824d2f0fdb

**Comment by saledjenic** [comment] 2022-01-12 12:35
This should be fixed in commit `b5435dfa3052bae76405c36dea820cfb46a957ed` (issue was in `controller.nim` file of the message module). After that I wasn't able to reproduce this.

**Comment by richard-ramos** [comment] 2022-01-17 13:43
I can confirm that this issue cannot be reproduced in latest base_bc

**Comment by anastasiyaig** [comment] 2022-01-17 13:44
confirming that as well, it is fixed in base_bc

**Closed** 2022-01-17 13:48 UTC
Labels: bug, refactor, branch: base_bc
