### ISSUE TITLE
[StatusChatInput] Some images do not get pasted in the chat input

### ISSUE THREAD

**Issue by jrainville** [status-im/status-desktop#10926] opened 2023-06-05 13:30 UTC
# Bug Report

## Description

Some images do no show in the Status Input when pasted and are not submitted after pressing enter either.

## Steps to reproduce

1. Open the image in this link https://media.discordapp.net/attachments/927668982964715521/1115199506624024617/IMG_20230605_104339.jpg?width=1556&height=779
(if the link is dead, use the image below)
2. Right click on it and select copy image
3. Go in a community and hit CTRL+V

Result: an empty image appears. You can hover and see the X, but it doesn't show the image itself. Submitting the message just closes the input and doesn't send anything

#### Expected behavior

Image is shown when pasted and can get sent as a message

#### Actual behavior

No image is shown, except the empty image zone

### Additional Information

```
Warning: qrc:/imports/shared/status/StatusChatInputImageArea.qml:24:13: QML Image: Error decoding: data:image/jpeg;base64,: Unsupported image format (qrc:/imports/shared/status/StatusChatInputImageArea.qml:24, )
```

- Status desktop version: 0.12.0
- Operating System: Ubuntu 20

![image](https://github.com/status-im/status-desktop/assets/11926403/25b240ac-5715-429c-91e9-cae60210c705)

**Comment by jrainville** [comment] 2023-06-05 19:58
The issue is only with pasting.

Drag and drop works.

I printed the format (`img.format()`) and it returns `0`, which is `QImage::Format_Invalid`. 

However, the same image can be drag and dropped in the app, or pasted in Discord, so something is weird here.

I'll continue investigating

**Comment by jrainville** [comment] 2023-06-05 20:00
I also found that if I download the image, open it in my Image Viewer, then copying it and pasting it works fine. 

If I open it in the browser and do the same, it doesn't work.

**Comment by caybro** [comment] 2023-06-06 17:22
What can I say.... I can't reproduce at all:

![image](https://github.com/status-im/status-desktop/assets/5377645/03a7958a-2c48-481d-af38-0f218d74eda0)


Worked 10/10

Just FYI:
- status master (09815de915ef28436175fa2487a9e054d52e0018)
- Linux
- Qt version 5.15.9

**Comment by caybro** [comment] 2023-06-06 17:32
OK, so copy&paste from Firefox worked fine as well but when I tried DND:

```
Fatal: Object 0x111cd300 destroyed while one of its QML signal handlers is in progress.
Most likely the object was deleted synchronously (use QObject::deleteLater() instead), or the application is running a nested event loop.
This behavior is NOT supported!
qrc:/imports/shared/status/StatusChatInput.qml:953: function() { [native code] } (:0, )
Traceback (most recent call last)
/home/ltinkl/git/status/status-desktop/src/nim_status_client.nim(193) nim_status_client
/home/ltinkl/git/status/status-desktop/src/nim_status_client.nim(166) mainProc
/home/ltinkl/git/status/status-desktop/src/app/boot/app_controller.nim(287) delete
/home/ltinkl/git/status/status-desktop/src/app/global/global_singleton.nim(75) delete
/home/ltinkl/git/status/status-desktop/vendor/nimqml/src/nimqml/private/qqmlapplicationengine.nim(40) delete
SIGABRT: Abnormal termination.
make: *** [Makefile:753: run-linux] Neúspěšně ukončen (SIGABRT) (obraz paměti uložen)
19:31:13: make exited with code 2
```

Ok, we have a problem here :)

**Comment by caybro** [comment] 2023-06-06 17:34
![image](https://github.com/status-im/status-desktop/assets/5377645/219f405a-ecac-45db-b9ff-468220f3e860)

**Comment by jrainville** [comment] 2023-06-06 17:35
> but when I tried DND:

For me DnD always worked :thinking: 

The stack trace is not helpful either.

Is the crash reproducible?

**Comment by caybro** [comment] 2023-06-06 17:36
Yeah the DND crash from Firefox is 100% reproducible on my side but doesn't happen at all when dragging from Chrome... gremlins

**Comment by caybro** [comment] 2023-06-06 19:38
OK some progress: the Firefox crash happens inside the `StatusChatImageSizeValidator`; if disabled it still doesn't work because the URL check fails `StatusChatImageExtensionValidator` due to the URL containing a `query`, like: 

```
Warning: !!! isValidImageUrl QUrl("https://media.discordapp.net/attachments/927668982964715521/1115199506624024617/IMG_20230605_104339.jpg?width=1556&height=779")
```

**Comment by caybro** [comment] 2023-06-06 19:45
The crash happens in Utils.qml, `function isFilesizeValid(img)` in:
```js
let size = parseInt(globalUtils.getFileSize(img))
```
so I suspect inside some NIM code

**Comment by caybro** [comment] 2023-06-06 19:51
...which doesn't make sense as it's either a binary blob, and then we have already a check in place, or it's a URL that can't be opened (it's not a local file)

**Comment by caybro** [comment] 2023-06-06 20:21
The image can't still be sent though because of:

```
DBG 2023-06-06 22:20:50.419+02:00 NewBE_callPrivateRPC                       topics="rpc" tid=203958 file=core.nim:27 rpc_method=wakuext_sendChatMessages
ERR 2023-06-06 22:20:50.771+02:00 rpc response error                         topics="rpc" tid=203958 file=core.nim:36 err="\nstatus-go error [methodName:wakuext_sendChatMessages, code:-32000, message:can\'t post on chat ]\n"
ERR 2023-06-06 22:20:50.771+02:00 error doing rpc request                    topics="rpc" tid=203958 file=core.nim:40 methodName=wakuext_sendChatMessages exception="\nstatus-go error [methodName:wakuext_sendChatMessages, code:-32000, message:can\'t post on chat ]\n"
ERR 2023-06-06 22:20:50.771+02:00 Error sending images                       topics="chat-service" tid=203958 file=service.nim:503 msg="\nstatus-go error [methodName:wakuext_sendChatMessages, code:-32000, message:can\'t post on chat ]\n"
```

**Comment by caybro** [comment] 2023-06-06 20:34
@jrainville ok so I was finally able to reproduce, albeit with DND only (copy/paste from clipboard of this image still works):

The error in console:
```
Warning: QImage::scaled: Image is a null image (:0, )
DBG 2023-06-06 22:31:30.704+02:00 NewBE_callPrivateRPC                       topics="rpc" tid=207156 file=core.nim:27 rpc_method=wakuext_sendChatMessages
ERR 2023-06-06 22:31:30.706+02:00 rpc response error                         topics="rpc" tid=207156 file=core.nim:36 err="\nstatus-go error [methodName:wakuext_sendChatMessages, code:-32000, message:EOF ]\n"
ERR 2023-06-06 22:31:30.706+02:00 error doing rpc request                    topics="rpc" tid=207156 file=core.nim:40 methodName=wakuext_sendChatMessages exception="\nstatus-go error [methodName:wakuext_sendChatMessages, code:-32000, message:EOF ]\n"
ERR 2023-06-06 22:31:30.706+02:00 Error sending images                       topics="chat-service" tid=207156 file=service.nim:503 msg="\nstatus-go error [methodName:wakuext_sendChatMessages, code:-32000, message:EOF ]\n"
```

Does this ring a bell?

![image](https://github.com/status-im/status-desktop/assets/5377645/ab325ed6-3dc7-4901-8f84-3a8b7bf5ea06)

**Comment by caybro** [comment] 2023-06-06 20:35
Esp. the part with `Warning: QImage::scaled: Image is a null image (:0, )` leads me to think we screw the image when scaling it

**Comment by jrainville** [comment] 2023-06-06 20:41
> Does this ring a bell?

The `Image is a null image` error is similar to what I had, but my repro step doesn't even reach the scaling.

The image in the clipboard itself is considered Null, even though it does understand that it is an image.

Anyway, this particular issue seems really annoying to fix. I moved it to 0.14, so we can retry later.

The issue you have seems to be different, so it might be worth to add to the backlog too. Probably to 0.14 for now as well.

**Comment by caybro** [comment] 2023-06-06 20:46
> > Does this ring a bell?
> 
> The `Image is a null image` error is similar to what I had, but my repro step doesn't even reach the scaling.

I fixed some things locally (which I'll post in a PR anyway, fixes the crashes I had) so I got further

> The image in the clipboard itself is considered Null, even though it does understand that it is an image.

The image in the clipboard is fine, I checked. `Warning: QImage::scaled` it gets somehow destroyed when we _scale_ it

**Comment by jrainville** [comment] 2023-06-06 21:01
> The image in the clipboard is fine, I checked. Warning: QImage::scaled it gets somehow destroyed when we scale it

Yeah, it seems like we don't have the same issue.

Here is what happens for me:

[pasting.webm](https://github.com/status-im/status-desktop/assets/11926403/7b91ebb1-f125-4da0-8b01-8c403063de2b)


You can see that it fails in the `imageBase64` function, which is before any scaling happens.

If I take the same image and open it in the image viewer instead, the same flow works and the format is `4` instead of `0`.

**Comment by caybro** [comment] 2023-06-06 21:49
@jrainville what's the browser you copy from? Can you try to do the same with either Chrome or Firefox?

**Comment by jrainville** [comment] 2023-06-06 22:05
I use Brave. I'll try tomorrow with Firefox

**Comment by jrainville** [comment] 2023-06-07 18:05
Copying from Firefox works correctly, contrarily to Brave.

I'm gonna try your PR

**Comment by caybro** [comment] 2023-06-07 22:37
@jrainville I'd call this specific problem a Qt bug? Copying and DND of this image works for me in every possible web browser I tried (Chrome, Firefox, Brave, Epiphany)

**Comment by jrainville** [comment] 2023-06-08 15:31
Reopened because the issue is not fully fixed with it. It looks like this is fixed with version 5.15.8 of Qt, but our linux host still has 5.15.2.

So fixing https://github.com/status-im/status-desktop/issues/9350 would probably fix it

**Comment by iurimatias** [comment] 2024-02-12 17:54
moved to 2.29 due to lack of space in this milestone

**Comment by igor-sirotin** [comment] 2024-02-23 15:05
I have a screenshot png file. 
<img width="997" alt="image" src="https://github.com/status-im/status-desktop/assets/25482501/a3b1736c-815d-4ebd-969a-2ae811130211">


When I drag&drop the file to Status it's sent just fine.

<img width="505" alt="image" src="https://github.com/status-im/status-desktop/assets/25482501/13383d64-5c75-4fca-9c8d-a65a44df715c">

But when open Finder, select the file and click `Cmd+V` and paste it to Status, I get this (which is an Apple icon for images)

<img width="713" alt="image" src="https://github.com/status-im/status-desktop/assets/25482501/52cb7235-e394-499b-b204-0c7f1b214a0e">

**Comment by iurimatias** [comment] 2024-08-13 12:26
closing as this will be part of a wider rethink of this feature

**Closed by iurimatias** 2024-08-13 12:26 UTC
Labels: bug, backend-team, Desktop ChatInput Markdown/Refactor, E:D Msg Bugfixes MX
