### ISSUE TITLE
Support formatting code in the text input and messages

### ISSUE THREAD

**Issue by iurimatias** [status-im/status-desktop#5974] opened 2022-06-02 14:54 UTC
### Description

see figma: https://www.figma.com/file/17fc13UBFvInrLgNUKJJg5/Kuba%E2%8E%9CDesktop?node-id=207%3A44228

- This should support markdown as in:

\`\`\`js
a = 3
\`\`\`

```js
a = 3
```

![Screen Shot 2022-06-02 at 10 53 22 AM](https://user-images.githubusercontent.com/176720/171658121-897539d4-46de-47d2-9919-4d2146798041.png)

![Screen Shot 2022-06-02 at 10 53 28 AM](https://user-images.githubusercontent.com/176720/171658134-fe93a779-1115-4be6-a687-a2e8ef15b2cd.png)

Mobile reference: https://www.figma.com/file/PPWkgOYlZZDxZv5SDGsZVV/Posts-%26-Attachments?node-id=2230%3A116813
Desktop: https://www.figma.com/file/Mr3rqxxgKJ2zMQ06UAKiWL/💬-Chat⎜Desktop?node-id=572%3A4517

**Comment by caybro** [comment] 2022-08-29 11:12
https://api.kde.org/frameworks/syntax-highlighting/html/index.html would be a good option... but it requires Qt 5.15 :(

**Comment by alexandraB99** [comment] 2022-10-03 11:00
@iurimatias this sounds like a duplicate of https://github.com/status-im/status-desktop/issues/7565

**Comment by alexandraB99** [comment] 2022-10-03 11:00
@iurimatias this sounds like a duplicate of https://github.com/status-im/status-desktop/issues/7565

**Comment by PascalPrecht** [comment] 2022-11-16 09:55
Closing this as a dupe of #7565

**Closed by PascalPrecht** 2022-11-16 09:55 UTC
Labels: ui, Chat, feature, priority F2: important, S:5
