### ISSUE TITLE
Fetch messages duplicate indicator in community with wrong dates

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#4812] opened 2022-02-15 10:51 UTC
### Description

I do have data folder that i keep for a while, and i have created community a while ago. I opened this community today and noticed there are weird `Fetch messages` labels with wrong dates

<img width="1523" alt="Screenshot 2022-02-15 at 13 48 25" src="https://user-images.githubusercontent.com/82375995/154047129-25956f0d-d77d-4bdc-821f-b6d9a9728bb4.png">

**Comment by iurimatias** [comment] 2022-02-22 18:41
duplicate of #4850

**Closed by iurimatias** 2022-02-22 18:41 UTC
Labels: bug, Chat, Communities
