### ISSUE TITLE
Voice/audio messages does not play on Windows build

### ISSUE THREAD

**Issue by 3esmit** [status-im/status-desktop#3339] opened 2021-08-31 05:11 UTC
Version: StatusIm-Desktop-v0.2.1-beta-1632af.exe (Windows)

Description: When trying to play a received voice/audio message, the button does not work. Nothing happens. Works fine on Linux build.

**Comment by iurimatias** [comment] 2021-08-31 20:00
duplicate of #1947 being worked on PR https://github.com/status-im/status-desktop/pull/3164

**Closed by iurimatias** 2021-08-31 20:00 UTC
