### ISSUE TITLE
Import-tool: error items are truncated, but no longer truncated when closing/reopening the modal

### ISSUE THREAD

**Issue by 0x-r4bbit** [status-im/status-desktop#8129] opened 2022-11-04 12:23 UTC
So assuming there's an import that happens to have some warnings/errors (please ignore the colors in the screenshot):

![Screenshot from 2022-11-03 10-25-00](https://user-images.githubusercontent.com/445106/199971673-ab0bb505-8da8-4c81-9d70-e4dcb8ed9b65.png)

the issues/warnings are truncated.

Then, when hiding the window and then reopening it via the global progress bar banner, the issues are no longer truncated.
We probably want those generally not be truncated.

**Comment by caybro** [comment] 2022-11-15 10:31
@PascalPrecht I was unable to reproduce this:

![image](https://user-images.githubusercontent.com/5377645/201897016-5af024d0-3986-414a-9c33-29758fb7099e.png)

However, I ran into a different issue; as you can see, there is no global progress banner so after closing this initial dialog, I couldn't open it again :/

**Comment by caybro** [comment] 2022-11-15 10:44
Will try with a clean build/data folder

**Comment by PascalPrecht** [comment] 2022-11-15 10:50
That is unexpected.

**Comment by caybro** [comment] 2022-11-15 10:55
clean build/user:

![image](https://user-images.githubusercontent.com/5377645/201902710-15eebfa3-abcb-4632-8c74-0ac5ead70b56.png)

=> can not reproduce :/

**Comment by PascalPrecht** [comment] 2022-11-15 10:57
@caybro I just tried again with latest master as well:

I do have the global progress bar
![Screenshot from 2022-11-15 11-56-05](https://user-images.githubusercontent.com/445106/201903049-02629e21-0ee7-4065-872f-3f3ff2021c3d.png)

I do see issues being truncated
![Screenshot from 2022-11-15 11-56-31](https://user-images.githubusercontent.com/445106/201903129-547c3d21-2517-4fef-b2f2-e9e63a4b6e14.png)

**Comment by caybro** [comment] 2022-11-15 10:58
Yeah... I'm pretty sure it's some kind of binding loop that gets resolved the second time you open the dialog :/

**Comment by anastasiyaig** [comment] 2023-01-12 08:10
@caybro @0x-r4bbit is it still an issue? Maybe we can close it?

**Comment by caybro** [comment] 2023-01-30 16:36
This should get fixed with the move to Qt 5.15

**Comment by 0x-r4bbit** [comment] 2023-02-21 08:12
Will have to check, but feel free to do so in the meantime yourself.
I'm busy with other things atm

**Comment by caybro** [comment] 2023-02-22 11:36
> Will have to check, but feel free to do so in the meantime yourself. I'm busy with other things atm

I was never able to reproduce; so when you get a spare second to verify (and close this), it would be appreciated, thanks!

**Comment by caybro** [comment] 2023-02-22 11:42
> here's a very different issue now when reopening the import modal:

:facepalm: ok... another victim of the StatusScrollView changes I assume.... will fix

**Closed** 2023-02-23 13:05 UTC
Labels: bug, E: Discord-Import
