### ISSUE TITLE
Assets are not rendered in appearance settings

### ISSUE THREAD

**Issue by osmaczko** [status-im/status-desktop#5369] opened 2022-04-05 15:43 UTC
Assets are not rendered in appearance settings. 
![image](https://user-images.githubusercontent.com/33099791/161792064-95224bf9-3e97-4c5f-991f-f3b64f85cab1.png)

---

**Probably in other places as well, please follow output warnings.**

```
qt.svg: :/imports/assets/images/appearance-normal-system.svg:116:6: Could not resolve property: #pattern0
qt.svg: :/imports/assets/images/appearance-normal-system.svg:116:6: Could not resolve property: #pattern1
qt.svg: :/imports/assets/images/appearance-normal-system.svg:116:6: Could not resolve property: #pattern0
qt.svg: :/imports/assets/images/appearance-normal-system.svg:116:6: Could not resolve property: #pattern1
qt.svg: :/imports/assets/images/appearance-normal-system.svg:116:6: Could not resolve property: #pattern0
qt.svg: :/imports/assets/images/appearance-normal-system.svg:116:6: Could not resolve property: #pattern1
qrc:/imports/shared/status/StatusImageRadioButton.qml:28:5: QML SVGImage: Cannot open: qrc:/imports/assets/icons/appearance-normal-system.svg
qrc:/imports/shared/status/StatusImageRadioButton.qml:28:5: QML SVGImage: Cannot open: qrc:/imports/assets/icons/appearance-normal-system.svg
qrc:/imports/shared/status/StatusImageRadioButton.qml:28:5: QML SVGImage: Cannot open: qrc:/imports/assets/icons/appearance-normal-dark.svg
qrc:/imports/shared/status/StatusImageRadioButton.qml:28:5: QML SVGImage: Cannot open: qrc:/imports/assets/icons/appearance-normal-dark.svg
qrc:/imports/shared/status/StatusImageRadioButton.qml:28:5: QML SVGImage: Cannot open: qrc:/imports/assets/icons/appearance-normal-light.svg
qrc:/imports/shared/status/StatusImageRadioButton.qml:28:5: QML SVGImage: Cannot open: qrc:/imports/assets/icons/appearance-normal-light.svg
qrc:/imports/shared/status/StatusGifPopup.qml:232:13: QML SVGImage: Cannot open: qrc:/imports/assets/icons/gif-light.svg
qrc:/imports/shared/status/StatusGifPopup.qml:232:13: QML SVGImage: Cannot open: qrc:/imports/assets/icons/gif-light.svg
qrc:/app/AppLayouts/Profile/views/EnsWelcomeView.qml:36:13: QML Image: Cannot open: qrc:/imports/assets/png/ens-header-light@2x.png
qrc:/imports/shared/status/StatusGifPopup.qml:232:13: QML SVGImage: Cannot open: qrc:/imports/assets/icons/gif-dark.svg
qrc:/imports/shared/status/StatusGifPopup.qml:232:13: QML SVGImage: Cannot open: qrc:/imports/assets/icons/gif-dark.svg
qrc:/app/AppLayouts/Profile/views/EnsWelcomeView.qml:36:13: QML Image: Cannot open: qrc:/imports/assets/png/ens-header-dark@2x.png
qrc:/imports/shared/status/StatusGifPopup.qml:232:13: QML SVGImage: Cannot open: qrc:/imports/assets/icons/gif-light.svg
qrc:/imports/shared/status/StatusGifPopup.qml:232:13: QML SVGImage: Cannot open: qrc:/imports/assets/icons/gif-light.svg
qrc:/app/AppLayouts/Profile/views/EnsWelcomeView.qml:36:13: QML Image: Cannot open: qrc:/imports/assets/png/ens-header-light@2x.png
qrc:/imports/shared/status/StatusGifPopup.qml:232:13: QML SVGImage: Cannot open: qrc:/imports/assets/icons/gif-dark.svg
qrc:/imports/shared/status/StatusGifPopup.qml:232:13: QML SVGImage: Cannot open: qrc:/imports/assets/icons/gif-dark.svg
qrc:/app/AppLayouts/Profile/views/EnsWelcomeView.qml:36:13: QML Image: Cannot open: qrc:/imports/assets/png/ens-header-dark@2x.png
qrc:/imports/shared/status/StatusGifPopup.qml:232:13: QML SVGImage: Cannot open: qrc:/imports/assets/icons/gif-light.svg
qrc:/imports/shared/status/StatusGifPopup.qml:232:13: QML SVGImage: Cannot open: qrc:/imports/assets/icons/gif-light.svg
qrc:/app/AppLayouts/Profile/views/EnsWelcomeView.qml:36:13: QML Image: Cannot open: qrc:/imports/assets/png/ens-header-light@2x.png
```

**Comment by iurimatias** [comment] 2022-04-05 16:05
duplicate of https://github.com/status-im/status-desktop/issues/5357

**Closed by iurimatias** 2022-04-05 16:05 UTC
Labels: bug, ui
