### ISSUE TITLE
missing context menu to quit app on windows

### ISSUE THREAD

**Issue by hesterbruikman** [status-im/status-desktop#2919] opened 2021-07-15 09:03 UTC
On Windows, when closing and reopening the app, it seems like multiple instances of the app are running and causing some sort of db conflict. I get a 'wrong password' entry in these cases and when I check I see multiple instances in the tray on Windows https://www.loom.com/share/ec87e33363de4c52ab712f51118904f9

### Current
When _Closing_ the app Window it appears to me as a user that I _Quit_ the app. This expectation is reinforced by having to enter my password after Clicking on the app icon to restart Status Desktop. When entering my password I get a wrong password error. I have to manually force quit the app via Task manager and restart to avoid this error. There is no UI to Quit the application when the Window is closed

### Expected

- When closing and reopening the application window I can enter a correct password without error message to access my account
- I can quit the application from the tray by right-clicking on the Status app icon (see Discord for example)
![Screenshot 2021-07-15 110145](https://user-images.githubusercontent.com/35233054/125760905-706d0883-1192-4c06-a2a0-d9e85e5159e8.png)

Issue occurred with Master of 15/07 on Windows

**Comment by iurimatias** [comment] 2021-07-15 12:10
the login issue is probably a duplicate of #2843 and #2362
the missing menu however, although is familiar I don't see an issue for it, so we'll use this as the issue for that, I'll change the title to match that

**Closed** 2021-09-20 15:37 UTC
Labels: bug, windows, general
