### ISSUE TITLE
Token Management: Grouped items are sorted in incorrect order

### ISSUE THREAD

**Issue by lukaszso** [status-im/status-desktop#13394] opened 2024-02-01 22:00 UTC
# Bug Report

## Description

If the user decides to group assets/collectibles they should be sorted from the most items to lowest in community/collection. This is correct initially, but going outside settings and coming back reveals that items are sorted randomly (? - not sure what is the logic here, just a guess).

## Steps to reproduce

1. Go to Settings > Wallet > Manage tokens
2. On Assets/Collectibles tab click "Arrange by collection" - note the order changes and displays from highest items in collection to lowest
3. Go out from settings, e.g. to Wallet view
4. Go back Manage tokens view

#### Expected behavior
The order is from highest amount of items in a collection to lowest.
#### Actual behavior
The order appears to be random and the expected one.
### Additional Information

https://github.com/status-im/status-desktop/assets/52439419/aeff5062-ea5e-4bde-b8ee-e211a7540818

- Status desktop version: StatusIm-Desktop-240201-060925-c995ff-aarch64
- Operating System: macOS Sonoma

**Comment by caybro** [comment] 2024-02-02 08:17
Yup, a known issue: https://github.com/status-im/status-desktop/issues/13276

**Comment by caybro** [comment] 2024-02-02 08:25
Dupe of https://github.com/status-im/status-desktop/issues/13276

**Closed by caybro** 2024-02-02 08:25 UTC
Labels: bug, ui-team, E: Desktop Token management
