### ISSUE TITLE
Community: View&Post token-permitted channel input is not locked when requirements do not match

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#14117] opened 2024-03-22 12:46 UTC
### Description

1. create community
2. create a permission saying "Keep 0.1 ETH to view and post in general channel"
3. for community member, create 2 addresses. One address should match the requirements, second address should not
4. invite member to community
5. as the member, share the address that do not match the requirements and confirm

As result, member is somewhat joined the community, is able to see a channel and the channel input is not locked. However, posting to the channel do not send the messages (they are not delivered)

https://github.com/status-im/status-desktop/assets/82375995/d8af264c-f9d3-4a4c-954b-97343e20c447

**Comment by anastasiyaig** [comment] 2024-03-22 12:46
@jrainville sounds like 2.29?

**Comment by jrainville** [comment] 2024-03-22 16:52
> @jrainville sounds like 2.29?

Nah, that should be RC. It used to work in 2.27 though

**Comment by jrainville** [comment] 2024-03-22 16:53
@cammellos you self-assigned because you know what is going on? From the video, it feels like the backend code is ok. Or at least the canPost code works, because it doesn't send.

**Comment by cammellos** [comment] 2024-03-22 16:57
@jrainville I assigned myself since I was looking on similar issue on mobile https://github.com/status-im/status-mobile/issues/19363 , but if anyone wants in the meantime to look into it, i will unassign myself, it might be 2 different issues

**Comment by kounkou** [comment] 2024-03-25 19:49
Hi there, I managed to reproduce the issue easily by following the steps.
We can see that we are allowed to type the message and hit the send message but the logs show

```bash
...
_sendChatMessage
DBG 2024-03-25 12:48:37.185-07:00 [threadpool task thread] initiating task   topics="task-threadpool" tid=422996 file=threadpool.nim:54 messageType=AsyncGetTextURLsToUnfurlTaskArg:ObjectType threadid=422996 task="{\"$type\":\"AsyncGetTextURLsToUnfurlTaskArg:ObjectType\",\"text\":\"plop\",\"requestUuid\":\"e3401975-e89a-4128-9a95-dd12b00d5101\",\"vptr\":93994562982848,\"slot\":\"onAsyncGetTextURLsToUnfurl\",\"tptr\":93994542558448}"
DBG 2024-03-25 12:48:37.185-07:00 NewBE_callPrivateRPC                       topics="rpc" tid=422996 file=core.nim:27 rpc_method=wakuext_getTextURLsToUnfurl
ERR 2024-03-25 12:48:37.189-07:00 rpc response error                         topics="rpc" tid=422962 file=core.nim:36 err="\nstatus-go error [methodName:wakuext_sendChatMessage, code:-32000, message:can't post message type '1' on chat '0x03d596865454ef963dfaaa687d4d7972b298874ecd08efa86432f4501cc9cd2a3d845c8962-35ed-490e-99c5-9a8786e0e7bf' ]\n"
ERR 2024-03-25 12:48:37.189-07:00 error doing rpc request                    topics="rpc" tid=422962 file=core.nim:40 methodName=wakuext_sendChatMessage exception="\nstatus-go error [methodName:wakuext_sendChatMessage, code:-32000, message:can't post message type '1' on chat '0x03d596865454ef963dfaaa687d4d7972b298874ecd08efa86432f4501cc9cd2a3d845c8962-35ed-490e-99c5-9a8786e0e7bf' ]\n"
ERR 2024-03-25 12:48:37.189-07:00 Error sending message                      topics="chat-service" tid=422962 file=service.nim:567 msg="\nstatus-go error [methodName:wakuext_sendChatMessage, code:-32000, message:can't post message type '1' on chat '0x03d596865454ef963dfaaa687d4d7972b298874ecd08efa86432f4501cc9cd2a3d845c8962-35ed-490e-99c5-9a8786e0e7bf' ]\n"
...
```



[Screencast from 2024-03-25 12:48:29 PM.webm](https://github.com/status-im/status-desktop/assets/2589171/1a338c68-5c43-47db-bdc3-2199b51c2bbd)

**Comment by jrainville** [comment] 2024-03-25 19:53
> We can see that we are allowed to type the message and hit the send message but the logs show

That means that the backend works correctly and that the addresses were shared correctly.

We are just failing to update correctly the permission model so that the UI is blocked.

Does a restart fix it?

If so, we only need to recalculate the permissions.

If not, then we need to improve the calculation to use the selected addresses only.

**Comment by kounkou** [comment] 2024-03-25 20:00
> > We can see that we are allowed to type the message and hit the send message but the logs show
> 
> That means that the backend works correctly and that the addresses were shared correctly.
> 
> We are just failing to update correctly the permission model so that the UI is blocked.
> 
> Does a restart fix it?
> 
> If so, we only need to recalculate the permissions.
> 
> If not, then we need to improve the calculation to use the selected addresses only.

So a restart fixes it indeed! 
So going to the analysis now to meet your guidance. Thanks so much

![Screenshot from 2024-03-25 12-59-42](https://github.com/status-im/status-desktop/assets/2589171/6cd184e4-22b8-47fc-8a5f-9cbe7d68b140)

**Comment by kounkou** [comment] 2024-03-26 18:42
**Surprising fact**

If I leave the address with sufficient funds as checked in the UI (like shown below), I get the reversed behavior. It seems from this observation that the addresses are just swapped...


![Image](https://github.com/status-im/status-desktop/assets/2589171/09a10fff-33b0-4cae-94de-cd6932951161)

result : 

![Image](https://github.com/status-im/status-desktop/assets/2589171/7410fdfe-0ede-4885-a959-f6f2b4605b74)

**Comment by kounkou** [comment] 2024-03-27 07:58
The issue is coming from the final calculation of the permission indeed. and this code is the entry point https://github.com/status-im/status-go/blob/98c3be55b937582374e60adb651543c5f1348c29/protocol/communities/manager.go#L2884
I will probaby need 1-2 days to spot the error/improvment and produce a PR

**Comment by cammellos** [comment] 2024-03-28 18:08
We had a discussion with @kounkou 

One issue we identified is that `lock` icons are calculated using a client check for channel permissions. 

That's not the correct way, mobile was doing the same and we had the same issue. Access is checked by the control node, as you need encryption keys for example, and those are only sent over once the admin can validate the user has the available tokens, so all the access control should be directed by the admin, rather than the client. There are flags `tokenGated` `canPost` `canView` for each channel which should be used for showing lock icons/etc.

happy to go into more details if needed. 
Unfortunately, even if that's fixed, there's still underlaying issues, most likely control node side, as we have a couple of open issues in mobile (I was hoping that this was the same issue, but at this point it looks different).

**Comment by kounkou** [comment] 2024-04-01 20:14
So the main source of the problem I have identified in the flow of `CheckPermissions` here https://github.com/status-im/status-go/blob/develop/protocol/communities/permission_checker.go#L200 is that we are interested in chainID's 

```bash
Ethereum Classic (ETC) network   : 420
Fantom Opera network (FTM)       : 421613
Goerli Testnet                   : 5
```

while we expect the following chainIDs

```bash
Ethereum Mainnet                 : 1
Optimistic Ethereum (OΞ) network : 10
Arbitrum network                 : 42161
```

Solving this issue will help fix the root cause of why we aren't able to fetch balance for an address and therefore not validate the constraints.

**Comment by kounkou** [comment] 2024-04-02 16:59
Because I was using a community where the owner token was minted with Goerli, this had misleading effects on my tests. I need to move away from using that community and reperform some tests to make sure I can fix the issue more consistently.

**Comment by kounkou** [comment] 2024-04-08 16:00
linking PR : https://github.com/status-im/status-go/pull/5023

**Comment by jrainville** [comment] 2024-04-10 17:52
@kounkou don't forget to create a cherry-pick for `develop`. Bonus points for bumping `master` to that merged `develop` afterwards

**Comment by jrainville** [comment] 2024-04-10 17:53
Fixed in https://github.com/status-im/status-go/pull/5023 and https://github.com/status-im/status-go/pull/5046#event-12426118700

**Closed by jrainville** 2024-04-10 17:53 UTC
Labels: bug, messenger-team, E:Desktop Comm Perms and Minting MVP
