### ISSUE TITLE
Community: channel is not being scrolled to the bottom when being opened

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#9303] opened 2023-01-26 07:35 UTC
### Description

whenever I open any chat/channel (for the first time) I am not positioned to the bottom of the messages list, but need to scroll towards bottom to see the last received/sent message

1. join community with some channels (for ex dogfoodging status community)
2. open a channel that is marked as bold (having unread messages)

As result, the channel is being opened, however the scrolling to the very recent (last) message is not happening

<img width="1552" alt="Screenshot 2023-01-26 at 10 32 40" src="https://user-images.githubusercontent.com/82375995/214780844-ce644909-512b-46f3-8df0-a37101a4db34.png">

**Comment by caybro** [comment] 2023-01-26 11:25
Well, it's scrolled so that you can see the "New messages" marker :) But I agree, this also happens even if there's no new messages

**Comment by mprakhov** [comment] 2023-02-03 14:32
@anastasiyaig could you please retest on the latest master build?
I can't reproduce it on the latest build. Maybe it was fixed in the scope of other tickets?

**Closed** 2023-02-09 11:54 UTC
Labels: bug, priority 2: medium, E:Bugfixes, E:Communities
