### ISSUE TITLE
Tray icon does not close app when app is non-active

### ISSUE THREAD

**Issue by mprakhov** [status-im/status-desktop#14998] opened 2024-05-31 12:47 UTC
# Bug Report

## Description

When I'm trying to close the non-active Status app by clicking on tray icon via right mouse btn - nothing happens... the app starts to be non-responsive

https://github.com/status-im/status-desktop/assets/117639195/dbe42b64-bea4-4479-8937-109e98bab705

## Steps to reproduce

1. Open app
2. Make the app non-active (click outside the app)
3. Click on the tray icon by right mouse click
4. Select close

#### Expected behavior

Non-active app is closed

#### Actual behavior

Nothing happens. Toolbar icon exists, app is not opening

### Additional Information

- Status desktop version: latest master
- Operating System: macos

**Comment by caybro** [comment] 2024-05-31 13:04
Would be nice to get this with the console output

**Comment by jrainville** [comment] 2024-08-12 17:59
Duplicate of https://github.com/status-im/status-desktop/issues/15939

**Closed by jrainville** 2024-08-12 17:59 UTC
Labels: bug, ui-team, E:Desktop Misc Bugfixes
