### ISSUE TITLE
Community collectibles are duplicated

### ISSUE THREAD

**Issue by osmaczko** [status-im/status-desktop#14007] opened 2024-03-17 14:47 UTC
# Bug Report

## Description

![Screenshot from 2024-03-17 15-44-18](https://github.com/status-im/status-desktop/assets/33099791/2bd2c246-d248-438f-8b0d-f8d325a0f89c)

## Steps to reproduce

- edit channel & add channel permission
- edit channel & remove channel permission
- edit channel & add channel permission
- edit channel & remove channel permission
- etc.

### Additional Information

- Status desktop version: master (79fa3795ca4ef1233a1e3f7185dcd8c0f26c1c38)
- Operating System: Fedora

**Comment by endulab** [comment] 2024-03-18 14:20
Dupe of #13993

**Closed** 2024-03-18 14:21 UTC
Labels: bug, ui-team, E:Desktop Comm Perms and Minting MVP
