### ISSUE TITLE
Clicking Status app icon in Mac dock when app is fullscreen exits fullscreen

### ISSUE THREAD

**Issue by benjthayer** [status-im/status-desktop#14670] opened 2024-05-09 16:03 UTC
Steps to reproduce on Mac:
1) Launch 2.28.1
2) Enter Full Screen mode by clicking green chrome control top left of app
3) Click on Status app in dock
4) App automatically exits Full Screen mode

Expected behaviour:
App should stay in Full Screen mode even if app icon is click in dock while in Full Screen mode

**Comment by friofry** [comment] 2024-05-09 16:20
+1

Here is a similar issue: https://github.com/status-im/status-desktop/issues/14132

**Comment by caybro** [comment] 2024-05-09 22:38
Dupe of https://github.com/status-im/status-desktop/issues/14132

**Closed by caybro** 2024-05-09 22:38 UTC
Labels: bug, macos, E:Desktop Communities UX fix - Medium
