### ISSUE TITLE
'Enable links preview in chat' overlaps the grey area of the message

### ISSUE THREAD

**Issue by elina2015** [status-im/status-desktop#7652] opened 2022-09-29 06:02 UTC
# Bug Report

## Steps to reproduce
In Dark mode
1. Go to Status community and open issues channel
2. Hover over any message with ''Enable links preview in chat' 
#### Expected behavior
'Enable links preview in chat' doesn't overlap the grey area of the message
#### Actual behavior
<img width="1401" alt="image" src="https://user-images.githubusercontent.com/14942081/192951263-13d944d8-40d9-4b8a-8bd6-9549f6426b9c.png">

### Additional Information

- Status desktop version: https://ci.status.im/job/status-desktop/job/platforms/job/macos/221
- Operating System: macOS Monterey

**Comment by caybro** [comment] 2022-09-29 08:13
That would be a dupe of #7651

**Closed** 2022-10-03 14:31 UTC
Labels: bug, Communities
