### ISSUE TITLE
Error "Collectibles providers down for Optimism ..." when in the channel chat view

### ISSUE THREAD

**Issue by heEXDe** [status-im/status-desktop#14918] opened 2024-05-25 13:29 UTC
# Bug Report

## Description

The following message:
"Collectibles providers down for Optimism. Collectibles for this chain are as of [date]."
appears when using chat in different channels.
The appearance of the message is occasional.

![Screenshot_2024-05-25_15-06-02](https://github.com/status-im/status-desktop/assets/61631314/fd3bc51b-39da-4b95-bcab-15d9d1c64e60)

## Steps to reproduce

1. login to the app
2. go to the "Status" menu
3. start doing something in the channels (e.g. change channels, click on links in user posts)

### Additional Information

- Status desktop version: 2.28.1
- Operating System: Linux, POP_OS 22.04 LTS (Ubuntu 22.04 based)

**Comment by caybro** [comment] 2024-05-27 07:44
Dupe of https://github.com/status-im/status-desktop/issues/14862

**Closed by caybro** 2024-05-27 07:44 UTC
Labels: bug
