### ISSUE TITLE
 [SwapModal]: Can approve Swap with no amount entered

### ISSUE THREAD

**Issue by caybro** [status-im/status-desktop#15553] opened 2024-07-11 22:51 UTC
# Bug Report

See the video:

[Záznam obrazovky z 2024-07-12 00-45-02.webm](https://github.com/user-attachments/assets/df82369d-fa65-4acd-8afc-204c9f27d1c1)

## Steps to reproduce

1. Get a proposal
2. Change account to one with no balance
3. Delete the amount
4. "Approve" button gets enabled

#### Expected behavior
Button stays disabled with no amount entered

#### Actual behavior
Button is enabled with empty amount or 0

### Additional Information

- Status desktop version: master
- Operating System: linux

**Comment by dlipicar** [comment] 2024-07-15 13:24
Hmm I feel like this was because a re-calc was not getting triggered (due to balance checks, should be fixed now). However, any change in input parameters should invalidate whatever proposal we had before IMO, and THEN if checks pass trigger a re calculation. WDYT @Khushboo-dev-cpp ?

**Comment by Khushboo-dev-cpp** [comment] 2024-07-16 12:28
not 

> Hmm I feel like this was because a re-calc was not getting triggered (due to balance checks, should be fixed now). However, any change in input parameters should invalidate whatever proposal we had before IMO, and THEN if checks pass trigger a re calculation. WDYT [@Khushboo-dev-cpp](https://github.com/Khushboo-dev-cpp) ?

@dlipicar yes a change input params should reset the output values for sure. I tried reproducing it and was able to reproduce, different ones than the one mentioned. on it now.



https://github.com/user-attachments/assets/388b306a-b03b-4f39-8fd4-9a020e3a2fef

**Closed** 2024-07-19 15:35 UTC
Labels: bug, E:D Swap M1, swap-team
