### ISSUE TITLE
Can't mark activity as read

### ISSUE THREAD

**Issue by PascalPrecht** [status-im/status-desktop#3488] opened 2021-09-13 13:52 UTC
<img width="583" alt="Screenshot 2021-09-13 at 15 51 35" src="https://user-images.githubusercontent.com/445106/133095932-9e3affaa-8165-4313-bc56-067c3c5c0e8d.png">

Not sure if that's related to the message type, but that last activity in the activity center I cannot mark as read because I don't see the button for that.

**Comment by iurimatias** [comment] 2021-09-13 20:21
this is a strange one, it's a community invite, but it's been show as a message, and it's a contact request as well, thus why it doesn't show the button to mark activity as read

**Comment by iurimatias** [comment] 2021-09-13 20:22
related #3483

**Comment by iurimatias** [comment] 2021-09-15 16:48
duplicate of #3522

**Closed by iurimatias** 2021-09-15 16:48 UTC
Labels: to analyze, Activity_center
