### ISSUE TITLE
Crash on launch of 0.14 RC4

### ISSUE THREAD

**Issue by glitchminer** [status-im/status-desktop#12108] opened 2023-09-08 09:02 UTC
# Bug Report

## Description

This happens on application launch. Most of the time it has been fine but have now seen this crash twice.

```
panic: insufficient write buffer

goroutine 7968 [running]:
github.com/anacrolix/torrent.(*Peer).applyRequestState(0x240096e9500, {{{0x24008607520, 0x8, 0x8}, 0x240096e9500}, 0x1})
	/Users/jenkins/workspace/status-desktop/systems/macos/aarch64/package/vendor/status-go/vendor/github.com/anacrolix/torrent/requesting.go:234 +0x6b8
github.com/anacrolix/torrent.(*Peer).maybeUpdateActualRequestState.func1({0x10cfe8460?, 0x240043a4240?})
	/Users/jenkins/workspace/status-desktop/systems/macos/aarch64/package/vendor/status-go/vendor/github.com/anacrolix/torrent/requesting.go:225 +0x70
runtime/pprof.Do({0x10cfe83f0?, 0x24000198018?}, {{0x240009e2e00?, 0x30000007d?, 0x3?}}, 0x2400404bb88)
	/usr/local/go/src/runtime/pprof/runtime.go:44 +0x80
github.com/anacrolix/torrent.(*Peer).maybeUpdateActualRequestState(0x240096e9500)
	/Users/jenkins/workspace/status-desktop/systems/macos/aarch64/package/vendor/status-go/vendor/github.com/anacrolix/torrent/requesting.go:220 +0x214
github.com/anacrolix/torrent.(*PeerConn).fillWriteBuffer(0x240096e9500)
	/Users/jenkins/workspace/status-desktop/systems/macos/aarch64/package/vendor/status-go/vendor/github.com/anacrolix/torrent/peerconn.go:682 +0x28
github.com/anacrolix/torrent.(*PeerConn).startWriter.func1()
	/Users/jenkins/workspace/status-desktop/systems/macos/aarch64/package/vendor/status-go/vendor/github.com/anacrolix/torrent/peer-conn-msg-writer.go:24 +0xa0
github.com/anacrolix/torrent.(*peerConnMsgWriter).run(0x240096e9960, 0xdf8475800)
	/Users/jenkins/workspace/status-desktop/systems/macos/aarch64/package/vendor/status-go/vendor/github.com/anacrolix/torrent/peer-conn-msg-writer.go:69 +0xa4
github.com/anacrolix/torrent.(*PeerConn).startWriter.func3()
	/Users/jenkins/workspace/status-desktop/systems/macos/aarch64/package/vendor/status-go/vendor/github.com/anacrolix/torrent/peer-conn-msg-writer.go:40 +0xd0
created by github.com/anacrolix/torrent.(*PeerConn).startWriter
	/Users/jenkins/workspace/status-desktop/systems/macos/aarch64/package/vendor/status-go/vendor/github.com/anacrolix/torrent/peer-conn-msg-writer.go:36 +0x198
SIGABRT: Abnormal termination.
zsh: abort      ./nim_status_client
```

## Steps to reproduce

Launch CI build of 0.14 RC4

### Additional Information

- Status desktop version: 0.14 RC4
- Operating System: Mac

**Comment by jrainville** [comment] 2023-09-18 13:17
This was a duplicate of https://github.com/status-im/status-desktop/issues/11996 which is now closed

**Closed by jrainville** 2023-09-18 13:17 UTC
Labels: bug, messenger-team
