### ISSUE TITLE
When sending multiple pics only 1 shows on the sender side 

### ISSUE THREAD

**Issue by Hbouaz** [status-im/status-desktop#6247] opened 2022-06-27 17:25 UTC
# Bug Report

## Description

When sending multiple pics only 1 shows on the sender side 

## Steps to reproduce

Start a 1-to-1 or Community chat
select and send multiple pictures at once 
notice recipient can see all of them but the sender can only see 1

#### Expected behaviour
both recipient and sender can see all pictures 

#### Actual behavior
The sender can only see 1

### Additional Information
![3PicsSelected](https://user-images.githubusercontent.com/26457452/176000676-04e1c269-d8ba-403b-8b3b-65091530553d.png)
![Only1Shown](https://user-images.githubusercontent.com/26457452/176000701-58549192-9586-438a-a395-276e47edd991.png)

- Status desktop version: master
- Operating System: MacOS

**Comment by iurimatias** [comment] 2022-07-07 18:41
duplicate of https://github.com/status-im/status-desktop/issues/4905

**Closed by iurimatias** 2022-07-07 18:41 UTC
Labels: bug, priority 1: high
