### ISSUE TITLE
Onboarding is shown while restoring the account by a seed phrase

### ISSUE THREAD

**Issue by elina2015** [status-im/status-desktop#6256] opened 2022-06-28 01:10 UTC
# Bug Report

## Steps to reproduce
1. Launch the app, click "I already use Status' - 'Enter a seed phrase'
2. Enter the seed phrase: 
<img width="751" alt="image" src="https://user-images.githubusercontent.com/14942081/176065080-cba10f70-528f-4a48-8b72-79b9f185f24b.png">

#### Expected behavior
The profile is recovered successfully
#### Actual behavior
The Onboarding steps (Display Name, Password, etc.) are shown and a new account is created after finishing the onboarding instead of restoring the old profile.
### Additional Information
https://user-images.githubusercontent.com/14942081/176065216-d1b3bc73-66ba-4bf4-a21f-07d9ab05ad0b.mov

Status desktop version: https://ci.status.im/job/status-desktop/job/branches/job/macos/job/master/2246/
Operating System: macOS Monterey 12.3 Beta (21E5227a)

**Comment by iurimatias** [comment] 2023-01-16 18:17
probable duplicate of #5622

**Closed by iurimatias** 2023-01-16 18:17 UTC
Labels: onboarding, feature, priority F2: important, E:Onboarding, S:3
