### ISSUE TITLE
It is possible to see the pictures of users that werent added as contacts

### ISSUE THREAD

**Issue by richard-ramos** [status-im/status-desktop#2370] opened 2021-04-22 18:40 UTC
![image](https://user-images.githubusercontent.com/1106587/115768615-8c4a1380-a378-11eb-9189-fa39c5ea3735.png)

(I dont have the setting enabled to see pics from non-contacts)

**Comment by iurimatias** [comment] 2021-04-26 20:57
duplicate of #2365

**Closed by iurimatias** 2021-04-26 20:57 UTC
