### ISSUE TITLE
[Communities] Airdrop: Amount precision is incorrect

### ISSUE THREAD

**Issue by friofry** [status-im/status-desktop#13843] opened 2024-03-05 15:33 UTC
# Bug Report

## Description
Issue with the precision on low-significant digits 

## Steps to reproduce
1. Create a Community Asset with 10 Decimal digits and 999'999'999 total amount
2. Airdrop 0.0000000001 
3. Airdrop again for 999999998.99999995 

#### Expected behavior
It should be possible to airdrop all remaining supply

#### Actual behavior
The maximum amount is smaller than remaining supply

### Additional Information
From the logs
maximumAmount equals 999999998999999999900000000
amount is 9.99999999e+26
and SQUtils.AmountsArithmetic.cmp(amount, maximumAmount) returns 1

It looks like the amountNumber loses precision
<kbd>
<img width="340" alt="image" src="https://github.com/status-im/status-desktop/assets/1083341/d883bdb0-770e-4945-8ca6-c401c89b12e8">
</kbd>

on master (commit https://github.com/status-im/status-desktop/commit/f3bf194187677557a6d2c90592780bb68b1f059f)

**Comment by friofry** [comment] 2024-03-05 15:41
Hi @micieslak 
I suspect this issue is a duplicate of https://github.com/status-im/status-desktop/issues/11489

**Comment by caybro** [comment] 2024-06-20 09:04
Dupe of https://github.com/status-im/status-desktop/issues/11489

**Closed by caybro** 2024-06-20 09:04 UTC
Labels: bug
