### ISSUE TITLE
It's impossible to add new community

### ISSUE THREAD

**Issue by elina2015** [status-im/status-desktop#6741] opened 2022-08-01 06:53 UTC
# Bug Report

## Steps to reproduce
1. Go to create a new community
2. Fill out all necessary fields and click 'Next'
3. Check the field for community rules and try to fill it out

#### Expected behavior
1. It's possible to fill out the field of rules
2. It's possible to create a new community
#### Actual behavior
1. It's impossible to fill out the field of rules
2. It's impossible to create a new community
<img width="659" alt="image" src="https://user-images.githubusercontent.com/14942081/182089639-514eefad-2717-4158-918e-125b0525ff4d.png">

### Additional Information
- Status desktop version: https://ci.status.im/job/status-desktop/job/master/20/
- Operating System: macOS Monterey

**Comment by micieslak** [comment] 2022-08-01 09:26
It's a duplicate of https://github.com/status-im/status-desktop/issues/6697

**Comment by iurimatias** [comment] 2022-08-01 13:23
closing as duplicate

**Closed by iurimatias** 2022-08-01 13:23 UTC
Labels: bug, Communities, priority 1: high
