### ISSUE TITLE
Invalid community members count

### ISSUE THREAD

**Issue by alaibe** [status-im/status-desktop#13049] opened 2023-12-19 14:33 UTC
# Bug Report
From settings ![image](https://github.com/status-im/status-desktop/assets/491074/8ab206a0-6ca5-457b-9225-f024c736c57c)

While actually:
![image](https://github.com/status-im/status-desktop/assets/491074/5205e8d2-106f-4d52-8fae-e7b95fd9577f)

## Description

Invalid community members count

**Comment by caybro** [comment] 2023-12-19 15:10
Dupe of https://github.com/status-im/status-desktop/issues/12967 and already fixed in https://github.com/status-im/status-desktop/pull/12981; pls reopen if the issue persists

**Closed by caybro** 2023-12-19 15:10 UTC
Labels: bug, messenger-team
