### ISSUE TITLE
searching for an ens name and adding it should remove that contact from the 'non contacts' category in the search

### ISSUE THREAD

**Issue by iurimatias** [status-im/status-desktop#2369] opened 2021-04-22 18:39 UTC
note: missing ENS name is issue #2368

after I add Hester, the contact should immediately show in the contacts category of the search

https://images.zenhubusercontent.com/261270348/cb28e296-8e7c-437a-be4d-95cd5c912745/screen_recording_2021_04_22_at_2_37_36_pm.mov

**Comment by saledjenic** [comment] 2021-07-14 09:33
@iurimatias @simonricoo is this really a bug? Cause when you start new chat and type ens name and that name is not in your contacts and it is listed in "Non contacts" section as we may see in the attached video. Then when you click that "+" button to add it to your contacts in that moment it's not your contact yet, and won't be as long as it accepts your contact invitation.  So I guess there is no need to remove it from "Non contacts" section. What do you think?

**Comment by iurimatias** [comment] 2021-07-14 12:59
That’s a good point, this issue predates the existence of mutual contact requests

**Comment by saledjenic** [comment] 2021-07-15 11:52
I am closing this as based on Iuri's comment it feels like it's either not a bug, or the behaviour needs to be changed.

**Closed by saledjenic** 2021-07-15 11:52 UTC
Labels: Chat, bug, ui
