### ISSUE TITLE
List of suggestions is not showing up when pasting @ to mention someone in chat

### ISSUE THREAD

**Issue by iurimatias** [status-im/status-desktop#4754] opened 2022-02-07 20:53 UTC
### Description

mentions don't show the autocomplete menu, also emojis etc..

**Comment by anastasiyaig** [comment] 2022-02-08 11:57
i was not able to reproduce problem with emojis and etc, however the mentions indeed are not showing up (list of suggestions when using @ )

**Comment by jrainville** [comment] 2022-02-09 20:28
I think this was fixed in master already, can you try again?

**Comment by anastasiyaig** [comment] 2022-02-15 11:08
i will close it

**Closed by anastasiyaig** 2022-02-15 11:08 UTC
Labels: Chat, refactor, priority 0: blocker
