### ISSUE TITLE
Crash when removing keycard reader

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#16904] opened 2024-12-06 11:41 UTC
### Description

1. Download and install Status for Desktop. Use clean Installation. Open Status.
2. Press I’m new to Status
3. Press import a seed phrase
4. Press Import a seed phrase into a new Keycard and connect reader
5. Remove the reader from the computer

```
DBG 2024-12-06 11:07:55.110Z keycardStartFlow                           topics="keycard-service" tid=51718283 file=service.nim:168 kcServiceCurrFlow=LoadAccount payload={} response=ok
keycard - listing readers
keycard - waiting for card
fatal error: concurrent map writes
fatal error: concurrent map writes

goroutine 40 [running, locked to thread]:
github.com/ebfe/scard.(*ReaderState).toSys(...)
	/Users/anastasiya/go/pkg/mod/github.com/ebfe/scard@v0.0.0-20190212122703-c3d1b1916a95/scard_darwin.go:198
github.com/ebfe/scard.(*Context).GetStatusChange(0x2400008e090, {0x240000b4080, 0x1, 0x0?}, 0x0?)
	/Users/anastasiya/go/pkg/mod/github.com/ebfe/scard@v0.0.0-20190212122703-c3d1b1916a95/scard.go:112 +0x1ec
github.com/status-im/status-keycard-go.(*keycardContext).waitForCard(0x1081780d1?, 0x240000aa000?, {0x24000090110, 0x1, 0x0?})
	/Users/anastasiya/status-desktop/vendor/status-keycard-go/keycard_context.go:203 +0xc8
github.com/status-im/status-keycard-go.(*keycardContext).connect(0x240000942d0)
	/Users/anastasiya/status-desktop/vendor/status-keycard-go/keycard_context.go:147 +0x54
github.com/status-im/status-keycard-go.(*keycardContext).run(0x240000942d0)
	/Users/anastasiya/status-desktop/vendor/status-keycard-go/keycard_context.go:100 +0x8c
created by github.com/status-im/status-keycard-go.startKeycardContext in goroutine 14
	/Users/anastasiya/status-desktop/vendor/status-keycard-go/keycard_context.go:61 +0xc4

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/opt/homebrew/Cellar/go@1.21/1.21.10/libexec/src/runtime/asm_arm64.s:1197 +0x4

goroutine 23 [select]:
github.com/status-im/status-keycard-go.(*KeycardFlow).connect(0x2400012c120)
	/Users/anastasiya/status-desktop/vendor/status-keycard-go/flow.go:197 +0xc4
github.com/status-im/status-keycard-go.(*KeycardFlow).connectedFlow(0x2400012c120)
	/Users/anastasiya/status-desktop/vendor/status-keycard-go/flow.go:221 +0x2c
github.com/status-im/status-keycard-go.(*KeycardFlow).runFlow(0x2400012c120)
	/Users/anastasiya/status-desktop/vendor/status-keycard-go/flow.go:91 +0x8c
created by github.com/status-im/status-keycard-go.(*KeycardFlow).Start in goroutine 17
	/Users/anastasiya/status-desktop/vendor/status-keycard-go/flow.go:50 +0x90

goroutine 21 [syscall, locked to thread]:
github.com/ebfe/scard._Cfunc_SCardGetStatusChange(0xa, 0xffffffff, 0x240001a6180, 0x1)
	_cgo_gotypes.go:234 +0x34
github.com/ebfe/scard.scardGetStatusChange.func1(0xa, 0x0?, 0x2400005fcd8?, {0x240001a6140?, 0x1, 0x240001a2078?})
	/Users/anastasiya/go/pkg/mod/github.com/ebfe/scard@v0.0.0-20190212122703-c3d1b1916a95/scard_darwin.go:66 +0x88
github.com/ebfe/scard.scardGetStatusChange(0x1081e7180?, 0x11e120?, {0x240001a6140?, 0x1, 0x1})
	/Users/anastasiya/go/pkg/mod/github.com/ebfe/scard@v0.0.0-20190212122703-c3d1b1916a95/scard_darwin.go:66 +0xfc
github.com/ebfe/scard.(*Context).GetStatusChange(0x24000126298, {0x24000176080, 0x1, 0x0?}, 0x0?)
	/Users/anastasiya/go/pkg/mod/github.com/ebfe/scard@v0.0.0-20190212122703-c3d1b1916a95/scard.go:118 +0x270
github.com/status-im/status-keycard-go.(*keycardContext).waitForCard(0x1081780d1?, 0x2400002a0c0?, {0x240001184b0, 0x1, 0x0?})
	/Users/anastasiya/status-desktop/vendor/status-keycard-go/keycard_context.go:203 +0xc8
github.com/status-im/status-keycard-go.(*keycardContext).connect(0x24000172240)
	/Users/anastasiya/status-desktop/vendor/status-keycard-go/keycard_context.go:147 +0x54
github.com/status-im/status-keycard-go.(*keycardContext).run(0x24000172240)
	/Users/anastasiya/status-desktop/vendor/status-keycard-go/keycard_context.go:100 +0x8c
created by github.com/status-im/status-keycard-go.startKeycardContext in goroutine 41
	/Users/anastasiya/status-desktop/vendor/status-keycard-go/keycard_context.go:61 +0xc4

goroutine 42 [runnable, locked to thread]:
github.com/ebfe/scard.(*ReaderState).toSys(...)
	/Users/anastasiya/go/pkg/mod/github.com/ebfe/scard@v0.0.0-20190212122703-c3d1b1916a95/scard_darwin.go:198
github.com/ebfe/scard.(*Context).GetStatusChange(0x2400008e0d0, {0x240000b4100, 0x1, 0x0?}, 0x0?)
	/Users/anastasiya/go/pkg/mod/github.com/ebfe/scard@v0.0.0-20190212122703-c3d1b1916a95/scard.go:112 +0x1ec
github.com/status-im/status-keycard-go.(*keycardContext).waitForCard(0x1081780d1?, 0x24000180060?, {0x240000901e0, 0x1, 0x0?})
	/Users/anastasiya/status-desktop/vendor/status-keycard-go/keycard_context.go:203 +0xc8
github.com/status-im/status-keycard-go.(*keycardContext).connect(0x240000943f0)
	/Users/anastasiya/status-desktop/vendor/status-keycard-go/keycard_context.go:147 +0x54
github.com/status-im/status-keycard-go.(*keycardContext).run(0x240000943f0)
	/Users/anastasiya/status-desktop/vendor/status-keycard-go/keycard_context.go:100 +0x8c
created by github.com/status-im/status-keycard-go.startKeycardContext in goroutine 23
	/Users/anastasiya/status-desktop/vendor/status-keycard-go/keycard_context.go:61 +0xc4

goroutine 51 [running, locked to thread]:
	goroutine running on other thread; stack unavailable
created by github.com/status-im/status-keycard-go.startKeycardContext in goroutine 22
	/Users/anastasiya/status-desktop/vendor/status-keycard-go/keycard_context.go:61 +0xc4

goroutine 51 [running, locked to thread]:
github.com/ebfe/scard.(*ReaderState).toSys(...)
	/Users/anastasiya/go/pkg/mod/github.com/ebfe/scard@v0.0.0-20190212122703-c3d1b1916a95/scard_darwin.go:198
github.com/ebfe/scard.(*Context).GetStatusChange(0x2400019c008, {0x240001a4000, 0x1, 0x0?}, 0x0?)
	/Users/anastasiya/go/pkg/mod/github.com/ebfe/scard@v0.0.0-20190212122703-c3d1b1916a95/scard.go:112 +0x1ec
github.com/status-im/status-keycard-go.(*keycardContext).waitForCard(0x1081780d1?, 0x24000180120?, {0x2400019a020, 0x1, 0x0?})
	/Users/anastasiya/status-desktop/vendor/status-keycard-go/keycard_context.go:203 +0xc8
github.com/status-im/status-keycard-go.(*keycardContext).connect(0x24000198000)
	/Users/anastasiya/status-desktop/vendor/status-keycard-go/keycard_context.go:147 +0x54
github.com/status-im/status-keycard-go.(*keycardContext).run(0x24000198000)
	/Users/anastasiya/status-desktop/vendor/status-keycard-go/keycard_context.go:100 +0x8c
created by github.com/status-im/status-keycard-go.startKeycardContext in goroutine 22
	/Users/anastasiya/status-desktop/vendor/status-keycard-go/keycard_context.go:61 +0xc4
SIGABRT: Abnormal termination.
make: *** [run-macos] Abort trap: 6
```

**Comment by bitgamma** [comment] 2024-12-11 01:45
@anastasiyaig I tracked the issue to the `ebfe/scard` dependency we rely on for PC/SC communication. I will need to fork it to fix this

**Comment by anastasiyaig** [comment] 2024-12-11 06:32
thanks @bitgamma, do you have estimate? I am just wondering if we can make it to 2.32 or not

**Comment by bitgamma** [comment] 2024-12-11 06:39
@anastasiyaig even if the change I have to do seems rather simple, that library is a fundamental component with platform-specific behaviour so I'd like to have the time to verify that nothing breaks. Since the workaround to this issue seems rather easy (do not unplug the reader while using it), it could be a good idea to move it to a future release (I don't know when 2.32 is planned for, though)

**Comment by anastasiyaig** [comment] 2024-12-11 06:53
ya perfect i agree :) thanks @bitgamma

**Comment by bitgamma** [comment] 2024-12-13 02:18
@saledjenic the issue has been fixed in branch [fix-16904](https://github.com/keycard-tech/status-keycard-go/tree/fix-16904) of `status-keycard-go`. Please update status-desktop to use this version to verify that the fix solves the issue (I cannot reproduce the issue using the tests)

**Comment by saledjenic** [comment] 2024-12-13 07:39
Thanks @bitgamma, here is a desktop PR including the changes https://github.com/status-im/status-desktop/pull/16961

**Closed** 2024-12-13 15:27 UTC
Labels: bug, crash, wallet-team

**Comment by saledjenic** [comment] 2024-12-13 15:31
@bitgamma you can merge changes to master branch of status-keycard-go, @anastasiyaig confirmed that the issue is not reproducible after your changes.

**Comment by bitgamma** [comment] 2024-12-14 00:00
@saledjenic done
