### ISSUE TITLE
When @ mentioning a contact in a 1to1 chat, the contact's 3 word username is shown

### ISSUE THREAD

**Issue by abhi-status** [status-im/status-desktop#5438] opened 2022-04-08 10:18 UTC
# Bug Report

## Description

- After adding a contact (contact request is accepted on the other side), 
- Start a 1 to 1 chat with this contact
- In the chat field, use @ to mention the contact

#### Expected behavior
The suggestions popup must show the contact's chosen user name

#### Actual behavior
![image](https://user-images.githubusercontent.com/95302135/162416202-f448597a-be0e-4bc8-a695-dd16d4a0098f.png)

### Additional Information

- Status desktop version: Master : 1a8dfde1b28e73213d4a5f37fa774e679a7232bc

**Comment by saledjenic** [comment] 2022-04-11 10:34
@abhi-status I checked this issue in the `master` branch and looks ok there, see the screenshot below.

![testIssue](https://user-images.githubusercontent.com/86303051/162722773-e4d7f77f-20a1-42db-858a-dbb515ad40a1.png)

**Comment by abhi-status** [comment] 2022-04-11 12:11
@saledjenic So this now appears, when the contact has been renamed.

1 - Add a contact
2 - Rename the contact
3 - Start a 1 to 1 chat with this account
4 - Use `@` to start the mention

**Expected:** The suggestion given must be the renamed account
**Actual:** 3 word user name is shown

**Comment by iurimatias** [comment] 2022-04-11 17:26
> @saledjenic So this now appears, when the contact has been renamed.
> 
> 1 - Add a contact 2 - Rename the contact 3 - Start a 1 to 1 chat with this account 4 - Use `@` to start the mention
> 
> **Expected:** The suggestion given must be the renamed account **Actual:** 3 word user name is shown
> 
> ![image](https://user-images.githubusercontent.com/95302135/162737051-982e5c06-103d-4d7e-a8b9-93a66339ba04.png)

duplicate of https://github.com/status-im/status-desktop/issues/5462

**Closed by iurimatias** 2022-04-11 17:26 UTC
Labels: bug, Chat, priority 1: high
