### ISSUE TITLE
The contact list is shown incorrectly

### ISSUE THREAD

**Issue by elina2015** [status-im/status-desktop#5258] opened 2022-03-29 21:58 UTC
# Bug Report

## Description
The contact list is shown incorrectly - only one contact is visible

## Steps to reproduce
1. Launch the app
2. Sign in with a user that has few contacts
3. Open Chat and click on the pencil icon near the search field for opening the dialog for writing to some contact
4. Check the list of contacts under the field "To:"

#### Expected behavior
All contacts are shown in the list of contacts
#### Actual behavior
Only one contact is shown and a small part of the second contact appears in the contact list
<img width="1306" alt="image" src="https://user-images.githubusercontent.com/14942081/160712978-9871473d-47cd-4415-88d3-cd644dfd9012.png">

### Additional Information

- Status desktop version: https://github.com/status-im/status-desktop/commit/591a5bdf34cb2ad161e6cb4e59ecaf6c039abb2e
- Operating System: macOS Monterey, 12.3 Beta (21E5227a)

**Comment by iurimatias** [comment] 2022-03-31 22:10
probably a duplicate of https://github.com/status-im/status-desktop/pull/5229

**Closed** 2022-04-01 14:37 UTC
Labels: bug, priority 1: high, E:Bugfixes
