### ISSUE TITLE
Adding a mention on a new line (second line or more) removes the line breaks

### ISSUE THREAD

**Issue by jrainville** [status-im/status-desktop#2089] opened 2021-03-22 14:01 UTC
Steps:
1. write text on the first line of  a chat message
2. hit SHIFT+space (to go to the second line)
3. Enter a mention and hit Enter to apply it
-> goes back to the first line. Line breaks are gone

**Comment by iurimatias** [comment] 2021-03-22 14:20
duplicate of #2000

**Closed** 2021-03-22 14:20 UTC
Labels: Chat, bug
