### ISSUE TITLE
[Chat] Messages are overlapped when they contain more than one line

### ISSUE THREAD

**Issue by noeliaSD** [status-im/status-desktop#7618] opened 2022-09-27 14:37 UTC
### Description

Not always reproducible and sometimes they are correctly reorganized after a resize, but sometimes not.

See the video for better understanding:

https://user-images.githubusercontent.com/97019400/192555537-4904c848-5506-43aa-aee8-389d5db09976.mov

**Comment by caybro** [comment] 2022-09-27 14:38
@noeliaSD can you pls try again in latest master, it was fixed already

**Comment by micieslak** [comment] 2022-09-28 07:55
@caybro Right now the problem exists in the master, caused by https://github.com/status-im/status-desktop/pull/7485, as described in https://github.com/status-im/status-desktop/issues/7522#issuecomment-1259716653

**Comment by noeliaSD** [comment] 2022-09-28 08:58
> @noeliaSD can you pls try again in latest master, it was fixed already

Tried and I can still reproduce it on current master!

**Comment by caybro** [comment] 2022-10-03 09:22
Closing as a duplicate of #7703

**Closed** 2022-10-03 14:40 UTC
Labels: bug, Chat, priority 1: high, S:3
