### ISSUE TITLE
Contact Verification: placeholder of the answer field is placed very close to the left edge

### ISSUE THREAD

**Issue by elina2015** [status-im/status-desktop#8949] opened 2023-01-04 04:17 UTC
# Bug Report

## Steps to reproduce
1. Get a contact Verification request
2. Open the modal for answering
3. Check the placeholder in the answer field

#### Expected behavior
The placeholder of the answer field is placed NOT very close to the left edge
#### Actual behavior
<img width="242" alt="image" src="https://user-images.githubusercontent.com/14942081/210482759-3a51b114-571d-462d-aaf4-cdb65b61bd46.png">

### Additional Information

- Status desktop version: https://github.com/status-im/status-desktop/releases/0.9.0-rc.1
- Operating System: macOS Monterey

**Comment by caybro** [comment] 2023-01-04 10:32
Another dupe of https://github.com/status-im/status-desktop/issues/8910

**Closed by caybro** 2023-01-04 10:32 UTC
Labels: bug, pixel-perfect-issues, 0.9.0
