### ISSUE TITLE
Messaging / Activity Centre: Year missing from date stamp

### ISSUE THREAD

**Issue by imagiMary** [status-im/status-desktop#11453] opened 2023-07-07 15:14 UTC
Version: 0.13.0-rc.6
OS: Windows 10

***
Preconditions: Download 0.13 - rc.6 and restore Status account from seed phrase

<ins>Steps to reproduce:</ins>

1. Navigate to an older message in a community.

<ins>What currently incorrectly happens:</ins>

2. The date stamp is missing the year.

<ins>What is supposed to happen:</ins>

2. The date stamp should contain the year (dd/mm/yyyy). 

<ins>Other information</ins>
The same issue is present in the Activity Centre notifications

![07 03 Year missing from date stamp](https://github.com/status-im/status-desktop/assets/124154641/bdfb0063-0e0e-4179-afdc-902f166dc63b)

**Comment by caybro** [comment] 2023-07-07 16:51
Looks like a dupe of https://github.com/status-im/status-desktop/issues/10615; I'll have a look later :)

**Closed by caybro** 2023-07-07 16:51 UTC
Labels: bug
