### ISSUE TITLE
DApp browser doesn't work

### ISSUE THREAD

**Issue by osmaczko** [status-im/status-desktop#7974] opened 2022-10-20 08:08 UTC
# Bug Report

https://user-images.githubusercontent.com/33099791/196892615-95f788f1-a6f6-4fed-96f4-7f4e3b566237.mp4

Results in ton of renderer errors:
```
qml: Render process exited with code 159 (killed)                                                                                                                                                                    
qml: Render process exited with code 159 (killed)                                                                                                                                                                    
qml: Render process exited with code 159 (killed)                                                                                                                                                                    
qml: Render process exited with code 159 (killed)                                                                                                                                                                    
qml: Render process exited with code 159 (killed)                                                                                                                                                                    
qml: Render process exited with code 159 (killed)                                                                                                                                                                    
qml: Render process exited with code 159 (killed)                                                                                                                                                                    
qml: Render process exited with code 159 (killed)                                                                                                                                                                    
qml: Render process exited with code 159 (killed)                                                                                                                                                                    
qml: Render process exited with code 159 (killed)                                                                                                                                                                    
qml: Render process exited with code 159 (killed)                                                                                                                                                                    
qml: Render process exited with code 159 (killed)                                                                                                                                                                    
qml: Render process exited with code 159 (killed)                                                                                                                                                                    
qml: Render process exited with code 159 (killed)                                                                                                                                                                    
qml: Render process exited with code 159 (killed)                                                                                                                                                                    
qml: Render process exited with code 159 (killed)
```

## Steps to reproduce

- enable Dapp Browser in experimental features
- try to open any url

### Additional Information

- Status desktop version: 0.7 beta
- Operating System: Ubutnu 22.04

**Comment by PascalPrecht** [comment] 2022-10-20 08:27
As discussed offline, I cannot reproduce this on my machine.

Distributor ID: Ubuntu
Description:    Ubuntu 20.04.5 LTS
Release:        20.04

**Comment by caybro** [comment] 2022-10-20 08:43
Me neither

**Comment by osmaczko** [comment] 2022-10-20 12:37
@richard-ramos can reproduce it on Ubuntu 22.04

**Comment by caybro** [comment] 2022-10-20 15:07
What Qt version are you running and where it comes from? Likely Ubuntu fault

**Comment by richard-ramos** [comment] 2022-10-20 15:24
If you run desktop with this env variable, it works.
`QTWEBENGINE_DISABLE_SANDBOX=1`

https://askubuntu.com/questions/1403693/ebook-viewer-qt-webengine-render-process-has-crashed-ubuntu-22-04
According to prev link, in Calibre 5.42 they use that workaround due to Qt WebEngine not working on systems with glibc > 2.33

**Comment by caybro** [comment] 2022-10-20 16:09
> If you run desktop with this env variable, it works. `QTWEBENGINE_DISABLE_SANDBOX=1`
> 
> https://askubuntu.com/questions/1403693/ebook-viewer-qt-webengine-render-process-has-crashed-ubuntu-22-04 According to prev link, in Calibre 5.42 they use that workaround due to Qt WebEngine not working on systems with glibc > 2.33

From the blame-ubuntu-dept-i-told-you-so ;)

**Comment by iurimatias** [comment] 2022-11-04 12:12
closed in favour of the browser epic

**Closed by iurimatias** 2022-11-04 12:12 UTC
Labels: bug, Browser, E:Browser
