### ISSUE TITLE
Recipient of the transaction message is not notified that transaction is completed

### ISSUE THREAD

**Issue by saledjenic** [status-im/status-desktop#2916] opened 2021-07-15 05:51 UTC
Connected issues:
- [Issue 2719](https://app.zenhub.com/workspaces/nim-status-client--nim-status-5ea70d29c12ee928df5ae848/issues/status-im/status-desktop/2719)
- [Issue 2720](https://app.zenhub.com/workspaces/nim-status-client--nim-status-5ea70d29c12ee928df5ae848/issues/status-im/status-desktop/2720)
- [Issue 1205](https://app.zenhub.com/workspaces/nim-status-client--nim-status-5ea70d29c12ee928df5ae848/issues/status-im/status-desktop/1205)
- [Issue 1201](https://app.zenhub.com/workspaces/nim-status-client--nim-status-5ea70d29c12ee928df5ae848/issues/status-im/status-desktop/1201)

PR for this may be seen [here](https://github.com/status-im/status-desktop/pull/2914) but it's not completed cause in the step when sender "Sign and Send" transaction, transaction bubble on the sender side is updated, transaction is received by recipient and funds are on account in his wallet, but transaction message bubble on the recipient side has not been updated.

**Comment by iurimatias** [comment] 2021-07-15 12:32
duplicate of #2915

**Closed by iurimatias** 2021-07-15 12:32 UTC
Labels: Chat, bug
