### ISSUE TITLE
Community History Archive service - missing messages

### ISSUE THREAD

**Issue by John-44** [status-im/status-desktop#10406] opened 2023-04-24 12:33 UTC
See screenshot below:

![2023-04-24_13-22-37](https://user-images.githubusercontent.com/22846356/233995374-b947aa7f-9125-46d8-9ee7-79464f5e084a.png)

After doing a fresh install of Status desktop one week ago, In the #infra channel I can only see messages from when the channel started in 2019 until 19th November 2020, and then the next message is see is from 24th April 2023.

So two questions here:

1) why are the messages from 19th November 2020 until 'the date the Discord export was run' missing?

2) why are the messages from 'the date the Discord export was run' until 24th April 2023 missing?

Perhaps there was an issue unpacking the messages (which could explain both issues)?  Or perhaps an issue with the export (check if other folks can see messages after 19th November 2020 in #infra) and another issue with creating new weekly archives? Or something else? ;-)

**Comment by caybro** [comment] 2023-04-24 12:40
The timestamp looks wrong too, can you pls create a separate ticket and assign it to me? ;) Thx

**Comment by John-44** [comment] 2023-04-24 12:58
> The timestamp looks wrong too, can you pls create a separate ticket and assign it to me? ;) Thx

@caybro wrong timestamp issue opened here https://github.com/status-im/status-desktop/issues/10408

**Comment by 0x-r4bbit** [comment] 2023-05-02 07:51
The timestamp in the message shown in this screenshot is correct. You can find it in discord here:
https://discord.com/channels/624205794384281629/626045898878877696/778920503611490304

So this indeed looks like there's a massive message gap. 
Question then is, what exactly is going on there.

There are a few options:

1. Some archives have not been downloaded (this is unlikely because the node only starts importing into the database once all archives have been downlaoded
2. All archvies are downloaded but not all have been imported. This should also not be the case, at least the node should keep importing messages from all archives that were previously downloaded

It's hard to tell without looking into the database. I do see all messages from discord in my installation.
So I think I'd have to look into your database @John-44 to figure out what's going on

**Comment by jrainville** [comment] 2023-11-23 18:25
This one is probably gonna be hard to fix.

@borismelnik at leats try to reproduce with a big import. If You can reproduce, check the code quickly to see if something maybe would cause the import to fail or abort before the end.

If you still find nothing, we can close and reopen when we have a repro state. We'd need to have the DB.

**Comment by iurimatias** [comment] 2024-02-14 19:25
moved to 2.29 due to lack of space in this milestone

**Comment by iurimatias** [comment] 2024-08-12 23:08
descoped for now

**Closed by iurimatias** 2024-08-12 23:08 UTC
Labels: bug, backend-team, E:Desktop Discord Import And Archive Protocol, Desktop Discord Import And Archive Protocol
