### ISSUE TITLE
App hangs after some time in the background

### ISSUE THREAD

**Issue by qoqobolo** [status-im/status-desktop#13543] opened 2024-02-13 14:54 UTC
# Bug Report

## Description

Sometimes the app freezes after being in the background for a while.
Other mobile QAs also have been facing the issue randomly for the last two weeks.
 
For me, this reproduces with the following conditions, but I'm not sure if all of them are directly related to the issue:
- enabled `Testnet mode`
- enabled `Manage communities on testnet`
- freezing happens most often when I'm on the community management screen, e.g. `Community overview` or `Permissions` or `Tokens`

I can't reproduce this at the moment of creating this issue but I faced it a couple of times during the day.

[geth-2024-02-13T13-50-27.679.log.zip](https://github.com/status-im/status-desktop/files/14267731/geth-2024-02-13T13-50-27.679.log.zip)
[geth 2.log.zip](https://github.com/status-im/status-desktop/files/14267730/geth.2.log.zip)

## Steps to reproduce

1. Open app
2. Keep it open but continue using other apps for about 5 minutes
3. Try to use the Status app again

#### Expected behavior
The app works as before background

#### Actual behavior
The app freezes

### Additional Information

- Status desktop version: my version https://ci.status.im/job/status-desktop/job/systems/job/macos/job/x86_64/ 
however, we started randomly experiencing this about 2 weeks ago
- Operating System: 
MacBook Pro Sonoma 14.3 (Intel)
MacBook Pro macOS Monterey v.12 (chip Apple M1 Pro)

**Comment by anastasiyaig** [comment] 2024-02-13 15:09
@iurimatias @jrainville

**Comment by igor-sirotin** [comment] 2024-03-01 14:33
I'm trying to reproduce this, but no luck so far.
But I can confirm I've seen this before with 2.27.

**Comment by igor-sirotin** [comment] 2024-03-07 12:39
I can't reproduce this anymore. 
@jrainville I'm tending to close the issue for now, wdyt?

**Comment by qoqobolo** [comment] 2024-03-07 12:46
This hasn't happened to me lately either.

**Comment by jrainville** [comment] 2024-03-07 14:28
Closing since Diana and Igor can't reproduce. We can reopen if it happens again

**Closed by jrainville** 2024-03-07 14:28 UTC
Labels: bug, messenger-team, E:Desktop Bugfixes 2.28.0

**Comment by alexjba** [comment] 2025-02-06 07:45
Seems to be back. Constantly reproducing on 2.32
