### ISSUE TITLE
Transaction history is empty when account is recovered from scratch

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#3444] opened 2021-09-09 09:13 UTC
1. recover account (no data folder present) with some transactions in history
2. open wallet -> History

Transactions are not shown, load more also does not help. Balances are shown fine though

Account: https://etherscan.io/address/0xf38d2cd3c6ad02dd6f8b68e0a7b2f959819954b6

<img width="1552" alt="Screenshot 2021-09-09 at 12 13 42" src="https://user-images.githubusercontent.com/82375995/132658295-9f884355-3da6-4f3a-96b8-c96b925e8d8a.png">

<img width="1552" alt="Screenshot 2021-09-09 at 11 32 44" src="https://user-images.githubusercontent.com/82375995/132658143-dba153fe-557a-478b-a4c3-dfe34404f19b.png">

**Comment by Khushboo-dev-cpp** [comment] 2022-01-07 10:14
The issue seems to be cause due to the use of an non-archival key . As discussed with @alaibe, the KEY is changes to an archival one during production. Hence this is not a bug, but just a limitation in a dev build.

**Comment by Khushboo-dev-cpp** [comment] 2022-01-07 10:46
Tried with desktop release version Version: 0.3.0-beta and it seems to work alright. closing this as it not a bug.

**Closed** 2022-01-07 13:25 UTC
Labels: bug, Wallet, to analyze, priority 1: high
