### ISSUE TITLE
Login failed. Please re-enter your password and try again

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#15846] opened 2024-07-29 07:56 UTC
### Description

Sometimes autotests encounter this:

![image](https://github.com/user-attachments/assets/aa476713-45a4-4916-910a-3883ec927ff1)

```
WRN 2024-07-29 07:11:40.448+00:00 Error decoding signal                      topics="signals-manager" tid=1958979 file=signals_manager.nim:49 err="Unknown signal received: mediaserver.started"
ERR 2024-07-29 07:11:42.477+00:00 node.crashed                               topics="signals-manager" tid=1958979 file=signals_manager.nim:58 error="{\"type\":\"node.crashed\",\"event\":{\"error\":\"listen tcp 0.0.0.0:8545: bind: address already in use\"}}"
ERR 2024-07-29 07:11:42.477+00:00 node.login                                 topics="signals-manager" tid=1958979 file=signals_manager.nim:54 error="listen tcp 0.0.0.0:8545: bind: address already in use"
DBG 2024-07-29 07:11:42.477+00:00 app state changed                          tid=1958979 file=view.nim:122 state=StartupState
ERR 2024-07-29 07:11:42.478+00:00 login error                                topics="app-controller" tid=1958979 file=module.nim:406 methodName=onNodeLogin errDesription="listen tcp 0.0.0.0:8545: bind: address already in use"
```

[geth.log](https://github.com/user-attachments/files/16409347/data_attachments_de3acbd6fc6d33bf.txt)

**Comment by anastasiyaig** [comment] 2024-07-29 07:57
@MishkaRogachev @igor-sirotin please take a look

**Comment by jrainville** [comment] 2024-07-29 14:49
@MishkaRogachev if you can't reproduce and it's mostly on Windows, @kounkou can take it

**Comment by anastasiyaig** [comment] 2024-07-29 14:57
@jrainville actually i noticed that with my tests from linux

**Comment by kounkou** [comment] 2024-07-29 15:49
Hey, which branch/version is this ?

**Comment by anastasiyaig** [comment] 2024-07-29 15:51
thats master at some moment , i did not note the exact commit i am sorry :(

**Comment by kounkou** [comment] 2024-07-30 19:24
That's interesting, last time the error was reproducible. Did any of you reproduce the issue? I have tried on Linux as of now and nothing. I am thinking of analyzing since when the issue started happening after I merged the last [fix](https://github.com/status-im/status-desktop/commit/5db513980f4d9230971785f31f725174c0db3078)

**Comment by kounkou** [comment] 2024-07-30 19:56
Current proposal from @anastasiyaig is that the issue is monitored by `QA`, and more data are provided before Backend team can work on it. Which I accepted, transferring the issue to QA on common aggreement.

**Comment by anastasiyaig** [comment] 2024-07-31 07:00
i will do some research , moved this task to 2.31 @jrainville

**Comment by anastasiyaig** [comment] 2024-08-06 06:55
i saw it today in https://github.com/status-im/status-desktop/pull/15980 for example @jrainville 

https://ci.status.im/job/status-desktop/job/e2e/job/prs/1620/allure/#suites/ea35bd66d78deeec4a096260dd1d8144/a3b8fdb9e9c26567/

![image](https://github.com/user-attachments/assets/3525cbbc-e5eb-4373-bcdc-5d53ccddd1a2)

**Comment by anastasiyaig** [comment] 2024-08-06 09:56
also , autotests encountered the same in nightly run https://ci.status.im/job/status-desktop/job/nightly/459/
commit 2352a96b7e0c2b9b3f48ddbd207ca8b3a7df89ab, Linux

**Comment by igor-sirotin** [comment] 2024-08-06 21:44
@anastasiyaig in these tests, do you start 2 instances at the same time?
I mean, they're lunched consequently, or in they're opened together in parallel?

It seems to be that the issue can happen like this:
1. `Instance 1`: check if the port `8545` is free here:
https://github.com/status-im/status-desktop/blob/8754b0193dc70f746e00ff30fe4774f840a82de4/src/app_service/service/accounts/dto/api_config.nim#L24
2. `Instance 1`: find the port free, pass it to status-go
3. `Instance 2`: starting, also find the port free, instruct status-go to use the port
4. `Instance 1`: actually start using the port
5. `Instance 2`: try to use the port, it's busy.

**Comment by anastasiyaig** [comment] 2024-08-07 07:37
@igor-sirotin the intention of the test is to start instances one by one

this is the code of starting application (first step i start it)

https://github.com/status-im/status-desktop/blob/bef66612c55452bfec0dc3662048cd8700f2f727/test/e2e/driver/aut.py#L96

second step, i attach to it
https://github.com/status-im/status-desktop/blob/bef66612c55452bfec0dc3662048cd8700f2f727/test/e2e/driver/aut.py#L79

this is the fixture (a hook) that launches multiple instances
https://github.com/status-im/status-desktop/blob/bef66612c55452bfec0dc3662048cd8700f2f727/test/e2e/fixtures/aut.py#L62

the code could be buggy, its a subject to inspect for sure. However this is the method looking for free port:
https://github.com/status-im/status-desktop/blob/bef66612c55452bfec0dc3662048cd8700f2f727/test/e2e/scripts/utils/local_system.py#L28

**Comment by anastasiyaig** [comment] 2024-08-07 09:56
i suspect the app within automation uses 2 ports. one port is needed to establish squishserver thing for instance (we use 61500 port for example) but we dont really care about port required for status go it seems.. I wonder why tests are working 90% of time, and fail only sometimes with this issue :( and it seem to be working fine when I launch the apps on the machine manually

**Comment by igor-sirotin** [comment] 2024-08-07 16:59
Alright. I guess it's not that simple to fix on our side.
Is it possible in e2e tests to wait for the first app instance to fully launch, and only then start the second instance? Or even some simple delay should help.

## Details

Would be ideal is to ignore the `listen tcp` error and continue starting the app. But the PRC server is deep inside go-ethereum ( `startGethNode` -> `openEndpoints` -> `startRPC` -> `httpServer.start` -> `net.Listen`):
https://github.com/status-im/status-go/blob/fc836e4c762c4c8e6e5d6318a8c87a682f404adc/vendor/github.com/ethereum/go-ethereum/node/rpcstack.go#L143

And we get the error somewhere here:
https://github.com/status-im/status-go/blob/fc836e4c762c4c8e6e5d6318a8c87a682f404adc/vendor/github.com/ethereum/go-ethereum/node/rpcstack.go#L143

Soooo...
Modifying `go-ethereum` for this is not the right solution.

I tried to catch this error in status-go and start again without RPC server:
```go
func (n *StatusNode) startGethNode() error {
	err := n.gethNode.Start()
	if err == nil {
		return nil
	}
	if !strings.Contains(err.Error(), "address already in use") {
		return err
	}
	n.log.Warn("RPC address is already in use, trying to start without RPC server", "error", err)
	n.gethNode.Config().HTTPHost = ""
	return n.gethNode.Start()
}
```

It didn't work, I get `failed to start node: node not started` error. Because you need to fully recreate the `Node` to try to start it again.

I tried to move the same logic to a higher level, to `LoginAccount`. Get error `failed to start node: node is already running`.

And if I simply close the app that holds port `8545` and login to second instance (without restarting after failure), I'm also not able to login. So it seems to be not really possible in current status-go architecture 🙁

**Comment by igor-sirotin** [comment] 2024-08-07 16:59
Yet, in real world it will happen super rarely. You have to login into 2 instances at the same time. Then there's a race condition.

**Comment by anastasiyaig** [comment] 2024-08-07 17:02
i think @antdanchenko is planning to run tests in docker, that should perhaps deal with that situation. 
meanwhile @igor-sirotin what condition should met to consider the app fully launched? I could try to match it with tests for now :)

**Comment by igor-sirotin** [comment] 2024-08-07 17:03
> What condition should met to consider the app fully launched? 

Just wait till the user is logged in. That's when you land to the main screen of the app.
This should be enough (if my guess above is correct).

**Comment by anastasiyaig** [comment] 2024-08-07 17:42
okay so how it is working now is : test launches as many apps as needed (for example 3). then focuses on app1. logins and does what he is planned to do, then switches to app2 and so on. So the only problem i see is that i keep 3 instances open on the very first screen after launch. I think i can fix it but dont yet know how :) will think about it

**Comment by igor-sirotin** [comment] 2024-08-07 17:54
So all 3 instances hang on login screen first. And then you login them one by one consequently.
is this right?

Then my guess is wrong I suppose 🤔

**Comment by anastasiyaig** [comment] 2024-08-07 17:55
@igor-sirotin but i also see this problem when i restart the app it seems https://ci.infra.status.im/job/status-desktop/job/systems/job/linux/job/x86_64/job/tests-e2e-new/419/allure/#suites/24b8faf696a2de3bee3049f40dc0316e/4267ce61a497fd8e/

**Comment by anastasiyaig** [comment] 2024-08-07 17:57
> So all 3 instances hang on login screen first. And then you login them one by one consequently.
> is this right?

yes, thats the only way, as Squish operates with Application context and it could be only one attached to driver at the same time. So i attach to the app i need, do what i need, then i re-attach to another one

**Comment by igor-sirotin** [comment] 2024-08-07 17:59
Then indeed my guess is wrong. It's pretty weird though, not sure how to deal with it.
We could provide some env variables to control wether to enable RPC server or not.
@anastasiyaig let me know how painful it is now and if you're not able to tackle it in tests. We should be able to provide way to disable RPC server.

**Closed** 2024-08-15 12:44 UTC
Labels: bug, autotest-blocker, 2-30-bug-bash, core-team
