### ISSUE TITLE
Contact request remains active in AC after acceptance

### ISSUE THREAD

**Issue by saledjenic** [status-im/status-desktop#8592] opened 2022-12-02 15:16 UTC
When I got a new contact request I got it in `Contacts` of `Chat` section and in `Activity Center`, after I accepted it via `Contacts` it still remained in the same unchanged state in the `Activity Center` (as shown on the image below) and I was able to click there without any effect.

![ContactRequest](https://user-images.githubusercontent.com/86303051/205325522-d25bc483-fd18-4e0c-9b99-4d12a166df41.png)

**Comment by caybro** [comment] 2022-12-02 15:27
Possibly a duplicate of: https://github.com/status-im/status-desktop/issues/7851

**Closed** 2022-12-05 11:57 UTC
Labels: bug, Chat, Activity_center, E:ActivityCenter
