### ISSUE TITLE
User picture is different on onboarding screen and profile after upgrade 

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#5562] opened 2022-04-15 11:22 UTC
### Description

1. install Beta 3
2. do not set any custom user picture
3. join some chats
4. install latest master on top of the build ( upgrade)
5. open login screen
6. login and open profile

<img width="1512" alt="Screenshot 2022-04-15 at 14 19 15" src="https://user-images.githubusercontent.com/82375995/163565053-f5653f05-c368-4ca7-8cbc-056efbe0bf75.png">

<img width="1512" alt="Screenshot 2022-04-15 at 14 18 55" src="https://user-images.githubusercontent.com/82375995/163565059-9b27e8e2-a471-4499-804d-ddb99620d376.png">

**Comment by iurimatias** [comment] 2022-05-23 20:35
duplicate of #5838

**Closed by iurimatias** 2022-05-23 20:35 UTC
Labels: bug, onboarding, priority 3: low, E:Onboarding
