### ISSUE TITLE
Community: Need to delete the bad-looking stickers pack 'Status Blue Fire'

### ISSUE THREAD

**Issue by elina2015** [status-im/status-desktop#8563] opened 2022-12-02 01:02 UTC
# Bug Report

## Steps to reproduce
1. Go to chat or a community
2. Open the sticker's pack 'Status Blue Fire'

#### Expected behavior
Only good and professional-looking stickers packs are available for our users
#### Actual behavior
The pack looks very bad and we need to delete it
<img width="247" alt="image" src="https://user-images.githubusercontent.com/14942081/205191050-350caa1b-5ce6-46e0-ac20-2f2017e071e4.png">

### Additional Information

Status desktop version: https://github.com/status-im/status-desktop/releases/tag/0.8.0-rc.9
Operating System: macOS Monterey

**Comment by du64** [comment] 2022-12-02 01:49
If I want to fork Status and add my own stickers, how would I do that?

**Comment by iurimatias** [comment] 2023-01-09 17:14
closing as it's not a bug per se, but a feature request / something to discuss in regards to the stickers

**Closed by iurimatias** 2023-01-09 17:14 UTC
Labels: bug, Communities
