### ISSUE TITLE
Syncing -> biometrics: failed biometrics prompt screen is broken

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#11420] opened 2023-07-05 12:26 UTC
### Description

<img width="1547" alt="Screenshot 2023-07-05 at 14 39 46" src="https://github.com/status-im/status-desktop/assets/82375995/121df2fe-6cdc-4b6d-b6ef-3ce776387ef4">

<img width="1547" alt="Screenshot 2023-07-05 at 14 39 51" src="https://github.com/status-im/status-desktop/assets/82375995/c110fdc6-a833-4149-b5b1-4909da42c71e">

**Comment by alexjba** [comment] 2023-07-07 10:31
Duplicate of https://github.com/status-im/status-desktop/issues/11335
It's the same popup

**Closed by alexjba** 2023-07-07 10:31 UTC
Labels: bug, ui-team
