### ISSUE TITLE
Refactor contacts' user models to have only one model that is filtered on the UI side

### ISSUE THREAD

**Issue by jrainville** [status-im/status-desktop#16549] opened 2024-10-18 18:50 UTC
### Description

Similar to https://github.com/status-im/status-desktop/issues/16433

In the contacts module, there are 5 models for the different types of contacts:

- contactsModel: **all** the known users aka contacts
- myMutualContactsModel: the contacts that we added and were also added
- blockedContactsModel: people we blocked
- receivedContactRequestsModel: contacts that sent us contact requests
- sentContactRequestsModel: contacts to whom we sent a contact request

All those models could be deleted and we only keep `contactsModel` and then use SortFilterProxyModels on the QML side to filter the right contacts for the different lists.

**Comment by jrainville** [comment] 2024-10-18 18:55
Also, the way we update items is **very** bad. We remove all items from the models and then replace them with new items. That is highly ineffective

```nim
proc removeIfExistsAndAddToAppropriateModel(self: Module, publicKey: string) =
  self.removeItemWithPubKeyFromAllModels(publicKey)
  let item = self.createItemFromPublicKey(publicKey)
  self.addItemToAppropriateModel(item)
```

**Comment by micieslak** [comment] 2024-10-31 18:30
Seems to be duplicate of https://github.com/status-im/status-desktop/issues/14966

**Comment by jrainville** [comment] 2024-10-31 18:51
> Seems to be duplicate of [#14966](https://github.com/status-im/status-desktop/issues/14966)

Indeed. I think maybe we can just close #14966 since I already linked my own issue to the PR?

@alexjba can you check both issues and the PR to see if I indeed covered what you proposed.

**Closed** 2024-11-28 14:15 UTC
Labels: refactor, core-team, goal:core:P0:no_critical_or_high_regressions
