### ISSUE TITLE
Accept invitation (tap Join button) functionality is missing when being [invited] to community that requires approval from mobile

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#2509] opened 2021-05-06 16:40 UTC
**NOTE:** _**there is significant difference between ### SHARE and ### INVITE community flows on mobile**_

**Steps:**

1. as a mobile (device A) -> create a community that requires approval to join
2. as a mobile (device A) -> add desktop (device B) to contacts
3. as mobile (device A) -> go to community you just created and tap + button -> invite people
4. as mobile (device A) -> select desktop (device B) to send an invitation to join the community

**As a result on device B (desktop):**

- community invitation is appeared in 1x1 chat as joined
- user is autojoined the community 

**Expected result:** user should bypass the accepting invitation flow (tap Join to confirm the will to join it). No auto join flow should be present. NOTE: since this is **invitation**  and not sharing -> no request access flow expected (this is working correctly).

<img width="1431" alt="Screenshot 2021-05-06 at 19 35 18" src="https://user-images.githubusercontent.com/82375995/117334521-c2bc7e00-aea2-11eb-8cb8-9de5a59b9b49.png">

**Comment by jrainville** [comment] 2021-05-18 17:54
This is an issue that is on the status-go side. hen the admin send an invite, it autojoins the user, so the front-end just reacts accordingly.

This is a discussion with should have with the others to see if we want to change it in status-go

**Comment by guylouis** [comment] 2021-05-20 14:27
See a temptative here https://github.com/status-im/status-react/issues/12135 to summarizz how communities invitation/sharing works in 'require approval' type of communities. 

Taking this into account, the behaviour as seen on desktop and described in this issue is the intended behaviour (the admin can invite anyone to the community and he'll automatically be a member, this is different from sharing), and this issue can be closed.

**Comment by jrainville** [comment] 2021-05-20 14:50
Makes sense, I'll close this

**Closed by jrainville** 2021-05-20 14:50 UTC
Labels: Communities, bug
