### ISSUE TITLE
Sent messages loose formatting after editing

### ISSUE THREAD

**Issue by 0x-r4bbit** [status-im/status-desktop#10680] opened 2023-05-15 08:51 UTC
Today I wrote a message in our `#travel-requests` channel. The message was formatted like a description list a la

```
**Item**: Description
**Item2**: Description2
**Item3**: Description3 
```
etc. Unfortunately I don't have a screenshot of the original message anymore, but after noticing that there was a typo, I've edited the message, fixed the typo, and after saving the message looked like this:

![Screenshot from 2023-05-15 10-46-43](https://github.com/status-im/status-desktop/assets/445106/eddc429c-1662-4254-827d-9d931ad08848)

Some things broke here:

- All description items lost their formatting (eg `Event`, `Date`, `Goal` etc should be bold)
- The mention of  @jrainville just... got neutralized or something?

I know we have a bunch of problems with message formatting, but I wasn't expecting it to be gone entirely + mentions breaking after editing a message.

**Comment by jrainville** [comment] 2023-05-15 13:31
Duplicate of https://github.com/status-im/status-desktop/issues/7804

**Closed by jrainville** 2023-05-15 13:31 UTC
Labels: bug, ui-team
