### ISSUE TITLE
Wallet - Collectibles view with two foldable sections

### ISSUE THREAD

**Issue by micieslak** [status-im/status-desktop#13194] opened 2024-01-11 15:49 UTC
## Description

View of collectibles divide into two foldable sections with behavior analogous to assets view where regular list view is used.

![image](https://github.com/status-im/status-desktop/assets/20650004/ec6a3bf7-3ad4-4e4b-857e-1c7383e66e5e)

Depends on: https://github.com/status-im/status-desktop/issues/13193

**Comment by alexandraB99** [comment] 2024-01-22 17:04
Duplicate of https://github.com/status-im/status-desktop/issues/13045

**Closed by alexandraB99** 2024-01-22 17:04 UTC
Labels: ui-team, wallet-team, feature
