### ISSUE TITLE
Wallet - Add account - invalid private key results with native dialog with message

### ISSUE THREAD

**Issue by micieslak** [status-im/status-desktop#6984] opened 2022-08-11 15:22 UTC
# Bug Report

When invalid PK is provided, e.g.: 0x0000000000000000000000000000000000000000000000000000000000000000,
native dialog is displayed with some status-go errors.

## Steps to reproduce

Wallet -> Add account:
- Advanced: change to "Generate from Private key"
- set correct password
- set account name
- set invalid private key e.g. 0x0000000000000000000000000000000000000000000000000000000000000000
- press "Add Account"

https://user-images.githubusercontent.com/20650004/184167372-8bd8b923-86cb-4074-af45-f4aee8fbc456.mp4

#### Expected behavior

The proper validation is handled on the qt/qml side.

#### Actual behavior

Status-go error is displayed directly.

### Additional Information

- Status desktop version:
- Operating System: Ubuntu

**Comment by stefandunca** [comment] 2022-08-29 08:57
I can't reproduce and judging by the code and discussing with @micieslak it seems to be fixed by https://github.com/status-im/status-desktop/pull/6992

**Comment by stefandunca** [comment] 2022-08-29 13:33
Wanted to create another issue to remove the workaround of hiding the validation as a password error:  https://github.com/status-im/status-desktop/blob/master/ui/app/AppLayouts/Wallet/popups/AddAccountModal.qml#L63

Decided to fix it using this one and remove the dialogue that shows status-go errors completely from the code.

**Closed** 2022-08-30 17:05 UTC
Labels: bug, Wallet, E:Bugfixes, E:Wallet
