### ISSUE TITLE
Strange snippet of HTML code sent as a regular chat message

### ISSUE THREAD

**Issue by zah** [status-im/status-desktop#8624] opened 2022-12-05 12:25 UTC
# Bug Report

## Description

I'm sorry for the poor quality of this bug report, but I'm not sure what I did to trigger the bug below. All my attempts to reproduce it have failed so far. I hope that the peculiar HTML code visible below will help someone identify the root cause:

## Steps to reproduce

While trying to mention another user in the chat, I've ran into the known https://github.com/status-im/status-desktop/issues/7686 issue. Haven't seen this issue before, I naturally tried to understand what's going on by sending another message featuring a similar mention. To my surprise, the client inserted a short blurb of HTML code (probably related to how the mention is being rendered in the client?) before the second message I sent, even though this time it rendered the mention correctly.

I wasn't sure what I did to make this happen as follow up attempts to do the same was not successful:

<img width="924" alt="image" src="https://user-images.githubusercontent.com/175462/205632397-35d1a010-f2e1-45b1-ab40-6e2e51c2b023.png">

### Additional Information

- Status desktop version: 0.8
- Operating System: macOS

**Comment by caybro** [comment] 2022-12-05 12:26
Duplicate of https://github.com/status-im/status-desktop/issues/8495

**Closed by caybro** 2022-12-05 12:26 UTC
Labels: bug
