### ISSUE TITLE
Identity ring in onboarding screen is gone

### ISSUE THREAD

**Issue by 0x-r4bbit** [status-im/status-desktop#8615] opened 2022-12-05 11:25 UTC
![Screenshot from 2022-12-05 12-22-31](https://user-images.githubusercontent.com/445106/205625806-998b39db-afcf-45bf-b2d8-78716112cbe0.png)

This is in latest master (`97190ce71`)

**Comment by caybro** [comment] 2022-12-08 10:07
Duplicate of https://github.com/status-im/status-desktop/issues/8551

**Closed by caybro** 2022-12-08 10:07 UTC
Labels: bug, ui, E:Onboarding
