### ISSUE TITLE
Community -> Minting: No redirect to Tokens screen when minting a token

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#11731] opened 2023-08-01 10:24 UTC
### Description

I am stuck on this screen even the transaction for minting is completed a while ago. I think we did the redirect to Tokens page where we show `Minting` status for a token

<img width="1650" alt="Screenshot 2023-08-01 at 12 56 49" src="https://github.com/status-im/status-desktop/assets/82375995/914b65a9-5e3f-4907-85ab-f25f049222a5">

**Comment by anastasiyaig** [comment] 2023-08-01 10:24
@noeliaSD can u please check this out?

**Comment by noeliaSD** [comment] 2023-08-01 11:17
> @noeliaSD can u please check this out?

Sure! I'll assign to myself!

Yes, it should redirect to the "main" page with the list of tokens already minted. 

1. Can you confirm if the toast message with the `minting complete` information is displayed? 

2. The page you provide seems to be the one BEFORE minting, since the `Mint` button is present and fees calculation is in progress. So.. Can you confirm if the steps to reproduce are:

- Start minting process, fill the form and click `Preview`.
- It navigates to the preview page, then you press `Mint`.
- It navigates to the send transactions modal, and you accept the transaction.
- It shows the toast messages.
- Then, instead of moving back to the list, it moves back to `Preview` page.

**Comment by anastasiyaig** [comment] 2023-08-01 11:20
yes confirmed that! @noeliaSD 


https://github.com/status-im/status-desktop/assets/82375995/15e4490d-94e2-4f3d-a864-bbc25fa53134

**Closed** 2023-08-02 13:55 UTC
Labels: bug, ui-team, C3, E:Desktop Comm Perms and Minting MVP
