### ISSUE TITLE
[Account restore] App freezes after fetching data failed

### ISSUE THREAD

**Issue by lukaszso** [status-im/status-desktop#12350] opened 2023-10-05 11:01 UTC
The app freezes when the user wants to continue (try again or create new account) after fetching data failed.

## Steps to reproduce

1. Open the app
2. Attempt to restore an account via seed phrase or keycard
3. When fetching data fails click Continue
4. Choose "Try to fetch profile again" or "Create new profile with the same chatkey"

#### Expected behavior
App allows the user to continue the flow and retry the fetching process or create a new profile

#### Actual behavior
App freezes.

### Additional Information
Logs:
[log.txt](https://github.com/status-im/status-desktop/files/12817571/log.txt)

- Status desktop version: master from CI StatusIm-Desktop-231005-090506-a9ebf7
- Operating System: macOS Ventura 13.4

**Comment by jrainville** [comment] 2023-10-05 13:58
I tried reproducing on latest master and also using the same build as you @lukaszso but I didn't experience the same freeze.

I wonder if it's a problem with the particular seed you were using or if it's the OS. I tried on Ubuntu 20.

Do you have another OS you can try that same seed on?

**Comment by jrainville** [comment] 2023-10-26 18:59
I still can't reproduce it. I'll close it for now. Reopen if you experience it again

**Closed by jrainville** 2023-10-26 18:59 UTC
Labels: bug, messenger-team, E:Desktop Bugfixes 0.15
