### ISSUE TITLE
app log timestamp is revealing user's timezone

### ISSUE THREAD

**Issue by chaitanyaprem** [status-im/status-desktop#16154] opened 2024-08-20 05:06 UTC
# Bug Report

## Description
Noticing that app logs are generated in user's timezone which reveals user location.
If logs are generated in UTC time, when they are shared for debugging or any other purpose user's location will not be revealed.

All logs in status-go and go-waku use UTC time.

## Steps to reproduce

Run desktop and look at app.log

#### Expected behavior
Logs should use UTC time

#### Actual behavior
Logs are using user's timezone

### Additional Information

- Status desktop version: latest master 224dd5e58d9fbd886cf16aceb6e1fec9d5693993
- Operating System: any

**Comment by jrainville** [comment] 2024-08-20 14:48
Duplicate of https://github.com/status-im/status-desktop/issues/15198

**Closed by jrainville** 2024-08-20 14:48 UTC
Labels: bug, core-team
