### ISSUE TITLE
"Start chat" takes precedence over settings

### ISSUE THREAD

**Issue by Menduist** [status-im/status-desktop#8588] opened 2022-12-02 14:29 UTC
# Bug Report

## Description

![image](https://user-images.githubusercontent.com/13471753/205314798-f468b475-68dc-4097-85f1-e258483e1503.png)
## Steps to reproduce

Click on "Start chat"
Go to settings

#### Expected behavior
See the settings

### Additional Information

- Status desktop version: 0.8.0
- Operating System: Arch

**Comment by PascalPrecht** [comment] 2022-12-02 14:58
This seems to be a duplicate of https://github.com/status-im/status-desktop/issues/7675

**Closed by PascalPrecht** 2022-12-02 14:58 UTC
Labels: bug
