### ISSUE TITLE
Some channels are being shown out of category in community for dogfooding

### ISSUE THREAD

**Issue by osmaczko** [status-im/status-desktop#10618] opened 2023-05-10 13:13 UTC
# Bug Report

## Description

AFAIR `standups` channel should is within `Core Mobile` category.

![image](https://github.com/status-im/status-desktop/assets/33099791/6eb1ba28-0237-4f54-921a-293038bea86d)

## Steps to reproduce

Open the app after migration from 0.11.0 to 0.12.0 RC1

#### Expected behavior

Channels in proper categories

#### Actual behavior

Channels out of category

### Additional Information

- Status desktop version: 0.12.0 RC1
- Operating System: Ubuntu 22

**Comment by anastasiyaig** [comment] 2023-05-10 13:17
could that have been done on purpose? To have them on top?

**Comment by iurimatias** [comment] 2023-05-10 13:21
duplicate of https://github.com/status-im/status-desktop/issues/10381

**Comment by jrainville** [comment] 2023-05-10 14:12
I don't think this is a duplicate. The one Magnus created was on Channel creation and this on is for everyone else that the channels are not ordered correctly (alledgedly)

**Closed** 2023-05-17 18:07 UTC
Labels: bug, Chat, messenger-team
