### ISSUE TITLE
[dogfooding] reply original message is empty for some replies

### ISSUE THREAD

**Issue by flexsurfer** [status-im/status-desktop#8158] opened 2022-11-08 08:44 UTC
<img width="314" alt="image" src="https://user-images.githubusercontent.com/11790366/200517086-4469b59d-ed79-4145-ac34-2fc9e2cc8edc.png">

**Comment by flexsurfer** [comment] 2022-11-08 08:44
does that mean i miss messages ?

**Comment by PascalPrecht** [comment] 2022-11-08 09:40
I believe that means the messages being replied to do not exist in your memory.
I"ve experienced this as well, see https://github.com/status-im/status-desktop/issues/7248

**Comment by flexsurfer** [comment] 2022-11-08 09:42
i believe we somehow show them on mobile

**Comment by PascalPrecht** [comment] 2022-11-08 09:46
@jrainville should we close those in favour of #7248

**Comment by jrainville** [comment] 2022-11-11 15:10
Yes, this is a duplicate of https://github.com/status-im/status-desktop/issues/7248

**Closed by jrainville** 2022-11-11 15:10 UTC
Labels: bug, Chat
