### ISSUE TITLE
Unclear how to open invitation from browser to Desktop app

### ISSUE THREAD

**Issue by fryorcraken** [status-im/status-desktop#15072] opened 2024-06-06 09:31 UTC
# Bug Report

## Description

I have a link to a community, opened it in Firefox.
I have Status Desktop install.

No idea where to click to open this community in my Status Desktop app.

![image](https://github.com/status-im/status-desktop/assets/110212804/7d7b6508-5d80-48a5-a48a-7e836951e11a)

## Steps to reproduce

1. Get a community link
2. Open it in Firefox

#### Expected behavior

3. Clear button to click to open in Desktop

#### Actual behavior

3. Wonder

### Additional Information

- Status desktop version: 2.28.1 app image
- Operating System: Linux c86_64

**Comment by jrainville** [comment] 2024-06-06 16:29
I'm gonna close this as a duplicate of https://github.com/status-im/status-desktop/issues/8027

Basically, we don't support deep links on Linux for now. It's a bit more complex than other OSes since we need to re-do how we package the app.

We're gonna try to get it done for 2.30

**Closed by jrainville** 2024-06-06 16:29 UTC
Labels: bug
