### ISSUE TITLE
[Wallet]: Buying stickers doesn't work and popup may be misleading for the user

### ISSUE THREAD

**Issue by micieslak** [status-im/status-desktop#15764] opened 2024-07-24 09:41 UTC
# Bug Report

## Description

When `Send Modal` is opened from stickers menu, the routes are not found, and transfer is not possible:

![Screenshot from 2024-07-24 11-11-14](https://github.com/user-attachments/assets/41f2f90e-f7ef-4dd4-ac92-c6b0e552d9aa)

However it's possible to copy the address and use regular `Send Modal` to send the funds. The user may expect that it will lead to buying related stickers:

![Screenshot from 2024-07-24 11-07-17](https://github.com/user-attachments/assets/d4bd937f-e221-4f3b-a7a9-f1686bc6d458)

The transaction is done:

![Screenshot from 2024-07-24 11-40-31](https://github.com/user-attachments/assets/3bd6c34f-0fe7-4f3d-ae7a-e33407480131)

But the list of stickers remains empty:

![Screenshot from 2024-07-24 11-14-43](https://github.com/user-attachments/assets/e7a3590e-268a-4b59-bd11-05dc69c29577)

#### Expected behavior
Bought stickers appear in stickers menu.

#### Actual behavior
No stickers, funds seem to be lost.

**Comment by anastasiyaig** [comment] 2024-07-24 11:37
@micieslak i doubt user can do that as sending is not equal to contract interactions, but we need to clarify with @saledjenic

**Comment by anastasiyaig** [comment] 2024-07-24 11:39
@xAlisher maybe you have thoughts on this?

**Comment by saledjenic** [comment] 2024-07-24 11:48
> @micieslak i doubt user can do that as sending is not equal to contract interactions, but we need to clarify with @saledjenic other words, it is nothing to do with stickers address. user can paste any address he wants, no matter which one is that. 

Yes, you're right. Sending to the contract address from the Send modal doesn't buy stickers. That's just a sent to the desired address. Running the Send modal form the clicking on buy button for certain sticker is something different, we use the same Send modal for this, but the data being sent in that case are prepared differently, it's a contract interaction in that case.

For the first screenshot form the description, it's odd that you didn't get the route. It could be up to the provider issue (we should always try at least twice before saying it's an issue), but in case this is a real issue you should try after the latest improvements for the Router get merged on the statusgo side.

**Comment by micieslak** [comment] 2024-07-24 11:55
I've reported this ticket from the user perspective which many have no insight how it works under the hood. Te `Send modal` for stickers looks as EXACTLY the same thing like for regular send. If it's not the case, there should be some explanation to the user that's special operation leading to real purchase because some additional metadata ara attached. And that "raw" send to that address is different operation.

**Comment by saledjenic** [comment] 2024-07-24 12:01
@micieslak I agree with that, we should be more expressive in that case, but I think that in Send modal, which is run from buy sticker button user should not be able to:
- change the amount,
- change the address,
- open advance or custom tab (since changing network is not possible in that case)

New issue which we can log if we don't have it yet:
An improvement for regular Send modal would be, after user enters the recipient address to check if the entered address is contract address and let user know that.

**Comment by micieslak** [comment] 2024-07-24 12:04
> @micieslak I agree with that, we should be more expressive in that case, but I think that in Send modal, which is run from buy sticker button user should not be able to:
> 
> * change the amount,
> * change the address,
> * open advance or custom tab (since changing network is not possible in that case)
> 
> **New issue which we can log if we don't have it yet:**
> 
> * An improvement for regular Send modal would be, after user enters the recipient address to check if the entered address is contract address and let user know that.

Yes, I agree. What I reported is an issue, what you wrote is a potential solution, or at lest part of solution because maybe some additional explanation to the user would be useful as well.

**Comment by saledjenic** [comment] 2024-07-24 12:05
Also I have to say that the title of the issue is not appropriate one "Attempt to buy stickers MAY lead to funds loss"
cause running Send modal and entering sticker's contract address and placing such transactions is not buying stickers, it's sending transaction (assets) to a certain address, the app cannot know your intention. :)

**Comment by caybro** [comment] 2024-07-24 12:05
> @micieslak I agree with that, we should be more expressive in that case, but I think that in Send modal, which is run from buy sticker button user should not be able to:
> 
> * change the amount,
> * change the address,
> * open advance or custom tab (since changing network is not possible in that case)

That is all true, all these values are fixed when launched from Buy stickers and can't be changed by the user

**Comment by micieslak** [comment] 2024-07-24 12:33
> Also I have to say that the title of the issue is not appropriate one "Attempt to buy stickers MAY lead to funds loss" cause running Send modal and entering sticker's contract address and placing such transactions is not buying stickers, it's sending transaction (assets) to a certain address, the app cannot know your intention. :)

I don't know how to name it. If changed it but if you have better idea, please update.

**Closed** 2024-07-25 14:30 UTC
Labels: bug, ui-team, E:Desktop Send Bridge Modal Bug MVP, wallet-core-team, E:D Wallet SendModal, 2-30-bug-bash
