### ISSUE TITLE
Channel list in community view scrolls horizontally

### ISSUE THREAD

**Issue by PascalPrecht** [status-im/status-desktop#7683] opened 2022-09-30 06:46 UTC
Can't really see this on the screenshot, but if you create a community and have a channel, you can horizontally wobble the contents of the left panel.

![Screenshot from 2022-09-30 08-43-58](https://user-images.githubusercontent.com/445106/193207691-bd49daab-553a-49bd-bf97-e5004cddcc1e.png)

**Comment by micieslak** [comment] 2022-10-17 11:01
I cannot reproduce. @PascalPrecht could you check if it still happends?

**Comment by micieslak** [comment] 2022-10-17 11:13
It happens in `0.7.0-beta` but works as expected on master for the exactly same data. I think we can close it.

**Closed by micieslak** 2022-10-17 11:13 UTC
Labels: ui, E:Communities

**Comment by PascalPrecht** [comment] 2022-10-20 09:14
Sorry, I didn't get to respond here quickly enough. Yes this has been fixed by a short while ago, but apparently this issue was not referenced/closed.
