### ISSUE TITLE
crash after accepting contact request

### ISSUE THREAD

**Issue by iurimatias** [status-im/status-desktop#4826] opened 2022-02-16 14:56 UTC
# Bug Report

## Description

accepted a contact request and crashed shortly after with this trace

```
ERR 2022-02-16 09:54:13.832-05:00 rpc response error                         topics="rpc" tid=824085 file=core.nim:34 err="\nstatus-go error [methodName:wakuext_addContact, code:-32000, message:add-contact: invalid id ]\n"
INF 2022-02-16 09:54:13.832-05:00 shutting down...                           topics="status-app" tid=824085 file=nim_status_client.nim:115
Object 0x7fa3130bef00 destroyed while one of its QML signal handlers is in progress.
Most likely the object was deleted synchronously (use QObject::deleteLater() instead), or the application is running a nested event loop.
This behavior is NOT supported!
qrc:/app/AppLayouts/Chat/popups/ContactRequestsPopup.qml:45: function() { [native code] }
Traceback (most recent call last)
```

**Comment by saledjenic** [comment] 2022-02-22 09:10
@iurimatias I cannot reproduce this, are there any specific steps for this or? Tried on mainnet and on ropsten network, but all good. Maybe it's fixed in meantime? 

@anastasiyaig please try to reproduce it when you can.

**Comment by anastasiyaig** [comment] 2022-02-22 10:01
@saledjenic i cant reproduce it in master now

**Comment by anastasiyaig** [comment] 2022-02-23 09:31
@iurimatias i will close this one for now, lets see if u can reproduce in master too

**Closed by anastasiyaig** 2022-02-23 09:31 UTC
Labels: bug, Chat, Communities, priority 1: high
