### ISSUE TITLE
Communities: token holders list is not always populated

### ISSUE THREAD

**Issue by micieslak** [status-im/status-desktop#12062] opened 2023-09-01 08:56 UTC
# Bug Report

## Description

Sometimes (with various frequency) the token holders list is empty. The only way to have it filled with actual holders is to restart the app.

[Kazam_screencast_00024.webm](https://github.com/status-im/status-desktop/assets/20650004/f697810f-7103-478a-b5c7-aa684c383e64)

## Steps to reproduce

1. Create community
2. Mint token
3. Airdrop to address (or member)
4. Rerun the app several times

#### Expected behavior
The token holders list always present holders.

#### Actual behavior
Every few starts the list is empty.

### Additional Information

- Status desktop version: master
- Operating System: Linux

**Comment by noeliaSD** [comment] 2023-11-28 12:34
@anastasiyaig I've added it into the bug fixing for this milestone since you closed [that](https://github.com/status-im/status-desktop/issues/12888) in favour of this. Update it accordingly in case it's not needed now! Thanks!

**Comment by anastasiyaig** [comment] 2023-11-28 12:46
it is still an issue, i closed my task as a duplicate of this bug

**Comment by endulab** [comment] 2023-12-13 10:55
I noticed that we also do not display assets aurdropped to community members.

**Closed** 2024-01-17 12:24 UTC
Labels: bug, messenger-team, E:Desktop Community Bugfixes MVP, E:Desktop Bugfixes 0.15.5, sprint-12-19
