### ISSUE TITLE
Wallet -> Activity view: clicking New transactions button results in error

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#11466] opened 2023-07-10 09:47 UTC
### Description

```
Warning: qrc:/app/AppLayouts/Wallet/views/TransactionDetailView.qml:346:17: QML DetailsPanel: Binding loop detected for property "height" (qrc:/app/AppLayouts/Wallet/views/TransactionDetailView.qml:346, )
abi: cannot marshal in to go slice: offset 21796157974083048550319244236929488537086114760591164995662691024316225107800 would go over slice boundary (len=128)
Warning: qrc:/app/AppLayouts/Wallet/views/TransactionDetailView.qml:417: TypeError: Cannot read property 'input' of null (qrc:/app/AppLayouts/Wallet/views/TransactionDetailView.qml:417, )
abi: cannot marshal in to go slice: offset 21796157974083048550319244236929488537086114760591164995662691024316225107800 would go over slice boundary (len=128)
```

**Steps:**
1. add `0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2` as watch only
2. open activity view and click New transactions button
3. check logs

**Comment by stefandunca** [comment] 2023-07-10 11:38
The report seems a side effect of opening the first transaction with hash `0x13314391098fca8c29fe07bb133504acd2db7ca2397399fef02efb6678a025c5`
Can be reproduced by opening the details panel when `wallet_fetchDecodedTxData` calls `eth_getBlockByNumber` which generates this error. Following it it seems to be an issue/log from the ethereum go lib while decoding the transaction data
@alaibe assigning you to this due to your recent work maybe can quickly tell if this is fixable or a data issue with that specific transaction.

**Comment by alaibe** [comment] 2023-07-10 12:21
Closing as fixed this morning

**Closed by alaibe** 2023-07-10 12:21 UTC
Labels: bug, wallet-team, hard-to-replicate, E:Bugfixes
