### ISSUE TITLE
Messaging: app self-closed with [Timers cannot be stopped from another thread]

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#8996] opened 2023-01-09 06:57 UTC
### Description

1. i had my 0.8.1 installed and some data folder in place
2. i removed the app (not the data folder)
3. i downloaded RC 1 for 0.9.0 https://ci.infra.status.im/job/status-desktop/job/release/job/release%252F0.9.x/1/ for Mac
4. i started the app from application folder (default installation path)

As result, the app was closed with:

`status-desktop` output leading to crash.
```log
2023-01-10T18:46:21.099+0400	[34mINFO[0m	net/identify	identify/id.go:369	failed negotiate identify protocol with peer	{"peer": "16Uiu2HAm4kUuM9mn32FQst7YBf4czVb1Q9VfDdsGo9AT25qicfVY", "error": "stream reset"}
2023-01-10T18:46:21.100+0400	[33mWARN[0m	net/identify	identify/id.go:334	failed to identify 16Uiu2HAm4kUuM9mn32FQst7YBf4czVb1Q9VfDdsGo9AT25qicfVY: stream reset
2023-01-10T18:46:21.099+0400	[34mINFO[0m	net/identify	identify/id.go:369	failed negotiate identify protocol with peer	{"peer": "16Uiu2HAm4kUuM9mn32FQst7YBf4czVb1Q9VfDdsGo9AT25qicfVY", "error": "stream reset"}
2023-01-10T18:46:21.100+0400	[33mWARN[0m	net/identify	identify/id.go:334	failed to identify 16Uiu2HAm4kUuM9mn32FQst7YBf4czVb1Q9VfDdsGo9AT25qicfVY: stream reset
2023-01-10T18:46:23.808+0400	INFO	communities/manager.go:111	importing message archive, 86 left
2023-01-10T18:46:26.301+0400	INFO	communities/manager.go:111	extracting messages from history archive	{"archive id": "0x229d10e6c28b096e9d7b8f40d794621828f9a894b07ab59286aeb21364e83c09"}
2023-01-10T18:46:33.815+0400	INFO	communities/manager.go:111	importing message archive, 85 left
2023-01-10T18:46:36.217+0400	INFO	communities/manager.go:111	extracting messages from history archive	{"archive id": "0x3c89b82dd272e9ccb8dcc43d86c74f1c5773de80361e4d538056f96a047d7189"}
2023-01-10T18:46:38.074+0400	[34mINFO[0m	net/identify	identify/id.go:369	failed negotiate identify protocol with peer	{"peer": "16Uiu2HAkwX574mSk1JRnJUw2i7r3YW8xiz5dDmceHSPS4yYYZ979", "error": "stream reset"}
2023-01-10T18:46:38.074+0400	[33mWARN[0m	net/identify	identify/id.go:334	failed to identify 16Uiu2HAkwX574mSk1JRnJUw2i7r3YW8xiz5dDmceHSPS4yYYZ979: stream reset
2023-01-10T18:46:38.074+0400	[34mINFO[0m	net/identify	identify/id.go:369	failed negotiate identify protocol with peer	{"peer": "16Uiu2HAkwX574mSk1JRnJUw2i7r3YW8xiz5dDmceHSPS4yYYZ979", "error": "stream reset"}
2023-01-10T18:46:38.074+0400	[33mWARN[0m	net/identify	identify/id.go:334	failed to identify 16Uiu2HAkwX574mSk1JRnJUw2i7r3YW8xiz5dDmceHSPS4yYYZ979: stream reset
[90mDBG[0m 2023-01-10 18:46:44.078+04:00 [1mNewBE_callPrivateRPC                      [0m topics="[93mrpc[0m" [90mtid[0m=[94m2387718[0m [90mfile[0m=[94mcore.nim:20[0m [90mrpc_method[0m=[94mwakuext_messageByMessageID[0m
2023-01-10T18:46:44.081+0400	INFO	communities/manager.go:111	importing message archive, 84 left
[90mDBG[0m 2023-01-10 18:46:44.083+04:00 [1mNewBE_callPrivateRPC                      [0m topics="[93mrpc[0m" [90mtid[0m=[94m2387718[0m [90mfile[0m=[94mcore.nim:20[0m [90mrpc_method[0m=[94mwakuext_emojiReactionsByChatIDMessageID[0m
[90mDBG[0m 2023-01-10 18:46:44.115+04:00 [1mNewBE_callPrivateRPC                      [0m topics="[93mrpc[0m" [90mtid[0m=[94m2387718[0m [90mfile[0m=[94mcore.nim:20[0m [90mrpc_method[0m=[94mchat_getMembers[0m
2023-01-10T18:46:46.648+0400	INFO	communities/manager.go:111	extracting messages from history archive	{"archive id": "0x0383ebef137f8bb5327b2c5af875e1723a17f41098c0e3069ca595ad50f649f5"}
2023-01-10T18:46:49.353+0400	[34mINFO[0m	net/identify	identify/id.go:369	failed negotiate identify protocol with peer	{"peer": "16Uiu2HAmMcyYYkhR7u1vA6vydeTSFMcf9yTakxvuHn2xQJt27mhP", "error": "stream reset"}
2023-01-10T18:46:49.354+0400	[33mWARN[0m	net/identify	identify/id.go:334	failed to identify 16Uiu2HAmMcyYYkhR7u1vA6vydeTSFMcf9yTakxvuHn2xQJt27mhP: stream reset
2023-01-10T18:46:49.353+0400	[34mINFO[0m	net/identify	identify/id.go:369	failed negotiate identify protocol with peer	{"peer": "16Uiu2HAmMcyYYkhR7u1vA6vydeTSFMcf9yTakxvuHn2xQJt27mhP", "error": "stream reset"}
2023-01-10T18:46:49.354+0400	[33mWARN[0m	net/identify	identify/id.go:334	failed to identify 16Uiu2HAmMcyYYkhR7u1vA6vydeTSFMcf9yTakxvuHn2xQJt27mhP: stream reset
[90mDBG[0m 2023-01-10 18:46:53.218+04:00 [1mNewBE_callPrivateRPC                      [0m topics="[93mrpc[0m" [90mtid[0m=[94m2387718[0m [90mfile[0m=[94mcore.nim:20[0m [90mrpc_method[0m=[94mchat_getMembers[0m
2023-01-10T18:46:53.220+0400	INFO	communities/manager.go:111	importing message archive, 83 left
2023-01-10T18:46:54.215+0400	INFO	communities/manager.go:111	extracting messages from history archive	{"archive id": "0x0a857b73c06550c2a4eeea2bd903f8545592123d5edbbb9d40c3b5856d7dce46"}
2023-01-10T18:46:58.225+0400	[33mWARN[0m	net/identify	identify/id.go:334	failed to identify 16Uiu2HAm4kUuM9mn32FQst7YBf4czVb1Q9VfDdsGo9AT25qicfVY: stream reset
2023-01-10T18:46:58.225+0400	[33mWARN[0m	net/identify	identify/id.go:334	failed to identify 16Uiu2HAm4kUuM9mn32FQst7YBf4czVb1Q9VfDdsGo9AT25qicfVY: stream reset
2023-01-10T18:46:58.225+0400	[33mWARN[0m	net/identify	identify/id.go:334	failed to identify 16Uiu2HAm4kUuM9mn32FQst7YBf4czVb1Q9VfDdsGo9AT25qicfVY: stream reset
2023-01-10T18:47:01.233+0400	[34mINFO[0m	net/identify	identify/id.go:369	failed negotiate identify protocol with peer	{"peer": "16Uiu2HAkymPjsG71PS2P6dXfP45fMRLb1Menxja4yx27UMBwiAXo", "error": "stream reset"}
2023-01-10T18:47:01.233+0400	[33mWARN[0m	net/identify	identify/id.go:334	failed to identify 16Uiu2HAkymPjsG71PS2P6dXfP45fMRLb1Menxja4yx27UMBwiAXo: stream reset
2023-01-10T18:47:01.233+0400	[33mWARN[0m	net/identify	identify/id.go:437	error reading identify message: stream reset
2023-01-10T18:47:01.233+0400	[33mWARN[0m	net/identify	identify/id.go:334	failed to identify 16Uiu2HAkymPjsG71PS2P6dXfP45fMRLb1Menxja4yx27UMBwiAXo: stream reset
2023-01-10T18:47:15+0400 unset [github.com/anacrolix/go-libutp.sendtoCallback:71]: error sending packet: write udp6 [::]:9025->[2a01:e0a:232:c040:f5ba:220b:be1d:38f9]:9025: sendto: no route to host
2023-01-10T18:47:15+0400 unset [github.com/anacrolix/go-libutp.sendtoCallback:71]: error sending packet: write udp6 [::]:9025->[2a02:21b4:943b:8e00:eb:291a:aae9:9d71]:9025: sendto: no route to host
2023-01-10T18:47:18+0400 unset [github.com/anacrolix/go-libutp.sendtoCallback:71]: error sending packet: write udp6 [::]:9025->[2a01:e0a:232:c040:f5ba:220b:be1d:38f9]:9025: sendto: no route to host
2023-01-10T18:47:18+0400 unset [github.com/anacrolix/go-libutp.sendtoCallback:71]: error sending packet: write udp6 [::]:9025->[2a02:21b4:943b:8e00:eb:291a:aae9:9d71]:9025: sendto: no route to host
2023-01-10T18:47:24+0400 unset [github.com/anacrolix/go-libutp.sendtoCallback:71]: error sending packet: write udp6 [::]:9025->[2a01:e0a:232:c040:f5ba:220b:be1d:38f9]:9025: sendto: no route to host
2023-01-10T18:47:24+0400 unset [github.com/anacrolix/go-libutp.sendtoCallback:71]: error sending packet: write udp6 [::]:9025->[2a02:21b4:943b:8e00:eb:291a:aae9:9d71]:9025: sendto: no route to host
2023-01-10T18:47:35+0400 unset [github.com/anacrolix/go-libutp.sendtoCallback:71]: error sending packet: write udp6 [::]:9025->[2a02:21b4:943b:8e00:eb:291a:aae9:9d71]:9025: sendto: no route to host
2023-01-10T18:47:35+0400 unset [github.com/anacrolix/go-libutp.sendtoCallback:71]: error sending packet: write udp6 [::]:9025->[2a01:e0a:232:c040:f5ba:220b:be1d:38f9]:9025: sendto: no route to host
2023-01-10T18:47:38+0400 unset [github.com/anacrolix/go-libutp.sendtoCallback:71]: error sending packet: write udp6 [::]:9025->[2a02:21b4:943b:8e00:eb:291a:aae9:9d71]:9025: sendto: no route to host
2023-01-10T18:47:38+0400 unset [github.com/anacrolix/go-libutp.sendtoCallback:71]: error sending packet: write udp6 [::]:9025->[2a01:e0a:232:c040:f5ba:220b:be1d:38f9]:9025: sendto: no route to host
2023-01-10T18:47:44.379+0400	INFO	communities/manager.go:111	importing message archive, 82 left
2023-01-10T18:47:48.585+0400	INFO	communities/manager.go:111	extracting messages from history archive	{"archive id": "0x456d5dda1b347a1178078b8193ad56d9e418819e814c2e07ef6247ce6ded4855"}
panic: close of closed channel

goroutine 9378962 [running]:
github.com/status-im/status-go/protocol.(*Messenger).HandleHistoryArchiveMagnetlinkMessage.func1(0x1c015e3e630, {0x1c01508cde0, 0x21, 0x21})
	/Users/jenkins/workspace/status-desktop/platforms/macos/vendor/status-go/protocol/messenger_handler.go:924 +0x7f
created by github.com/status-im/status-go/protocol.(*Messenger).HandleHistoryArchiveMagnetlinkMessage
	/Users/jenkins/workspace/status-desktop/platforms/macos/vendor/status-go/protocol/messenger_handler.go:920 +0x6aa
Warning: QObject::~QObject: Timers cannot be stopped from another thread (:0, )
```

**Status Version**: `0.9.0-rc-1`
**OS Version**: `macOS Ventura 13.0 (22A380)`

**Comment by anastasiyaig** [comment] 2023-01-11 07:04
@stefandunca i logged this ticket (replying as a part of conversation in community)

**Comment by caybro** [comment] 2023-01-11 10:48
I bet this is a duplicate of https://github.com/status-im/status-desktop/issues/8931, @0x-r4bbit ?

**Comment by 0x-r4bbit** [comment] 2023-01-11 15:03
@caybro nope these are two different issues.
#8931 seems to panic due to insufficient write buffer inside the torrent library (haven't looked into this yet, and I'm honestly surprised to see this coming from the library)

This issue here panics due to close of an already closed channel.
Most likely related to the node trying to handle a new magnetlink while it's already processing a magnetlink (I thought I've ironed out all the edge cases but it seems like this is not the case)

**Comment by 0x-r4bbit** [comment] 2023-01-23 14:36
PR is here: https://github.com/status-im/status-go/pull/3123

**Comment by jrainville** [comment] 2023-02-01 14:49
Has been merged via updating status-go

**Closed by jrainville** 2023-02-01 14:49 UTC
Labels: bug, hard-to-replicate, syncing_and_message_history, E:Bugfixes
