### ISSUE TITLE
Can't see any PNs if preference is set to "Mentions only"

### ISSUE THREAD

**Issue by churik** [status-im/status-desktop#3344] opened 2021-08-31 14:43 UTC
#### Expected behavior
can see PN in cases 3-5

#### Actual behavior
no PN at all
Notification preferences:
![image](https://user-images.githubusercontent.com/4557972/131522844-12556a77-932b-4da8-995e-da108be4d61c.png)

### Reproduction

1) User A(desktop) and User B(mobile) are contacts
2) Join same public chat
3) User B: mention User A in public chat
4) User B: reply to User A message in public chat
5) User B: send message to 1-1 User A chat

### Additional Information

- Status version: 0.2.1-beta 
- Operating System: Mac OS Big Sur 11.5.2 (20G95)

[comment]: # (Please, add logs/notes if necessary)

**Comment by anastasiyaig** [comment] 2021-08-31 16:48
potential duplicate of https://github.com/status-im/status-desktop/issues/2552

**Comment by anastasiyaig** [comment] 2021-08-31 16:49
also, all the matrix for possible cases is provided in https://github.com/status-im/status-desktop/issues/2552

**Comment by anastasiyaig** [comment] 2021-09-01 07:18
@churik thanks for reporting this, it seems to be fixed in status-desktop/pull/3269 which is not merged yet, but i see the notifications when mentioning there

**Comment by iurimatias** [comment] 2021-09-20 20:46
should be fixed in #3269

**Closed by iurimatias** 2021-09-20 20:46 UTC
Labels: bug, push_notifications
