### ISSUE TITLE
bug(ui): scrolling with slow/medium momentum gets stuck

### ISSUE THREAD

**Issue by emizzle** [status-im/status-desktop#3539] opened 2021-09-15 01:17 UTC
1. Community channel, try scrolling with the mouse wheel using a slow or medium speed.
2. Expected: the messages should scroll smoothly
3. Actual: sometimes the messages get "stuck" and I'm unable to scroll past a certain point.

![imgur](https://imgur.com/DM9tP9O.gif)

**Comment by iurimatias** [comment] 2021-09-15 17:18
duplicate of #3067

**Closed by iurimatias** 2021-09-15 17:18 UTC
