### ISSUE TITLE
Message content is not displayed after link

### ISSUE THREAD

**Issue by osmaczko** [status-im/status-desktop#7522] opened 2022-09-23 09:30 UTC
The message is cut just after the link, see video:

https://user-images.githubusercontent.com/33099791/191931800-844a2ac6-4d53-4fd3-89ff-3a4d70a69a90.mp4

**Comment by caybro** [comment] 2022-09-23 11:15
Also not rendered correctly inside a reply

Another problem: sending a single emoji ":)" message renders that empty too

**Comment by caybro** [comment] 2022-09-23 11:31
Most likely culprit: https://github.com/status-im/status-desktop/pull/7452

**Comment by caybro** [comment] 2022-09-23 11:54
CC @micieslak

**Comment by micieslak** [comment] 2022-09-27 15:01
The real culprit is this pr: https://github.com/status-im/status-desktop/pull/7456
CC @faust4exe

**Comment by faust4exe** [comment] 2022-09-27 15:57
> The real culprit is this pr: #7456 CC @faust4exe

I am on latest master + my fix = no issue on Linux

![Screenshot from 2022-09-27 18-55-58](https://user-images.githubusercontent.com/6445843/192575803-7079334f-e920-4617-bcca-533680ce5d5d.png)

**Comment by micieslak** [comment] 2022-09-27 16:01
The culprit responsible for initial issue from the videos is probably this PR: https://github.com/status-im/status-desktop/pull/7485

https://user-images.githubusercontent.com/20650004/192576750-d95f5991-8524-4712-82df-6bc00831fa82.webm

Restoring the line removed in the PR removes the problem.

**Comment by micieslak** [comment] 2022-09-28 07:46
> I am on latest master + my fix = no issue on Linux

@faust4exe please notice that the problem is there, in the screenshot you posted. The bubble is cut off in the bottom part. Message height is calculated improperly what was introduced in https://github.com/status-im/status-desktop/pull/7485

**Comment by micieslak** [comment] 2022-09-28 07:47
@faust4exe The issue with disappearing emoji is excluded to https://github.com/status-im/status-desktop/issues/7622

**Comment by micieslak** [comment] 2022-09-28 07:57
@caybro The issue with overlapping multiline messages is excluded by @noeliaSD to https://github.com/status-im/status-desktop/issues/7618.

Let's keep this task to verify if there are any problems directly related to links in messages. If links itself are not a problem and it's matter of multi-line input, the issue will be just closed.

**Comment by faust4exe** [comment] 2022-09-28 11:50
> > I am on latest master + my fix = no issue on Linux
> 
> @faust4exe please notice that the problem is there, in the screenshot you posted. The bubble is cut off in the bottom part. Message height is calculated improperly what was introduced in #7485

Oh - that is true. But I guess this issue is mentioning the message content cutoff, not just the bubble.

**Comment by micieslak** [comment] 2022-09-28 13:58
@osmaczko plase take a look, I suppose that this issue is not directly related with urls in a message and
https://github.com/status-im/status-desktop/issues/7622 + https://github.com/status-im/status-desktop/issues/7618 are solving issues mentioned in this ticket. If so, please close the ticket.

**Comment by iurimatias** [comment] 2022-09-29 14:51
closing in favour of https://github.com/status-im/status-desktop/issues/7618 and https://github.com/status-im/status-desktop/issues/7651

**Closed by iurimatias** 2022-09-29 14:51 UTC
Labels: bug, ui, Chat, priority 0: blocker, dogfooding-issues
