### ISSUE TITLE
Community link is not resolved and there is no way to unfurl it 

### ISSUE THREAD

**Issue by churik** [status-im/status-desktop#12593] opened 2023-10-31 12:14 UTC
# Bug Report

## Description

Happens randomly and in this case there is no way to reach the community.

## Steps to reproduce
- User A: create a token-gated community (in a particular case with these permissions):

![Status Desktop 2023-10-31 13-02-37](https://github.com/status-im/status-desktop/assets/4557972/e5125ba3-0edc-41e7-a91a-2038c5bd45e3)

- User A: add User B to contacts
- User A: add User B to the token-gated community

#### Expected behavior
User B: Can see the community info from the invite

#### Actual behavior
1) The link to the community shows "Community data cannot be shown yet"
2) Community invite is not unfurled

https://github.com/status-im/status-desktop/assets/4557972/b3ff40a2-6249-4a15-9070-f82220172a5c

Video from the other user (as a confirmation that it is not only my issue): 

https://github.com/status-im/status-desktop/assets/4557972/59a502ed-9f1a-4409-8331-8dc0716e6821

### Additional Information

- Status desktop version: nightly 31/10/23
- Operating System: Mac OSx 13.2.1
- Logs: 
[Archive.zip](https://github.com/status-im/status-desktop/files/13216060/Archive.zip)
[geth_new.log](https://github.com/status-im/status-desktop/files/13216117/geth_new.log)

**Comment by jrainville** [comment] 2023-10-31 13:50
@igor-sirotin @osmaczko have your PRs about community fetches and community invites been merged?

If not, should they fix this?

As for the second video, it seems like the not being able to focus on the chat input is another issue. I've seen it once so far. I'll check if we already have an issue opened for that.

**Comment by osmaczko** [comment] 2023-10-31 14:26
Yes, my fix is merged: https://github.com/status-im/status-desktop/pull/12553

@churik for how long did you wait? It can take up to 2 minutes to verify the community owner.

**Comment by igor-sirotin** [comment] 2023-10-31 14:29
1. From what I see about the shared link, it works as intended. 
When the user clicks on link to community that is not known, we have to fetch the info first, there comes the ephemeral notification about it. I think as soon as it will be fethced, user will be switched to the community.
It's not UX-friednly I'd say, but it's not a bug 🙂 
Also with https://github.com/status-im/status-desktop/issues/12459 implemented it will be much better, because the community will be fetched as soon as the link is received and visible in the UI. I'm plan to open the PR today.

1. Community invitation will be fixed separately, it's coming here: https://github.com/status-im/status-desktop/issues/12570

1. Chat input issue: https://github.com/status-im/status-desktop/issues/12440

2. There's also an issue with logged version, it shows `9.9.0`, which is definitely wrong as the commit is `0f1b16006`
I guess it's related to https://github.com/status-im/status-desktop/issues/12349
```log
INF 2023-10-31 12:47:07.475+01:00 Version: 0.9.90                            topics="status-app" tid=15191588 file=nim_status_client.nim:197
INF 2023-10-31 12:47:07.475+01:00 Commit: 0f1b16006                          topics="status-app" tid=15191588 file=nim_status_client.nim:198
```

cc @churik @jrainville

**Comment by jrainville** [comment] 2023-10-31 14:29
Would it be possible that the connection to Pokt/Infura failed to call the contract? Though we do not see the banner at the top, so maybe not?

**Comment by jrainville** [comment] 2023-10-31 14:31
> There's also an issue with logged version, it shows 9.9.0, which is definitely wrong as the commit is 0f1b16006
I guess it's related to https://github.com/status-im/status-desktop/issues/12349

That's kinda intentional, since we didn't want to have to change the version on master each time. We use the commit instead.

**Comment by igor-sirotin** [comment] 2023-10-31 14:32
> > There's also an issue with logged version, it shows 9.9.0, which is definitely wrong as the commit is [0f1b160](https://github.com/status-im/status-desktop/commit/0f1b16006e0dd6674ca1471a04c9e7d00693cf54)
> > I guess it's related to #12349
> 
> That's kinda intentional, since we didn't want to have to change the version on master each time. We use the commit instead.

hmm, but we should the version in UI anyway. I think the logged version should be the same.
<img width="1312" alt="image" src="https://github.com/status-im/status-desktop/assets/25482501/121bccd4-a05d-417d-9cb4-f1f991fe2869">

**Comment by osmaczko** [comment] 2023-10-31 14:54
> Would it be possible that the connection to Pokt/Infura failed to call the contract? Though we do not see the banner at the top, so maybe not?

Yes, that is possible. Even if that happened, the verification would be retried in next iteration (after another 2 minutes). It should be auto-resolved eventually.

I will check the logs soon to see what happened.

**Comment by jrainville** [comment] 2023-11-01 13:36
Any chance that the Owner token was transferred to someone else @churik ?

**Comment by iurimatias** [comment] 2024-01-22 16:26
possibly already fixed

**Comment by igor-sirotin** [comment] 2024-01-29 18:54
Tested, seems to work fine now.

Community permissions:
<img width="1312" alt="Screenshot 2024-01-29 at 18 53 05" src="https://github.com/status-im/status-desktop/assets/25482501/48ac3d1c-0c92-49f2-97a2-2942d9e8362d">

Received message:
<img width="1268" alt="Screenshot 2024-01-29 at 18 53 17" src="https://github.com/status-im/status-desktop/assets/25482501/5a0f48c5-3cf8-4c0b-b7da-2c7c3cb38931">

Community opened with no problems:
<img width="1312" alt="Screenshot 2024-01-29 at 18 53 21" src="https://github.com/status-im/status-desktop/assets/25482501/76345087-8330-48a6-a2c2-e005c558dc57">

**Closed by igor-sirotin** 2024-01-29 18:54 UTC
Labels: bug, E:Desktop Community Bugfixes MVP
