### ISSUE TITLE
Mutual contact still shows "Not a contact" in chat header

### ISSUE THREAD

**Issue by jrainville** [status-im/status-desktop#5544] opened 2022-04-13 15:24 UTC
# Bug Report

## Description

When a user accepts our contact request and becomes a mutual contact, the label "Not a contact" still shows at the top

![image](https://user-images.githubusercontent.com/11926403/163214652-bc6a5c34-d5a2-4cda-a2c3-90643f398fc4.png)

## Steps to reproduce

1. On account A, add Account B as a contact.
   - This will open the 1-1 chat., The label Not a contact is ok
2. On Account B, accept the contact request, while Account A is still open

Result, Account A still shows "Not a contact". It only updates when closing and reopening the app.

**Comment by PascalPrecht** [comment] 2022-04-14 11:57
Duplicate of https://github.com/status-im/status-desktop/issues/5164

**Closed** 2022-04-14 13:11 UTC
Labels: bug, priority F2: important
