### ISSUE TITLE
Cant disable network if no gas

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#15701] opened 2024-07-22 12:16 UTC
### Description

<img width="1696" alt="Screenshot 2024-07-22 at 15 12 51" src="https://github.com/user-attachments/assets/d2688fa7-19ef-4e44-a093-f0a2479f2dd2">

can't really lock a network when there is `no gas`

**Comment by belalshehab** [comment] 2024-07-25 17:57
Hi @anastasiyaig @saledjenic 
I guess it should be disabled by default since there is no gas.
so the real problem is that it is even suggested.
this should be resolved by [Suggestion is present even there is no gas #15700](https://github.com/status-im/status-desktop/issues/15700)

**Comment by belalshehab** [comment] 2024-07-29 15:21
Hi @anastasiyaig,

To clarify, I'm wondering what the expected behavior should be after a network is disabled due to insufficient gas. From my understanding, the only scenario where a network without enough gas would still appear is when it's the only possible route for the desired transaction. However, this would always result in an error indicating insufficient funds.

Therefore, if we allow the user to disable the network, it seems they will always encounter a "no route" error, as they are attempting to send an amount exceeding their available balance on the remaining networks.

Instead of letting the user disable the network, we should ensure that a clear error message is displayed to explain the situation. This message should specify that the selected network lacks the necessary gas for the transaction and indicate the maximum amount that can be sent using the available balances and fees on other networks.

this is how it will look like:
<img width="1312" alt="image" src="https://github.com/user-attachments/assets/78fc274f-840b-423a-9513-aaee6b1ee3a1">

**Comment by anastasiyaig** [comment] 2024-07-29 15:23
I dont have any expected result here, besides the fact that application should not suggest me network which has 0 balance. The main issue here, is that even application suggests me wrong chain, i can't fix it as a user, because i cant disable this network manually. Because the button Disable is not accessible when i have out of gas error.

**Comment by belalshehab** [comment] 2024-07-29 15:39
the point is if you disable the network with no gas then what will happen is that you will get no route error. so unless the amount the user wants to send is not changed, there is no point!

as for why the router suggested this route, this was by design by @saledjenic to show that there is no route but this is the best route that could be used if there was enough gas fee.

here is how it will look like if we disable in this case:


https://github.com/user-attachments/assets/42c530aa-3f4a-490d-92cc-159eaea3c3e0

**Comment by anastasiyaig** [comment] 2024-07-29 16:27
thats awesome :) lets get confirmation from @saledjenic to be safe

**Comment by saledjenic** [comment] 2024-07-30 07:19
> the point is if you disable the network with no gas then what will happen is that you will get no route error. so unless the amount the user wants to send is changed, there is no point!

correct

**Closed** 2024-07-30 15:52 UTC
Labels: bug, wallet-core-team, E:Wallet Router bugs
