### ISSUE TITLE
Not possible to mint owner token on ARB, OPT even if you have enough balance (Mainnet)

### ISSUE THREAD

**Issue by mprakhov** [status-im/status-desktop#15023] opened 2024-06-04 09:16 UTC
# Bug Report

## Description

Based on the fee info, I have enough balance of OPT and ARB on mainnet, but I can't mint the owner token

Note: this can be related to incorrect displaying of the Fees, as I have a low amount of ARB and OPT

https://github.com/status-im/status-desktop/assets/117639195/1142cada-d5e4-4896-ae5e-6a5e84091b8f

## Steps to reproduce

1. Create a community (mainnet)
2. Mint owner token

#### Expected behavior

Owner token minted

#### Actual behavior

Can't mint due to not enough funds

### Additional Information

- Status desktop version:2.29-0 rc-7, latest master
- Operating System: macos

**Comment by anastasiyaig** [comment] 2024-06-04 09:27
It is probably another issue @mprakhov , the issue with app showing incorrect estimated cost on UI

https://github.com/status-im/status-desktop/assets/82375995/b6dc85db-3185-4e18-ab52-1110274ef404

it was discussed and potentially fixed in https://github.com/status-im/status-desktop/issues/13892, maybe worth reopening?

**Comment by jrainville** [comment] 2024-06-07 15:47
> it was discussed and potentially fixed in https://github.com/status-im/status-desktop/issues/13892, maybe worth reopening?

Yeah I remember that issue. I think we found that in the end, we couldn't fully fix, because the fees were always about 10x higher than the estimation could give us.

Was there anything we could do about it? cc @dlipicar @alaibe

**Comment by alaibe** [comment] 2024-06-07 16:01
@jrainville there is now an L1 fee that should be returned, by displaying this, you will have the real cost of a tx

It has been added by @saledjenic

**Comment by jrainville** [comment] 2024-06-07 16:07
> @jrainville there is now an L1 fee that should be returned, by displaying this, you will have the real cost of a tx
> 
> It has been added by @saledjenic

Ok, so this issue should be fixed by our team? ie it's only this community minting part that is missing the L1 fee? Or the wallet function itself should be returning the full? @alaibe 

I do recall that @endulab worked on adding L1 fees at one point. Do you think there was a regression?

**Comment by alaibe** [comment] 2024-06-07 16:35
well somehow u get that it is blocked, so there is something in the UI that prevent it.
it is either because the total fees being displayed is incorrect or something else ?

**Comment by saledjenic** [comment] 2024-06-10 06:38
At first what I see in the video is that the ETH asset is 14.11 USD, but across all networks, not only on opt or arb as said above, also minting token should happen on opt only, right?
Anythow this is worth checking also maybe we can add this as a new type to the router?

**Comment by endulab** [comment] 2024-06-10 10:36
After checking Mikhailo's logs:
Optimism mainnet: walletBalance=0.0 ethValueWithL1Fee=0.000724732373525969 l1Fee=0.000389200000000000
Arbitrum: walletBalance=0.0 ethValueWithL1Fee=5.719641e-05 l1Fee=0.000000000000000000
It seems that the wallet balance is computed incorrectly.
I will check it.

**Comment by endulab** [comment] 2024-06-10 14:00
According to my discussions with @alaibe OP and ARB are ERC20 tokens.
They are ETHs which are bridged to Arbitrum or Optimism networks.
In order to interact with contracts on concrete chains we need to have bridged ETHs.

**Comment by jrainville** [comment] 2024-06-10 14:07
Ahhh! How have I not caught it. I did find it weird that Mykhailo had `OP` instead of `ETH`.

I guess I'll close since it's a non-issue

**Comment by jrainville** [comment] 2024-06-10 14:07
Thanks for looking into it @endulab

**Closed by jrainville** 2024-06-10 14:07 UTC
Labels: bug, backend-team, E:Desktop Tokenized Ownership, E:D:Wallet Bugfixes

**Comment by dlipicar** [comment] 2024-06-10 15:38
> @endulab mmm... can I exchange it to bridged ETHs using our wallet? I wonder how can I fund it correctly. What I did before - just sent OP token from my Binance wallet to the Status wallet

@mprakhov you can withdraw ETH from Binance and select the Opt and Arb networks, that's what I do
