### ISSUE TITLE
Profile settings misbehave when recovering old account

### ISSUE THREAD

**Issue by osmaczko** [status-im/status-desktop#11662] opened 2023-07-25 09:52 UTC
# Bug Report

## Description

Once an old account is recovered and the display name is not accessible anymore in waku store, then the profile settings' `Display Name` field misbehave as in attached video.

[
](https://github.com/status-im/status-desktop/assets/33099791/f4b5898a-fd7d-49ae-a06b-0b85ba01ffd6)

## Steps to reproduce

Recover account without display name (enter random seed phrase).

#### Expected behavior

Once the account is recovered and we detect that display name is missing we should force user to set the display name at the onboarding stage.

#### Actual behavior

User is able to proceed without display name leading to broken state in profile settings.

### Additional Information

- Status desktop version: master (27c159d464cf5a1fdb1e4fe7a8599ed6f99994a9)
- Operating System: Fedora 38

**Comment by iurimatias** [comment] 2024-02-19 15:18
added to next milestone, but possibly will be fixed already because this screen is being replaced

**Comment by caybro** [comment] 2024-02-19 15:21
That's a very old master @osmaczko :) The screen looks completely different now

**Comment by caybro** [comment] 2024-04-18 11:59
I can no longer reproduce in current master, feel free to reopen if the problem happens again

**Closed by caybro** 2024-04-18 11:59 UTC
Labels: bug, ui-team, E:Desktop Onboarding & Login, E:Desktop Misc Bugfixes
