### ISSUE TITLE
Permission check is not working properly with values above 1000

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#14062] opened 2024-03-20 13:17 UTC
### Description

**NOTE: it looks like there is a specific problem with values above 1000**

**CASE 1:**

1. create community
2. add a member
3. add a permission to keep **10000** eth to be a member of that community and save
4. check if the member is kicked

As result, the member is still present in community. Restart does not help. Editing community description does not help

<img width="1920" alt="Screenshot 2024-03-20 at 16 16 52" src="https://github.com/status-im/status-desktop/assets/82375995/37c57023-a409-479b-b885-553384dd4751">

**CASE 2:** 

1. create community
2. add a member
3. add a permission to keep **10000** eth to be **an admin** of that community and save
4. check if the member can join

As result, member cant join

<img width="1920" alt="Screenshot 2024-03-20 at 16 23 34" src="https://github.com/status-im/status-desktop/assets/82375995/70858106-fc3f-4aeb-ae85-dfd810abc4f5">

```
ERR 2024-03-20 16:26:55.418+03:00 communities:                               tid=40006940 file=module.nim:358 err="\nstatus-go error [methodName:wakuext_requestToJoinCommunity, code:-32000, message:amountInWeis value is incorrect ]\n"
```

**Comment by anastasiyaig** [comment] 2024-03-20 13:18
@jrainville i think it is for RC (if that is reproducible for you)

**Comment by jrainville** [comment] 2024-03-20 13:36
Dupe of https://github.com/status-im/status-desktop/issues/14006

**Closed by jrainville** 2024-03-20 13:36 UTC
Labels: bug, messenger-team, E:Desktop Community Bugfixes MVP
