### ISSUE TITLE
Navigation and chat become unavailable when using scroll wheel

### ISSUE THREAD

**Issue by glitchminer** [status-im/status-desktop#12043] opened 2023-08-30 16:30 UTC
# Bug Report

## Description

The primary nav to select communities disappears or becomes unresponsive when using a mouse scroll wheel. This makes is impossible or difficult to reach communities that are not currently displayed. 

Although the list can be clicked on and dragged as well, it's not particularly intuitive and we use scrollbars elsewhere. The navigation becomes visible again after touching the touchpad, but not everyone will have one.

https://github.com/status-im/status-desktop/assets/50769329/a45bab1a-7492-4ca8-9003-ef943369bd46

A similar behaviour is seen when scrolling in other parts of the app.

![image](https://github.com/status-im/status-desktop/assets/50769329/6f333ac9-d6ac-4abb-afe5-02261c1c5c13)

## Steps to reproduce

Use a scroll wheel over a scrollable component in both directions and at various speeds

#### Expected behavior

Smooth scrolling

#### Actual behavior

Unresponsive scrolling, or components disappearing from view

### Additional Information

- Status desktop version: 0.14 RC3 (has also been seen in previous versions)
- Operating System: Mac
- Mouse: Logitech MX Master 3

**Comment by iurimatias** [comment] 2024-02-14 16:10
moving to 2.39 due to lack of space in the milestone

**Comment by caybro** [comment] 2024-06-07 14:10
I was never able to reproduce on Linux; maybe someone on macOS can give it a try?

**Comment by noeliaSD** [comment] 2024-06-17 10:13
Moved to next milestone due to team capacity and priorities.

**Comment by caybro** [comment] 2024-08-12 22:34
Cannot repro, pls reopen if it ever happens again

**Closed by caybro** 2024-08-12 22:34 UTC
Labels: bug, ui-team, E:Desktop Misc Bugfixes
