### ISSUE TITLE
Default account naming in Wallet

### ISSUE THREAD

**Issue by benjthayer** [status-im/status-desktop#13198] opened 2024-01-12 09:17 UTC
A note has been added to the `Add New Account` flows (linked below) to define the name attributed to the first auto-generated account the user receives when they create their Status profile and the naming convention for each subsequently created new account for that profile.

Figma:
https://www.figma.com/file/FkFClTCYKf83RJWoifWgoX/Wallet-v2?type=design&node-id=12272-269191&mode=design&t=8gE6sTvCjjQUA8rO-4

**Logic:**
- The user's first account, which is automatically generated for a new Status profile should be named `Account 1` - the user is free to change this.
- The next user-created account should then be named `Account 2` - again the user is free to change this. 
- Any subsequently created account should follow the pattern of incrementing the account number by 1: `Account 3, Account 4...` etc.

@saledjenic

**Comment by benjthayer** [comment] 2024-01-26 12:51
Related to this, we should also follow the same convention for watched addresses - the first watched address should be `Watched address 1`

**Logic:**

- When the user adds their first watched address, this address should be auto-named `Watched address 1` - the user is free to change this.

- The next watched address added should then be named `Watched address 2` - as always, the user is free to change this.

- Any subsequently added watched addresses should follow the pattern of incrementing the watched address number by 1: `Watched address 3`, `Watched address 4`... etc.

**Comment by alaibe** [comment] 2024-02-02 11:08
Duplicate of https://github.com/status-im/status-desktop/issues/12693

**Closed by alaibe** 2024-02-02 11:08 UTC
Labels: wallet-team, Design-QA, E: Desktop Wallet Stabilization 0.17
