### ISSUE TITLE
Old Contact requests timestamp is wrong after restoring my profile using seed phrase

### ISSUE THREAD

**Issue by chaitanyaprem** [status-im/status-desktop#14052] opened 2024-03-20 01:11 UTC
# Bug Report

If i restore my status desktop profile using seed-phrase, all the profile data gets synced properly.
But when i click on "Bell" icon on top right and see contact requests, all the contact requests accepted are shown with currentTimestamp i.e time at which profile was restored. 

## Description

Attaching a sample image showing all contact requests times shown as profile restoration time eventhough these contact requests were done days and months ago.
<img width="540" alt="Screenshot 2024-03-20 at 6 40 13 AM" src="https://github.com/status-im/status-desktop/assets/20137744/2634faf9-6080-49da-8d8a-9f5d96767f45">

## Steps to reproduce

1. Restore profile using seed phrase
2. After logging in , click on Bell (Notifications) icon on top right
3. Click on Contact Requests in the shown list

#### Expected behavior

The original timestamp at which contact request is accepted should be shown and not the time at which profile is restored. 

#### Actual behavior

All contact requests (Accepted) are shown with time at which profile is restored.

### Additional Information

- Status desktop version: 2.27.0
- Operating System: macOS Sonoma 14.4

**Comment by chaitanyaprem** [comment] 2024-03-20 04:56
Also noticed this behaviour which doesn't seem right as well. 

For all contacts the only message that is shown is "Please add me to your contacts" with a timestamp of 01/01/1970 and a message indicating Fetch more messages Before 1 January 1970. Attaching screenshot of the same.
Note sure if i click on Fetch more messages, whether historyQuery is also done using this date to Store node. 

<img width="998" alt="Screenshot 2024-03-20 at 10 25 36 AM" src="https://github.com/status-im/status-desktop/assets/20137744/bddace6a-6ba2-4e11-a586-7bd75830c691">

**Comment by jrainville** [comment] 2024-12-09 19:11
Closing this one as a duplicate of https://github.com/status-im/status-desktop/issues/15849

**Closed by jrainville** 2024-12-09 19:11 UTC
Labels: bug, E:Desktop Contact Requests, Desktop Contact Requests, core-team
