### ISSUE TITLE
Wallet -> Collectibles: collapse / expand icons are mixed up

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#13852] opened 2024-03-06 07:16 UTC
### Description

it is showing collapsed when expanded and vice versa

https://github.com/status-im/status-desktop/assets/82375995/2b695f61-4072-48cf-bf02-1d501723ecdb

**Comment by caybro** [comment] 2024-03-06 07:57
Dupe of #13774

**Closed by caybro** 2024-03-06 07:57 UTC
Labels: bug, wallet-team, E:Desktop Wallet Collectibles
