### ISSUE TITLE
When unselecting token master owner account in shared addresses, token icons in permissions are somehow broken

### ISSUE THREAD

**Issue by noeliaSD** [status-im/status-desktop#14096] opened 2024-03-21 17:48 UTC
### Description
Unselecting account that contains token master breakes somehow the rest of the permission token icons. See video for better understanding:

https://github.com/status-im/status-desktop/assets/97019400/2d2f5ea4-a08e-4236-a1c5-56a3c7d86abe

**Comment by caybro** [comment] 2024-04-01 11:16
@noeliaSD pls retest against latest master; can't reproduce over here

**Comment by caybro** [comment] 2024-04-04 19:25
Closing as nobody can reproduce any longer

**Closed by caybro** 2024-04-04 19:25 UTC
Labels: bug, ui-team, E:Desktop Community Shared Addresses Selection
