### ISSUE TITLE
Lost yesterday's messages

### ISSUE THREAD

**Issue by hesterbruikman** [status-im/status-desktop#3569] opened 2021-09-16 08:50 UTC
## Problem
Today is September 16. UI jumps from `Yesterday` to `September 14` in the #desktop channel.

- There were messages, they show on mobile
- 3 messages send in the evening (20:29, 21:15, 21:45 PM CEST) are visible
- Yesterday's messages in #weather are visible
- I sent a message to both channels 
- In #desktop I also sent a reply
- I noticed an error window when returning to my laptop at some point. Could Select OK and continue using the app. It didn't crash, unfortunately didn't take a screenshot.

### Current

- No messages from yesterday in a specific channel
- No option to fetch messages manually (#3368) 

### Expected
- Yesterday's messages are complete. Behavior to accomplish depends on bug. Maybe the app could attempt fetching messages of the last x days again if an error is logged?
- Option to fetch messages manually (#3368)

**Comment by iurimatias** [comment] 2021-09-20 20:54
tentatively marking this as a duplicate of #3622 or at least the hope is that it will fix this too

**Closed by iurimatias** 2021-09-20 20:54 UTC
