### ISSUE TITLE
Onboarding: recovering account does not retrieve data sometimes

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#11882] opened 2023-08-14 13:00 UTC
### Description

1. download the master build, for example https://ci.infra.status.im/job/status-desktop/job/master/2871/
2. go to `I already use status` -> and import your seed phrase (the seed should has an account with metadata)
3. wait for the Import data dialog appears

Sometimes, the dialog is shown as all in grey, with spinners, and it does not retrieve data (please check the video below ). The video shows the recovery of the same account , so sometimes it fetches the data and sometimes - not

https://github.com/status-im/status-desktop/assets/82375995/29171c05-4f02-4403-a277-321718dbd497

**Comment by caybro** [comment] 2023-08-14 13:08
Yup, nothing got imported (I tried twice) on a freshly restored account from seedphrase; no contacts, communities, profile data... nothing :/

![Snímek obrazovky z 2023-08-11 15-03-11](https://github.com/status-im/status-desktop/assets/5377645/3f00c32b-7542-4f55-bcc5-83a2a19cad53)

**Comment by jrainville** [comment] 2023-08-14 14:29
I guess something timed out or something, but on the status-go side, so maybe we don't show anything in the console logs.
I know the store nodes still use sqllite, so if there are a lot of people querying them at the same time, it might time out.
If that's the case, maybe we can increase the time out when doing the import sync.

**Comment by anastasiyaig** [comment] 2023-08-15 10:57
@igor-sirotin could u please take a look? Maybe u know something. @saledjenic your help is more than appreciated over here

**Comment by saledjenic** [comment] 2023-08-15 11:18
@anastasiyaig even there are data stored on waku related to your key (a seed phrase you're recovering an account with) they sometimes may not be delivered to the app, that should not happen often, but it happens (faced it few times myself as well). That's the reason why we set 2 minutes timeframe with the hope that all data will be recovered within it, but if not, after that period of user will be asked whether he wants to:
1. re-fetch data or 
2. proceed creating a new account using the same key he used before

If user proceeds with the option 1, that doesn't necessary mean that data will be fetched now, maybe he will need to re-fetch one or two times more, but if data are backed up for sure, then they will be fetched for sure it's just a question of time (maybe we can discuss this with waku team if this can be improved, but I guess that it depends on the network congestion).

If user proceeds with option 2, means he will lose all data he had before and will be like he just created a brand new Status account, just using an already known seed phrase. Guess that was the path @caybro followed.

All in all this is not an issue.

**Comment by caybro** [comment] 2023-08-15 11:54
Alright, I'll try a few more times to see if it eventually fetches the data and proceeds with the sync :)

**Comment by anastasiyaig** [comment] 2023-08-15 11:56
maybe we can notify user somehow about that? 
@benjthayer wdyt?

**Comment by igor-sirotin** [comment] 2023-08-15 14:15
@saledjenic do you think waiting longer would be better than restarting the fetch?
If that's the case, then maybe we should change the UI somehow?

E.g., instead of a dumb 2-minutes timeout:
- Keep fetching in the background
- Show a message to the user `Still trying to fetch the data`
- Give user ability to cancel the waiting and proceed with "creating a new account using the same key"
- Maybe show more messages after more another 2 minutes

cc @benjthayer

**Comment by saledjenic** [comment] 2023-08-15 14:38
After user provides a seed phrase (or private key from keycard) we're requesting data from waku and have a delay of 30 seconds, that's why you always see loading screen after that action which lasts 30 seconds. In 90% cases data are fetched during that period, that's why you see all categories "green" after loading screen disappears (after those 30 seconds), but for the case when data are not fetched we're giving 2 mins extra time, if data doesn't appear within those 2 mins, re-fetch is a way to go, which is actually 2 mins more waiting with the hope that data will arrive, if not, a good way to proceed is to wait for some time, remove local Status folder and try to recover again. Actually by my opinion all is better that proceeding to create a new Status account with the same seed phrase, cause in that case you're losing all you had before, so that should be the very very last option to go with.

**Comment by saledjenic** [comment] 2023-08-15 14:55
Also we're waiting for a profile keypair related data to receive, if it appears then we let user proceed even other data are not arrived yet. In that case all data which come later will be applied, which is pretty good approach.

From my experience using recovering flow, so far, I can say that if data for any category arrives then in a very short period in 99% cases all backed up data get received. Also in 99% those backed up messages are received almost immediately.

> - Keep fetching in the background

if user proceeds with option 2. from above we should not do that, cause that will mix the things later

> - Show a message to the user Still trying to fetch the data
> - Give user ability to cancel the waiting and proceed with "creating a new account using the same key"
> - Maybe show more messages after more another 2 minutes

I think that explicit re-fetch is maybe better option cause it re-request data, while if we don't do that we will just wait that may take tooo long, especially if we know that messages should be received almost immediately after starting a messenger.

But also what I've noticed is that earlier fetching messages failed very rare, now that is easier reproducible maybe in 1 out of 10 tries, not sure if something has changed on waku side.

**Comment by caybro** [comment] 2023-08-15 15:02
I just tried re-fetching several times in a row, to no avail... :/

**Comment by saledjenic** [comment] 2023-08-15 15:05
@caybro does removing local Status folder and recovering again help?
Sorry to ask, but you're recovering an account you're sure you have a data backed up for?

**Comment by caybro** [comment] 2023-08-15 15:16
> @caybro does removing local Status folder and recovering again help? 

That's what I did and didn't help

**Comment by saledjenic** [comment] 2023-08-17 11:59
@lukaszso an update from @richard-ramos:

"something that would be useful to identify if the message exists in the storenode is to modify wakuv2/waku.go, and in line [1135](https://github.com/status-im/status-go/blob/develop/wakuv2/waku.go#L1135)  add the following:"
```
fmt.Println("=====================================================================")
fmt.Println("peerID", peerID.Pretty())
fmt.Println("StartTime", query.StartTime)
fmt.Println("EndTime", query.EndTime)
fmt.Println("ContentTopics", query.ContentTopics)
```

@caybro could you check cause you're able to constantly reproduce the issue.

**Comment by jrainville** [comment] 2023-09-28 13:56
Fixed with https://github.com/status-im/status-desktop/pull/12280

**Closed by jrainville** 2023-09-28 13:56 UTC
Labels: bug, messenger-team, E:Desktop Messenger Syncing, E:Onboarding & Login
