### ISSUE TITLE
Pending contact request sync state

### ISSUE THREAD

**Issue by alaibe** [status-im/status-desktop#8702] opened 2022-12-08 20:12 UTC
Here is the scenario to reproduce:
* Each time I import my seed phrase, the contact request are imported but in pending
* Then I receive new contact request a contact that is pending

As a result, in order to receive message from this contact I need to restart the app.

Manual workaround: I delete the pending contact request and the contact also remove me as a contact

**Comment by jrainville** [comment] 2022-12-08 21:35
Might be related to [#7734](https://github.com/status-im/status-desktop/issues/7734), that's why I assigned you @0x-r4bbit

**Comment by 0x-r4bbit** [comment] 2022-12-20 12:17
@alaibe this has been a while, but maybe you remember:

There's a certain time frame in which we perform backups of contacts (currently that's very 8 hours).
As a result of that, every contact request you've accepted in the past < 8 hours will not be backed up as such.
Then, when importing an account and assuming that the contact requests have been made in the past 30 days, those contact request messages will show up again as if they were new.

This is considered an edge case as per https://github.com/status-im/status-desktop/issues/8200#issuecomment-1321843444
If the above applies to you then I'm not sure there's much more we can do here

**Comment by 0x-r4bbit** [comment] 2023-01-02 13:18
I can reproduce this but only under the circumstances I've described above:

1. Accepted contacts have not yet been backed up as such
2. Past #n messages (including contact requests messages) will be received
3. Because contacts were not backed up and old contact requests have been received, contacts show up as pending requests again

This should not happen when contacts were backed up

**Comment by alaibe** [comment] 2023-01-03 09:31
Yes this is indeed the possible scenario
* Could we discard pending request or at least update the backup?

As even 1 month later I still have a lot of pending request, I would expect it to be changed by now

**Comment by 0x-r4bbit** [comment] 2023-01-03 09:38
> Ohh and each time I reimport the key the same pending request re-appears

Did you ever end up accepting those requests eventually?

**Comment by alaibe** [comment] 2023-01-03 09:43
Yes I did but it was not backed up and now I cannot anymore

**Comment by 0x-r4bbit** [comment] 2023-01-03 09:57
Discussed this with @alaibe offline.
It seems what he's experiencing is a bit different from what I tried to reproduce. 
I reproduced this with **incoming** contact requests, however, he's seeing **outgoing** pending ones.

Will need to check now if this is indeed happening the same way for **outgoing** requests, or if this is some bug in the UI.

**Comment by 0x-r4bbit** [comment] 2023-01-03 12:20
Here's a theory on what's happening, which I've now confirmed:

1. Anthony sends contact request to other account
2. This will create a local `contact` with the properties `added: true`, `hasAddedUs: false` (which is an outgoing request essentially)
3. Time goes by, and the backup routine kicks in. That account is now being backed-up
4. At some point after that, but before the second backup kicks in, that other account confirms the contact request
5. The local contact on Anthony's node is now `added true`, `hasAddedUs: true` -> a mutual contact
6. Now Anthony wipes out his Status folder, and reimports his account into a new instance
7. Upon account recovery, his node will receive backedup data and recovers his contacts. 
8. Because the backedup data doesn't have the latest state, the recovered account shows up as outgoing pending contact request.
9. The other party still has Anthony as a contact, flagged as `added: true`, hasAddedUs: true`

The result is the issue Anthony is experiencing.
This one is a tricky case. Reimporting a seedphrase should not be considered a day-to-day activity and is considered an edge case. However, I think it's still worth exploring solutions on getting higher chances that the backed up data is more up to date.

In this particular case, what we could do, is whenever we receive a contact request response, we back up our contact data.

It's a similar problem to what I've described in https://github.com/status-im/status-desktop/issues/8702#issuecomment-1359276117 and really boils down to whether we're willing to preform backups in certain events or not.

@cammellos @John-44 How do you feel about this?

**Comment by osmaczko** [comment] 2023-01-03 13:39
That's tricky indeed. IMO we should ensure once the "relevant event" is received we eventually sync our data before the app is closed. This would minimize the risk of data inconsistency.

To keep the network bandwidth low we should probably use some [Debounce](https://reactivex.io/documentation/operators/debounce.html) mechanism instead of performing a backup for every "relevant event". Example:
```
func handleContactRequest() {
    ...
    backup.debounce() // ensure backup is performed before app is closed, but not more often than once per specified interval
}
```
call `backup.debounce()` in every "relevant event".

Another, very naive solution, would be to keep the "dirty" state of the backup and perform backup just once before the app is closed. It has a drawback though, as it may block the app just before it is closed.
```
func handleContactRequest() {
    ...
    backup.makeDirty()
}
func beforeAppExit() {
   if (backup.isDirty()) {
       backup.perform() // blocking
   }
}
```

**Comment by cammellos** [comment] 2023-01-03 13:51
we should generally move away from backing up eagerly since it's a high cost for the network and doesn't scale, in situations like this it's better to be eventually consistent, we can piggyback for example contact information in ACK and message responses, so that state will eventually be restored.

For example, in a case like this one, we could on restore resend a contact request to pending contacts and they could carry back information on whether we have been added already in the ACK (that's just an extra byte).

We should look for more solutions like the above (for sure there are better), low bandwidth, low reliance on mailservers, rather than increasing dependency on mailservers, until we have a better way to store data.

**Comment by 0x-r4bbit** [comment] 2023-01-03 13:58
Thank you for your feedback @cammellos 
This is very helpful.

Adding the constraint that we don't want to rely too much on mailservers is a good requirement to keep an eye on.
I'll explore this a bit more.

**Comment by anastasiyaig** [comment] 2023-01-12 08:14
@0x-r4bbit is my assumption correct that u are actively working on this ticket, so its status should be `In progress` rather than `Can't reproduce`?

**Comment by 0x-r4bbit** [comment] 2023-01-12 08:36
@anastasiyaig First of all, I put it that label not because I can't reproduce, but because it's "to analyze". Might be worth splitting those labels.

Then, following @cammellos comment here https://github.com/status-im/status-go/pull/3052#discussion_r1066295420 I'll put it in the backlog for now as I have some more urgent issues to work on.

**Comment by MishkaRogachev** [comment] 2023-04-06 12:06
<img width="1012" alt="Screenshot 2023-04-06 at 15 58 56" src="https://user-images.githubusercontent.com/2522130/230372862-22b2d333-3068-4df8-afca-1c6218edb42d.png">
Reproduced. There were been 3 contacts before i restored, no contacts and 1 pending CR after restore

**Comment by anastasiyaig** [comment] 2023-04-06 12:07
but i think it is not a RC issue, master it the same. Can we consider it moving to 0.12? @jrainville @alaibe @iurimatias

**Comment by MishkaRogachev** [comment] 2023-04-26 14:25
This should be re-checked after merging https://github.com/status-im/status-desktop/pull/10336

**Comment by MishkaRogachev** [comment] 2023-05-19 11:22
Should be resolved here: https://github.com/status-im/status-desktop/pull/10739

**Closed** 2023-05-22 15:34 UTC
Labels: bug, E:MutualContacts, S:4, messenger-team
