### ISSUE TITLE
Message from the Contacts Request is not displayed correctly in the chat

### ISSUE THREAD

**Issue by juliaiskandarian** [status-im/status-desktop#8662] opened 2022-12-06 12:23 UTC
# Bug Report

## Description
Message from the Contacts Request is not displayed correctly in the chat after the request was accepted.

How it was sent:
<img width="185" alt="image" src="https://user-images.githubusercontent.com/109152754/205910822-d701d40b-ba15-4b9b-8cc2-31ec16ba7ce7.png">

How it is displayed in the chat:
<img width="240" alt="image" src="https://user-images.githubusercontent.com/109152754/205910088-53a03836-10b0-435e-90b8-d24c81fa5196.png">

## Steps to reproduce
1. Send a contact request with the message containing symbols
2. Wait for the accept
3. Go to the chat
4. Check

### Additional Information

- Status desktop version: 0.8.0
- Operating System: mac OS

**Comment by caybro** [comment] 2022-12-06 12:26
Dupe of https://github.com/status-im/status-desktop/issues/8613

**Closed by caybro** 2022-12-06 12:26 UTC
Labels: bug
