### ISSUE TITLE
Community shown with 0 members

### ISSUE THREAD

**Issue by glitchminer** [status-im/status-desktop#12047] opened 2023-08-30 20:32 UTC
# Bug Report

## Description

Older community started in March that I am still a member of is shown as having 0 members and no members list.

![image](https://github.com/status-im/status-desktop/assets/50769329/c742aaac-77e6-412d-ae77-84cb6013012d)

## Steps to reproduce

Revisit older less frequently used community

#### Expected behavior

Community has at least 1 member (or 2 including owner)

#### Actual behavior

Community is shown as having 0 members

### Additional Information

- Status desktop version: Mac
- Operating System: 0.14 RC3 (also in older versions)

**Comment by caybro** [comment] 2023-08-30 21:28
Possibly a dupe of https://github.com/status-im/status-desktop/issues/12046?

**Comment by glitchminer** [comment] 2023-08-31 02:40
> Possibly a dupe of #12046?

Possibly related, but in that case the count under the community name is shown as 195 even though the list is missing. Here it's 0.

**Comment by MishkaRogachev** [comment] 2023-09-06 13:06
<img width="297" alt="Screenshot 2023-09-06 at 17 05 47" src="https://github.com/status-im/status-desktop/assets/2522130/226af9a7-f695-4f42-8e1a-1251943d688d">

Should be also fixed here: https://github.com/status-im/status-desktop/pull/12094

**Comment by jrainville** [comment] 2023-09-18 16:48
@MishkaRogachev the hotfix PR was closed, so what should happen with this issue?

**Comment by iurimatias** [comment] 2023-09-18 17:27
If this only applies to older communities (except status CC community) then we can close this issue

**Comment by MishkaRogachev** [comment] 2023-09-18 17:40
> @MishkaRogachev the hotfix PR was closed, so what should happen with this issue?

Yes, we can close this issue. But I should warn that every community where the control node has not been updated will be mapped to clients with 0 members

**Closed** 2023-09-18 17:43 UTC
Labels: bug, messenger-team, E:Desktop Community Bugfixes MVP
