### ISSUE TITLE
Status CC Community Channel doesnt load

### ISSUE THREAD

**Issue by Khushboo-dev-cpp** [status-im/status-desktop#12209] opened 2023-09-20 07:59 UTC
# Bug Report

## Description

Ive tried to access the status CC community after several days and its just to slow and I am not able to access the channels any more

## Steps to reproduce

Avoid going the Status CC Community for a few days
After a few days try to open some channels in the community

#### Expected behavior

The channels should load with the chat history in sometime

#### Actual behavior

I left the channel open overnight and the channel still did not open
(ex the people ops channel)

### Additional Information

- Status desktop version: 0.13.3
- Operating System: MacOS

<img width="1456" alt="Screenshot 2023-09-20 at 9 59 14 AM" src="https://github.com/status-im/status-desktop/assets/60327365/722caf40-7f64-450c-96e6-2f0463eebc02">

**Comment by alaibe** [comment] 2023-09-20 09:46
I can confirm, some channel don't open to me too and it is very slow to navigate

**Comment by jrainville** [comment] 2023-09-20 14:35
This is known and should be fixed in 0.14.0 RC5+
If it still happens, doing a Mark as read on it will fix it.
The reason why it happened is that some Discord messages were not marked as read (pin messages in particular), so the "scroll to last unread message" feature tried to scroll to a message in 2021, so it took forever/failed.

**Closed** 2023-09-20 14:35 UTC
Labels: bug, messenger-team
