### ISSUE TITLE
Communities -> Invite contact: member to be invited is shown as off

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#7458] opened 2022-09-21 08:14 UTC
### Description

1. create community
2. click add members
3. select a contact and proceed
4. check the contact representation on the Invite contact screen

<img width="1061" alt="Screenshot 2022-09-21 at 11 10 28" src="https://user-images.githubusercontent.com/82375995/191451576-5cd676da-f096-4f6b-87db-4a6f791365bc.png">

**Comment by iurimatias** [comment] 2022-09-22 20:13
duplicate of https://github.com/status-im/status-desktop/issues/7472

**Closed by iurimatias** 2022-09-22 20:13 UTC
Labels: bug, Communities, E:Bugfixes, E:Communities, pixel-perfect-issues
