### ISSUE TITLE
[Profile Showcase - Profile Popup] Review own profile details. Now QR code is a new popup.

### ISSUE THREAD

**Issue by alexandraB99** [status-im/status-desktop#13348] opened 2024-01-29 15:27 UTC
[Figma](https://www.figma.com/file/ibJOTPlNtIxESwS96vJb06/%F0%9F%91%A4-Profile-%7C-Desktop?type=design&node-id=2460-30744&mode=design&t=jumwFduKExodhRUc-4)

**Comment by caybro** [comment] 2024-02-08 11:42
Dupe of https://github.com/status-im/status-desktop/issues/13417

**Closed by caybro** 2024-02-08 11:42 UTC
Labels: ui-team, E:Desktop Profile Showcase, E:Desktop Features 2.28.0
