### ISSUE TITLE
Minting status of a token is not updated when transaction is being processed for a long time by blockchain

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#13700] opened 2024-02-23 09:10 UTC
### Description

I tested some minting yesterday with @pavloburykh 
I tried to mint an asset and the transaction was not minting for long long time.
The app UI was constantly saying that token is being minted

I checked the same transaction in the morning today and it finally has been completed https://optimistic.etherscan.io/tx/0xbf2a71611cc8bc76b35dcbf2bd9b1d1353b32e14bc9886d0ae74808a85918944

however the status UI still does not know about it and shows Minting still

<img width="1967" alt="Screenshot 2024-02-23 at 11 04 28" src="https://github.com/status-im/status-desktop/assets/82375995/6069a044-f718-4d99-976c-06b3b6c9684e">

I though i could force refresh the UI by minting another token and by doing this odd thing appeared - the new token has been minted, then app UI refreshed and Mint Owner token screen become available which does not make any sense because i i have these tokens minted already

Also , minting another token did not help dealing with Minting status of the previous one. Restart of application also does not help

<img width="1923" alt="Screenshot 2024-02-23 at 11 07 10" src="https://github.com/status-im/status-desktop/assets/82375995/73f151d5-7198-406b-b292-649d526fe3d0">

https://github.com/status-im/status-desktop/assets/82375995/ff8d5ae0-6c92-4cef-8c47-4ef82bbbdc98

**Comment by jrainville** [comment] 2024-03-27 17:45
Closing as duplicate of https://github.com/status-im/status-desktop/issues/13851

**Closed by jrainville** 2024-03-27 17:45 UTC
Labels: bug, messenger-team, E:Desktop Comm Perms and Minting MVP
