### ISSUE TITLE
`displayName` is not correctly updated in profile page

### ISSUE THREAD

**Issue by noeliaSD** [status-im/status-desktop#10827] opened 2023-05-26 13:26 UTC
# Bug Report

## Description

When user tries to edit the display name, it is not updated correctly in the profile page but after a restart, the display name has been correctly updated with the new value.

**NOTE:** Scenario `suite_settings/tst_userIdentity/The user can change own display name in profile` will be skipped until this bug is solved. Please, enable it again when the bug is solved.

## Steps to reproduce

1. Go to profile screen / Edit
2. Introduce new display name value and save.

#### Expected behavior
The new display name is correctly updated.

#### Actual behavior
The display name input field is updated to the previous value.

### Additional Information

https://github.com/status-im/status-desktop/assets/97019400/30fa188b-b088-4a63-a5f9-a20ee4d425ad

- Status desktop version: master commit ` 0b9d7e19625992aed4b9605dce645b004afa9dae`
- Operating System: macos

**Comment by noeliaSD** [comment] 2023-05-26 13:32
Skipped scenario here: https://github.com/status-im/status-desktop/pull/10828

**Comment by caybro** [comment] 2023-05-30 12:19
Duplicate of https://github.com/status-im/status-desktop/issues/10838

**Closed by caybro** 2023-05-30 12:19 UTC
Labels: bug, ui-team, Profile
