### ISSUE TITLE
Multiple `Can't connect to mail server` popups

### ISSUE THREAD

**Issue by MishkaRogachev** [status-im/status-desktop#9150] opened 2023-01-17 08:57 UTC
# Bug Report

## Description

<img width="646" alt="Screenshot 2023-01-17 at 12 37 38" src="https://user-images.githubusercontent.com/2522130/212852964-342004dc-ca39-4ee0-8304-38ee0a05f5a2.png">

`Can't connect to mail server` popup appears every time this error happens and popup created for each error

## Steps to reproduce

Just wait for a while

### Additional Information

- Status desktop version: 0.9.0-rc2
- Operating System: Mac

**Comment by anastasiyaig** [comment] 2023-01-17 11:08
duplicate of https://github.com/status-im/status-desktop/issues/9131

**Closed by anastasiyaig** 2023-01-17 11:08 UTC
Labels: bug
