### ISSUE TITLE
[Profile Showcase - Profile Popup] General layout updates: Review new design, there are some details updated (buttons, combobox for different perspectives..).

### ISSUE THREAD

**Issue by alexandraB99** [status-im/status-desktop#13344] opened 2024-01-29 15:22 UTC
[Figma](https://www.figma.com/file/ibJOTPlNtIxESwS96vJb06/%F0%9F%91%A4-Profile-%7C-Desktop?type=design&node-id=2460-30704&mode=design&t=jumwFduKExodhRUc-4)

**Comment by caybro** [comment] 2024-02-08 11:41
Dupe of https://github.com/status-im/status-desktop/issues/13416

**Closed by caybro** 2024-02-08 11:41 UTC
Labels: ui-team, E:Desktop Profile Showcase, E:Desktop Features 2.28.0
