### ISSUE TITLE
App shows badge to back up seedphrase even though account was imported 

### ISSUE THREAD

**Issue by 0x-r4bbit** [status-im/status-desktop#5971] opened 2022-06-02 10:49 UTC
After importing an account (although, the process crashed, see #5970) the app show indicators for backing up the seed phase, which should not be the case as the account was restored from a seed phrase in the first place.

![Screenshot from 2022-06-02 12-41-33](https://user-images.githubusercontent.com/445106/171613597-165f3987-3780-49b4-a15f-a1d48dbc98d8.png)

That being said, it could be that this is a second order effect due to #5970 which might prevent status-go from updating accordingly (this is just a guess).

**Comment by jrainville** [comment] 2023-01-12 19:39
Even though this is the older issue, I'll close it as duplicate, since I assigned the most recent one already https://github.com/status-im/status-desktop/issues/7859

**Comment by 0x-r4bbit** [comment] 2023-02-07 08:45
Reopening this one as @jakubgs ran into it in 0.10.0-rc3

**Comment by anastasiyaig** [comment] 2023-02-14 09:04
it seems i am seeing this issue being fixed and opened again 6-7 times already

**Comment by borismelnik** [comment] 2023-03-20 09:54
@0x-r4bbit I can't reproduce it on latest master. May it be a result of import account process crash?

**Comment by 0x-r4bbit** [comment] 2023-03-20 10:04
If non reproducible, feel free to close this one.

**Comment by borismelnik** [comment] 2023-03-20 10:33
can't reproduce on `latest master`

**Closed by borismelnik** 2023-03-20 10:33 UTC
