### ISSUE TITLE
Nickname is overwriting the ENS of the user

### ISSUE THREAD

**Issue by simonricoo** [status-im/status-desktop#1809] opened 2021-02-09 12:50 UTC
https://user-images.githubusercontent.com/52249767/107365918-bf9d3600-6add-11eb-974d-35508787eb02.mov

**Comment by simonricoo** [comment] 2021-02-09 15:16
One more bug related to Nicknames: When I delete the nickname I've assigned to the user its still shown to me in the chat. 

https://user-images.githubusercontent.com/52249767/107384225-0b59da80-6af2-11eb-8dd4-89eb32369097.mov

**Comment by ace-smart** [comment] 2021-02-11 15:46
Could you assign this issue to me?

**Comment by ace-smart** [comment] 2021-02-12 18:31
@simonricoo @jrainville Could you reproduce this issue from the latest master?
Currently, I couldn't view this issue.

**Comment by jrainville** [comment] 2021-02-12 18:42
@ace-smart I couldn't reproduce the bug where the ENS name gets replaced by the nickname, however, I still see the issue where if I give someone a Nickname, close the profile popup and reopen it, it says "None" where it should say the person's nickname

**Comment by ace-smart** [comment] 2021-02-12 18:49
I couldn't reproduce this issue yet, could you share the video for me?

**Comment by jrainville** [comment] 2021-02-12 18:59
Here is a video. You can't see my mouse pointing, but you can see at the end when I reopen the popup, the nickname is empty

https://user-images.githubusercontent.com/11926403/107810298-78f84780-6d3a-11eb-9156-f66f8676414d.mp4

**Comment by ace-smart** [comment] 2021-02-12 19:18
It is strange, I couldn't reproduce it still. Did you pull latest master?

**Comment by jrainville** [comment] 2021-02-12 19:22
I just checked and I am indeed on latest master. Tested on Windows and Linux

**Comment by ace-smart** [comment] 2021-02-12 20:22
https://user-images.githubusercontent.com/76216456/107818752-812fa180-6d91-11eb-8746-5d34a98cf3d8.mp4

This is my captured video

**Comment by iurimatias** [comment] 2021-03-08 21:14
cannot replicate, has been fixed in the meanwhile

**Closed by iurimatias** 2021-03-08 21:14 UTC
Labels: bug
