### ISSUE TITLE
Badge and new message line doesn't appear when messages are fetched that are a little older than most recent

### ISSUE THREAD

**Issue by jrainville** [status-im/status-desktop#9218] opened 2023-01-20 15:47 UTC
# Bug Report

## Description

This might be hard to reproduce without tinkering with the code.

If you have a chat where the message fetching from store nodes is unreliable, the messages might come in the wrong order.

What happened was that a recent message came in, I got the badge for it and read the message. I went to another chat. Later, I receive an OS notification for a "new message", but no badge appeared. I checked the channel where the message was. It was an older message (but not super old, just like the second in the list). 

Even though it's not the most recent message, it should still produce the unread badge and the new message line, since I didn't read that message.

I assume the issue is desktop side, but it could be status-go since it's what tells us we have unread message. It might be that we mark as read wrongly though

## Steps to reproduce

There is no way to get this reliably using the app normally,

I'd recommend modifying the code to manually force the behavior. Maybe use a timer to send a first fake message, then another a bit later and force the second message to have a clock lower than the first.

### Additional Information

- Status desktop version: 0.9RC3

**Comment by caybro** [comment] 2023-01-20 15:56
![image_20-01-2023_16-54-23](https://user-images.githubusercontent.com/5377645/213744484-01d45485-41eb-4c91-b8d6-fba7276d0f03.png)

Similar case here, the marker says "5 messages" while there's really only one. The problem is that this 1 new message arrived later, only after I'd sent the 4 below. Should my own messages also count as unread?

**Comment by osmaczko** [comment] 2023-01-31 11:44
> ![image_20-01-2023_16-54-23](https://user-images.githubusercontent.com/5377645/213744484-01d45485-41eb-4c91-b8d6-fba7276d0f03.png)
> 
> Similar case here, the marker says "5 messages" while there's really only one. The problem is that this 1 new message arrived later, only after I'd sent the 4 below. Should my own messages also count as unread?

I would say yes. IMO displaying "1 new message" and seeing multiple messages below the marker would be more surprising to the ordinary user who doesn't probably understand the technicalities of why messages may come out of order.

**Comment by osmaczko** [comment] 2023-01-31 11:50
> I assume the issue is desktop side, but it could be status-go since it's what tells us we have unread message.

I would say it is rather a status-go issue because we get the info about unread messages count from there.

>  It might be that we mark as read wrongly though

It's unlikely. If the chat is not active it can't mark messages as read even if scrolled to the most recent message. Unless something has changed in the meantime..

**Comment by MishkaRogachev** [comment] 2023-01-31 12:01
From the user's perspective, if we got a new message with timestamp earlier, what exactly we should show to user?
1) No new message marker because we already gone forward in the chat
2) New message marker before the new arrived message with right number (one in @caybro 's case) and maybe some extra-highting for the new messages(s)

**Comment by osmaczko** [comment] 2023-01-31 12:10
> From the user's perspective, if we got a new message with timestamp earlier, what exactly we should show to user?
> 
> 1. No new message marker because we already gone forward in the chat
> 2. New message marker before the new arrived message with right number (one in @caybro 's case) and maybe some extra-highting for the new messages(s)

The question is, should the new message with the older clock be marked as read if we have already marked more recent messages as read? The source of truth is status-go, new messages marker will always point to the first unread message, also the chat will be highlighted when unreadMessagesCount > 0.

**Comment by MishkaRogachev** [comment] 2023-02-01 07:42
<img width="1010" alt="Screenshot 2023-02-01 at 11 38 55" src="https://user-images.githubusercontent.com/2522130/215980501-f52e7a29-89cb-4f08-a679-4509007c26cd.png">
`10` and `12` messages were delivered later, so wrong is only number on the NewMessageMarker's badge

**Comment by MishkaRogachev** [comment] 2023-02-01 08:46
@osmaczko is this behaviour expected? When we open chat with new message marker every new message updates unread count?

https://user-images.githubusercontent.com/2522130/215994039-e11b3a0f-ce5a-4cd6-a5cf-d9f2699c3919.mov

**Comment by osmaczko** [comment] 2023-02-01 08:59
> IMO it would be more confusing, if we'll display `2 missed messages since ...` on the marker what is above 6 messages

Exactly

> Here 10 and 12 messages were delivered later, so wrong is only number on the NewMessageMarker's badge?

The number is ok, see above

**Comment by osmaczko** [comment] 2023-02-01 09:02
> @osmaczko is this behaviour expected? When we open chat with new message marker every new message updates unread count?
> 
>  Screen.Recording.2023-02-01.at.12.43.42.mov

Yes, the number is simply the count of messages under the marker.

**Comment by MishkaRogachev** [comment] 2023-02-01 15:19
> > @osmaczko is this behaviour expected? When we open chat with new message marker every new message updates unread count?
> > Screen.Recording.2023-02-01.at.12.43.42.mov
> 
> Yes, the number is simply the count of messages under the marker.

Thanks! So only one problem left - missing marker in case when we receive rotteт message

**Comment by MishkaRogachev** [comment] 2023-02-01 15:36
> So in the end, the behaviour we have right now seems ok? Maybe the original issue of the marker and badge not appearing has been fixed? Or maybe it's just too hard to reproduce?

I'm not sure that origin issue is gone. I've made a test there 1/2 of messages sent with clock downshifted and it behave in same way

**Comment by MishkaRogachev** [comment] 2023-02-02 16:35
@osmaczko i've fixed logic when chat is not visible... And it's still have problem with new message marker position. https://user-images.githubusercontent.com/2522130/216384634-41b6619a-c712-4284-b261-87a4732c96cb.mov

**Comment by MishkaRogachev** [comment] 2023-02-03 11:23
UPD: 
<img width="514" alt="Screenshot 2023-02-03 at 15 12 08" src="https://user-images.githubusercontent.com/2522130/216589630-0a2bedf0-56e7-42b6-87d8-3f1c95396bbe.png">
This situation may happen when you open a chat while client is still receiving messages. And if receives a message out of order while chat is already activated, this message is already marked as seen

**Closed** 2023-04-25 13:03 UTC
Labels: bug, priority 1: high, E:Bugfixes, S:3, messenger-team
