### ISSUE TITLE
Chat: Messages are not being grouped by received date 

### ISSUE THREAD

**Issue by glitchminer** [status-im/status-desktop#8962] opened 2023-01-04 16:44 UTC
# Bug Report

## Description

In chat history, messages from the same day are split up and divided by messages from other days. Noted after upgrading to 0.9rc1 but may have been occurring previously.

For example, 
- December 23
   - message 1
- December 26
   - message 3
- December 23
   - message 2
- December 26
   - message 4
- December 27
   - message 6
- December 26
   - message 5

## Steps to reproduce

Unknown, does not appear on all chats. Upgraded to 0.9, scrolled up in group chat to view message history.

#### Expected behavior

Messages are grouped by day

#### Actual behavior

Messages are not grouped by day

### Additional Information

- Status desktop version: 0.9
- Operating System: Mac

**Comment by osmaczko** [comment] 2023-01-11 17:30
Can't reproduce anymore. Most likely fixed by: https://github.com/status-im/status-desktop/pull/9001

**Comment by osmaczko** [comment] 2023-01-16 18:07
I can reproduce it on 0.9.0 RC2.

The root cause behind this is: diverged `whisper_timestamp` values.

| clock_value | whisper_timestamp | timestamp | text | c_t | username | chat_id | response_to |
| -- | -- | -- | -- | -- | -- | -- | -- |
| 1673514570146 | 1673514573000 | 1673514570146 | A | 1 | Curvy... | 06b9cf6b... |   | 
| 1673516761013 | 1673516763000 | 1673516761013 | B | 1 | Delicious... | 06b9cf6b... | 0x524c... | 
| 1673517063622 | 1673599961000 | 1673517063622 | C | 1 | Sardonic... | 06b9cf6b... | 0x524c... | 
| 1673517347444 | 1673600248000 | 1673517347444 | D | 1 | Sardonic... |  06b9cf6b... | 0x2a4e... | 
| 1673521819673 | 1673521821000 | 1673521819673 | E | 7 | Curvy... |  06b9cf6b... |   | 
| 1673521820173 |1673521827000 | 1673521820173 | F | 1 | Curvy... |  06b9cf6b... |   | 

Converted to datetime:
| clock_value | whisper_timestamp | timestamp | text |
| -- | -- | -- | -- |
| 1673514570146 | 12/01/2023, 10:09:33 | 12/01/2023, 10:09:30 | A |
| 1673516761013 | 12/01/2023, 10:46:03 | 12/01/2023, 10:46:01 | B |
| 1673517063622 | **13/01/2023, 09:52:41** | 12/01/2023, 10:51:03 | C |
| 1673517347444 | **13/01/2023, 09:57:28** | 12/01/2023, 10:55:47 | D |
| 1673521819673 | 12/01/2023, 12:10:21 | 12/01/2023, 12:10:19 | E |
| 1673521820173 | 12/01/2023, 12:10:27 | 12/01/2023, 12:10:20 | F |

As discussed with @cammellos, we should probably use `timestamp` instead of `whisper_timestamp` to display messages' datetime.

**Comment by caybro** [comment] 2023-01-16 23:10
Latest master has this too; last 2 messages are out of order:
![image](https://user-images.githubusercontent.com/5377645/212778242-162b0be8-20e7-4ad3-9ccf-faecbcf06850.png)

**Comment by osmaczko** [comment] 2023-01-17 08:07
> Latest master has this too; last 2 messages are out of order: ![image](https://user-images.githubusercontent.com/5377645/212778242-162b0be8-20e7-4ad3-9ccf-faecbcf06850.png)

Where can I find these messages? Most likely the order is right but the datetime displayed is wrong, I would need to check the database to confirm.

**Comment by cammellos** [comment] 2023-01-17 08:34
> Latest master has this too; last 2 messages are out of order: ![image](https://user-images.githubusercontent.com/5377645/212778242-162b0be8-20e7-4ad3-9ccf-faecbcf06850.png)

It's always good to differentiate order and timestamps, the two are only tangentially related, unix timestamps are not (and should not) be used for ordering or check for potential ordering, since clocks differ on different devices, we use lamport timestamps hinted by a unix timestamp for that (clock values are called). (Just a neatpick, but it's always good to make sure people reading not "in the known" don't get the wrong idea :) )

**Closed** 2023-01-17 15:21 UTC
Labels: bug, Chat, priority 1: high, E:Bugfixes
