### ISSUE TITLE
Desktop 0.11 will not open after install on MacOS. 

### ISSUE THREAD

**Issue by jonathanbarker** [status-im/status-desktop#10360] opened 2023-04-19 08:14 UTC
# Bug Report

## Description
Followed the instructions to upgrade to 0.11, but after install the app would not open. 

## Steps to reproduce
Download 0.11. 
Install 0.11 (replacing last version)
Application installs in application folder
Click open
Click ok on "this app was downloaded from the internet, do you want to open"
Asks for Touch-ID or password (have tried both)
App does not open. 
Status then appears as "not responding" in Activity Monitor. 
Waited a few hours - nothing. 
Only thing I'm able to do is Force Quit. 

#### Expected behavior

App opens

#### Actual behavior
App does not open.

### Additional Information

- Status desktop version: 0.11
- Operating System: MacOS Monterey 12.5.1. 
- Machine: MacBook Pro M2, 2022.

**Comment by caybro** [comment] 2023-04-19 09:26
Duplicate of https://github.com/status-im/status-desktop/issues/10332

**Closed by caybro** 2023-04-19 09:26 UTC
Labels: bug
