### ISSUE TITLE
The chat is opened to not contact after sending a contact request

### ISSUE THREAD

**Issue by elina2015** [status-im/status-desktop#6294] opened 2022-06-29 19:40 UTC
# Bug Report

## Steps to reproduce
1. Open the test chat and click on any user name in the chat - 'Send Contact Request'
2. Enter any text and click 'Send Contact Request'

#### Expected behavior
The request is sent, and the current user stays in the public test chat
#### Actual behavior
The chat is opened with a non-mutual contact
### Additional Information
https://user-images.githubusercontent.com/14942081/176522409-ae33791e-d7bf-427a-bf86-ad31a3d360f9.mov

- Status desktop version: https://ci.status.im/job/status-desktop/job/branches/job/macos/job/master/2255/
- Operating System: macOS Monterey, 12.3 Beta (21E5227a)

**Comment by iurimatias** [comment] 2022-06-29 20:16
duplicate of https://github.com/status-im/status-desktop/issues/6291

**Closed by iurimatias** 2022-06-29 20:16 UTC
Labels: bug, Chat, priority 1: high
