### ISSUE TITLE
The long Display Name doesn't look good in Settings

### ISSUE THREAD

**Issue by elina2015** [status-im/status-desktop#5067] opened 2022-03-17 04:56 UTC
# Bug Report

## Description
The long Display Name is shown incorrectly

## Steps to reproduce
1. Sign out
2. Click 'Generate new keys'
3. In the field 'DisplayName' enter more than 24 characters
4. Click on the arrow-button
5. Go to Settings

#### Expected behavior
The long Display Name is shown correctly
#### Actual behavior
The long Display Name is shown incorrectly
<img width="1323" alt="image" src="https://user-images.githubusercontent.com/14942081/158739766-d22f3e7f-4b60-40eb-8426-a6d0eb316176.png">

### Additional Information

- Status desktop version: commit b07910e27feed930ba0b73b18b791bffb7b7b229
- Operating System: macOS v. 11.6.5 (20G517)

**Comment by iurimatias** [comment] 2022-03-17 20:17
same/similar issue as https://github.com/status-im/status-desktop/issues/5066

**Comment by iurimatias** [comment] 2022-03-20 12:19
closing as duplicate of #5066 (if that one is fixed this one is fixed)

**Closed by iurimatias** 2022-03-20 12:19 UTC
Labels: bug, ui, Profile, priority 2: medium
