### ISSUE TITLE
'Search' field (on Communities Portal) differs from the Design

### ISSUE THREAD

**Issue by elina2015** [status-im/status-desktop#6358] opened 2022-07-05 03:33 UTC
# Bug Report

## Steps to reproduce
1. Sign in and create a few communities
2. Open the Communities Portal and check the 'Search' field according to the [Design](https://www.figma.com/file/17fc13UBFvInrLgNUKJJg5/Kuba%E2%8E%9CDesktop?node-id=2090%3A245814)

#### Expected behavior
<img width="952" alt="image" src="https://user-images.githubusercontent.com/14942081/177244267-eb294213-010c-40f0-bb90-3d5d059758d0.png">

#### Actual behavior
<img width="1269" alt="image" src="https://user-images.githubusercontent.com/14942081/177244221-10370e5f-0dd9-48aa-a01c-551a5976cb98.png">

### Additional Information

- Status desktop version: https://ci.status.im/job/status-desktop/job/branches/job/macos/job/master/2275/
- Operating System: macOS Monterey, 12.3 Beta (21E5227a)

**Comment by alexandraB99** [comment] 2022-07-18 13:52
@elina2015 the text is of 15 pixels as in Figma
<img width="363" alt="srchfigma" src="https://user-images.githubusercontent.com/31625338/179526461-e476dba1-080a-4983-a215-e200285c02f9.png">

Could you please check again, I don't see a difference there
<img width="437" alt="srchtxt" src="https://user-images.githubusercontent.com/31625338/179526525-81e28b7b-f2a4-420a-9d53-ca0b7d4de606.png">

**Comment by noeliaSD** [comment] 2022-07-19 07:16
@iurimatias removed the `bug` tag some days ago so maybe the issue is about enabling the search functionality??

**Comment by alexandraB99** [comment] 2022-07-19 08:34
@noeliaSD there's a different issue for that https://github.com/status-im/status-desktop/issues/6360

**Comment by elina2015** [comment] 2022-07-20 22:39
@noeliaSD thank you, I checked on the latest master () and the size of the 'Search' words looks correct. 
There is only one small thing:
1. The space between the Search word and the magnifying glass icon
2. The Search field is too long
Could you kindly help with it?
<img width="787" alt="image" src="https://user-images.githubusercontent.com/14942081/180094489-fe3b575d-4556-4ee1-ad98-71ccf9214717.png">

**Comment by alexandraB99** [comment] 2022-07-25 12:58
PR https://github.com/status-im/status-desktop/pull/6584 with respective updates merged. @elina2015 please check on master again!

**Comment by elina2015** [comment] 2022-07-25 18:17
@alexandraB99 thank you for the updates! Tested on the latest master and now it looks much better.

**Comment by alexandraB99** [comment] 2022-07-26 10:54
Closing as per above comment!

**Closed by alexandraB99** 2022-07-26 10:54 UTC
Labels: Communities, tested, pixel-perfect-issues
