### ISSUE TITLE
[Windows] Call RPC error after creating new account

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#3384] opened 2021-09-07 07:14 UTC
<img width="1552" alt="Screenshot 2021-09-07 at 10 12 24" src="https://user-images.githubusercontent.com/82375995/132300829-cef06b3a-5ef9-45c9-b357-1074c289cad1.png">

**To reproduce:**

1. download `Build #1004 (06-Sep-2021 21:00:34)`
2. create a new account and proceed

As result, right after the password is set, this error above is shown

**Comment by michaelsbradleyjr** [comment] 2021-09-07 14:22
So far, I have been unable to reproduce this error on my Windows 10 laptop (x86_64).

I tried several times with `Build #1004` and several times with a local dev build of latest `master`, each time creating a new account.

Give the error *can* happen, per the screenshot included in this issue, that strongly indicates it's a race condition of some kind; per the stack trace in the screenshot, the race condition is related in some way to `getOpenseaCollections`.

**Comment by anastasiyaig** [comment] 2021-09-07 14:23
@michaelsbradleyjr i know that @flexsurfer received this error as well (or i am wrong)

**Comment by iurimatias** [comment] 2021-09-10 18:15
fixed by https://github.com/status-im/status-lib/pull/4

**Closed by iurimatias** 2021-09-10 18:15 UTC
Labels: bug, windows, general, priority 0: blocker
