### ISSUE TITLE
Contact requests are broken

### ISSUE THREAD

**Issue by Valentina1133** [status-im/status-desktop#13322] opened 2024-01-29 08:08 UTC
# Bug Report

No requests for receiver

1. Send contact request from one user to another
2. Go to the instance for second user
3. Open Settings/Messaging/Contacts

#### Expected behavior
Request received and is in Pending requests

#### Actual behavior
No request received

### Additional Information

- Status desktop version: the latest master build
- Operating System: Mac OS Ventura 13.5

**Comment by anastasiyaig** [comment] 2024-01-29 08:12
i assigned 0.16 because the issue is crucial to fix for RC

**Comment by anastasiyaig** [comment] 2024-02-06 12:15
This issue is sporadic. I need to monitor that in release branch (client + go). As i got from @chaitanyaprem , there were some changes on backend that could impact that functionality.

**Comment by chaitanyaprem** [comment] 2024-02-06 12:19
> This issue is sporadic. I need to monitor that in release branch (client + go). As i got from @chaitanyaprem , there were some changes on backend that could impact that functionality.

I realized what i had quoted in the call was when Filter was being used. But in desktop i am assuming relay is being used. 
In that case would be good to have debug log on both sides to get an idea of what might be causing this.

**Comment by anastasiyaig** [comment] 2024-02-06 12:20
sure, I agree. I will rested that in release when it comes to that, meanwhile will test master

**Comment by anastasiyaig** [comment] 2024-02-20 06:46
dont see that in RC, closing for now

**Closed by anastasiyaig** 2024-02-20 06:46 UTC
Labels: bug, messenger-team, E:Desktop Contact Requests
