### ISSUE TITLE
The "switch to chat" dialog launched with Command+K should offer fuzzy matching

### ISSUE THREAD

**Issue by zah** [status-im/status-desktop#8616] opened 2022-12-05 11:31 UTC
The current dialog requires an exact case-sensitive substring matching which is too inconvenient to use.

At a bare minimum, the matching should be done in case-insensitive fashion, but competing products such as Discord and Slack offer even fuzzier matching where for example typing "jms" will successfully match for a contact named "James".

**Comment by jrainville** [comment] 2022-12-05 14:43
duplicate of https://github.com/status-im/status-desktop/issues/8460

**Closed by jrainville** 2022-12-05 14:43 UTC
Labels: feature

**Comment by zah** [comment] 2022-12-06 16:25
@jrainville, I could argue that my suggestion here is about supporting fuzzy matching while the other issue is focusing only on case insensitivity.

**Comment by zah** [comment] 2022-12-07 20:41
Done:
https://status-desktop.featureupvote.com/suggestions/347077/switch-to-chat-cmdk-should-offer-fuzzy-matching
