### ISSUE TITLE
[Contacts]: Add to Contacts button appears when updating to 0.10.0

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#9406] opened 2023-02-02 12:47 UTC
### Description

1. i had my status data folder with 0.9.0 build
2. i updated to 0.10.0
3. i opened a conversation in 1x1 chat
4. there is a `add to contact` button at the top for a contact i already have as mutual

<img width="638" alt="Screenshot 2023-02-02 at 15 40 24" src="https://user-images.githubusercontent.com/82375995/216328936-cedd2cfb-5a2d-4dcc-8617-03df3ea7e569.png">

**Comment by anastasiyaig** [comment] 2023-02-02 12:51
<img width="666" alt="Screenshot 2023-02-02 at 15 51 27" src="https://user-images.githubusercontent.com/82375995/216329847-a1ce4ba6-00e2-48d6-b80f-a919427cf92b.png">

community layout is broken too

**Comment by 0x-r4bbit** [comment] 2023-02-02 13:29
The later is already fixed with https://github.com/status-im/status-desktop/pull/9403

**Comment by jrainville** [comment] 2023-02-02 14:41
The contact issue is fixed in latest master here: https://github.com/status-im/status-desktop/pull/9400

The bug was caused by  a bad migration

**Closed by jrainville** 2023-02-02 14:41 UTC
Labels: bug, priority 1: high, E:Bugfixes
