### ISSUE TITLE
Mentions and members list after channel permissions are added

### ISSUE THREAD

**Issue by glitchminer** [status-im/status-desktop#14239] opened 2024-04-01 13:24 UTC
# Bug Report

## Description

After permissions were added to the QA channel users no longer had access to it. The following issues were noted about this state:

1. The members list for the channel includes users that do not have access to it
2. It was possible to @ mention users that do not have access to the channel
3. Users that were mentioned received notifications about it even though they could not access the channel

### Additional Information

- Status desktop version: 2.28RC3
- Operating System: Mac

cc: @saledjenic

**Comment by jrainville** [comment] 2024-05-02 17:26
Those this still reproduce in the latest RCs? We fixed a couple of issues about re-evaluation of members.

Do note that especially for the Status community, the re-evaluation is not fast, since there are so many permissions and channels. 
It's worth testing in a more controlled environment first.

**Comment by jrainville** [comment] 2024-05-03 19:59
Also, do note that it takes a few minutes for the members to be re-evaluated, so it's possible that a permission is a added and the member doesn't get removed yet

**Comment by jrainville** [comment] 2024-05-06 14:52
I'm gonna close this as it seems like it was just the delay before evaluation. The delay will be optimized in 2.29, so the problem should become less noticeable.

**Closed by jrainville** 2024-05-06 14:52 UTC
Labels: bug, backend-team, E:Desktop Comm Perms and Minting MVP
