### ISSUE TITLE
Can't join Status CC Community

### ISSUE THREAD

**Issue by fryorcraken** [status-im/status-desktop#11676] opened 2023-07-25 23:56 UTC
# Bug Report

## Description

I was able to import my keycard account on Status Desktop so I am now trying to join the Status CC community using it but it fails to import

## Steps to reproduce

1. Log in old account
2. View Status CC Community
4. Copy URL
![share_cc](https://github.com/status-im/status-desktop/assets/110212804/aa5650e0-cc8f-4d10-a6b4-4aa0d893a6c1)

5. log out
6. Login with keycard (new account)
7. Go to Communities -> Import using key
8. Past Status CC URL (I am not revealing the key on purpose): https://status.app/c/zQ3shf8Evh...czZkvS69P6rJ7aed
9. I can see green "Public Key detected"
10. Click "Import"

#### Expected behavior

I join the community or at least I have some indication that I am now waiting from approval from community owner

#### Actual behavior

Modal stays open with wheel of death

![wheel_of_death](https://github.com/status-im/status-desktop/assets/110212804/fe7df50d-bc0e-4824-b9b9-2b6b64aacac2)
### Additional Information

- Status desktop version: v0.13.2
- Operating System: Fedora Linux x86_64

#### Bonus

When I open the URL https://status.app/c/zQ3shf8Evh...czZkvS69P6rJ7aed in firefox, I get an auth modal:

![browser](https://github.com/status-im/status-desktop/assets/110212804/690dc15b-dcdb-4449-875a-0f8ca0af8389)

Logs:

```

 ./StatusIm-Desktop-v0.13.2-8acc0a-x86_64.AppImage 
INFO [07-26|09:40:35.471] Status backend initialized               backend=geth version=0.158.1 commit=3ebf67fcd IpfsGatewayURL=https://ipfs.status.im/
Info: Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway. (:0, )
INF 2023-07-26 09:40:36.599+10:00 Version: 0.13.2                            topics="status-app" tid=332062 file=nim_status_client.nim:182
INF 2023-07-26 09:40:36.599+10:00 Commit: 8acc0a00f                          topics="status-app" tid=332062 file=nim_status_client.nim:183
INF 2023-07-26 09:40:36.600+10:00 Current date:                              topics="status-app" tid=332062 file=nim_status_client.nim:184 currentDateTime=2023-07-26T09:40:36+10:00
INF 2023-07-26 09:40:36.600+10:00 starting application controller...         topics="status-app" tid=332062 file=nim_status_client.nim:186
keycard - listing readers
keycard - waiting for card
keycard - card found at index 0
keycard - using reader ACS ACR39U ICC Reader 00 00
keycard - card protocol T1
Warning: libpng warning: iCCP: known incorrect sRGB profile (:0, )
INF 2023-07-26 09:40:44.324+10:00 starting application...                    topics="status-app" tid=332062 file=nim_status_client.nim:189
WRN 2023-07-26 09:40:44.326+10:00 Error decoding signal                      topics="signals-manager" tid=332062 file=signals_manager.nim:48 err="Unknown signal received: mediaserver.started"
Debug: Network Cache Dir:  "/home/fryorcraken/.config/Status/tmp/netcache" (:0, )
keycard - listing readers
keycard - waiting for card
keycard - card found at index 0
keycard - using reader ACS ACR39U ICC Reader 00 00
keycard - card protocol T1
WRN 2023-07-26 09:42:52.382+10:00 Error decoding signal                      topics="signals-manager" tid=332062 file=signals_manager.nim:48 err="Unknown signal received: mediaserver.started"
INF 2023-07-26 09:42:55.025+10:00 initMailservers                            topics="mailservers-service" tid=332062 file=service.nim:202 name=node-01.ac-cn-hongkong-c.status.prod nodeAddress=/dns4/node-01.ac-cn-hongkong-c.status.prod.statusim.net/tcp/30303/p2p/16Uiu2HAkvEZgh3KLwhLwXg95e5ojM8XykJ4Kxi2T7hk22rnA7pJC
INF 2023-07-26 09:42:55.025+10:00 initMailservers                            topics="mailservers-service" tid=332062 file=service.nim:202 name=node-01.gc-us-central1-a.status.prod nodeAddress=/dns4/node-01.gc-us-central1-a.status.prod.statusim.net/tcp/30303/p2p/16Uiu2HAkwBp8T6G77kQXSNMnxgaMky1JeyML5yqoTHRM8dbeCBNb
INF 2023-07-26 09:42:55.026+10:00 initMailservers                            topics="mailservers-service" tid=332062 file=service.nim:202 name=node-01.do-ams3.status.prod nodeAddress=/dns4/node-01.do-ams3.status.prod.statusim.net/tcp/30303/p2p/16Uiu2HAm6HZZr7aToTvEBPpiys4UxajCTU97zj5v7RNR2gbniy1D
INF 2023-07-26 09:42:55.027+10:00 initMailservers                            topics="mailservers-service" tid=332062 file=service.nim:202 name=node-02.ac-cn-hongkong-c.status.prod nodeAddress=/dns4/node-02.ac-cn-hongkong-c.status.prod.statusim.net/tcp/30303/p2p/16Uiu2HAmFy8BrJhCEmCYrUfBdSNkrPw6VHExtv4rRp1DSBnCPgx8
INF 2023-07-26 09:42:55.027+10:00 initMailservers                            topics="mailservers-service" tid=332062 file=service.nim:202 name=node-02.do-ams3.status.prod nodeAddress=/dns4/node-02.do-ams3.status.prod.statusim.net/tcp/30303/p2p/16Uiu2HAmSve7tR5YZugpskMv2dmJAsMUKmfWYEKRXNUxRaTCnsXV
INF 2023-07-26 09:42:55.028+10:00 initMailservers                            topics="mailservers-service" tid=332062 file=service.nim:202 name=node-02.gc-us-central1-a.status.prod nodeAddress=/dns4/node-02.gc-us-central1-a.status.prod.statusim.net/tcp/30303/p2p/16Uiu2HAmDQugwDHM3YeUp86iGjrUvbdw3JPRgikC7YoGBsT2ymMg
INF 2023-07-26 09:42:55.029+10:00 fetch mailservers                          topics="mailservers-service" tid=332062 file=service.nim:208 rpc_proc=mailservers_getMailservers response="(jsonrpc: \"2.0\", result: null, id: 0, error: nil)"
2023-07-26T09:42:55+1000 unset [github.com/anacrolix/torrent.(*Client).NewAnacrolixDhtServer.func2:406]: dht server on [::]:38329 (node id 1b5985bf2ecb8f3110977891bb4415486d5f6b25) completed bootstrap ({NumAddrsTried:12 NumResponses:0})
WRN 2023-07-26 09:42:58.031+10:00 missing locale details                     tid=332062 file=module.nim:43 locale=base
WRN 2023-07-26 09:42:58.038+10:00 expected response is not a json object     topics="ens-service" tid=332062 file=service.nim:156 procName=getAllMyEnsUsernames
getMtInAndOutAmounts 2 3 0xaac74cd922ceead 0x3cf8a3dc17690aa00
getMtInAndOutAmounts 1 3 0x1158e460913d00000 0x18733ddb3415a
ERR 2023-07-26 09:42:58.285+10:00 rpc response error                         topics="rpc" tid=332112 file=core.nim:36 err="\nstatus-go error [methodName:wallet_getOpenseaAssetsByOwnerWithCursor, code:-32000, message:unsuccessful request: 403 Forbidden ]\n"
ERR 2023-07-26 09:42:58.285+10:00 error doing rpc request                    topics="rpc" tid=332112 file=core.nim:40 methodName=wallet_getOpenseaAssetsByOwnerWithCursor exception="\nstatus-go error [methodName:wallet_getOpenseaAssetsByOwnerWithCursor, code:-32000, message:unsuccessful request: 403 Forbidden ]\n"
keycard - listing readers
keycard - waiting for card
keycard - card found at index 0
keycard - using reader ACS ACR39U ICC Reader 00 00
keycard - card protocol T1
ERR 2023-07-26 09:43:02.905+10:00 get - bloom level is supported only for a waku version 1 topics="node-config-service" tid=332062 file=service.nim:101
ERR 2023-07-26 09:43:02.931+10:00 get - bloom level is supported only for a waku version 1 topics="node-config-service" tid=332062 file=service.nim:101
Warning: qrc:/app/AppLayouts/Chat/stores/RootStore.qml:650: TypeError: Cannot call method 'getMySectionId' of undefined (qrc:/app/AppLayouts/Chat/stores/RootStore.qml:650, )
Warning: qrc:/app/AppLayouts/Chat/stores/RootStore.qml:74: TypeError: Cannot read property 'loadingHistoryMessagesInProgress' of undefined (qrc:/app/AppLayouts/Chat/stores/RootStore.qml:74, )
Warning: qrc:/app/AppLayouts/Chat/stores/RootStore.qml:72: TypeError: Cannot read property 'contactRequestsModel' of undefined (qrc:/app/AppLayouts/Chat/stores/RootStore.qml:72, )
Warning: qrc:/app/AppLayouts/Chat/stores/RootStore.qml:48: TypeError: Cannot read property 'collectiblesModel' of undefined (qrc:/app/AppLayouts/Chat/stores/RootStore.qml:48, )
Warning: qrc:/app/AppLayouts/Chat/stores/RootStore.qml:36: TypeError: Cannot read property 'tokenList' of undefined (qrc:/app/AppLayouts/Chat/stores/RootStore.qml:36, )
Warning: qrc:/app/AppLayouts/Chat/stores/RootStore.qml:33: TypeError: Cannot read property 'model' of undefined (qrc:/app/AppLayouts/Chat/stores/RootStore.qml:33, )
Warning: qrc:/app/AppLayouts/Chat/stores/PermissionsStore.qml:71: TypeError: Cannot read property 'allTokenRequirementsMet' of undefined (qrc:/app/AppLayouts/Chat/stores/PermissionsStore.qml:71, )
Warning: qrc:/app/AppLayouts/Chat/stores/PermissionsStore.qml:52:9: Unable to assign [undefined] to QAbstractItemModel* (qrc:/app/AppLayouts/Chat/stores/PermissionsStore.qml:52, )
Warning: qrc:/app/AppLayouts/Chat/stores/PermissionsStore.qml:33:9: Unable to assign [undefined] to QAbstractItemModel* (qrc:/app/AppLayouts/Chat/stores/PermissionsStore.qml:33, )
Warning: qrc:/app/AppLayouts/Chat/stores/PermissionsStore.qml:19:9: Unable to assign [undefined] to QAbstractItemModel* (qrc:/app/AppLayouts/Chat/stores/PermissionsStore.qml:19, )
Warning: qrc:/app/AppLayouts/Chat/stores/PermissionsStore.qml:15: TypeError: Cannot read property 'permissionsModel' of undefined (qrc:/app/AppLayouts/Chat/stores/PermissionsStore.qml:15, )
Warning: qrc:/app/AppLayouts/Chat/stores/RootStore.qml:67: TypeError: Cannot read property 'activeItem' of undefined (qrc:/app/AppLayouts/Chat/stores/RootStore.qml:67, )
Warning: qrc:/app/AppLayouts/Onboarding/OnboardingLayout.qml:149:9: Unable to assign [undefined] to QObject* (qrc:/app/AppLayouts/Onboarding/OnboardingLayout.qml:149, )
Warning: qrc:/main.qml:145:9: Unable to assign [undefined] to QObject* (qrc:/main.qml:145, )
WRN 2023-07-26 09:43:03.240+10:00 Error decoding signal                      topics="signals-manager" tid=332062 file=signals_manager.nim:48 err="Unknown signal received: mediaserver.started"
ERR 2023-07-26 09:43:03.252+10:00 unexisting chat key:                       topics="chat-section-module" tid=332062 file=module.nim:505 chatId= methodName=getChatContentModule
ERR 2023-07-26 09:43:03.261+10:00 get - bloom level is supported only for a waku version 1 topics="node-config-service" tid=332062 file=service.nim:101
ERR 2023-07-26 09:43:03.279+10:00 unexisting chat key:                       topics="chat-section-module" tid=332062 file=module.nim:505 chatId= methodName=getChatContentModule
ERR 2023-07-26 09:43:03.280+10:00 unexisting chat key:                       topics="chat-section-module" tid=332062 file=module.nim:505 chatId= methodName=getChatContentModule
ERR 2023-07-26 09:43:03.345+10:00 unexisting chat key:                       topics="chat-section-module" tid=332062 file=module.nim:505 chatId= methodName=getChatContentModule
ERR 2023-07-26 09:43:03.346+10:00 unexisting chat key:                       topics="chat-section-module" tid=332062 file=module.nim:505 chatId= methodName=getChatContentModule
ERR 2023-07-26 09:43:03.494+10:00 unexisting chat key:                       topics="chat-section-module" tid=332062 file=module.nim:505 chatId= methodName=getChatContentModule
ERR 2023-07-26 09:43:03.504+10:00 get - bloom level is supported only for a waku version 1 topics="node-config-service" tid=332062 file=service.nim:101
Warning: libpng warning: iCCP: known incorrect sRGB profile (:0, )
ERR 2023-07-26 09:43:03.659+10:00 unexisting chat key:                       topics="chat-section-module" tid=332062 file=module.nim:505 chatId= methodName=getChatContentModule
Warning: qrc:/app/AppLayouts/Chat/views/ChatColumnView.qml:274: TypeError: Cannot read property 'chatDetails' of undefined (qrc:/app/AppLayouts/Chat/views/ChatColumnView.qml:274, )
Warning: qrc:/app/AppLayouts/Chat/views/ChatView.qml:40: TypeError: Cannot read property 'viewAndPostPermissionsSatisfied' of null (qrc:/app/AppLayouts/Chat/views/ChatView.qml:40, )
Warning: qrc:/app/AppLayouts/Chat/views/ChatView.qml:39: TypeError: Cannot read property 'viewOnlyPermissionsSatisfied' of null (qrc:/app/AppLayouts/Chat/views/ChatView.qml:39, )
Warning: qrc:/app/AppLayouts/Chat/ChatLayout.qml:139: TypeError: Cannot read property 'id' of undefined (qrc:/app/AppLayouts/Chat/ChatLayout.qml:139, )
Warning: qrc:/app/AppLayouts/Chat/ChatLayout.qml:131: TypeError: Cannot read property 'memberRole' of undefined (qrc:/app/AppLayouts/Chat/ChatLayout.qml:131, )
Warning: qrc:/app/AppLayouts/Chat/ChatLayout.qml:122: TypeError: Cannot read property 'id' of undefined (qrc:/app/AppLayouts/Chat/ChatLayout.qml:122, )
Warning: qrc:/app/AppLayouts/Chat/stores/RootStore.qml:19: TypeError: Cannot read property 'chatDetails' of undefined (qrc:/app/AppLayouts/Chat/stores/RootStore.qml:19, )
INF 2023-07-26 09:43:04.111+10:00 active mailserver changed                  topics="mailservers-service" tid=332062 file=service.nim:163 node=/dns4/node-01.gc-us-central1-a.status.prod.statusim.net/tcp/30303/p2p/16Uiu2HAkwBp8T6G77kQXSNMnxgaMky1JeyML5yqoTHRM8dbeCBNb
ACTIVE MAILSERVER CHANGED: ref 0x7f236f913bb0 --> [nodeAddress = 0x7f23789d6380"/dns4/node-01.gc-us-central1-a.status.prod.statusim.net/tcp/30303/p2p/16Uiu2HAkwBp8T6G77kQXSNMnxgaMky1JeyML5yqoTHRM8dbeCBNb"]
INF 2023-07-26 09:43:04.112+10:00 mailserver available                       topics="mailservers-service" tid=332062 file=service.nim:168
INF 2023-07-26 09:43:04.112+10:00 history request started                    topics="mailservers-service" tid=332062 file=service.nim:178 numBatches=1
INF 2023-07-26 09:43:04.198+10:00 history request completed                  topics="mailservers-service" tid=332062 file=service.nim:183
INF 2023-07-26 09:43:04.199+10:00 history request started                    topics="mailservers-service" tid=332062 file=service.nim:178 numBatches=1
INF 2023-07-26 09:43:04.201+10:00 history request completed                  topics="mailservers-service" tid=332062 file=service.nim:183
INF 2023-07-26 09:43:04.202+10:00 history request started                    topics="mailservers-service" tid=332062 file=service.nim:178 numBatches=1
INF 2023-07-26 09:43:04.205+10:00 history request completed                  topics="mailservers-service" tid=332062 file=service.nim:183
INF 2023-07-26 09:43:04.205+10:00 history request started                    topics="mailservers-service" tid=332062 file=service.nim:178 numBatches=1
ERR 2023-07-26 09:43:04.274+10:00 rpc response error                         topics="rpc" tid=332111 file=core.nim:36 err="\nstatus-go error [methodName:wakuext_curatedCommunities, code:-32000, message:403 Forbidden: {\"jsonrpc\":\"2.0\",\"id\":1,\"error\":{\"code\":-32002,\"message\":\"project ID does not have access to optimism l2\",\"data\":{\"see\":\"https://infura.io/dashboard\"}}} ]\n"
ERR 2023-07-26 09:43:04.274+10:00 error doing rpc request                    topics="rpc" tid=332111 file=core.nim:40 methodName=wakuext_curatedCommunities exception="\nstatus-go error [methodName:wakuext_curatedCommunities, code:-32000, message:403 Forbidden: {\"jsonrpc\":\"2.0\",\"id\":1,\"error\":{\"code\":-32002,\"message\":\"project ID does not have access to optimism l2\",\"data\":{\"see\":\"https://infura.io/dashboard\"}}} ]\n"
Warning: libpng warning: iCCP: known incorrect sRGB profile (:0, )
Warning: libpng warning: iCCP: known incorrect sRGB profile (:0, )
Warning: libpng warning: iCCP: known incorrect sRGB profile (:0, )
Warning: libpng warning: iCCP: known incorrect sRGB profile (:0, )
INF 2023-07-26 09:43:04.316+10:00 history request completed                  topics="mailservers-service" tid=332062 file=service.nim:183
INF 2023-07-26 09:43:04.317+10:00 history request started                    topics="mailservers-service" tid=332062 file=service.nim:178 numBatches=1
ERR 2023-07-26 09:43:04.339+10:00 error onRxOwnedCollectibles:               topics="collectible-service" tid=332062 file=service.nim:398 errorStr="\nstatus-go error [methodName:wallet_getOpenseaAssetsByOwnerWithCursor, code:-32000, message:unsuccessful request: 403 Forbidden ]\n"
INF 2023-07-26 09:43:04.355+10:00 history request completed                  topics="mailservers-service" tid=332062 file=service.nim:183
INF 2023-07-26 09:43:04.356+10:00 history request started                    topics="mailservers-service" tid=332062 file=service.nim:178 numBatches=1
ERR 2023-07-26 09:43:04.360+10:00 sm_cannot resolve current state            topics="app-controller" tid=332062 file=module.nim:137
INF 2023-07-26 09:43:04.567+10:00 history request completed                  topics="mailservers-service" tid=332062 file=service.nim:183
ERR 2023-07-26 09:43:04.732+10:00 Error requesting community info            topics="community-service" tid=332062 file=service.nim:1563 msg="\nstatus-go error [methodName:wakuext_curatedCommunities, code:-32000, message:403 Forbidden: {\"jsonrpc\":\"2.0\",\"id\":1,\"error\":{\"code\":-32002,\"message\":\"project ID does not have access to optimism l2\",\"data\":{\"see\":\"https://infura.io/dashboard\"}}} ]\n"
ERR 2023-07-26 09:43:04.995+10:00 rpc response error                         topics="rpc" tid=332102 file=core.nim:36 err="\nstatus-go error [methodName:wallet_getOpenseaAssetsByNFTUniqueID, code:-32000, message:unsuccessful request: 403 Forbidden ]\n"
ERR 2023-07-26 09:43:04.996+10:00 error doing rpc request                    topics="rpc" tid=332102 file=core.nim:40 methodName=wallet_getOpenseaAssetsByNFTUniqueID exception="\nstatus-go error [methodName:wallet_getOpenseaAssetsByNFTUniqueID, code:-32000, message:unsuccessful request: 403 Forbidden ]\n"
ERR 2023-07-26 09:43:04.997+10:00 error loadTransactionsTask:                topics="transaction-service" tid=332102 file=async_tasks.nim:64 errDesription="\nstatus-go error [methodName:wallet_getOpenseaAssetsByNFTUniqueID, code:-32000, message:unsuccessful request: 403 Forbidden ]\n"
2023-07-26T09:43:11+1000 unset [github.com/anacrolix/torrent.(*Client).NewAnacrolixDhtServer.func2:406]: dht server on 0.0.0.0:38329 (node id b085cad3550cc9556953f0facb96a48fb73967d5) completed bootstrap ({NumAddrsTried:48 NumResponses:25})
ERR 2023-07-26 09:44:02.764+10:00 rpc response error                         topics="rpc" tid=332107 file=core.nim:36 err="\nstatus-go error [methodName:wakuext_curatedCommunities, code:-32000, message:403 Forbidden: {\"jsonrpc\":\"2.0\",\"id\":1,\"error\":{\"code\":-32002,\"message\":\"project ID does not have access to optimism l2\",\"data\":{\"see\":\"https://infura.io/dashboard\"}}} ]\n"
ERR 2023-07-26 09:44:02.764+10:00 error doing rpc request                    topics="rpc" tid=332107 file=core.nim:40 methodName=wakuext_curatedCommunities exception="\nstatus-go error [methodName:wakuext_curatedCommunities, code:-32000, message:403 Forbidden: {\"jsonrpc\":\"2.0\",\"id\":1,\"error\":{\"code\":-32002,\"message\":\"project ID does not have access to optimism l2\",\"data\":{\"see\":\"https://infura.io/dashboard\"}}} ]\n"
ERR 2023-07-26 09:44:02.765+10:00 Error requesting community info            topics="community-service" tid=332062 file=service.nim:1563 msg="\nstatus-go error [methodName:wakuext_curatedCommunities, code:-32000, message:403 Forbidden: {\"jsonrpc\":\"2.0\",\"id\":1,\"error\":{\"code\":-32002,\"message\":\"project ID does not have access to optimism l2\",\"data\":{\"see\":\"https://infura.io/dashboard\"}}} ]\n"
Warning: qrc:/app/AppLayouts/CommunitiesPortal/stores/CommunitiesStore.qml:99: TypeError: Property 'setCommunityIdToSpectate' of object View(0x555811161120) is not a function (qrc:/app/AppLayouts/CommunitiesPortal/stores/CommunitiesStore.qml:99, )

```

**Comment by caybro** [comment] 2023-07-26 08:09
CC @jrainville I see `setCommunityIdToSpectate` has only been added recently; looks like it's missing in 0.13?

**Comment by jrainville** [comment] 2023-07-26 13:29
> CC @jrainville I see `setCommunityIdToSpectate` has only been added recently; looks like it's missing in 0.13?

Ah right! There was a bug where `setCommunityIdToSpectate` was deleted by accident. It was re-added in master, but it's missing in 0.13. Oops.

**Comment by jrainville** [comment] 2023-07-26 13:30
```
ERR 2023-07-26 09:44:02.765+10:00 Error requesting community info            topics="community-service" tid=332062 file=service.nim:1563 msg="\nstatus-go error [methodName:wakuext_curatedCommunities, code:-32000, message:403 Forbidden: {\"jsonrpc\":\"2.0\",\"id\":1,\"error\":{\"code\":-32002,\"message\":\"project ID does not have access to optimism l2\",\"data\":{\"see\":\"https://infura.io/dashboard\"}}} ]\n"
```

This error is weird to me. We shouldn't need optimism to get community info, so that's for sure something to fix if that's still happening.

**Comment by jrainville** [comment] 2023-07-26 14:34
I just tested latest master and the issue is resolved.

I'm gonna close this issue for now. The flow is gonna be way better also when 0.14 releases.

A good work around for now @fryorcraken is to take the link and paste it in a channel (any type). It will unfurl, load the data and show a button to see the community.

**Closed by jrainville** 2023-07-26 14:34 UTC
Labels: bug, messenger-team, C2, E:DesktopCommunityBugFixesForMVP
