### ISSUE TITLE
Overflowing on higher zoom levels combined with lower resolution

### ISSUE THREAD

**Issue by Michal-Status** [status-im/status-desktop#13728] opened 2024-02-26 20:38 UTC
# Bug Report

## Description

When combining low screen resolution and high zoom levels, multiple app functionalities do not work properly. Resizing the application does not resolve the issue, only changing the zoom level, which requires a restart. All of the recordings/screenshots were captured while the application was stretched to cover the entire screen.

Reported as a single ticket due to a probability that all of the issues have common root cause that will fix all of them. Mainly as a knowledge base and a tool for retesting.

## Steps to reproduce

1. Log into the application on a low display resolution (for example 1440x900)
2. Set the application zoom to 300%
3. Restart the app
4. Log in

#### Expected behavior
All of the application functionalities are scaled in a way that makes it possible to use them.

#### Actual behavior
Some of the application functionalities are scaled in a way that makes it impossible to use them.

### Additional Information

- Status desktop version: PR: https://github.com/status-im/status-desktop/pull/13689
Download link: https://status-im-desktop-prs.ams3.cdn.digitaloceanspaces.com/StatusIm-Desktop-240222-172309-2bb65c-pr13689-aarch64.dmg

- Operating System: macOS

Examples of issues found:

**New message field not accessible**
https://github.com/status-im/status-desktop/assets/155960867/c417bff9-2ed7-453f-b1c1-ef321a9c58d5

**Communities buttons not accessible**
https://github.com/status-im/status-desktop/assets/155960867/0202e80b-fedd-4ed2-91f9-3ccb908108d6

**Asset balance in the wallet overlaps**
<img width="1440" alt="Wallet" src="https://github.com/status-im/status-desktop/assets/155960867/4a2e3692-857d-4fe3-ada6-9f2b9b261978">

**Tabs in profile settings not accessible due to lack of a scroll**
https://github.com/status-im/status-desktop/assets/155960867/d085ab49-05ad-4d4b-8e34-9cb43c82e762

**ENS username settings not accessible**
https://github.com/status-im/status-desktop/assets/155960867/23c45659-8fde-473f-a1cc-864be0b9dcf6

**Sync info outside of pop-up window**
<img width="1440" alt="Sync 2" src="https://github.com/status-im/status-desktop/assets/155960867/1f7777c2-b68b-45de-8b00-0b8afe5eaaee">
<img width="1440" alt="Sync 1" src="https://github.com/status-im/status-desktop/assets/155960867/220c1b3c-edb5-418c-8049-9068ba2c8e95">

**Comment by Michal-Status** [comment] 2024-02-26 20:39
@caybro tagging you due to our discussion on the potential common root cause and a potential solution

**Comment by caybro** [comment] 2024-02-27 09:12
Quoting myself for the proposed long term solution:
> Fractional scaling is sort of unsupported feature of Qt and its "completeness" and implementation varies greatly across the OSs (macOS, Windows, Linux); see https://doc.qt.io/qt-5/highdpi.html
> There's another way to do it which would require introducing a Global.dp(px) scaling function that all the physical pixel values would have to go thru; this requires a substantial amount of work, getting rid of all the hardcoded values that we use across the whole codebase

**Comment by caybro** [comment] 2024-04-16 12:54
Duplicate of https://github.com/status-im/status-desktop/issues/14137

**Closed by caybro** 2024-04-16 12:54 UTC
Labels: bug, ui-team, to analyze
