### ISSUE TITLE
Communities section are shown duplicated

### ISSUE THREAD

**Issue by noeliaSD** [status-im/status-desktop#8350] opened 2022-11-21 10:25 UTC
### Description
A `Status` user posted the following issue in the `issues` channel:

The communities section is duplicated 3 times:
![image](https://user-images.githubusercontent.com/97019400/203026410-8c71ca31-7e70-4ec6-b461-927d1ea7b116.png)

No steps shared to reproduce the issue.

## Additional information:
Version `0.8.0-rc.2`

**Comment by jrainville** [comment] 2022-11-21 14:57
This is a duplicate of https://github.com/status-im/status-desktop/issues/7167

**Closed by jrainville** 2022-11-21 14:57 UTC
Labels: bug, Communities, priority F2: important, S:3
