### ISSUE TITLE
improve login time

### ISSUE THREAD

**Issue by iurimatias** [status-im/status-desktop#1387] opened 2020-11-19 21:26 UTC
lately it has gotten *much* slower, we should investigate and improve this

**Comment by hesterbruikman** [comment] 2021-01-27 17:05
Resurfacing this issue as current login time on Windows is pretty sad and 50% to 90% of connected peers is using Windows.

To be verified is how widespread the issue is among Windows users. In this [recording](https://drive.google.com/file/d/1FyJz1u5U_FLKfqgZ30wAlhbiETEIaYg7/view?usp=sharing) my login time is about 1min30sec

**Comment by jrainville** [comment] 2021-01-27 20:43
So, I just did a couple of tests and thought I had found the reason, but in my case, it turned out that I just had a very old data folder that might have had "bad data" in it. 

So, to explain a bit, I found out that even though I was only "subscribed" to 8 channels, we were calling the `chatMessages` function 28 times, and that included a lot of old private channels that I had created for test purposes.

So, that, plus the fact that private channels are very slow in Windows (there is another issue for that), created a very slow login in my case (more than 1 minute).

I thought I found that maybe we didn't check the `active` state of the channels before fetching, but we actually do. It just happened that in my old data, I somehow had private channels marked as `active` even though they shouldn't. It's most likely due to using a lot of dev builds and the backend changing a lot.

I just wiped my data folder and re-synched and now I can login in 12 seconds. It's still not super fast, but it's way better.

I don't really have private chats, so if you do have some, those are the likely culprits and even if you wipe your data older, if you start having a lot of private chats (especially group one), you'll see a huge slow down, but still, if you want, you can wipe your data folder anyway just to see if it ever gets as bad. That's what I'll do for now.

Fixing the other issue about private messages in Windows would be the best to fix the slow login I think, but what I discovered today can help, considering we're still in beta and it's possible that we had some bugs in old data

**Comment by hesterbruikman** [comment] 2021-01-27 21:45
I'll give that a try as well! Could very well be the case. If the root cause is fetching chats, the UI could use a loading state / other indicators so that at least you don't seem stuck on login

**Closed** 2021-02-22 16:31 UTC
Labels: bug
