### ISSUE TITLE
Keycard PIN input behaviour when not in focus

### ISSUE THREAD

**Issue by glitchminer** [status-im/status-desktop#8678] opened 2022-12-06 20:50 UTC
# Bug Report

## Description

The Keycard PIN input can give the impression that it is in focus when it is not. For example when the modal is open the first position will be flashing but will not actually accept any input.

![image](https://user-images.githubusercontent.com/50769329/206020003-ee4233bd-12d5-43b8-8083-7a9295d4aa44.png)

## Steps to reproduce

Have the keycard PIN entry modal open but the PIN entry field out of focus via tab/click.

#### Expected behavior

Users can easily tell if the PIN entry field is in focus or not so the app behaves as a user may expect

#### Actual behavior

No input is registered by the field and it is not obvious to the user that the field is not in focus. 

### Additional Information

- Status desktop version: 0.8
- Operating System: Mac

**Comment by glitchminer** [comment] 2023-02-13 22:36
Hi @alaibe, this was moved to QA earlier, please can you link a PR or specify a version with the fix?

**Comment by saledjenic** [comment] 2023-02-14 08:10
@glitchminer this is an outdated issue, I am not sure which PR exactly fixed this, but the thing is that it works fine in the master branch. Most likely fixed via some other issue.

We just need you to verify this and close with "not reproducible any more" comment.

**Comment by glitchminer** [comment] 2023-02-14 18:57
@saledjenic @anastasiyaig This issue is no longer reproducible on the sign in screen. Please note that, while it can be closed, a similar issue is likely to be raised again in the future as the requirements around keyboard navigation are refined further. For example, is simply preventing a change in focus from PIN entry suitable when there are other controls on the same screen.

Also, the issue is still present in other areas of the app, such as the keycard factory reset, where if the tab key is pressed then the focus will change from the PIN entry field without being obvious to the user.

Retested on 0.10rc7

**Comment by saledjenic** [comment] 2023-02-14 19:04
Key navigation is an issue we're suffering from since the very beginning. We need to do that properly on the app level. At the moment mostly it doesn't work, but there are some rare places where it works, but in a chaotic, non determined way.

**Closed** 2023-02-14 22:36 UTC
Labels: bug, ui, priority 3: low, E:Wallet, E:Keycard
