### ISSUE TITLE
Join Community: Incorrect order of accounts when sharing addresses with relevant tokens

### ISSUE THREAD

**Issue by lukaszso** [status-im/status-desktop#14469] opened 2024-04-18 12:40 UTC
# Bug Report

## Description

According to the designs, if user has more than one account with relevant tokens while sharing addresses, they should be ordered by highest amount of the tokens required to join. Currently, the order is the same as in Wallet and the amount of tokens is not taken into consideration.

## Steps to reproduce

1. Create a community with at least one permission
2. Try to join with a user that has the required tokens in at least two wallet accounts
3. Start the share addresses flow and observe the order

#### Expected behavior
Accounts are ordered from highest to lowest amount of required tokens.
#### Actual behavior
Order is as in Wallet.
### Additional Information
<img width="632" alt="Screenshot 2024-04-18 at 14 36 11" src="https://github.com/status-im/status-desktop/assets/52439419/1969b8dd-239d-4057-a006-d8835bd77e84">

- Status desktop version: 2.28.1 rc1
- Operating System: macOS

**Comment by caybro** [comment] 2024-04-18 12:51
Duplicate of https://github.com/status-im/status-desktop/issues/14192

**Closed by caybro** 2024-04-18 12:51 UTC
Labels: bug
