### ISSUE TITLE
Community invite links are not working 

### ISSUE THREAD

**Issue by Valentina1133** [status-im/status-desktop#13375] opened 2024-02-01 09:58 UTC
# Bug Report

After receiving community invitation user cannot open the link to join community

https://github.com/status-im/status-desktop/assets/141633821/b3c17c8e-ecf3-42a5-b7e8-578f2147e743

## Steps to reproduce

1. Send invite from User 1 invite User 2 to community
2. Go to instance for User 2
3. Open Messages
4. Click on Community Invitation from User 1

#### Expected behavior
Community is opened and Join to community button appears

#### Actual behavior
Nothing happens, User 2 sees the message with invitation

### Additional Information

- Status desktop version: the latest master build
- Operating System: Mac OS Ventura 13.5

**Comment by anastasiyaig** [comment] 2024-02-01 10:54
apparently it is caused by some issue on store nodes for shards.test fleet. Alexis is trying to fix it

**Comment by anastasiyaig** [comment] 2024-02-01 12:21
it should be fixed now

**Comment by Valentina1133** [comment] 2024-02-02 05:13
I runned the test and all works good, thank you !

**Closed** 2024-02-02 05:13 UTC
Labels: bug, messenger-team, E:Desktop New Share URL Format
