### ISSUE TITLE
Wallet/SendModal: Token selector ignores token management

### ISSUE THREAD

**Issue by micieslak** [status-im/status-desktop#15801] opened 2024-07-25 10:31 UTC
# Bug Report

## Description

Tokens not visible in wallet's main view (assets) are visible in send modal's tokens selector.

`TokenSelectorViewAdaptor` seems to completely ignoring token management functionality.

![Screenshot from 2024-07-25 12-23-22](https://github.com/user-attachments/assets/6cda98ad-5ce7-43b8-af56-7ca952d20f77)

NOTE: Potential fix can use data directly from the assets model, no need to use controller.

## Steps to reproduce
1. Hide some assets via token management
2. Open send modal
3. Open token selector

#### Expected behavior
Assets not visible in main view should be hidden also in tokens selector

#### Actual behavior
Token management setup is not taken into account

### Additional Information

- Status desktop version:
- Operating System:

**Comment by caybro** [comment] 2024-07-25 10:38
Duplicate of https://github.com/status-im/status-desktop/issues/15277, scheduled for 2.31

**Closed by caybro** 2024-07-25 10:38 UTC
Labels: bug, ui-team, E:Desktop Token management, 2-30-bug-bash
