### ISSUE TITLE
Deleting permitted channel forces kick of community member

### ISSUE THREAD

**Issue by MishkaRogachev** [status-im/status-desktop#14979] opened 2024-05-29 18:10 UTC
From https://github.com/status-im/status-desktop/issues/14915#issuecomment-2136168365

# Bug Report

https://github.com/status-im/status-desktop/assets/2522130/52835598-5f61-460d-b532-a9a5ed072d2e

## Description

Then a permitted channel got removed, community member is forced to kick

**Comment by jrainville** [comment] 2024-05-31 17:18
Moving this to 2.30 as it seems like it's not a bug that happens a lot and might be a very edge case.

**Closed** 2024-06-05 15:28 UTC
Labels: bug, backend-team, E:D Comm Bugfixes 2.30
