### ISSUE TITLE
Inconsistent group chat message history

### ISSUE THREAD

**Issue by glitchminer** [status-im/status-desktop#7741] opened 2022-10-04 13:10 UTC
# Bug Report

#### 1. Messages previously seen disappeared after an application restart
Messages between these 2 are no longer available

![image](https://user-images.githubusercontent.com/50769329/193822000-cdf1ffab-e391-4d8a-942a-45a5cb797d14.png)

---
#### 2. Messages removed after receiving a new message

 The following messages are no longer shown after a new one was received (including ones sent by the user). Note msg at 11:26 is not shown.

![image](https://user-images.githubusercontent.com/50769329/193822000-cdf1ffab-e391-4d8a-942a-45a5cb797d14.png)

![image](https://user-images.githubusercontent.com/50769329/193823636-4046aee4-e750-4650-9720-fc0985244d17.png)

---
## Steps to reproduce

Specific steps unknown.
Observe message history over day and previous days

#### Expected behavior

Message history remains consistent for user and between all users

#### Actual behavior

Users are reporting differences in message history and messages being removed (without manual deletion)

### Additional Information

- Status desktop version: 0.7.0 rc1 (dogfooding)
- Operating System: Mac

**Comment by iurimatias** [comment] 2022-10-07 01:14
duplicate of https://github.com/status-im/status-desktop/issues/7381

**Closed by iurimatias** 2022-10-07 01:14 UTC
Labels: bug, Chat, priority 1: high, E:Bugfixes, E:Groups
