### ISSUE TITLE
Onboard validation message for display name looks off

### ISSUE THREAD

**Issue by PascalPrecht** [status-im/status-desktop#5363] opened 2022-04-05 12:22 UTC
![Screenshot from 2022-04-05 14-21-29](https://user-images.githubusercontent.com/445106/161752532-62ec28f5-c19b-4a3d-98e2-133b5543970b.png)

**Comment by anastasiyaig** [comment] 2022-04-05 13:24
duplicate of https://github.com/status-im/status-desktop/issues/5352

**Closed by anastasiyaig** 2022-04-05 13:24 UTC
Labels: bug, ui
