### ISSUE TITLE
Community: the channel description is hidden not evenly

### ISSUE THREAD

**Issue by elina2015** [status-im/status-desktop#8941] opened 2023-01-03 20:41 UTC
# Bug Report

## Steps to reproduce
1. Create a community
2. Create a channel with a long description. 
    For example: http://www.google.com - my new search engine! Join it today and get the best experience! Yay! Yay! Yay! Yay!Yay!Yay!Yay!Yay!Yay!Yay!Yay!Yay!
3. Change the weight of the app's window (make it smaller or bigger) and check the channel's description

#### Expected behavior
The channel is hidden evenly
#### Actual behavior
<img width="718" alt="image" src="https://user-images.githubusercontent.com/14942081/210437687-dfd5fc70-6be4-40c0-b8b3-e3d07ac68c8b.png">

https://user-images.githubusercontent.com/14942081/210438008-a70856b6-ce8d-427c-8db3-2a4be7c9942f.mov

### Additional Information

- Status desktop version: 0.8.1
- Operating System: macOS Monterey

**Comment by caybro** [comment] 2023-01-03 21:08
Duplicate of https://github.com/status-im/status-desktop/issues/8884

**Closed by caybro** 2023-01-03 21:08 UTC
Labels: bug, Communities
