### ISSUE TITLE
Channel chat items should only show a badge count when there are mentions 

### ISSUE THREAD

**Issue by PascalPrecht** [status-im/status-desktop#2841] opened 2021-07-07 14:16 UTC
The it's currently implemented, is that every unread message adds to the "count" of a badge that's attached to the channel item (as of #2745, it's an `@` symbol in `master` before  https://github.com/status-im/status-desktop/commit/b352341295549ec187fbc5cb3ec089525f0fd373).

The same logic has been applied in #2745 (https://github.com/status-im/status-desktop/commit/b352341295549ec187fbc5cb3ec089525f0fd373) but this needs to be updated.

The correct behaviour is that `hasUnreadMessages` is used to indicate any number of unread messages, while the badge is used for rendering the count of mentions in a channel.

**Comment by PascalPrecht** [comment] 2021-07-07 14:17
To clarify @simonricoo, we still show a count for unread messages in 1-on-1 chats?

**Comment by iurimatias** [comment] 2021-07-07 20:17
I'm marking this as a feature since it's not really a bug per se, the current behaviour was intended

**Comment by PascalPrecht** [comment] 2021-07-09 13:39
This can be closed once #2791 lands, but needs clarification on https://github.com/status-im/status-desktop/issues/2841#issuecomment-875643813 first

**Comment by simonricoo** [comment] 2021-07-09 14:02
Yes, new messages in 1-1 chat appear in the list item as a new message with mention so when you have 3 new messages you see a badge with number 3.

**Closed** 2021-07-12 15:37 UTC
Labels: Chat, Communities, feature, ui
