### ISSUE TITLE
Chat content updates in the background while playing with the Edit Shared Popup addresses

### ISSUE THREAD

**Issue by jrainville** [status-im/status-desktop#14376] opened 2024-04-09 15:57 UTC
# Bug Report

## Description

You can see it happening in the video from this comment: https://github.com/status-im/status-go/pull/5023#issuecomment-2043655144

Basically, if you have a community with permissioned channels and have different accounts that have different tokens, if you go in a channel that has permissions, then go in the Edit Shared Addresses popup, when you select/unselect accounts, the permission check result will not only affect the popup, but also the chat in the background.

One solution would be to add a UUID to the permission check, so that when we send the result from the service, only the module that asked for that check handles the result. In this case, only the communities module should react to that event.

## Steps to reproduce

0. Have a community with some channels containing permissions to view/post (let's say 0.01 ETH)
1. Have another Status account with 2 wallet accounts, one with 0.01 ETH and the other has nothing
2. With that account, go see the channel that has a permission -> you should have access
3. Go in the Edit Shared Addresses popup
4. Unselect the account that has 0.01 ETH

Result: the popup edit correctly showing that you no longer have access to the channel, but in the background, the channel also loses access, even if we didn't send yet.

#### Expected behavior

Only the popup updates until the addresses are actually sent

#### Actual behavior

The chat_section module reacts to the check permission event even if it wasn't meant for it, resulting in the chat content to lock up before the addresses are even sent.

### Additional Information

- Status desktop version: master (`277dda7533c8602f2fe0a4c72615be05ff9df118`)

**Comment by caybro** [comment] 2024-04-09 16:37
Ah, I think we had a similar bug with multiple communities, and then editing the shared addresses would get the permissions from another community. Can't find it now, @alexjba ?

**Comment by alexjba** [comment] 2024-04-09 17:21
Duplicate of https://github.com/status-im/status-desktop/issues/14200.

@jrainville When the shared addresses popup is opened we have 2 permissions models for the same community. When changing the shared addresses we request new permissions check with the selected address and the update is propagated in both models. This bug is a side effect of the wrong model being updated with the new permissions check.

**Comment by jrainville** [comment] 2024-04-09 17:29
I'd say they are related, but it's not exactly the same issue

 In this case, the problem is that the chat section module reacts to the event if it was not meant for it.

I think doing the UUID solution is needed anyway, because even with your change to move the permisisonsModel to the chat section module, we still need to differentiate a real call to check permissions vs one from the Edit Shared addresses popup

**Comment by alexjba** [comment] 2024-04-09 17:36
> I'd say they are related, but it's not exactly the same issue
> 
> In this case, the problem is that the chat section module reacts to the event if it was not meant for it.
> 
> I think doing the UUID solution is needed anyway, because even with your change to move the permisisonsModel to the chat section module, we still need to differentiate a real call to check permissions vs one from the Edit Shared addresses popup

It's true and the refactoring should consider this broken flow as well.

**Comment by MishkaRogachev** [comment] 2024-05-03 12:20
Works in the current master

**Closed by MishkaRogachev** 2024-05-03 12:20 UTC
Labels: bug, backend-team, E:Desktop Community Shared Addresses Selection, E:Desktop Comm Perms and Minting MVP
