### ISSUE TITLE
[Community Mint Token] Review self destruct popup scrollview

### ISSUE THREAD

**Issue by noeliaSD** [status-im/status-desktop#10259] opened 2023-04-11 14:06 UTC
### Description

Difficult to scroll between token holdrs using the **touchpad**. If the cursor is inside the list it doesn't scroll slightly, if the cursor is on the edges of the listview then it does.

_Originally posted by @alexjba in https://github.com/status-im/status-desktop/pull/10112#discussion_r1155760024_

**Comment by caybro** [comment] 2023-06-26 18:38
This is a Qt bug and a general issue we have with all `Flickable`s

**Comment by alexjba** [comment] 2023-06-26 18:49
I guess something changed in the meantime.

https://github.com/status-im/status-desktop/assets/47811206/64185cd9-f4c5-42a0-b717-8d3f7f0ed08c

**Comment by caybro** [comment] 2023-07-26 18:10
> I guess something changed in the meantime.
> 
>  Screen.Recording.2023-06-26.at.21.46.21.mov

I can't reproduce either in latest master, closing

**Closed by caybro** 2023-07-26 18:10 UTC
Labels: ui-team, ui-improvements, C2, E:DesktopCommunityBugFixesForMVP
