### ISSUE TITLE
Message gap is not displaying the date period correctly

### ISSUE THREAD

**Issue by richard-ramos** [status-im/status-desktop#4188] opened 2021-11-25 17:51 UTC
![image](https://user-images.githubusercontent.com/1106587/143484975-a5381176-dc79-4c4e-9554-2f1f0c643117.png)

**Comment by anastasiyaig** [comment] 2021-11-30 08:04
@alexandraB99 was it merged to release? Why the issue is open when PR is closed? Please make sure the commit is added to release 0.4.0 , thanks

**Closed** 2021-11-30 08:17 UTC
Labels: bug, ui, Chat, 0.4.0
