### ISSUE TITLE
Minting community tokens doesn't work on Arbitrum (mainnet)

### ISSUE THREAD

**Issue by jrainville** [status-im/status-desktop#13646] opened 2024-02-20 17:05 UTC
# Bug Report

## Description

We were testing mainnet communities.
Nastya was able to mint the Owner and TM tokens using Arbitrum mainnet.

She then tried to mint a community NFT. It failed with `intrinsic gas too low` error.
She tried an ERC20 as well, but same error.

We think it might be the gas estimation not working well on Arbritrum (is it hardcoded?)

we tried Optimism afterwards and everything worked fine.

## Steps to reproduce

0. Have ETH on Arbitrum
1. Create a community
2. Mint the Owner and TM tokens
3. Try to mint a community token

It fails

https://github.com/status-im/status-desktop/assets/82375995/4356e0a9-286b-4ad0-9a8c-be3528025140

#### Expected behavior

Tokens can be minted

#### Actual behavior

Fails because of gas error

### Additional Information

- Status desktop version: 2.27 RC
- Operating System: Mac

**Comment by alaibe** [comment] 2024-02-21 09:51
Duplicate of https://github.com/status-im/status-desktop/issues/13441 i believe

**Comment by anastasiyaig** [comment] 2024-02-21 09:53
but it is arbitrum and token owner was minted fine? if thats the same issue lets close one for sure

**Comment by anastasiyaig** [comment] 2024-02-21 13:36
@jrainville i am removing that from release milestone , as discussed with John

**Closed** 2024-03-12 19:05 UTC
Labels: bug, messenger-team, E:Desktop Comm Perms and Minting MVP
