### ISSUE TITLE
Chat: 'Fetch more messages' CTA should not show if there are no previous messages to fetch

### ISSUE THREAD

**Issue by benjthayer** [status-im/status-desktop#8257] opened 2022-11-15 15:23 UTC
**Issue:**
The CTA to 'Fetch more messages' should not be shown at the start of the chat history when there are no previous chats to fetch.

<img width="1229" alt="Screenshot 2022-11-15 at 15 21 50" src="https://user-images.githubusercontent.com/110033914/201957525-7934018c-146b-42dc-99ae-f803ce95a62f.png">

**Comment by iurimatias** [comment] 2023-05-10 16:31
moved to 0.14

**Comment by iurimatias** [comment] 2024-02-12 16:57
moving to 2.29 due to lack of space in the current milestone

**Comment by iurimatias** [comment] 2024-04-03 14:04
duplicate of https://github.com/status-im/status-desktop/issues/9445

**Closed by iurimatias** 2024-04-03 14:04 UTC
Labels: messenger-team, Design-QA, E:Desktop Features 2.27.0, E:Desktop Messaging UX fix - High
