### ISSUE TITLE
Scan error on column index 9 in login process

### ISSUE THREAD

**Issue by StateOf-Vlado** [status-im/status-desktop#10744] opened 2023-05-19 08:38 UTC
I got an error when I logged in to my account.
I did not recover the seed phrase, I just left my workplace on Wednesday, (one day off) and started the app on Friday.

I got this issue on StatusIm-Desktop-v0.12.0-rc.1-dd1c30-x86_64.AppImage, then tried on StatusIm-Desktop-v0.12.0-rc.2-c0111a-x86_64.AppImage the error reproduced.

I don't have concrete steps to reproduce, the error image and logs attached

![Image](https://github.com/status-im/status-desktop/assets/128374224/a9a63368-a97e-49a0-b737-53cf57e4a48c)

**Comment by anastasiyaig** [comment] 2023-05-19 08:43
@jrainville @osmaczko did u see that ever before?

**Comment by StateOf-Vlado** [comment] 2023-05-19 08:44
I can not attach a log file, so log contains this:
INF 2023-05-19 10:23:24.626+02:00 Version: 0.12.0-rc.1                       topics="status-app" tid=6896 file=nim_status_client.nim:186
INF 2023-05-19 10:23:24.626+02:00 Commit: dd1c30b92                          topics="status-app" tid=6896 file=nim_status_client.nim:187
INF 2023-05-19 10:23:24.626+02:00 Current date:                              topics="status-app" tid=6896 file=nim_status_client.nim:188 currentDateTime=2023-05-19T10:23:24+02:00
INF 2023-05-19 10:23:24.627+02:00 starting application controller...         topics="status-app" tid=6896 file=nim_status_client.nim:190
INF 2023-05-19 10:23:28.786+02:00 starting application...                    topics="status-app" tid=6896 file=nim_status_client.nim:193
ERR 2023-05-19 10:23:39.503+02:00 error:                                     topics="accounts-service" tid=6896 file=service.nim:604 procName=verifyDatabasePassword errDesription="file is not a database"
ERR 2023-05-19 10:23:41.116+02:00 node.login                                 topics="signals-manager" tid=6896 file=signals_manager.nim:53 error="file is not a database"
ERR 2023-05-19 10:23:41.118+02:00 login error                                topics="app-controller" tid=6896 file=module.nim:419 methodName=onNodeLogin errDesription="file is not a database"
ERR 2023-05-19 10:23:56.892+02:00 error:                                     topics="accounts-service" tid=6896 file=service.nim:604 procName=verifyDatabasePassword errDesription="file is not a database"
WRN 2023-05-19 10:23:58.402+02:00 Error decoding signal                      topics="signals-manager" tid=6896 file=signals_manager.nim:48 err="Unknown signal received: mediaserver.started"
ERR 2023-05-19 10:24:04.383+02:00 node.login                                 topics="signals-manager" tid=6896 file=signals_manager.nim:53 error="sql: Scan error on column index 9, name \"unviewed_message_count\": converting driver.Value type int64 (\"-2\") to a uint: invalid syntax"
ERR 2023-05-19 10:24:04.384+02:00 login error                                topics="app-controller" tid=6896 file=module.nim:419 methodName=onNodeLogin errDesription="sql: Scan error on column index 9, name \"unviewed_message_count\": converting driver.Value type int64 (\"-2\") to a uint: invalid syntax"

**Comment by caybro** [comment] 2023-05-19 09:11
Duplicate of #10649

**Closed** 2023-05-19 09:12 UTC
Labels: bug, messenger-team

**Comment by jrainville** [comment] 2023-05-19 15:28
@StateOf-Vlado sadly the fix I did only makes it so the issue cannot reproduce anymore. It doesn't have a DB migration because doing one is slow and also a bit dangerous, since it was on an RC.

If you want to fix that particular account, you need to log into your DB and execute the following query
```sql
UPDATE chats SET unviewed_message_count = 0  WHERE unviewed_message_count < 0;
```

The guide on how to access your DB is here. https://hackmd.io/@status-desktop/rJKk3sfJ5

I can assist you if needed.

**Comment by StateOf-Vlado** [comment] 2023-05-22 08:01
@jrainville what I'm doing wrong?
squisher@status:~/.config/Status/data (copy)$ sqlcipher 0x79af32f12ec5d6fa55ed78fe8f81470f95638186d3514901a962db59e138eab9.db
SQLCipher version 3.15.2 2016-11-28 19:13:37
Enter ".help" for instructions
Enter SQL statements terminated with a ";"
sqlite> PRAGMA key = "0x168c0fdb042272c884cb469d1983c862891392ba08184ab108287b6639cc3e40";
sqlite> PRAGMA cipher_page_size = 1024;
sqlite> PRAGMA kdf_iter = 256000;
sqlite> PRAGMA cipher_hmac_algorithm = HMAC_SHA1;
sqlite> PRAGMA cipher_kdf_algorithm = PBKDF2_HMAC_SHA1;
sqlite> UPDATE chats SET unviewed_message_count = 0  WHERE unviewed_message_count < 0;
Error: file is encrypted or is not a database
sqlite>
