### ISSUE TITLE
Sometimes joining a community has blank channels on the sidebar

### ISSUE THREAD

**Issue by iurimatias** [status-im/status-desktop#6167] opened 2022-06-20 19:31 UTC
# Bug Report

## Description

Sometimes joining a community has blank channels, this is fixed after restarting.

![upload_399a4fca602c348be39fb2834ccabfac](https://user-images.githubusercontent.com/176720/174667291-2c32a782-c9b2-431f-9ac6-de8bf69939f1.png)

## Steps to reproduce

not easy to replicate but happens often

1. get invited to a community and/or request access to one

**Comment by saledjenic** [comment] 2022-06-23 14:00
@anastasiyaig @elina2015 @Hbouaz may you help reproducing this? I was trying for some time in a many different ways, but community was displayed well to me each time (though I remember that I faced that issue when we started with dogfooding/phase4 for the first time, but now I cannot reproduce it, but now I am using build from commit `95326620c` maybe the issue is fixed in meantime).  Anyhow if you have some findings, please share here.

**Comment by elina2015** [comment] 2022-07-12 23:22
Tested on the latest master - the bug is not reproduced.

**Closed** 2022-08-19 12:38 UTC
Labels: bug, ui, Communities, tested, priority 1: high, E:Bugfixes, E:Communities, S:3
