### ISSUE TITLE
Search pop up doesn't render input value properly

### ISSUE THREAD

**Issue by PascalPrecht** [status-im/status-desktop#5219] opened 2022-03-28 11:38 UTC
Entering a value in the search popup input looks like this:

![Screenshot from 2022-03-28 13-36-38](https://user-images.githubusercontent.com/445106/160390148-d57d725f-553c-4e71-b8cd-9e4ecd4c3d1b.png)

**Comment by iurimatias** [comment] 2022-03-28 15:46
duplicate of https://github.com/status-im/status-desktop/issues/5200

**Closed by iurimatias** 2022-03-28 15:46 UTC
Labels: bug
